### ISSUE TITLE
Deploy on IPFS

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1]
`@klimadao/app` should be exportable with `next export`, but I haven't tested yet.

Ideally this would be part of our CI/CD pipeline, with the latest IPFS deployment and hash accessible via a subdomain like `ipfs-dapp.klimadao.finance`

**Comment by 0xAurelius** [comment]
This is done, isn't it?

**Comment by ArchimedesCrypto** [comment]
Correct, closing
