### ISSUE TITLE
(low priority) Migrate from CSS Modules to Emotion.

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#10]
I built the site initially with css-modules for development speed, as it was supported out-of-the-box with nextjs, and because I love the css-modules pattern overall.

But this was a mistake. CSS Modules is not under active maintenance, not well documented, and relies on transpilers, which means it can't be easily used in our `@klimadao/lib` if we want to publish a components library. I'd like to convert everything to Emotion, using a very similar pattern and structure (separating component files and styles files).

I have built production react apps with styled-components, css-modules, styled-jsx, and vanilla css. Emotion beats them all.

Note: we already have Emotion as a sub-dependency because we use @mui/material-icons
 
We probably want to go with the framework-agnostic `@emotion/css` https://emotion.sh/docs/introduction

**Comment by dodecaKlima** [comment]
Good shout. If you are committed to CSS-in-JS, have you considered [Stitches](https://stitches.dev)?

**Comment by Atmosfearful** [comment]
> Good shout. If you are committed to CSS-in-JS, have you considered [Stitches](https://stitches.dev)?

Ooh that's a new one for me, gonna take a closer look thank you for sharing!

**Comment by rplusq** [comment]
Hey, have you considered other options like TailwindCSS / Chakra-UI? They have been getting a lot of traction lately, can make the onboarding for users / development times quicker too

**Comment by Atmosfearful** [comment]
@goatsOnDrugs feel free to close this out if everything is done
