### ISSUE TITLE
[buy] Restrict amounts to be whole numbers

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1001]
It is possible currently to list a non-integer amount, such as 3.5 tonnes, and then for someone to buy the integer floor of this number, 3 tonnes. This leaves a fractional amount listed which is impossible to buy.
I believe the solution to this is to restrict listing and buying amounts to whole numbers in the frontend (and potentially the backend).

[Example](https://carbonmark.vercel.app/projects/VCS-487-2013/purchase/0x27)

![image](https://user-images.githubusercontent.com/99001851/220211819-bea1b17c-ae80-4c32-b727-f8e4ef73bc2a.png)

**Comment by Atmosfearful** [comment]
Fractional retirements is a requirement in my opinion, as users may want to retire a specific emissions count in full (e.g., a flight).
And the API should also support fractional retirements, which would appear in the Activity feed anyways.
