### ISSUE TITLE
[performance] General caching issues

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1019]
I recently reported an issue in discord after creating a listing the project title was missing.

![Image](https://user-images.githubusercontent.com/103535195/226177713-47494115-175a-4ea6-81a7-c8347dba1bae.png)

Turns out it was a caching issue.

Overall seeing some issues when creating/updating listings etc of the information not displayed correctly or very quickly on the frontend. This can lead to confusion since the user may not know they need to hard refresh multiple times to see changes. 

As one example, when I create a new listing, sometimes it takes numerous refresh for the listing to show and if I change screens, like go to marketplace and then back to my profile my listing is not there until I refresh.

The other thing I often see (not a caching issue) is every time I click on my profile page the create listing button spinner shows for 8,10 or more seconds - what is causing that?

There are other issues already created around caching, i.e. KlimaDAO/klimadao#1008 and KlimaDAO/klimadao#1015 so clearly caching is a known issue. I'm not sure we can icebox this before launch but also not sure what the solution or level of effort would be to improve the UX.

**Comment by ShimonD-KlimaDAO** [comment]
Single project page caching updates passed QA.
#1025

**Comment by ShimonD-KlimaDAO** [comment]
Portfolio data page looks good, except for two minor notes. See my comment in #1047 
https://github.com/KlimaDAO/klimadao/pull/1047#issuecomment-1515618024

**Comment by ShimonD-KlimaDAO** [comment]
#1099 passes QA. This concludes all caching PRs.
