### ISSUE TITLE
[docs] DNS changes to support docs.carbonmark.com

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1022]
gitbook has been setup with following URL `docs.carbonmark.com`

Following the same settings as docs.klimadao.finance

Need DNS updated.

**Comment by sy-zygy** [comment]
Requested record to add from Chaz

**Comment by jabby09** [comment]
@sy-zygy `1252e64f01-hosting.gitbook.io`

**Comment by sy-zygy** [comment]
Record has been created -- but getting a SSL err

**Comment by sy-zygy** [comment]
Now I am getting a cloudflare err
![image](https://user-images.githubusercontent.com/8546/231224676-d31d7172-0a9d-432e-aeb6-41be090446e9.png)

@Atmosfearful any ideas?

**Comment by sy-zygy** [comment]
It is working now @jabby09
