### ISSUE TITLE
[projects] Searching for a project id does not work as expected

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1029]
Unsure if this is an explicit requirement but intuitively searching for a project's registry id (e.g VCS-1052) should return that project in the search results.

https://registry.verra.org/app/projectDetail/VCS/1052

https://www.carbonmark.com/projects?search=VCS-1052

https://www.carbonmark.com/projects/VCS-1052-2012

![image](https://user-images.githubusercontent.com/7104689/231914687-2a61afb0-8dbf-41e2-8c4d-898e59472d74.png)

**US**
As a user when I view a listing on an existing registry website, I want to easily find that listing by it's ID in the Carbonmark Projects page by searching for that ID.

**Comment by 0xemc** [comment]
@jabby09 thoughts on this one?

**Comment by jabby09** [comment]
@Atmosfearful @ladytrekker what fields is search hooked up to? Is it only the project title and description?

I agree with @0xemc, this is a good catch and would be an expected pattern to search by project id

**Comment by ladytrekker** [comment]
The search is happening on the backend

The Frontend creates a query in the URL for the API endpoint.
In this case: https://api.carbonmark.com/api/projects?search=VCS-1052

Same goes for when searching for a string in a project title:
https://api.carbonmark.com/api/projects?search=biomass

I assume that the text search on the backend is not optimized for data other than the project title.

@Najada Can you explain a bit more how the search query works?
And if it can be possible to search for the project ID too?

**Comment by Najada** [comment]
@ladytrekker the search text is working only on the name. We could make it work for the project key as well

**Comment by Najada** [comment]
hi @jabby09 I can deliver this tomorrow.

**Comment by psparacino** [comment]
got it, thanks

**Comment by jabby09** [comment]
@psparacino unclear if this API change happened so you will need to investigate.

Connect with @Atmosfearful if you have questions as ladytrekker is also no longer available to provide context.
