### ISSUE TITLE
Fix staking input placeholder

### ISSUE THREAD

**Issue by mok0230** [KlimaDAO/klimadao#103]
Currently on the "Stake" tab, the input placeholder reads "Amount to unstake" and on the "Unstake" tab, it reads "Amount to stake". It seems like this should be reversed.

<img width="659" alt="stake tab" src="https://user-images.githubusercontent.com/92540752/150692565-fe906d1a-8bd9-4689-845e-8ddf6dafe0ea.png">
<img width="654" alt="unstake tab" src="https://user-images.githubusercontent.com/92540752/150692568-195bf4aa-3e68-47c2-82b5-d47f9f17c975.png">

**Comment by Atmosfearful** [comment]
Thanks for the quick fix!
