### ISSUE TITLE
[footer] Visual enhancement of Contact + email option

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1040]
This workstream is related to an enhancement of the Carbonmark footer to create more visual emphasis of the Contact option and to add an option for a user to email directly for support.

### Design requirements
- [x] Recommendation to more visually enhance the Contact option in the footer. Moving Contact to the end of the list of options might be enough but looking for your reco. _**Note:** should be the same reco for the homepage and in-app footer._
- [x] Add an email logo next to the social media options. On the dev side we will have this open the user default email client with To: set to support@carbonmark.com. _**Note:** should be the same reco for the homepage and in-app footer._
- [x] In-app, for example the [Profile page](https://www.carbonmark.com/users/login), there is an issue with the live chat widget overlapping the social icons. Need a design reco to fix this. Probably if the icons shifted in by the same amount as we see on the homepage that will do the trick but would like a reco and the solution documented
<img width="633" alt="Screenshot 2023-04-17 at 11 56 32 AM" src="https://user-images.githubusercontent.com/103535195/232524687-a609261b-3864-4567-946d-65b98f4b7c8f.png">

- [x] In this [discord thread](https://discord.com/channels/841390338324824096/1095703098783186985), there is a feature request for a `Book a Demo` CTA. This would be in-app screens only (i.e. not on the homepage). I wonder if we have room in the side nav. If a button is the reco, I'd be also curious to see what it looks like with a secondary primary colour (i.e. not blue background). _**Note:** the CTA will either go to a form or directly to an email._
- [x] <img width="607" alt="Screenshot 2023-04-17 at 11 52 37 AM" src="https://user-images.githubusercontent.com/103535195/232524383-f0655b7d-d677-465e-99eb-d16067ec6d1c.png">

**Comment by theprofessora** [comment]
Footer with "contact" moved to the end of the list, a mail icon being added to the social media icons, and the social media icons being shifted over to allow more room for the chat bubble when the screen is scrolled down.


![Image](https://user-images.githubusercontent.com/110631623/233140661-e9e75a6e-5e33-4222-8f9b-dec0e221433e.png)

**Comment by theprofessora** [comment]
For the "Book a Demo" CTA, I think it should be a button in the nav, but it shouldn't draw a lot of focus, because it's not one of the primary functions a user needs to use or see. I think we should go with a shorter variation of our usual button - only 36px tall - and make it follow our secondary CTA visual styles.

![Image](https://user-images.githubusercontent.com/110631623/233143488-84591fd8-fa64-4272-856e-4b7032e12c13.png)

**Comment by jabby09** [comment]
[Design reference
](https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN/Carbonmark-Design-System?type=design&node-id=31-1581&t=gPXbyAUDogPZFfNj-4)

## Dev tasks
- [ ] Notes these changes apply to desktop and mobile and the implementation may be slightly different according to the designs
- [ ] Footer - On homepage and in-app, move Contact option to the end of the list of footer options
- [ ] Footer - On homepage and in-app, add an email logo next to the social media options. Clicking this should open the user's default email client with To: set to [support@carbonmark.com](mailto:support@carbonmark.com)
- [ ] Footer - On homepage and in-app, add github as option in the social icons, it should link to https://github.com/KlimaDAO
- [ ] Footer - In the app, shift the icons to the left so on some screen sizes, the icons are not overlapping with the live chat widget
- [ ] Primary Nav - In the app, add a BOOK A DEMO button ([design](https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN/Carbonmark-Design-System?type=design&node-id=31-695&t=gPXbyAUDogPZFfNj-4)), which should link to the [Contact form](https://share-eu1.hsforms.com/1_VneTUObQZmJm4kNcRuEoQg3axk)
