### ISSUE TITLE
[navigation] Replace Infinity with Carbonmark in website menu

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1042]
On the [KlimaDAO website](https://www.klimadao.finance/), replace the INFINITY menu option (and sub-options) with CARBONMARK.

The CARBONMARK menu option will not have sub-options and will direct to https://www.carbonmark.com/

**NOTE:** The [INTRODUCTION](https://www.klimadao.finance/infinity) and [HOW TO PLEDGE](https://www.klimadao.finance/pledge) pages will still exist we will just not have menu links to them. This will ensure that any links to those pages do not break.

![Image](https://user-images.githubusercontent.com/103535195/232774409-cb5bf06c-efa6-41ff-b9c5-0a4bb7b10b5b.png)

**Comment by jabby09** [comment]
@0xemc do you have time for this one this week - shouldn't take too long I don't think.

**Comment by 0xemc** [comment]
> @0xemc do you have time for this one this week - shouldn't take too long I don't think.

No worries super easy. Will jump on it tomorrow
