### ISSUE TITLE
[sanity] Fix font size for bullet points

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1044]
DOMAIN = Carbonmark (i.e. this apparently works in the KlimaDAO instance)

Bug submitted as [feedback in discord](https://discord.com/channels/841390338324824096/1091068906858364980).

The font size for bullet points is smaller than for the body text. This could give the impression that this information is less important, when in fact it sits at just the same level in the hierarchy. As is typical, I think the same size font should be used for bullets as for paragraphs.

For example:
![image](https://user-images.githubusercontent.com/103535195/232786090-17cc7b84-5acc-4e20-80b4-28606544e7b1.png)

**Comment by jabby09** [comment]
@PaulineAnnBar here is another one for you. Let me know if any questions.

**Comment by ladytrekker** [comment]
Done in https://github.com/KlimaDAO/klimadao/pull/1170
