### ISSUE TITLE
[redirect] Pop up message when redirecting user to klimadao site

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1055]
Currently in Carbonmark, we are leveraging the retirement aggregator when a user chooses to buy/retire from a pool or retire an asset from their portfolio page. The UX is jarring in that there is not a lot of information provided to the user about why this is happening or where they are being redirected.

There is a feature request enhancement requested to create pop up a msg before the user is redirected to the klimadao app.

The pop up message should be enabled for the following:
- BUY button on pool listing on project details page
- RETIRE NOW button on pool listing on project details page
- RETIRE button on portfolio page listing

The message in the pop up should read:

> You will be taken to KlimaDAO.finance to complete this transaction. After you click the link below to continue, you will be asked to connect your wallet and the project you selected here will already be selected for you on KlimaDAO.finance. From there, follow the directions on that page to complete your transaction.
>     
> Carbon credits you purchase or any retirements you make on KlimaDAO.finance will also be accessible in your Carbonmark portfolio.

**Comment by jabby09** [comment]
@theprofessora this request came from Sy plus given it is a temporary step (while we migrate the app features into Carbonmark) we should prioritize this.

Text to be included in the popup is provided, will leave it with you to discuss with @Atmosfearful if this is best implemented as a modal popup or a new page. Beyond the required text, the rest of the design is your discretion.

**Comment by theprofessora** [comment]
1st pass:


![Image](https://user-images.githubusercontent.com/110631623/233160866-bdab5537-1372-4b12-a169-fbb7be8b08d8.png)

**Comment by theprofessora** [comment]
also seen here: https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F?node-id=11:59799#423677856

**Comment by jabby09** [comment]
@Atmosfearful ready for dev assignment

**Comment by jabby09** [comment]
@psparacino appreciate you dealing with these smaller QoL enhancements while we queue up a larger epic workstream for you.
