### ISSUE TITLE
[pdfs] New carbonmark styling for PDFs

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1062]
After #1061
Pending designs from @theprofessora

**Comment by theprofessora** [comment]
@Atmosfearful @jabby09 Does this task refer to the retirement receipt pdfs? or are there other pdfs as well for me to design?

**Comment by jabby09** [comment]
> @Atmosfearful @jabby09 Does this task refer to the retirement receipt pdfs? or are there other pdfs as well for me to design?

@theprofessora refers to the retirement receipt pdf so you basically already have it done

**Comment by jabby09** [comment]
@0xAeterno @Atmosfearful [Shipped design here](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6606&t=GsMARHHiNJnsw8V8-4)
