### ISSUE TITLE
[design] Update design for retire your own carbon screen

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1087]
This design task is related to supporting the ability to retire carbon you own but from within Carbonmark.

The flow we need to support at this point starts from https://www.carbonmark.com/portfolio

Currently in the beta/mvp, if a user clicks the RETIRE button on a project card in the portfolio page, they are redirected to the retirement aggregator, with the `Select carbon token to retire field` and `project information` pre-populated. For example:

![Screenshot 2023-04-26 at 4 21 37 PM](https://user-images.githubusercontent.com/103535195/234681147-b2ad7a56-a4f7-43d9-947d-2cbf9501b266.png)

It appears that the retire from portfolio design flow has been started in this [figma page](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?node-id=13-6294&t=IyT6bnB0RkDIRz3R-0).

In looking that that flow, these are the design changes that need to be considered to match what we have in the retirement aggregator example above:

- [x] Remove the Payment successful screen...this is not required since the user already owns this carbon asset and no purchase is required to retire
- [x] Repurpose / reuse the details screen currently being [designed for org retirement flow](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?node-id=13-6063&t=av1orrhnvr0rua7Q-4) with the following changes...
- Remove yellow price call out
- Remove price panel (note, there is no need for pricing to straight retire carbon you already own)
- Remove pay with field
- Add context for token being retired (name and address)
- Any other considerations related to existing functionality in the retirement aggregator

This is an engineering consideration but believe the URL path for this form/view will be something like: https://www.carbonmark.com/portfolio/retire and will be architected to support a linkable via URL, so that we can support query params in the future, like /portfolio/retire/[registry-projectid-vintage]?quantity=123

After clicking RETIRE CARBON button and completing the transaction, the user will be directed to a retirement receipt page. Separate design tickets will be created for that work.

**Comment by jabby09** [comment]
Other feedback from @Atmosfearful 

I'm looking at the figma now, here is my feedback
* [ ] (organization nitpick) Move this to `/portfolio` folder in figma, which is the URL path where this flow takes place. Right now it's in `Retire` which is not a view we support yet

### Retirement form view
![image](https://user-images.githubusercontent.com/88635679/234732004-26cc546a-016a-4030-905e-ae808fa867ef.png)

* [ ] Remove orange Price tag
* [ ] It might be nice to show the 0x address somewhere w/ a copy address button and/or a link to view that token's info on polygonscan.
  - Similarly it might be nice to show either the C3 or Toucan generic icon, and the Token Symbol  e.g. `C3T-VCS-1188-2015` or `TCO2-VCS-1190-2017`
* [ ] Remove all the pricing info in the Total Price card
  - I'm not sure what info is relevant to show in its place. Maybe project token info described above ☝️ ?
* [ ] a breadcrumb to show that this is a subview of /portfolio and help the user find their way back if needed

### Confirmation view
![image](https://user-images.githubusercontent.com/88635679/234732055-5ecb3015-56e5-4924-905b-f660492cc9e5.png)
A lot of the stuff in this mock is not relevant for a retirement.
Proposition: we simplify this down to barebones
- congrats text
- link to polygonscan
- VIEW AND SHARE CERTIFICATE -> navigates them to the retirement page
- RETIRE MORE CARBON
Our strongest CTA being that they visit the retirement page, which is where they can always go to view all the details.
* [ ] Another ask, can you show an intermediate state here while we are waiting for the retirement page to generate itself? We can say "Generating retirement receipt page" with a loading spinner perhaps? This is a prerequisite for #1096

**Comment by theprofessora** [comment]
Ready for review: https://www.figma.com/file/I5hXFeW1DKjV7agHq7T4UZ?node-id=229:20216#430846318

**Comment by theprofessora** [comment]
Done and shipped: https://www.figma.com/file/I5hXFeW1DKjV7agHq7T4UZ/Portfolio?type=design&node-id=0%3A1&t=ZCIldRkzRTHG2bab-1
