### ISSUE TITLE
[retirement receipt] Interim redesign to rebrand existing klimadao page to be used in Carbonmark

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1088]
This is a interim solution to support a retirement receipt before the new design is implemented.

**Comment by Atmosfearful** [comment]
Just dropping notes off the top of my head from our call earlier:
- update the `about klima` text (I can improvise this if needed)
- remove the get rewarded card
- remove the pledge button
- swap headers/footers to carbonmark

- depending on how far we get migrating the top level /retirements page, might need to remove the hyperlink on the user address/ENS/kns domain that links to /retirements

**Comment by theprofessora** [comment]
https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY?node-id=0:1#430744846

**Comment by jabby09** [comment]
@theprofessora @Atmosfearful here is rough sketch that I think highlights what needs to change.

[Retirement Receipt Changes.pdf](https://github.com/KlimaDAO/klimadao/files/11347257/Retirement.Receipt.Changes.pdf)

**Comment by jabby09** [comment]
@theprofessora might now need a design here, if you agree with the changes in the pdf that will probably be good enough for @0xMakka to work with as he copies over the page.
