### ISSUE TITLE
[retirement] Retirement receipt page based on new designs

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1089]
This workstream is for the dev work required to build the new retirement receipt pages for Carbonmark.

[New designs here.](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=0-1&t=GsMARHHiNJnsw8V8-0)

### Notes
- [x] This workstream is focused solely on the retirement receipt page - the PDF version is covered in #1062 
- [x] Note design differences for [desktop](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6420&t=GsMARHHiNJnsw8V8-4) and [mobile](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6515&t=GsMARHHiNJnsw8V8-4)
- [x] URL structure will be `/retirements/[beneficiary_address]/[retirement_index]` ("single retirement page"; same pattern as in KlimaDAO)
- [x] For the `/retirements/[beneficiary_address]` ("retirements list") page, we will use what is currently deployed in staging, for example https://staging.carbonmark.com/retirements/brice.klima
- [x] For Project Details section, ignore the project photo, we will launch with the default project cover images based on project category
- [x] VIEW CARBONMARK PROFILE link CTA takes user to `https://www.carbonmark.com/users/login` or `https://www.carbonmark.com/users/[user]` if logged in
- [x] CREATE YOUR OWN RETIREMENT link CTA takes user to https://www.carbonmark.com/projects
- [x] LEARN MORE link CTA takes user to the project details page in Carbonmark
- [x] Get started today link CTA in the About Carbonmark section takes the user to https://www.carbonmark.com/projects
- [x] Beneficiary section - logo comes from the profile image
- [x] DOWNLOAD PDF hands off the PDF creation code (#1062)
- [x] Social share icons inherit behaviour as per already completed in the staging environment; for example, see https://staging.carbonmark.com/retirements/brice.klima/11 
![Screenshot 2023-05-10 at 1 23 05 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/060c0637-cfb3-4f86-a834-c6e2afd10c08)

- [x] Note the [designs changes](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6853&t=GsMARHHiNJnsw8V8-4) that happen is no beneficiary information and/or retirement message is provided

**Comment by Atmosfearful** [comment]
I'm looking at the figma now, here is my feedback
* [ ] (organization nitpick) Move this to /portfolio folder in figma, which is the page where this flow takes place. Right now it's in `Retire` which isn't a view that we have built yet.
* [ ] Remove orange Price tag
* [ ] Remove all the pricing info in the Total Price card
  - I'm not sure what info is relevant to show in its place. Maybe project token info?
* [ ] It might be nice to show the 0x address somewhere w/ a copy address button and/or a link to view that token's info on polygonscan.
  - Similarly it might be nice to show either the C3 or Toucan generic icon, and the Token Symbol  e.g. `C3T-VCS-1188-2015` or `TCO2-VCS-1190-2017`
* [ ] a breadcrumb to show that this is a subview of /portfolio and help the user find their way back if needed

**Comment by jabby09** [comment]
@0xMakka the questions you had in the figma designs...I added responses but please take look at the to-do notes for this ticket above, should cover off what you are looking for.

Ideally as these are done you can check them off.

**Comment by 0xMakka** [comment]
@jabby09 thanks for this, I initially read through these when I started but completely crossed my mind that the details on the other questions I asked in the figma were in this ticket. Checking them off as I'm addressing them and putting in the necessary changes.
