### ISSUE TITLE
[api] Update carbonmark-api to pass down an `images` property

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1093]
Specifically needed for:

`/api/projects/vcs-1764-2020` https://api.carbonmark.com/api/projects/VCS-1764-2020

**Comment by Najada** [comment]
@jabby09 thank you. All clear. On it.

**Comment by jabby09** [comment]
@Najada @Atmosfearful project images for https://api.carbonmark.com/api/projects/VCS-1764-2020 have been uploaded. 

Note that we need the image caption data as well (in this case, each image has the same caption).

Images are in the order they should be shown in the carousel.

![Screenshot 2023-04-27 at 9 30 03 AM](https://user-images.githubusercontent.com/103535195/234862496-698c7241-d517-45d1-a4d4-612b91989d96.png)

**Comment by Najada** [comment]
hi @jabby09 , I added this field, but I dont not see these images on sanity for the particular project you mentioned.

<img width="1220" alt="image" src="https://user-images.githubusercontent.com/34971891/235174722-044659e9-938d-46a7-9973-c30dda3ad57f.png">

**Comment by jabby09** [comment]
> hi @jabby09 , I added this field, but I dont not see these images on sanity for the particular project you mentioned. The images field appears empty.
> 
> <img alt="image" width="1220" src="https://user-images.githubusercontent.com/34971891/235174722-044659e9-938d-46a7-9973-c30dda3ad57f.png">

@Najada very weird, I added them and now they are gone. I'll have to ask atmos

**Comment by jabby09** [comment]
@Najada @Atmosfearful 

The images got blown away when Marcus re-uploaded the Verra data to fix an issue in the project names

More from @0xAurelius 

> we can't just upload images manually onto the same Type
> I reuploaded the Verra data to fix an issue in the project names
> and it wiped out your manual uploads
> we need a separate Type like `ManualEnrichments` 
> and then a separate one like `AutomatedEnrichments` for any script-based enrichment like what Sy is working on for project descs
> frontend team should be able to handle adding those separate entities to the Sanity schema and reading from them for the photos instead of from the main Type (just use Project ID as the unique identifier to look up against)
> But if I need to step in let me know

**Comment by jabby09** [comment]
@Najada a new "Type" has been added to Sanity. Not sure if this impacts your api work or if the images property you pass is the same regardless of project-data type?

![Image](https://user-images.githubusercontent.com/103535195/235916080-11bf9880-adf5-49f8-a744-93447d42d3d0.png)

**Comment by Najada** [comment]
hi @jabby09 this changes a bit the queries I run on the backend. I will update the previous solution to support this new change.

**Comment by Najada** [comment]
@jabby09 i changed the query and I now passing the images of the project down (caption plus URL)

Example: https://api.carbonmark.com/api/projects/VCS-1764-2020
