### ISSUE TITLE
[project details] Create a ProjectMediaCarousel

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1094]
[Design is here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=11-60104&t=26s4JQ0g3hCMiYlx-0).

**Notes:**

- If the project does not have images, only show the map as it appears now
- Fade on either end when there's more images that direction (see designs for details)
- Info icon on the image supports image attribution information
- Auto-scrolling is a long term objective and not required for initial implementation

<img width="776" alt="Screenshot 2023-04-26 at 5 32 25 PM" src="https://user-images.githubusercontent.com/103535195/234695631-7dbffeed-2e60-44c0-86d1-808e334ad307.png">

**Comment by jabby09** [comment]
@0xMakka related backend tickets
#1092 
#1093

**Comment by jabby09** [comment]
@0xMakka 
There is currently only one project that will have images for the carousel.
![Screenshot 2023-05-09 at 9 18 02 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/12d6bc8d-8fc5-470c-a297-a5e9dff4f6ac)

**Comment by jabby09** [comment]
@0xMakka comment from Najada in #1093 

```
i changed the query and I now passing the images of the project down (caption plus URL)

Example: https://api.carbonmark.com/api/projects/VCS-1764-2020
```

**Comment by 0xMakka** [comment]
@jabby09 picking this ticket up again - is there any active projects that have images? the one above for [VCS-1764-2020](https://api.carbonmark.com/api/projects/VCS-1764-2020) doesn't seem to be working ant longer as the images object is returning null.

**Comment by jabby09** [comment]
> @jabby09 picking this ticket up again - is there any active projects that have images? the one above for [VCS-1764-2020](https://api.carbonmark.com/api/projects/VCS-1764-2020) doesn't seem to be working ant longer as the images object is returning null.

yea this project https://carbon-projects.sanity.studio/desk/projectContent;content-VCS-1764

but we recently did another data upload there so maybe we broke something in the api call, I'll have to follow up with @Najada

**Comment by Najada** [comment]
@jabby09 @0xMakka something has changed on the schema. Is the entity still called  `projectContent` ?

**Comment by jabby09** [comment]
> https://api.carbonmark.com/api/projects/VCS-1764-2020

@Najada @0xMakka I checked the sanity document again and it had publishing errors. I fixed those and published the doc and the api (https://api.carbonmark.com/api/projects/VCS-1764-2020) looks like it is working again, at least I can see the image urls
