### ISSUE TITLE
[retirements] Import /retirements pages to Carbonmark as-is

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1095]
This ticket replaces #1018 which originally described more comprehensive re-write of how we fetch data and render the pages and handle 404s.

Instead, in the interest of time, I think we should do a hard copy-paste of our existing /retirements/[address] and /retirements/[address]/[index] pages to carbonmark, tweaking only the design items highlighted in #1088 

After this ticket is complete, @theprofessora should have by then completed the fully redesigned carbonmark version of the retirement pages. When we implement the new designs would be a good time to consider the enhancements described in #1096 and #1018

# Considerations

Some of the elements in the KlimaDAO retirements pages are not relevant in carbonmark. We have highlighted these in #1088

**Comment by jabby09** [comment]
@0xMakka here is starting copy for About Carbonmark sections...

> Carbonmark is an all-in-one platform for the carbon markets. With millions of carbon credits available, the platform allows users to quickly list, acquire and offset Digital Carbon Credits with no additional fees. Carbonmark aims to reduce barriers to entry to the Digital Carbon Market, and empower market participants to better interact with one another. Learn more on our [resources page](https://www.carbonmark.com/resources).
