### ISSUE TITLE
[user] Check for latest activity timestamp instead of array length

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1100]
## Description

When a user is creating or editing a listing on the Profile page
Or when a user is creating a listing on the Portfolio page
and the contract transaction was successful 
=> the frontend polls the backend API for this user endpoint **every second** to wait until the user's activity has been updated
=> Check: the length of the activity from the backend response should be longer as the current one on the client
=> If true: Backend successfully updated the user's data !

## Problem

- [ ] As this check for the length of the activity of a user is a crucial check => the length should not be limited on the backend API response
- [ ] Please check if this is currently the case. From my testing it looks like the user's activity is limited to 100 entries

## Solution

- [ ] instead of checking for the length of the array => check for the timestamp in the latest activity item
- [ ] => See discussion below

**Comment by Najada** [comment]
@ladytrekker why not just listen to the activity event we dispatch from the contract?

**Comment by ladytrekker** [comment]
> @ladytrekker why not just listen to the activity event we dispatch from the contract?

Hi @Najada 

From the discussion in the former ticket, there is no event for the Activity:
- See your comment https://github.com/KlimaDAO/klimadao/issues/1008#issuecomment-1502222729

Can you point me to the event you mean in the ABI please?
- Here is the ABI https://github.com/KlimaDAO/klimadao/blob/staging/lib/abi/Carbonmark.json

**Comment by Najada** [comment]
**NewListing** -> event emitted when a new listing is added, second argument is the user wallet address.
**UpdatedListing** -> returns listing id - which can be compared to the current listings the user has on his portofolio. Or, when we upgrade we can add the user wallet on this event as well.

**Comment by Atmosfearful** [comment]
Event listener would be ideal, but I'm worried that there is still a delay between when the RPC triggers an event, and the API gives us the latest event data.

Another option is to rely on the event data itself rather than the length of the events data.

In SellerConnected/index.tsx it could look like this
```ts
      // API is updated when new activity exists
      const activityIsAdded = (prevTimestamp: number) => (newUser: User) => {
        const { timestamp } = newUser.activities[value.activities.length - 1];
        return timestamp > prevTimestamp;
      };

      const updatedUser = await pollUntil({
        fn: fetchUser,
        validate: activityIsAdded(user.activities[user.activities.length - 1].timestamp), // pass timestamp using closure, not sure if closure is needed
        ms: 1000,
        maxAttempts: 50,
      });
```

**Comment by ladytrekker** [comment]
> Another option is to rely on the most recent event timestamp rather than the length of the events array.
>

I like the idea with the timestamp.
If everyone agrees, I will take over this ticket next week and change from array length to timestamp.

**Comment by Najada** [comment]
@Atmosfearful if we are able to listen to the event, we have already registered the record on the subgraph, so we can safely query again the API.

**Comment by Atmosfearful** [comment]
hm I assumed there is delay between RPC emitting the event and subgraph indexing the event, is that not true?
Timestamp solution is easy enough let's try that out.
