### ISSUE TITLE
[purchase] Listing purchase page needs a width constraint / grid column

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1113]
![image](https://user-images.githubusercontent.com/88635679/235960857-67d60dc2-afc3-4c04-9c73-3fe029aae88e.png)

**Comment by jabby09** [comment]
@sprrwhwk I don't think this is an issue anymore but would be good if you could please check

If not, please just close this one.

**Comment by jabby09** [comment]
btw the create a listing feature is turned off in production but I assume you can still see the underlying code in your dev environment.

**Comment by sprrwhwk** [comment]
> btw the create a listing feature is turned off in production but I assume you can still see the underlying code in your dev environment.

Will the feature be re-enabled in the future?

**Comment by jabby09** [comment]
> Will the feature be re-enabled in the future?

yes but may be a few months. dependant on a carbonmark contract upgrade which is currently under discovery.

**Comment by sprrwhwk** [comment]
@jabby09 This doesn't seem to be an issue any longer


<details>
  <summary>Screenshot</summary>

![Image](https://github.com/KlimaDAO/klimadao/assets/138768831/7394b83f-4638-4649-a16b-f7672c135136)

</details>
