### ISSUE TITLE
[connect modal] Fix default wallet provider display on login modal

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#1132]
![image](https://github.com/KlimaDAO/klimadao/assets/91024694/b9d0accf-c637-4bdb-8c6b-14c121a45976)

When user is using Frame or similar non-standard browser-based wallets, we should have a cleaner default logo with the right sizing so it's consistent with the other options

Most other sites use the 🤑 emoji 
![image](https://github.com/KlimaDAO/klimadao/assets/91024694/911e1561-50a3-4954-92d9-9601f97fa151)

**Comment by jabby09** [comment]
@theprofessora @Atmosfearful thoughts on this one?

Design fix will be easy once a decision is made but atmos is this easy to detect in code?

**Comment by theprofessora** [comment]
Does that emoji (or emojis in general) fit in with our brand? I haven't seen us use emojis elsewhere, and I wonder whether the use of one here affects our outward messaging. Give me a few minutes to make an icon that might fit better.

**Comment by theprofessora** [comment]
What do we think of this option? (also found here: https://www.figma.com/file/uNBByAKEShEf3ryOX3R3Q2?node-id=0:1#441926387)

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/c7333c31-2c4f-453e-9e84-4a447a522fd1)

**Comment by jabby09** [comment]
@0xMakka more of an edge case but since we have the design might as well get it done
