### ISSUE TITLE
[resources] Not working in some languages

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1144]
## Description

When browsing the /resources page in a language other than english
=> no articles are shown.

**Compare:**
- https://www.klimadao.finance/resources  ✅ 
- https://www.klimadao.finance/de/resources 👎 
- https://www.klimadao.finance/fr/resources  👎 
- https://www.klimadao.finance/zh-CN/resources ✅ 
- https://www.klimadao.finance/es/resources 👎 
- https://www.klimadao.finance/hi/resources  👎

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO @Atmosfearful I'm not fully up-to-speed on translations, is this a known issue?

**Comment by ShimonD-KlimaDAO** [comment]
@jabby09 - the handful of articles showing in zh-CN have been translated. The rest have not been translated, and other languages do not have any translated articles. I believe this was a one-off task initiated by Drew.

I think that every article missing a translation in any language should show in English. Otherwise we have an empty translated resources page. 
@Atmosfearful - could you please reassign this to the appropriate developer?

**Comment by psparacino** [comment]
> > @jabby09 - the handful of articles showing in zh-CN have been translated. The rest have not been translated, and other languages do not have any translated articles. I believe this was a one-off task initiated by Drew.
> > I think that every article missing a translation in any language should show in English. Otherwise we have an empty translated resources page. @Atmosfearful - could you please reassign this to the appropriate developer?
> 
> @psparacino is this something you can pick up? Seems like it should be a quick change.
> 
> Please let me know if you need additional content or requirements.

Sounds good, I'll pick this one up

**Comment by psparacino** [comment]
@jabby09 I have a question on this I can drop into the discord; is it possible to give me back the contributor role so I can get to the engineering channel? I lost it in the hack yesterday. 

The question is that currently I don't see a unique identifier between translated posts. Therefore I don't see a way to filter which posts have translations and then provide the rest in default English. I could do all or nothing, but that doesn't sound like the preferred out come here.

**Comment by jabby09** [comment]
@psparacino will do on discord access

would need @Atmosfearful to address your question

**Comment by ladytrekker** [comment]
@psparacino Concerning your question in discord:

## Extend CMS with more languages

- [ ] extend the post.js schema in /cms repository with all languages [here](https://github.com/KlimaDAO/klimadao/blob/staging/cms/schemas/post.js#L29-L40)
- [ ] make sure that you use the same locale strings as in next.js (compare [here](https://github.com/KlimaDAO/klimadao/blob/staging/lingui.config.js#L7), use only production languages?)
- [ ] Deploy to Sanity so that the authors can flag the posts with the correct language (see screenshot below)

### Screenshots

![Bildschirmfoto 2023-05-23 um 11 02 50](https://github.com/KlimaDAO/klimadao/assets/95881624/4f005fda-3a1e-49b1-b137-294f3e1fe06e)

## Run CMS locally

- [ ] cd into /cms, run `npm run dev`, open http://localhost:3333/vision and put in your test queries
- [ ] you can tweak your queries here to test the return values (for example adding "locale" to the return queries etc)
- [ ] See screenshot below
![Bildschirmfoto 2023-05-23 um 11 17 02](https://github.com/KlimaDAO/klimadao/assets/95881624/c08e11df-ed52-414a-b99d-23c255154aea)

### BUG

- [ ] looks like this fallback does not work properly (see code [here](https://github.com/KlimaDAO/klimadao/blob/staging/site/lib/queries.ts#L17))
- [ ] when running the cms locally (see steps above) you can try it out yourself

**Comment by ladytrekker** [comment]
### BUG

- [ ] looks like this fallback does not work properly (see code [here](https://github.com/KlimaDAO/klimadao/blob/staging/site/lib/queries.ts#L17))
- [ ] First, change `(locale == $locale || (!defined(locale) && $locale == "en"))`  to `(locale == $locale || (!defined(locale) && locale == "en"))` => the latter has to be "locale" not "$locale"
- [ ] Still, this will return either posts with defined AND matching locale OR with which have no locale defined AND are in "en" in Sanity => the latter will always be empty (there can not be posts without a locale defined AND be in "en")
- [ ] Or ensure in Sanity that either "en" is not an option to choose, or always default to "en" when creating posts within Sanity so that the "locale" is always defined (update the posts schema with a default option)
- [ ] when running the cms locally (see steps above) you can try it out yourself and play with several options
