### ISSUE TITLE
[projects] Update descriptions from enriched content

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1149]
Enriched and enhanced project descriptions have been created using a custom GPT script by Sy Zygy, uploaded to Sanity via script.

Need to update the API to include project long and short description from the new Sanity type and then update the frontend to reflect that new data.

Project Content here: https://carbon-projects.sanity.studio/desk/projectContent
Has a `Short Description` and `Long Description` field

Long description will be used on the project details pages.
Short description will be used on the project cards in the marketplace and meta description tag.

**Comment by jabby09** [comment]
hi @Najada 

Need the API (https://api.carbonmark.com/api/projects) updated to have a short and long description field that is pulling data from https://carbon-projects.sanity.studio/desk/projectContent

**Comment by Najada** [comment]
hi @jabby09, okay pretty clear. The new API fields with be:

- `short_desc`
- `long_desc`

**Comment by jabby09** [comment]
> Long description will be used on the project details pages.
> Short description will be used on the project cards in the marketplace and meta description tag.

@Najada oops, sorry I thought I had addressed those

1. No, the new long_desc will replace that but let me 100% double check that we don't need the verra default project description for anything else.

2. Yes (assuming I understand your question)

Long description will be used on the project details pages.

<img width="1020" alt="Screenshot 2023-05-25 at 11 54 03 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/fb3d9e60-8278-4b83-af51-49e41d458405">

Short description will be used on the project cards in the marketplace.

<img width="323" alt="Screenshot 2023-05-25 at 11 54 26 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/9af210ca-f2c2-4d1b-8401-0b6280aaf98a">

**Comment by jabby09** [comment]
hi @Najada did this backend work get completed? thanks

**Comment by Najada** [comment]
hi @jabby09 

Yes. 

On the "/projects" endpoint, I added two properties:

- `long_description` (I kept the name as "description" for consistency with the previous name).
- `short_description`.

On the "/project/{projectId}" endpoint, I added the property `long_description`.

Furthermore, I also made an update, and now the initial response time is 1980ms, which is much faster compared to the previous ~2s response time.

**Comment by Najada** [comment]
hi @jabby09 okay, I will enable the same logic for short_description as well.

**Comment by Najada** [comment]
@jabby09  delivered on prod!

**Comment by jabby09** [comment]
@0xMakka over to you now on the front end.

For the /projects endpoint (which powers the marketplace cards)...

- [ ] Replace `description` with `short_description` for the project cards. **_Note...if a project does not have a short_description, then description should be the fall back._**

For the /project/{projectId} endpoint (used for project details description)...

- [ ] Replace Replace `description` with `long_description` for the project details description. **_Note...if a project does not have a long_description, then description should be the fall back._**

**Other notes & considerations:**

- [ ] Note the markup in `long_description` to ensure the spacing and styling matches this:

![Screenshot 2023-06-01 at 11 16 22 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/cbc76dab-8c9a-477c-b3cc-b0df42bc579e)

- [ ] Beyond project descriptions, we need to ensure we are changing other locations that use this data. One example is the retirement receipt.
