### ISSUE TITLE
[carbonmark-api] Identify default pool projects

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1156]
# Summary
API responses should indicate if a pooled project is the default for that pool, and show a lower price.

# Background
Every pool has 1 'default' project.
The default project is cheaper to retire and redeem (because it does not cost a % redemption fee).
Currently, **we do not differentiate the default projects**.

Going forward, we should.
- We need to know if the selected project is a default so we can choose the the correct retirement aggregator method `toucanRedeemPoolDefault` instead of `toucanRedeemPoolSpecific`.

Here are the defaults for each pool. It's the project with the oldest vintage.
- [BCT](https://www.carbonmark.com/projects/VCS-191-2008) - 0xb139c4cc9d20a3618e9a2268d73eff18c496b991
- [NCT](https://www.carbonmark.com/projects/VCS-1529-2012) - 0x6362364a37f34d39a1f4993fb595dab4116daf0d
- [UBO](https://www.carbonmark.com/projects/VCS-1140-2015) - 0xd6ed6fae5b6535cae8d92f40f5ff653db807a4ea
- [NBO](https://www.carbonmark.com/projects/VCS-981-2014) - 0xb6ea7a53fc048d6d3b80b968d696e39482b7e578

# Requirements for `/api/projects/[project_id]`
* [ ] Indicate if a project in the `prices` array is the pool default with a boolean.
* [ ] Show the discounted price, excluding all fees. This should match the price for 1 tonne shown in the klima app ui:
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/9dd36662-9a0e-4830-b1de-6d42e2a20829)

# Requirements for `/api/projects`
* [ ] show the discounted price, same as above

# Considerations
This method `getScoredTCO2s` on BCT and NCT tells us the projects held in the pool. The first address returned in the array is the default project.
https://polygonscan.com/address/0x2F800Db0fdb5223b3C3f354886d907A671414A7F#readProxyContract#F21
For UBO and NBO this method is called `getERC20Tokens`
https://polygonscan.com/address/0x2b3ecb0991af0498ece9135bcd04013d7993110c#readProxyContract#F11

I am not aware of a better way to determine which projects are default. Subgraph perhaps?

There are a few ways we can implement this, each has tradeoffs.
The default project should only change every few months, so whichever solution we use, it should be cached, and **not invoked every request**.
Idea 1 - fetch from smart contracts directly - cache the result in memory and reuse across all requests.
Idea 2 - fetch defaults at build time (daily) or first run-time (when the microservice instantiates)
Idea 3 - hardcode. I think this is the easiest option for now as volumes are low. When a default project runs out of pool supply, it will disappear from the listings, and should cause no harm.

**Comment by Atmosfearful** [comment]
If we decide to modify the `prices` array for #1160 to include both `poolTokenAddress` and `projectTokenAddress`, we could also include `isPoolDefault` That should be all the info we need.

**Comment by Atmosfearful** [comment]
Also, please update the price of each default project in API responses to reflect the price given by `RetirementAggregator.getSourceAmountDefaultRetirement()` which is cheaper

**Comment by Najada** [comment]
@Atmosfearful  where can I find RetirementAggregator.getSourceAmountDefaultRetirement()?

**Comment by Najada** [comment]
> Also, please update the price of each default project in API responses to reflect the price given by `RetirementAggregator.getSourceAmountDefaultRetirement()` which is cheaper

@Atmosfearful can you please help me with a hint here. Where can I find this `RetirementAggregator.getSourceAmountDefaultRetirement()`?

**Comment by ladytrekker** [comment]
@Najada 

On the client we use the Klima Aggregator contract to retrieve the final costs of a retirement.
The aggregator provides two different methods to calculate the final retirement costs depending on if the selected token is a 
project's pool default token or not. `getSourceAmountDefaultRetirement` or `getSourceAmountSpecificRetirement`

I guess you did not need this contract at any place so far.
Only for your information, here are the docs:
https://docs.klimadao.finance/developers/contracts/retirement/v2-diamond

@Atmosfearful Was your comment above connected to the refactoring Najada already did in this ticket here https://github.com/KlimaDAO/klimadao/issues/1160 ?

**Comment by Najada** [comment]
@ladytrekker, thank you. I added the `isPoolDefault` property, do I also need to update the price, or is it something you guys are doing on the FE?

**Comment by ladytrekker** [comment]
@Najada 

If I get this right, see this page for example:

https://carbonmark-git-lady-redeem-klimadao.vercel.app/projects/VCS-981-2014/purchase/pools/nbo

=> this is the pool default according to the updated price data of the carbonmark API
=> calculating the total costs with method `getSourceAmountDefaultRedeem` from the Klima Aggregator contract
=> **RESULT:** the final costs are less/smaller than the single unit price
**=> QUESTION:** Is it possible that the single unit price of a pool price from the carbonmark API is not the correct one for a default pool price?

**Comment by Atmosfearful** [comment]
> Is it possible that the single unit price of a pool price from the carbonmark API is not the correct one for a default pool price?

I would need to double check the code to see how we fetch prices, but yes this is probably an issue right now.

> do I also need to update the price

Yes please, for all projects in the /projects response, we should show the `best price` for 1 tonne.
The lowest price could be one of 3 possibilities:
1. It could be a listing (just show the exact listing price)
1. It could be a default project in a pool. In this case the price shown is the same as  `getSourceAmountDefaultRetirement()` for 1 tonne.
1. It could be a specific project in a pool, same as `getSourceAmountSpecificRetirement()` for 1 tonne
 
Likewise for the `/projects/[project]` endpoint, the prices in the array of `prices` should reflect whether thats a default or not.

### Engineering considerations...
At most it would be 8 requests to the RPC:
- get the default price for 1 tonne, for the 4 pools
- get the specific price for 1 tonne, for the 4 pools

This poses a significant performance challenge, let's hope the subgraph can give us these prices in 1 request...

**Comment by Atmosfearful** [comment]
I'm going to try and get a PR up for this by EOD today
