### ISSUE TITLE
[carbonmark-api] Differentiate project tokens

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1160]
A project like this one: https://api.carbonmark.com/api/projects/VCS-981-2014

Can be bridged on multiple bridges, and pooled in multiple pools.
It has a C3T address and a TCO2 address.

**Currently, the API only gives us the TCO2 address**. So when I want to selectively retire from NBO, I don't know what the project token address is.

This will pose a problem for "retire now" from pools @jabby09 @ladytrekker

**Comment by Najada** [comment]
@Atmosfearful Added these 2 fields on the /project/{projectid}. 
- `c3TokenAddress `
- `tco2TokenAddress`

When we start using this, we can remove the attribute `projectAddress`

**Comment by Atmosfearful** [comment]
@Najada I was hoping we would include that info in the prices array, which would make it easier for us on the frontend to know which is which.

Is that more difficult to do or is there a reason you went with these 2 properties?

This was what I tried to note in this hasty comment I left here while we were on the call (sorry if I did not make that super clear) 
https://github.com/KlimaDAO/klimadao/issues/1156#issuecomment-1568676421

**Comment by Najada** [comment]
@Atmosfearful becuase they will be the same for each of the prices.  But, i can change and update the prices array, no problem.

So C3T token address from UBO/NBO.
TCO2 token addres from BCT, NCT

**Comment by Najada** [comment]
@Atmosfearful @ladytrekker changed the prices array now. 


`"prices": [
    {
      "leftToSell": "15546.729385540101416778",
      "tokenAddress": "0xd838290e877e0188a4a44700463419ed96c16107",
      "singleUnitPrice": "1.829577",
      "name": "NCT",
      "poolTokenAddress": "0xabfd6760151c7f9361cc5b03bbeebe2d7c0251da",
      "isPoolDefault": false
    },
    {
      "leftToSell": "718.479968656883258472",
      "tokenAddress": "0x6BCa3B77C1909Ce1a4Ba1A20d1103bDe8d222E48",
      "singleUnitPrice": "1.213768",
      "name": "NBO",
      "poolTokenAddress": "0xb6ea7a53fc048d6d3b80b968d696e39482b7e578",
      "isPoolDefault": true
    }
  ],`

**Comment by ladytrekker** [comment]
@Najada Thanks, looks good to me.

@Atmosfearful When you agree too, I can take over the refactoring of the pool data (retire and redeem flow).

**Comment by Atmosfearful** [comment]
Looks perfect! Thanks @Najada !
