### ISSUE TITLE
[carbonmark-api] Duplicate projects in /projects list

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1161]
2015 of this project appears twice https://www.carbonmark.com/projects/VCS-875-2015
(search the name to reproduce)
Might be related to #1160

**Comment by jabby09** [comment]
@psparacino this is old and may no longer be a bug. Requires investigation to confirm.

**Comment by psparacino** [comment]
Yes, this issue still persists

**Comment by psparacino** [comment]
Fixed in API by @0xemc 

Closing
