### ISSUE TITLE
[carbonmark-api] Migrate to new merged subgraph

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1168]
Cujo wants to understand how/where we use the subgraph to make sure the new one covers all of our needs. So we should set up a call to walk though and then come up with a migration plan.

**Comment by psparacino** [comment]
@Atmosfearful Does this new subgraph now exist as it's been a couple months since this issue was opened?

**Comment by Atmosfearful** [comment]
https://thegraph.com/hosted-service/subgraph/klimadao/polygon-digital-carbon

**Comment by Atmosfearful** [comment]
We found a bug in https://github.com/KlimaDAO/klima-subgraph/issues/76

Which breaks the supply number that is shown on a /project page for example this should only have roughly .1 tonnes remaining.
https://www.carbonmark.com/projects/VCS-981-2017

This should be fixed soon. It should only affect Toucan pools (BCT, NCT) - the `Quantity Available` in the UI is wrong.

* [ ] Start by upgrading the places where this bug is impacting the UX
  - /projects/[project-id] supply shown for a project page - in the api `getById.ts`
  - /projects in the api `get.ts`

Open questions:
* [ ] Where else do we use the old graph(s)?
* [ ] Where can we merge queries into the new graph?
* [ ] What's a good order of operations for this migration to avoid one large PR
