### ISSUE TITLE
Enable automated dependency updates

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#117]
## Problem

To maintain a Node project one need to maintain a lot of dependencies too.
Github comes with dependabot by default. However, it is still not possible to group dependencies which might be quite annoying when hosting a monorepo.
- [issue](https://github.com/dependabot/dependabot-core/issues/1190)
- [issue](https://github.com/dependabot/dependabot-core/issues/2137)

**Requirements for an alternative tool:**

- Monorepo support
- Ability to group upgrades of the same dependency in multiple sub-projects into one PR

### Solution

- [ ] Look into [renovate](https://github.com/renovatebot/renovate/) which supports [monorepos](https://github.com/apps/renovate)
- [ ] discuss the research
- [ ] integrate

**Comment by Atmosfearful** [comment]
You still think we should do this @ladytrekker ?
