### ISSUE TITLE
[portfolio] Show loading spinner when wallet is initializing

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1174]
Currently, when navigating from /portfolio to /portfolio/[asset]/retire, the login screen briefly flashes.

Two reasons:
1. if we don't utilize next.js link to do a soft (client side) navigation, the whole app will remount, which causes the wallet to reconnect.
2. when the wallet provider is initializing, we assume there is no connected wallet. It would be better to wait until the provider is done initializing before we show a Login state.

We already return an `initializing` boolean from useWeb3 and useProvider hooks, which should allow us to show a loading spinner until we know for certain there is no connected wallet.

**Comment by psparacino** [comment]
Additional items for this PR:

```
To complete the release, we need to do the following:

1. Change the URL path on RETIRE button on assets in Portfolio.

2. In the Retirement Successful modal, change the URL path on VIEW AND SHARE CERTIFICATE to new CM retirement receipt page.

3. On the new CM retirement receipt page, change the URL path to the new CM designed PDF page.
```

**Comment by psparacino** [comment]
@jabby09 Not sure I understand # 3 above-->

`3. On the new CM retirement receipt page, change the URL path to the new CM designed PDF page.`

Is this the new receipt page (below) or certificate? If not which is the receipt and which is the PDF certificate? Or is the PDF page the download?

example url: /retirements/0x2559ff0f61870134a1d75ce3f271878dcdb0eee1/20

<img width="1342" alt="Screen Shot 2023-06-06 at 9 16 10 PM" src="https://github.com/KlimaDAO/klimadao/assets/72105234/a51f781c-c4cb-46d3-8612-eaabe45989ae">

**Comment by jabby09** [comment]
@psparacino yes sorry for the confusion, the pdf is what happens when the user clicks DOWNLOAD PDF on the retirement receipt page. Related to this merged PR https://github.com/KlimaDAO/klimadao/pull/1173
