### ISSUE TITLE
[forms] On CM forms, show red ring around invalid fields

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1175]
Would be helpful if @theprofessora can just do a quick example text input component somewhere in figma for us to reference
It could be a red ring, or a red text label, or red star...

Currently its not very clear which input is invalid
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/3fcf8928-cebc-4560-acb8-a597e503e569)

**Comment by jabby09** [comment]
@0xMakka see professor's design system update above.

My understanding is that we should be able to apply this change to the component and then that will update this across all the forms in the app.

Please let me know if you need any additional requirements or clarifications?

**Comment by 0xMakka** [comment]
@jabby09 Is this still a valid ticket? Just looking at the same fields that atmos posted and when an invalid address is entered I see a red border around the input field?

![Image](https://github.com/KlimaDAO/klimadao/assets/92357475/6aa6b556-aa18-439b-b403-14b824dc60b7)

**Comment by jabby09** [comment]
@0xMakka yes agreed, seems resolved on RETIRE and BUY forms for pool projects from project details.

However, take a look at the RETIRE form from Portfolio...looks like we need to apply the same logic still on this form.
<img width="567" alt="Screenshot 2023-07-04 at 10 49 54 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/14419d54-df4d-49d1-a14f-9fd5b480ee38">

**Comment by 0xMakka** [comment]
> @0xMakka yes agreed, seems resolved on RETIRE and BUY forms for pool projects from project details.
> 
> However, take a look at the RETIRE form from Portfolio...looks like we need to apply the same logic still on this form. <img alt="Screenshot 2023-07-04 at 10 49 54 AM" width="567" src="https://user-images.githubusercontent.com/103535195/250920444-14419d54-df4d-49d1-a14f-9fd5b480ee38.png">

Thanks for this @jabby09, will get working on adding to this form.
