### ISSUE TITLE
[carbon] Add support for Coorest CC02 in CM & RA

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1180]
[KIP-37](https://snapshot.org/#/klimadao.eth/proposal/0x73667d412854816966b4951efac02923cabe9c1b9720d8480467bcc878ae74f4) passed with 178k KLIMA voting ‘for’ and 99.52% in favor.

### Motivation
KlimaDAO seeks to offer a diverse array of carbon credits to its users. This goal can be advanced by adopting new digital carbon assets that undergo review and satisfy requirements around additionality, co-benefits, monitoring, reporting, and verification (MRV), and industry acceptance.

Coorest’s goal is to expand into partner ecosystems like KlimaDAO with their blockchain-native carbon credit token to gain more adoption for their assets.

Initial review, corroborated by discussions with advisors and among the community on the RFC, found that Coorest’s CCO2 digital carbon assets satisfied minimum requirements across the aforementioned factors.

### Proposal
Add support for CCO2 tokens within KlimaDAO’s Retirement Aggregator.
KlimaDAO’s Retirement Aggregator serves as base layer digital carbon infrastructure and provides an interface for selecting digital carbon assets for retirement, as well as handling routing between disparate liquidity pools for any required trading to complete retirements. CCO2 support will allow users to retire their CCO2 tokens and create a retirement certificate via KlimaDAO’s infrastructure, as well as via Coorest’s in-house certificate generating mechanism.

### Add support for CCO2 tokens on Carbonmark.
Carbonmark is the Universal Carbon Marketplace – an open-source, publicly available carbon credit market for every organization in the world seeking to acquire, trade, or retire carbon credits. Adding CCO2 listing, trading, buying and retiring support on Carbonmark will grant exposure to this asset for our various partners integrating with Carbonmark. Importantly, it will allow CCO2 to be accessed by digital carbon market participants via the Carbonmark interface, providing the same great user experience for both digitized (a.k.a. bridged) legacy credits and digitally-native credits like CCO2.

**Comment by cujowolf** [comment]
### General reference links:
Coorest Docs: https://coorest.gitbook.io/coorest-dapp-manual/
CCO2 Token: https://polygonscan.com/token/0x82b37070e43c1ba0ea9e2283285b674ef7f1d4e2
Coorest Contract for creating PoCC: https://polygonscan.com/address/0x363ae9b7dbf55c0956a74c3be4ed0996d277a8be

An important note: CCO2 tokens represent **1kg** of carbon, and not the 1 tonne other currently supported tokens represent.

## Contracts
### Retirement Aggregator
- Need to be able to quote/discover a price. Currently tokens supported all have a KLIMA paired AMM liquidity pool to swap against. Does such a pool for CCO2 exist currently, and if so, what DEX is it using?
- Gather the required information needed to correctly mint and produce a PoCC.
- Any amounts quoted to or provided to the RA should use the native token amounts and decimals for CCO2.
- There is mention of a retirement fee for CCO2. This should be included in any quote provided.

### Carbonmark
- CCO2 tokens are already abstracted and fungible with each other, and there may not be a way to list some generated from a specific batch. Need to research the docs a bit more, but if this is the case, we will need to add support for both the contract and API to handle only having essentially one fungible CCO2 project listed.
- Work and price tokens in the native amounts, without worrying about converting between tonnes and kg.

## Subgraphs
### Polygon Digital Carbon
- Add support for CCO2 tokens, and current holders.
- Add details for NFTrees?Along with metadata on how many tokens are generated per annum for said NFTree?
- Add support for all Coorest PoCC minting and related data.

**Comment by jabby09** [comment]
This ticket and the information contained has been moved to a milestone epic in the klimadao-solidity repo
https://github.com/KlimaDAO/klimadao-solidity/milestone/1

All additional tasks for this workstream will be managed there.
