### ISSUE TITLE
[header] Add language switcher functionality (staging only)

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1183]
The design calls for a language switcher icon in-app.

![Screenshot 2023-06-06 at 9 56 26 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/acb454a7-0efa-4214-8922-eb5fac44db72)

Need updated designs for the UI when clicking the language switcher button.

Also need design for the homepage.

**Comment by theprofessora** [comment]
![Image](https://github.com/KlimaDAO/klimadao/assets/110631623/ab4d2ab6-74b5-4b33-8d2f-6477f2d1ed51)

https://www.figma.com/file/hLlyv2V4SXIwwZoauDnfZN?node-id=0:1#465380515

**Comment by jabby09** [comment]
@0xMakka couple of things for this one...

- [ ] Add the language switcher on the carbonmark homepage and in-app
- [ ] Need to get the list of current languages we support from @ShimonD-KlimaDAO 
- [ ] We don't want to ship this feature to production until all the translations are done and reviewed so we will do this as a PR and then the translators will work from the PR preview link

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO what languages do you want in the drop down for carbonmark?
