### ISSUE TITLE
Add hover tooltips to labels in the dapp views

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#12]
- [ ] Add library, I strongly recommend [tippy.js](https://atomiks.github.io/tippyjs/) for a11y and dev happiness.
- [ ] Create a `TextInfoTooltip` component with Emotion stylesheet, exported from `@klimadao/lib/components`. The TextInfoTooltip component wraps any element and shows the provided text on hover.
- [ ] Add an icon-button and tooltip for any item which merits explanation (see below)
- [ ] Info icon-button likely needs alt text because it doesn't have a visible label
- [ ] Screen-readable aria labels are correctly appended to the target element (tippy should do this out of the box)
- [ ] Double check mobile views (tap to trigger tooltip)
```
Balance: Amount of unstaked KLIMA in your wallet
Staked: Amount of KLIMA tokens already staked by you and receiving rebase rewards 
Time Until Rebase:  Approximate time left before the next round of rebase rewards
Next Rebase:  Percentage increase in your staked KLIMA at the next rebase
5 day ROI:  Percentage increase in (or "Return on Investment" on) your staked KLIMA after 5 days, assuming the current reward rate stays the same over the 5 day period and taking into account the effect of compounding. 
APY:  Percentage increase in your staked KLIMA after 1 year ("Annual Percentage Yield"), assuming the current reward rate stays the same over the 1 year period and taking into account the effect of compounding.  PLEASE NOTE THAT THE CURRENT REWARD RATE MAY CHANGE AND IS NOT GUARANTEED TO STAY THE SAME OVER THE 1 YEAR PERIOD.
Current Index: Amount of staked KLIMA you would have now if you had staked 1 KLIMA from protocol inception.
```

**Comment by Vienio99** [comment]
can I get that one ser? will work on it today/tomorrow

**Comment by Atmosfearful** [comment]
@Vienio99 YES! Go for it! Hit me up on discord if you have any questions.

**Comment by spencerrichardhenry** [comment]
This should be closed

**Comment by Atmosfearful** [comment]
> This should be closed

yup, thanks!
