### ISSUE TITLE
[pdf] Accounting for no beneficiary or retirement message

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1200]
Beneficiary and retirement message are optional fields.

When missing, the retirement receipt does not show that component of the design, example [here](https://staging.carbonmark.com/retirements/0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483/16)

The resulting PDF still includes the beneficiary and a blank message as seen in this example
[retirement_16_0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483.pdf](https://github.com/KlimaDAO/klimadao/files/11706634/retirement_16_0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483.pdf)

### Requirements
If there is no beneficiary and/or retirement message:

- [ ] Remove beneficiary field from the pdf
- [ ] Remove the "" for the empty retirement message

**Comment by 0xAeterno** [comment]
I picked up this one in #1203 since it was a small change in the same space I was working in
