### ISSUE TITLE
[carbonmark api] Purchase pool transaction not shown in activity 

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1218]
## Problem

A user can buy from a project pool. 
However, these kind of transactions are not shown in the `activity` array from the Carbonmark API for a single user.

_**Note:**_
This transaction is not interacting with the Carbonmark contract but with the Retirement Aggregator instead.

**For example:**
See this transaction https://polygonscan.com/tx/0xcf7ac4f27858d0870bf21fa32e61f18b0606f3153c12d6bc26067f565ea17c1d
and the API response: https://api.carbonmark.com/api/users/0xD1a3699f2098ac92C2f4914979FCb22aba86D259?type=wallet
=> activity does not contain this transaction (possibly because this is not a carbonmark transaction)

## TODO
- [ ] discuss if and how these kind of transaction data should be included in the carbonmark API data
- [ ] discuss if this should also happen when a user retired from pool? (currently also not part of Carbonmark API)

**Comment by jabby09** [comment]
@cujowolf @ShimonD-KlimaDAO before this data would be available in the carbonmark API, am I correct in assuming we would need work done on the subgraph/contract side? Is this being considered as part of the subgraph merge work?

**Comment by jabby09** [comment]
[cujo]
it would be more of a subgraph issue since we would look at historical data. But I believe I already have this semi-staged on this subgraph https://thegraph.com/hosted-service/subgraph/cujowolf/klimadao-polygon-liquidity

Looks like I need to get the MCO2 pools added in on this one

**Comment by jabby09** [comment]
nobody has asked for this
may become relevant when we focus on activity dashboards
