### ISSUE TITLE
[carbonmark] Align all buy/retire confirm modals

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1220]
## Problem

Where we use Confirm modals during buy/purchase or retire transactions, there are slight variations on the modal UI elements, sizes, scroll etc.

## Examples

The Confirm Purchase modal (Buy from seller listing flow) has no GO BACK button, all the UI elements fit in the dimensions of the modal so no scroll required.
<img width="503" alt="Screenshot 2023-06-16 at 10 56 25 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/0e31b38c-080d-43e3-85e4-c1930c20568b">

The Confirm Retirement modal (Retire from portfolio flow) has a GO BACK button, and I need to scroll to see all the UI elements.
<img width="455" alt="Screenshot 2023-06-16 at 10 57 02 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/5defbbbd-197c-48f0-9ca2-ff7e57dc9b94">

When compared side-by-side, the modal width dimensions are not the same either.
<img width="1125" alt="Screenshot 2023-06-16 at 11 04 07 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/240c750f-c8a2-42ee-a998-14cbc696765a">

## Ask

Ideally we can standardize the dimensions and UI elements to create a component so the modal experience is the same across the site. The one question would be how to handle situations where some modals have more text content requiring a need to scroll.

Beyond Confirm modals, are there other modals used in Carbonmark that can also be standardized into a component.

**Comment by jabby09** [comment]
@theprofessora here is the UI review ticket for modals.

Let me know if you need more information.

While the focus of this ticket is the Confirm modals, I think this is a good time to look at all the different modal examples in Carbonmark and look for opportunities to standardize. Might not be able to get it down to one component but could we get it down to two or three components to cover off the majority of use cases?

**Comment by theprofessora** [comment]
hi there, we already have a standardized modal component that is the same modal template that I have used from the beginning. the width, title, padding & spacing between elements are aligned throughout the designs.

Can be found here: https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN?node-id=0:1#475495356

To clear up confusion, i've updated the component to also include the confirm&submit modal.

**Comment by sprrwhwk** [comment]
@jabby09 I'd like to tackle this one if possible 🐞

**Comment by jabby09** [comment]
> @jabby09 I'd like to tackle this one if possible

sure but i have not had time yet to review professor's designs and define the requirements.

but if the designs and the ticket requirements are clear enough for you to work with then sure, go for it!

**Comment by sprrwhwk** [comment]
@jabby09 where do these long texts come from? On figma there's just a text that reads "Please approve the transaction.".

**Comment by jabby09** [comment]
> @jabby09 where do these long texts come from? On figma there's just a text that reads "Please approve the transaction.".

these were outcomes of other tickets, for example #1059; Sy and I came up with content/copy for the modals but the designs were likely not updated. 

whatever copy is in the current modals is correct.
