### ISSUE TITLE
[carbonmark-api] API Versioning

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1221]
What: Add versioning to existing endpoints
Why: Allow easy rollback 
How: https://www.fastify.io/docs/latest/Reference/Routes/#version-constraints

Expected Outcome:
[ ] - some_outcome
[ ] - some_outcome

Testing Criteria:
	1. do_something
	2. do_something_else
	3. expect_something

**Comment by Atmosfearful** [comment]
Versioning will help us avoid the race condition we have with builds.

Currently, if we make a breaking API change and alter the frontend to handle it, there is no way to deploy both frontend and backend changes in parallel.

In the future we need to follow this process:
1. Breaking changes must go under a new versioned URL path `api.carbonmark.com/v22/projects`
1. Old, unbroken changes must stay unchanged
1. New API versions must go to production first, in their own PR.
1. Frontend must upgrade to consume the newer API version in a subsequent PR (to avoid the race condition)
1. When we have public consumers we can come up with a deprecation scheme:
  - Choose a deletion date
  - Update all public docs to indicate deprecation, w/ upgrade guide
  - Update the old version to respond with a special deprecation header, or status code, or both.
    - If we ever built an SDK for the rest API, the SDK could consume this header and emit logs to catch developer's attention.

**Comment by 0xemc** [comment]
@Atmosfearful the only missing piece to this puzzle is how to handle hotfixes. Two options I can think of:

1. We have long running version branches and all hot fixes got to all branches
2. We only hotfix latest versions, any issues in old versions are never fixed

I vote for 2, less chance of git issues because we're not maintaining many branches and less of our dev time is used up. However if a customer is relying on say v2 we are forcing them to upgrade.

Thoughts?

**Comment by 0xemc** [comment]
After thinking about this some more I think the best solution here is to use a git tag deployment strategy. Vercel have a rough guide here:

https://vercel.com/guides/can-you-deploy-based-on-tags-releases-on-vercel

The basic idea is:

- Creation of a git tag triggers a build and deploy
- That deploy is add an Vercel alias or custom domain with the version prefix

For this I'll need to set up some github secrets so that our Vercel API keys are not exposed publicly. We should be able to create a role that allows secret access without giving `admin` privileges:

https://docs.github.com/en/enterprise-cloud@latest/organizations/managing-peoples-access-to-your-organization-with-roles/managing-custom-repository-roles-for-an-organization

@Atmosfearful is that something you would have time to set up?
