### ISSUE TITLE
[app] Remove Offset and Buy Carbon tabs from app.klimadao.finance

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1235]
Atmos edit: see comment below

- remove tab content, replace with splash pages
- remove dead code

**Comment by jabby09** [comment]
@biwano this will likely require a 1-on-1 with @Atmosfearful so just book something in his calendar when you are ready to discuss

**Comment by Atmosfearful** [comment]
We will re-orient this ticket to instead focus on removing the Offset and Buy Carbon tabs from app.klimadao.finance

Me and @biwano  agreed we should make a splash page to educate the user about carbonmark before directing them there.

Me and biwano need to discuss 
- Should we keep the retirement totals? If yes - VIEW RETIREMENTs button needs new URL to carbonmark
- What should the splash page(s) and CTA say?
