### ISSUE TITLE
Add links to governance forum and Snapshot

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#125]
Per [this Notion project](https://www.notion.so/klima-dao/Add-forum-link-and-Snapshot-link-to-main-website-8cc7c4e4623a4878b445f3f5b51c08a6), we should add links to the governance forum and Snapshot to the main website

https://forum.klimadao.finance/
https://snapshot.org/#/klimadao.eth

I think under Resources > Community makes the most sense

We can use a scroll or something as the logo for the Governance Forum and make it Klima green

For Snapshot, they have a nice lightning bolt logo that would work well for the button

![image](https://user-images.githubusercontent.com/91024694/152091445-2e8cd73f-4e66-437b-a0b4-3fa6227e9d94.png)

**Comment by 0xAeterno** [comment]
Had a play around with this one for fun. Keen to gather some feedback on what I've come up with so far :)
Styling it in the mobile version was a tad interesting with the existing resource navigational bar.
I took the liberty of adding button hover styles too, however that won't be present in the screenshots ;)

|  Desktop |  Mobile  |  
| --------- | -------- |
| ![image](https://user-images.githubusercontent.com/97446324/152355199-a09e9384-cfdf-4cff-bf5d-7843b1b32351.png)  | ![image](https://user-images.githubusercontent.com/97446324/152355384-46cfcbb2-a4e8-4e54-8b21-f23aaf58efc2.png)

**Comment by Atmosfearful** [comment]
Thank you! I'm passing this to the designer to get his approval first!
