### ISSUE TITLE
[Carbonmark] Remove 'sell' and 'list' references in text

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1251]
There are multiple references to the option of 'selling' and 'listing' carbon on the marketplace, which is currently disabled. This ticket is to track their removal or discussion of their removal.

Examples:
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/f1b01f89-d090-4ce5-b47b-d5efde09fbd6)

![image](https://github.com/KlimaDAO/klimadao/assets/99001851/42faeb33-77a0-4057-b49e-3913e5f0289d)

no listings, no sellers:
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/279a775b-cd9f-4616-8ece-1fcc265fd7b5)

![image](https://github.com/KlimaDAO/klimadao/assets/99001851/2b32d9d5-1af2-402d-9809-899f32df08bb)

**Comment by jabby09** [comment]
noted, will not fix for time being unless we get a lot of pushback/feedback from users.
