### ISSUE TITLE
[retirement receipt] ensure fallback data works

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1261]
## Description 

RELATED TO https://github.com/KlimaDAO/klimadao/issues/1096

To render a retirement receipt page, the subgraph is queried to get the retirement data for a specific index.

In some cases, the subgraph is not fast enough on this flow:
- Successfully made an retirement from a project pool ( e.g. [here](https://www.carbonmark.com/projects/VCS-191-2008/retire/pools/bct))
- Click on "Show Receipt" link in Success Modal
- => Redirect to new page with the receipt `https://www.carbonmark.com/retirements/<address>/<retirement-index>`
- This page queries the subgraph on the server for the retirement data
- If there is no data from the subgraph => get fallback data from the contract
- => Ensure to render a page with fallback data
- See the code for the page here:  https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/pages/retirements/%5Bbeneficiary%5D/%5Bretirement_index%5D.tsx

## PROBLEM
- [ ] some users reported that this receipt page ended in a 404 page (not a page with fallback data)
- [ ] Investigate when this happens (specific tokens? What does actually throw on the server?)
- [ ] Ensure that the fallback data is always working to properly render a receipt page even when the subgraph is not returning any data

**Comment by jabby09** [comment]
@psparacino @Atmosfearful 

I was able to repeat getting a 404 page again for the retirement receipt.

This was the [transaction details](https://github.com/KlimaDAO/klimadao/issues/1261)

Everything is good to the Retirement Successful modal:
<img width="613" alt="Screenshot 2023-07-07 at 11 11 31 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/8a743a2e-e243-4bb5-80cc-17a3cf892f31">

When I click SEE YOUR RETIREMENT RECEIPT I get a 404 page:
<img width="1047" alt="Screenshot 2023-07-07 at 11 11 42 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/f84d50ef-dd74-47c5-a0ca-895ea30adfd1">

If I refresh the page a couple of times the receipt then does render properly: https://www.carbonmark.com/retirements/0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483/24

**Comment by Atmosfearful** [comment]
@psparacino is working on some refactors that will simplify this & improve performance, we will simplify the code so we never check the RPC for anything. This means, intentionally, 404s **will happen** when the subgraph is behind #1018 

we will create a simple poller util that waits for the subgraph to catch up to a specified block number (which we know in advance, from the txn receipt), before navigating the user to the page #1096 

Finally, in the future, we can enhance the retirement page and do a formal fallback design this time. I created #1290 to document this task, low prio.

I'll close this ticket and #578 in favor of #1096 #1018 and #1290
