### ISSUE TITLE
[devops] Remove config from vercel & env vars enhancements

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1281]
What: Extract variables from Vercel env config
Why: Developers should not need access to Vercel projects to work on the api
How: tbd

Expected Outcome:
- [ ]  developers are able to develop the carbonmark-api without requiring external tool access

**Comment by Atmosfearful** [comment]
Note from a PR review comment: https://github.com/KlimaDAO/klimadao/pull/1501#discussion_r1316377114

> On my laptop I ran into issues here, I couldn't get local firebase requests to work (firestore API was rejecting the cert). So it might be an expired cert, the wrong cert, or I did something wrong.

> Site note: I have never had problems storing the entire admin cert JSON as a string in vercel, the reason this quotation mark issue arises is because local builds rely on dotenv.

**Comment by 0xemc** [comment]
Marking as complete, the only remaining secrets in carbonmark-api are the JWT_SECRET and AUTHENTICATION_MESSAGE
