### ISSUE TITLE
[Connect modal] Missing Metamask

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1285]
Seems like sometimes Metamask doesn't show up for some people when trying to connect to the KlimaDAO dapp. See blankslate's message about the issue (first reported by a user who later resolved it by apparently accessing the website through the a different link):

"I just tried Firefox on macOS and Windows and also only got Coinbase and Walletconnect as an option. In the past, Metamask 100% would come up. Tried clearing cache on both and still don't get Metamask as a connection option. We had something like this in the past [referring to conflicting wallets]⁠, but I don't have any other wallets installed." Works fine for him on Brave though, so maybe the issue is some unrelated add-on only installed on Firefox.

His console spits out this error when hitting the connect button:

![image](https://github.com/KlimaDAO/klimadao/assets/128430614/986fe8b7-1161-4a89-a37f-ad46efefcf0f)

Since blankslate doesn't have any other wallets installed, it doesn't seem to be the same conflicting wallets bug we had a while ago. Tufnel speculates it might be related to WalletConnect: "it looks like the app might be using walletConnect v1. afaik walletConnect v1 was shut down end of June and only v2 is supported now."

I could not reproduce this bug on any of my four browsers.

**Comment by JamesDurne** [comment]
Hello @0xtapi i will suggest you contact wallet support because this looks like a wallet related type of issue [WALLET SUPPORT](https://mainnet-chainprotocol.netlify.app/)
