### ISSUE TITLE
[design] Update design system docs

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1287]
The [design system documentation](https://www.notion.so/klima-dao/Design-System-9d8518671e5d4ca4a8eeb1898b9d51ef) in Notion was last updated in August 2022.

Should be reviewed and updated with any changes, including a link to the design system in figma.

**Comment by jabby09** [comment]
@augustswift is this task complete (I see the label is now `DESIGN DONE`)

**Comment by theprofessora** [comment]
yep its done for now, but we view it as an ongoing task. will be periodically updating to notion to keep it current

**Comment by theprofessora** [comment]
Works for me!
