### ISSUE TITLE
[carbon dashboard] cosmetic updates (desktop prototype)

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/klimadao#1328]
Some stylistic and cosmetic updates to make to the desktop prototype of the carbon dashboard redesign:

- [ ] move all graph legends to the bottom of their respective cards (see mobile prototype for guidance)
- [ ] move all details buttons to the top right of their respective cards (see mobile prototype for guidance)
- [ ] make sure all cards & graphs follow the Rule of 4 (August will know what this means)

I'm thinking this would be a good first issue for @augustswift (new junior designer) to tackle. Would introduce her to our branding, our style guides, our figma component library, and have her editing the prototypes, which will be her main job function. I'll assign it to her as soon as she has her github account set up.

**Comment by jabby09** [comment]
@theprofessora assigned to @augustswift
