### ISSUE TITLE
[carbonmark design system] apply cover img consistency to figma files

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/klimadao#1329]
Would be a good 2nd issue for @augustswift.

Every figma file should contain a cover image (see [documentation](https://www.notion.so/klima-dao/Design-System-9d8518671e5d4ca4a8eeb1898b9d51ef)). Our number of figma files is growing and not all of them adhere to the guidelines, so let's take some time to unify everything once again.

**Comment by jabby09** [comment]
> Would be a good 2nd issue for @augustswift.

done cc @augustswift
