### ISSUE TITLE
Upgrade WalletConnect web3-provider to ethereum-provider

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1333]
> https://docs.walletconnect.com/2.0/advanced/migration-from-v1.x/dapps/#web3-provider

> If you are using @walletconnect/web3-provider, we stopped supporting this provider in favor of the improved version published under @walletconnect/ethereum-provider and you will be able to check the latest version on NPM [here](https://npmjs.com/package/@walletconnect/ethereum-provider).

**Comment by Atmosfearful** [comment]
This also covers our migration to V2 and should resolve some issues users are reporting with walletconnect

**Comment by 0xMakka** [comment]
Will pick this ticket up now, I had made a start on it previously but parked it to pick up other higher priority tasks.
