### ISSUE TITLE
[projects] Align project cards with design

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#1336]
The text fades out even if it fits perfectly. The cards also seem too tall in general.

<img width="484" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/564ede96-c6cf-4111-ab67-e4afd61f904a">

**Comment by jabby09** [comment]
> The text fades out even if it fits perfectly. The cards also seem too tall in general.

@sprrwhwk thanks for creating this issue, I had noted the exact same thing.

**Comment by jabby09** [comment]
@sprrwhwk @Atmosfearful btw, this did not appear to impact the card sizes on the retire page https://www.carbonmark.com/retire

**Comment by jabby09** [comment]
@sprrwhwk @Atmosfearful on the latest merge to production, the cards on the marketplace are not matching design again, they reverted back to the long format.
