### ISSUE TITLE
[retire] Reire page post launch enhancements

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1346]
@ladytrekker here is a collection of fixes / enhancements to the Retire page

- [x] Hover state on project cards on the Retire page should match hover state on the /projects cards. Currently they are reversed, i.e. when I hover on a card on the Retire page the focused card shrinks slightly in size, vs expanding.

- [x] For use case where a user has logged in at least once but does not have a Carbonmark profile, update the design to match below. [Figma design link here](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=823-9478&mode=design&t=T3zUEx2WA28aksEc-4).
![Screenshot 2023-07-19 at 3 15 12 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/706aeddf-12fb-4c2d-9373-c79782d77a58)

- [x] Featured project card descriptions should match design and be immediately following the project title, like cards in /projects:
![Screenshot 2023-07-19 at 3 17 34 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/4d58b43e-6d80-42a8-98de-0639a3ac5813)

**Comment by ladytrekker** [comment]
@jabby09 Point 2 is already integrated.

Just create a new wallet address, register on carbonmark, go to the Retire page

<img width="1283" alt="Bildschirmfoto 2023-07-19 um 20 43 07" src="https://github.com/KlimaDAO/klimadao/assets/95881624/f71d6052-ce42-4bc2-923a-4bd0e75ff7f5">

**Comment by jabby09** [comment]
> **UPDATE:** Sorry, you are talking about the other state

exactly :)
