### ISSUE TITLE
[api] user data is missing wallet address, Profile page does not work

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#1357]
## Description

The API should return this data from a user:
https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/lib/types/carbonmark.ts#L99-L107

Right now, the `wallet` data is missing which leads to several problems.

Example STAGING:
https://staging-api.carbonmark.com/api/users/0xd1a3699f2098ac92c2f4914979fcb22aba86d259?type=wallet

Example PRODUCTION:
https://api.carbonmark.com/api/users/0xD1a3699f2098ac92C2f4914979FCb22aba86D259?type=wallet

## Problem

The frontend is doing several checks on server before rendering a page to detect:

On the server:
**// USERS PROFILE**
- is the string in the URL a polygon address => continue
- is the string in the URL a ENS/KNS domain => get the polygon address
- is the string in the URL a Carbonmark User Handle => get the wallet address
- => pass the user address to the page

Continue on the client:
**// USER PROFILE: IS CONNECTED USER**
- check if a wallet is connected
- compare the polygon address (retrieved above) with the connected wallet address
- => HIGHLIGHT MENU correctly
- => show different texts and data
- => etc etc 

## CURRENT BUG in UI
- The Menu does not highlight "Profile" correctly when **a connected Carbonmark user** is looking at the own profile URL with the handle
- The User Profile page detects this user as **unconnected**
- => the user is unable to edit her own profile

Try yourself with a registered Carbonmark User:
1. https://www.carbonmark.com/users/login
2. Login
3. => redirect to the unconnected profile of your user
4. Unable to access your editable profile page

**Comment by Atmosfearful** [comment]
I'm not able to reproduce this. Feel free to reopen if you are @jabby09
