### ISSUE TITLE
[tech] Firestore Performance Testing

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#1360]
@Atmosfearful 

Branch with tests on it here: https://github.com/KlimaDAO/klimadao/tree/tufnel/endpoint-performance-918

Tests in `carbonmark-api/src/speedTests`

I realized after creating the tests the the ticket was supposed to come first, sorry about that. Progress so far:

1. Created a separate collection in firestore called `usersTesting`
2. Created 1000 random users in the collection
3. Copied over the 19 existing users into usersTesting so in the usersTesting collection there are 1000 random users and 19 actual users
4. Compared retrieving those 19 users out of the 1019 using three methods:
- `await Promise.all(ids.map(id => db.collection('usersTesting').where('address', '==', id).get()));`
- `await db.getAll(...ids.map(id => db.collection('usersTesting').doc(id)));`
- `await Promise.all(chunks.map((chunk) => db.collection('usersTesting').where('address', 'in', chunk).get()) );`

8. Returning target users out of whole collection :

> whereTest duration: 697 ms
> getAllTest duration: 159 ms
> inTest duration: 156ms

9. If returning all users in a collection:

> whereTest duration: 1077 ms
> getAllTest duration: 975 ms
> inTest duration: 291 ms

where-in wins when returning from a large collection.

Current changes in `fetchMarketplaceListings`.

### End result in performance of `carbonmark-api/src/routes/projects/getById.ts`:

**Original (not using getAll, multiple firestore calls):**

Promise.all in `getByID`: 1.1 -1.4 s

`fetchMarketplaceAndListings`: 918 ms

**Using getAll for one firestore call to create a user map:**

Promise.all in `getById`: 574 ms-682ms

`fetchMarketplaceAndListings`: 167 ms-335ms

**Using where-in for one firestore call to create a user map):**

Promise.all in `getById`: 368ms-537ms

`fetchMarketplaceAndListings`: 143.586ms-280ms

Where-In is by far the fastest in the tests, but that performance jump is not fully reflected in the handler itself yet, so there might be other factors slowing it down

**Comment by Atmosfearful** [comment]
Can you try the `in` operator from firestore:

```
const snapshot = await usersTestingCollection.where('address', 'in', ids).get();
```

Note the limitations in the docs: array can not exceed 30 entries. https://firebase.google.com/docs/firestore/query-data/queries#limitations_3
