### ISSUE TITLE
[retire] Retiring on behalf of another beneficiary & receipt errors

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1370]
As [identified by chaz](https://discord.com/channels/841390338324824096/1088366833687609374/1133072239030452224)

For pool listings, retire form, if I select another beneficiary for the retirement like so:

<img width="461" alt="Screenshot 2023-07-25 at 10 33 11 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/6f52b724-2d4c-462d-a9cb-c3d5604b3288">

Once the retirement is successful, the retirement receipt we link to the `SEE YOUR RETIREMENT RECEIPT` button is incorrect.

<img width="975" alt="Screenshot 2023-07-25 at 10 28 50 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/a3bc407b-7bd3-46ea-a98b-a6647293267c">

As you can see in screenshot above, the URL generated is for the logged in wallet and retirement 1. In this example, the user is redirected to [this receipt](https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/1)

Again for this example, the receipt URL should be https://www.carbonmark.com/retirements/0x3d23E091Cd16FaB640e7695D9682864BD4FC7D6e/1

So the receipt number is correct, but wrong wallet.

**Comment by Atmosfearful** [comment]
We will probably want to do a call to kickoff this one @sprrwhwk

**Comment by jabby09** [comment]
> We will probably want to do a call to kickoff this one @sprrwhwk

@Atmosfearful @sprrwhwk sure, no problem. I'm only available Mon - Wed morning next week then on a summer holiday until the 14th.

**Comment by sprrwhwk** [comment]
@Atmosfearful I've scheduled one for tomorrow. We can start this then!
