### ISSUE TITLE
[projects] Pool project missing from /projects API results

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1372]
Reported [here](https://discord.com/channels/841390338324824096/964698337230086174/1133764747687366737)

This is the [verra link](https://registry.verra.org/app/projectDetail/VCS/812) for the project

Project details page exists in Carbonmark: https://www.carbonmark.com/projects/VCS-812-2009

However, when I search for `VCS-812` in the /projects API (https://api.carbonmark.com/api/projects) I get zero results.

1. Why is this project not being returned the /projects API call?
2. Are we also missing other projects?

**Comment by Atmosfearful** [comment]
Here is the subgraph query that we invoke in the projects handler here on [Line 104](https://github.com/KlimaDAO/klimadao/blob/493d01df32a571a13818ef80c989f8cb226227a3/carbonmark-api/src/routes/projects/get.ts#L104)
I stripped it down and passed "overseas" directly, and I do see bullrun there.

https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/graphql?query=query+findCarbonOffsets+%7B%0A++carbonOffsets%28%0A++++first%3A+1000%0A++++where%3A+%7B%0A++++++name_contains_nocase%3A+%22overseas%22%0A++++%7D%0A++%29+%7B%0A++++id%0A++++name%0A++++tokenAddress%0A++++vintage%0A++++vintageYear%0A++++bridge%0A++++projectID%0A++++methodology%0A++++methodologyCategory%0A++++country%0A++++category%0A++++name%0A++++registry%0A++++totalBridged%0A++++totalRetired%0A++++storageMethod%0A++++lastUpdate%0A++++balanceUBO%0A++++balanceNBO%0A++++balanceNCT%0A++++balanceBCT%0A++%7D%0A%7D

So this means, potential causes for this bug:
- the way we pass other parameters is breaking the query?
- a mistake where we filter and merge the results in the handler somewhere?

**Comment by cujowolf** [comment]
You should be getting Belize in that first query if you pull in the first 1000 records. 

```graphql
query getCarbonOffsetsCountries {
  carbonOffsets (first:1000){
    country
  }
}
```

Should be getting Belize in this result set

**Comment by 0xemc** [comment]
Ah interesting.. is the default response size set to 100?

This also means that if there are more than 1000 projects it's possible we could miss a country when fetching for all.

Are you able to update the resolver so that the search params are able to be undefined?

**Comment by 0xemc** [comment]
@jabby09 I've created a ticket to track this 

https://github.com/KlimaDAO/klimadao/issues/1401
