### ISSUE TITLE
[API] Move project activity to a new /activity route 

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1377]
Currently when fetching a `Project` from `/projects/[id]` we also fetch recent activity for that project.

We have identified this as a major performance cost in #1360 and #1367 - I also anticipate more features around sorting, filtering and exploring that activity.

For these reasons I think it makes sense to treat `Activity` as it's own resources and serve it from a sub-path
`/projects/[id]/activity`

This is a breaking change with a new API version. A separate ticket will be needed to consume this new activity feed on the frontend.

**Comment by jabby09** [comment]
@biwano here is a new issue for you when you are free of Klima Data tasks

**Comment by biwano** [comment]
@Atmosfearful If I understand the release process I will make 3 pull requests:

- [X] Modify the API to Create the new activity route: #1888 
- [ ] Modify the UI to use the new activity route
- [ ] Modify the API to remove activity information when querying projects
