### ISSUE TITLE
[credit card] 2000 limit error state UI issues

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1382]
See [correct designs here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=890-29761&mode=design&t=xScP6hjsOt0wjb5H-4).

The error state when exceeding $2000 limit is not displaying properly or matching the designs.

### Non-default pool project...
for example https://www.carbonmark.com/projects/VCS-1718-2013/retire/pools/nct

- [x] Total cost in the Total Price panel should be red
- [x] RETIRE CARBON button should still be greyed out

<img width="949" alt="Screenshot 2023-07-29 at 9 47 53 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/b545bdf0-75f6-42ea-93b7-39146993a255">

### Edge case
EDIT: this is a subgraph bug tracked in https://github.com/KlimaDAO/klima-subgraph/issues/76
for example https://www.carbonmark.com/projects/VCS-981-2017/retire/pools/nct
NOTE: this project has two pool listings, not sure if that is the related

- [ ] Total cost in the Total Price panel in this case is red but the total is $0.00 and we are displaying a helper text message as well (not in the design)
- [ ] No helper text message until Pay with: (as per the design)
- [ ] RETIRE CARBON button should still be greyed out

<img width="911" alt="Screenshot 2023-07-29 at 9 53 07 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/03ee86d9-2a6a-44a1-a817-2db6eb222b52">

**Comment by jabby09** [comment]
@0xemc tagging you on this one since your Monday will start well in advance of atmos and this is a high priority one.

**Comment by Atmosfearful** [comment]
The second part of this ticket should be resolved when https://github.com/KlimaDAO/klima-subgraph/issues/76 is fixed in the subgraph, so let's track it there.

I'm moving forward with Michael's PR #1391 to close this ticket.
