### ISSUE TITLE
[design] Specify the SDG for which a specific project is suitable for

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/klimadao#1387]
I don't know what this means.

**Comment by jabby09** [comment]
> I don't know what this means.

@theprofessora these are the [UN sustainability goals](https://sdgs.un.org/goals)

Here is an [example of another site](https://market.climatetrade.com/projects/en/100-mw-solar-project-in-rajasthan---corsia-elegible/?id=374) and how they are used on a project page

Or again on [senken.io](https://www.senken.io/projects/499?orderType=BUY&tradeType=spot). On senken you can actually filter on these...
![Screenshot 2023-07-31 at 4 17 09 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/f01e2c08-3d7f-4910-948f-2fc8e5a7debc)

We do have placeholder fields in our backend projects database but I'm uncertain if the data is populated yet or if the API exposes it. Those are technical details that will need to be sorted out when displaying and using SDGs on the front end.

![Screenshot 2023-07-31 at 4 17 55 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/ab5ac736-a655-46ce-b364-5912ef149dce)
