### ISSUE TITLE
[design] Specify the standard / criteria that a project is suitable for - CORSIA, GEO, N-GEO.. etc

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/klimadao#1388]
I don't know what any of that means.

**Comment by jabby09** [comment]
> I don't know what any of that means.

@theprofessora 

CORSIA is [Carbon Offsetting and Reduction Scheme for International Aviation (CORSIA)](https://www.icao.int/environmental-protection/CORSIA/Pages/default.aspx)

I'm not familiar with GEO or N-GEO but sy or marcus might know.
