### ISSUE TITLE
[design] Increase Privacy potential on retirement receipts

### ISSUE THREAD

**Issue by theprofessora** [KlimaDAO/klimadao#1389]
see details here: https://www.notion.so/klima-dao/Feature-Requests-carbonmark-8752e5ae4c6f496fb5affca8a6e715ee?pvs=4#735828411bb34af9bd0318a3661634ef

**Comment by jabby09** [comment]
@theprofessora Related to #1474

**Comment by Atmosfearful** [comment]
Marking closed as this seems to be crossed off in our notion and hasn't resurfaced since.
