### ISSUE TITLE
[api] Selective redemption price estimation is incorrect

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1394]
In the handler for `/project/[project-id]` we calculate prices for each pool. We first get the pool prices from the graph, which should be fairly accurate. Then we manually derive the cost of selectively redeeming 1 tonne from that based on the known redemption fee % for each pool.

This calculation occurs here:

https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark-api/src/utils/helpers/fetchAllPoolPrices.ts#L13

Percentages are hardcoded here https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark-api/src/routes/projects/projects.constants.ts#L33

It seems we have missed the 1% aggregator fee and sushiswap fees. See [the new fee docs](https://docs.carbonmark.com/get-started/understanding-fees-on-carbonmark)

For debugging, query the aggregator directly to get a real time price for 1 tonne.

**Comment by Atmosfearful** [comment]
This might be another good learning exercise for @sprrwhwk , we can pair on this.

**Comment by sprrwhwk** [comment]
I started playing around with it in the debugger already. Let's tackle this together then.

**Comment by jabby09** [comment]
@biwano can this one be closed now?

**Comment by biwano** [comment]
> @biwano can this one be closed now?

Please leave it open @0xemc suggested I added tests to the percentage fee calculation. I will make a new PR that will close this issue.
