### ISSUE TITLE
[subgraph] Update findProjects GQL Resolver to allow null args

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1401]
In the getDefaultQueryArgs function in carbonmark-api/src/routes/projects/projects.utils.ts, we currently have a potential issue where the function may miss results if there are more than 1000 projects. This is due to the hardcoded limit of 1000 in the GraphQL query.

This could lead to a silent error where not all possible values are returned, which could affect the functionality of our application.

We need to update the GraphQL resolver to allow null search parameters to return all possible values, or implement a pagination or cursor-based solution to handle more than 1000 results.

https://github.com/KlimaDAO/klimadao/blob/634d423f444330b9e461673c229aa08b697486c2/carbonmark-api/src/routes/projects/projects.utils.ts#L19-L46

**Comment by Atmosfearful** [comment]
Pagination via query parameters is definitely the way forward. Before we hit the 1000 project limit we might run into performance issues, but for the time being no new supply is coming on chain and returning every project is working well enough

**Comment by Atmosfearful** [comment]
This requires subgraph changes so may actually need to split into separate tickets btw. I think it would be a good window to tackle this when we roll out the /carbonProjects endpoint

**Comment by Atmosfearful** [comment]
Closing here as no longer relevant for klimadao. Creating a new issue around pagination in Carbonmark.
