### ISSUE TITLE
[carbon dashboard] Design for the change language menu on Desktop and Mobile

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1421]
Maybe we can copy what as been done for CarbonMark

**Comment by theprofessora** [comment]
desktop: https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO?node-id=3086:9718&mode=design#532407805

**Comment by theprofessora** [comment]
mobile:https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO?node-id=3086:11346&mode=design#532416946

**Comment by theprofessora** [comment]
@biwano see above ^^
