### ISSUE TITLE
[tech] Migrate Ethers to v6

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1425]
https://docs.ethers.org/v6/migrating/#migrating

**Comment by jabby09** [comment]
@sidneyarida you may need to check with @0xMakka about any work on this that might have already been completed

**Comment by 0xMakka** [comment]
@sidneyarida / @jabby09 we started the work on this, but I agreed at the time with atmos to park the rest of the migration for the time being as the api was being worked on at the time, and we didn't want all the change going in at once.  

I broke it down into parts and tackled the basic util functions first (this was merged), other than that there was no other changes made - https://github.com/KlimaDAO/klimadao/pull/1516

**Comment by sidneyarida** [comment]
I almost covered all the changes of the migration on the guide.
I will need a call to check how I can test some stuff, who can help me with this?

**Comment by jabby09** [comment]
> I almost covered all the changes of the migration on the guide. I will need a call to check how I can test some stuff, who can help me with this?

@sidneyarida best approach here is create a thread in discord under engineering the the ticket number and short description and ask you question there. @0xemc and @biwano can help you
