### ISSUE TITLE
[carbon dashboard] LinguiJS forces us to use Client Components

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1427]
In order to use LinguiJS, the components must be wrapped in a I18nProvider component. But that component creates a Context. and Contexts can only be used in Client Components.

**Comment by Atmosfearful** [comment]
Check this out
https://github.com/sultan99/next.js-v13/tree/main/app

They set a dynamic route /[lang] at the route and they also wrap all the providers in a client component.

My question is, does this example still support `en` by default at the route path?

**Comment by biwano** [comment]
This is not really a problem. Server components can be used inside Client components.
Closed in favor of: https://github.com/KlimaDAO/klimadao/issues/1484
