### ISSUE TITLE
[retire] Summary QTY need more decimals on the tonnes

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1434]
As an example, see https://www.carbonmark.com/retirements/0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483 where we show the exact tonne quantity retired.

On the Retire page summary component, we are showing zero decimals so getting 0t values.

<img width="728" alt="Screenshot 2023-08-16 at 10 18 18 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d59b497b-b764-4c63-88bb-2227eacfd9e4">

We should change the QTY to support:
If > 1 tonne, show up to 2 decimals
If < 1 tonne, show up to 3 decimals

**Comment by 0xMakka** [comment]
@jabby09 the prod link above is showing a different page than the screenshot for me? Should I be seeing the page above?

<img width="1512" alt="Screenshot 2023-08-28 at 08 32 40" src="https://github.com/KlimaDAO/klimadao/assets/92357475/f206a3b1-162b-4af5-813c-566d989cf67e">

**Comment by jabby09** [comment]
> @jabby09 the prod link above is showing a different page than the screenshot for me? Should I be seeing the page above?

sorry, the URL to the screenshot is https://www.carbonmark.com/retire (as a logged in user)

the link to https://www.carbonmark.com/retirements/0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483 is a correct page, I shared as an example of showing actual retired amounts, instead of 0 on the /retire page.

Hopefully that cleared things up.

**Comment by 0xMakka** [comment]
@jabby09 Ah, cool cool that makes sense. Thanks for the explanation 👍
