### ISSUE TITLE
[navigation] Hamburger menu animation seems weird

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#1445]
Our hamburger menu animation looks a little confusing and seems inconsistent between opening and closing:

https://github.com/KlimaDAO/klimadao/assets/138768831/77abd166-3419-4ad9-80c2-e1f2da4bbb48

See here for some nice animations:

https://hamburger-react.netlify.app/

**Comment by jabby09** [comment]
@sprrwhwk perhaps discuss this one with @theprofessora before proceeding
