### ISSUE TITLE
[api] Versioned API types for frontend consumption

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1448]
# Problem
It's important that the frontend consume a stable version of the API, not the untagged commits to `main`.
It's also important that the frontend types match the API types, ideally are derived from the same `TypeBox` schemas.
So we run into a problem: we can't import directly from `@klimadao/carbonmark-api` to the frontend package.

How can we derive types on the frontend?

# Ideas
Best solution I can think of is to generate them from the openapi schema located at `[version].api.carbonmark.com/openapi.json`

1. frontend specifies an api version in a hardcoded config
2. when this version is incremented, a script needs to run to introspect the openapi schema and output to a `.generated` folder
3. components and utils in the frontend package import from these .generated types

**Comment by Atmosfearful** [comment]
One challenge right now is that `carbonmark` points to a different endpoint on staging builds.

https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/lib/constants.ts#L78-L79

This could lead to type mis-matches as staging is not versioned.

To ameliorate this I think the easiest solution is to always use a fixed version for both. Developers can configure it as-needed if they want to run a preview link or a local branch pointed at a different api version. I will put up a PR to change the default config to always be a stable API version.

**Comment by Atmosfearful** [comment]
Hmm. We will need to support testnet soon, so QA team can test on staging urls before we go live. So we will need to support a staging API that defaults to testnet, but matches the same typescript types... need to think on this a bit.

**Comment by Atmosfearful** [comment]
I'm going to move forward with FETS and try it out. Zero-codegen needed, it infers types from the openAPI spec.
https://the-guild.dev/openapi/fets/client/quick-start

If this goes well, it is a huge leap forward towards #1472

**Comment by 0xemc** [comment]
Marking this as complete since #1531 has been closed.

There are still manual types  that can be replaced but that will be a long running problem that we can solve over time.
