### ISSUE TITLE
[navigation] carbonmark footer uses suboptimal layout on small desktops

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#1461]
See how in the second row of links there is one item on the left and one on the very right which looks really unconventional.

<img width="1019" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/0a0f7d1c-768c-4eb8-83d9-dd3c409b416b">

**Comment by theprofessora** [comment]
@sprrwhwk @jabby09 let's implement some flexwrap as shown here:

https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN?node-id=1101:780&mode=design#533906740
