### ISSUE TITLE
Research: Broken Links Tester

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1468]
From my understanding, The most reccuring issue in our NextJS applications are dead links.
We could just crawl the vercel deployments during CI to check them.

Some nodeJS tools exist ie. https://www.npmjs.com/package/broken-link-checker.

**Comment by biwano** [comment]
@Atmosfearful

**Comment by Atmosfearful** [comment]
I believe our Monitoring tool can allow us to surface 404s
