### ISSUE TITLE
[carbon-dashboard] Develop definitive footer links

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1469]
- [ ] Put links to real URLs (should we use target="_blank" ?)
- [ ] Tag the labels for translation with t from @lingui/macro

**Comment by biwano** [comment]
@jabby09 Here is the ticket for the footer links in carbon dashboard.

**Comment by jabby09** [comment]
### Footer Links

- ~~Home~~ (remove, not required)
- KlimaDAO = https://www.klimadao.finance/
- Klima App = https://app.klimadao.finance/
- Carbonmark = https://www.carbonmark.com/
- ~~Klima Data~~ (remove, not required)
- Official Docs = https://docs.klimadao.finance/
- Blog = https://www.klimadao.finance/resources
- Contact = https://www.klimadao.finance/contact
- Disclaimer = https://www.klimadao.finance/disclaimer

- X = https://twitter.com/KlimaDAO
- YouTube = https://www.youtube.com/c/klimadaofinance
- Discord = https://discord.com/invite/klimadao
- LinkedIn = https://www.linkedin.com/company/klimadao/
- Telegram = https://t.me/joinchat/Zb06f_mnMosyYTYy

**Comment by sprrwhwk** [comment]
Hey @jabby09, the links you provided only seem to be for the desktop footer. Please note that the mobile footer has more links.
Can you also provide those here?
