### ISSUE TITLE
[research] Publish CarbonmarkJS on NPM

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1472]
As an extension to #1448 and #1221 it would be nice, for ourselves and our community, if we could publish an npm package that contains:

1. Typescript types for easy import in js/ts projects.
   - i.e. types for the `Request` params and `Response` data for things like `Project`, `User`, `Listing` etc.
2. A convenient SDK abstraction to use for runtime api interactions
   - i.e. to provide safer typing and method built-ins compared to raw untyped `fetch()` requests.

This is not a high priority, but we might get it 'for free' if we do a good job defining our Fastify schemas.

## Idea 1 - `feTS` re-export from OpenAPI spec
[feTS](https://the-guild.dev/openapi/fets/client/quick-start) provides an SDK wrapper around `fetch` that infers types. No codegen.
We would then use barrel files to reexport both the inferred types, and javascript methods, and publish it all on npm.

Would probably be maintained by hand (minimal maintenence). We would be early adopters of this package, which is a risk.

## Idea 2
- There are other unofficial SDK generators such as [OpenAPI generator for typescript](https://openapi-generator.tech/docs/generators/typescript/) (a Java based CLI tool), or another popular alternative called [openapi-typescript](https://github.com/drwpow/openapi-typescript).

# Considerations
- Let's wait until the SDK is a bit more solid and we know where we are headed with regards to credit-card retirements and purchases.
- This would slow down our own dev workflow because major changes to the API would require us to publish fresh types on NPM first. Importing the package locally from within the monorepo may be an alternative to NPM.

**Comment by 0xemc** [comment]
Following discussion with @Atmosfearful and exploring several options the following PRs attempt to implement this:

https://github.com/KlimaDAO/klimadao/pull/1641
https://github.com/KlimaDAO/klimadao/pull/1643

The following can be directly generated from the OpenAPI schema:
 - typesafe endpoint specific clients (getProjects, postUser etc)
 - frontend framework wrappers and their keys (SWR, React Query etc) _This will allow higher adoption_
 
THere are two major remaining pieces to this:

- [ ] Finalise the development flow (changes to api, generation of the package etc)
- [ ] Automate deployment to npm
- [ ] Document SDK
- [ ] Document SDK generation and process
