### ISSUE TITLE
[discovery] Design research on FE use cases using transfer history of a specific carbon credit

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1474]
PR for the subgraph changes are here: https://github.com/KlimaDAO/klima-subgraph/pull/75

Need a design jam session to discuss use cases for using this information and then designs for those screens.

**Comment by jabby09** [comment]
#1389 can be covered off as part of this discovery process

**Comment by jabby09** [comment]
[Discord thread here](https://discord.com/channels/1135827610434289727/1173629852050526289)

**Comment by jabby09** [comment]
@theprofessora 

- You'll see in the discord thread I've asked cujo to provide the data that can be expected using a real retirement but you may need to follow up with him. If you open https://github.com/KlimaDAO/klima-subgraph/pull/75 you will get some clues.

- I'd also suggest talking to drew/liam about the user persona's and related persona user requirements.

- Initial thinking was there would be another "link" on a [retirement receipt page](https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/26) that would lead to a page (URL to be determined) that would show the credit history. Something like CREDIT HISTORY: under IMMUTABLE TRANSACTION RECORD with a link to the page.

- And then maybe something we can do with a timeline component? (https://mui.com/material-ui/react-timeline/)

**Comment by jabby09** [comment]
@theprofessora FYI

![Screenshot 2023-11-13 at 2 20 09 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/734c87d0-ad88-4bdc-bd19-a957e005e72e)
![Screenshot 2023-11-13 at 2 20 30 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/dd587b9a-3c30-4272-9db6-26c2a28dd934)

**Comment by theprofessora** [comment]
First pass: https://www.figma.com/file/7N5csmr1NPeKefGh5MuGeh/Transfer-History?type=design&node-id=1-3&mode=design

1. this first iteration is very simple, but it seems to satisfy the ask, and it would be very very easy to build from dev perspective
2. also is quite modular, meaning the design will look just as good with little data as it will with a lot of data
3. We'll probably need to spend some time refining which exact details are shown, so it's not ready to ship yet

**Comment by jabby09** [comment]
> First pass

thanks @theprofessora - my feedback:

- [ ] Can you expand to show the entire journey from the receipt page?
- [ ] Ideally each credit history will be it's own page with a unique URL. I suppose on those pages there could also be a VIEW ALL cta that takes the user to a page as designed with a concatenated list of all retirements
- [ ] Please consider https://github.com/KlimaDAO/klimadao/issues/1389 as part of this design discovery work. There may be no specific design action at this time but want to make sure the review/research happens as part of this ticket.

**Comment by jabby09** [comment]
@theprofessora here is the link to the blog post on Digital Carbon Retirement Verification https://www.carbonmark.com/blog/digital-carbon-retirement-verification

**Comment by theprofessora** [comment]
feedback applied; designs shipped: https://www.figma.com/file/7N5csmr1NPeKefGh5MuGeh/Transfer-History?type=design&node-id=1-3&mode=design

**Comment by jabby09** [comment]
Shipped figma design
https://www.figma.com/file/7N5csmr1NPeKefGh5MuGeh/Transfer-History?type=design&node-id=1-90&mode=design&t=rDcTnXPNjtix3jl0-0
