### ISSUE TITLE
[api] Only show non-expired & valid listings

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1488]
see [api.carbonmark.com](https://api.carbonmark.com/#/)

this is an "under the hood change" for Countries, Categories, and Vintages endpoints.

only show for non-expired, valid listings.

@Atmosfearful to add any additional engineering specific requirements.

**Comment by Atmosfearful** [comment]
Update:
These endpoints will get their data from polygon-bridged-carbon - they won't be able to support testnet yet. I will close this ticket. Related to this, @0xemc will do a small refactor on each of these endpoints-- there is no point in them hitting the `marketplace` subgraph.
