### ISSUE TITLE
[api] "List projects" endpoint changes for CM contract v2

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1489]
See https://api.carbonmark.com/#/paths/api-projects/get

**Requirements:**
- [x] Add a property to indicate if listing is “expired” and / or “invalid"
- [x] Update GQL query to not return expired listings

Edit: let's bump the following two requirements to a follow up PR, they are needed for relaunch.
* Add a filter to not return "expired listings"
* Add a filter to not return "invalid listings”

**Comment by Atmosfearful** [comment]
First item was completed in #1565
I am working on the second item. The remaining two can be bumped, `invalid` is difficult to filter out at-scale because we have to check seller balances.

**Comment by Atmosfearful** [comment]
I discovered an additional change that is needed under the hood: the `marketplace` subgraph no longer supports `country` search.

We need to refactor /projects to first search polygon-bridged-carbon for compatible assets, *then* check if the marketplace has any listings for those assets.

In addition we still need to consume the `network` param in /projects, I closed https://github.com/KlimaDAO/klimadao/issues/1492 prematurely
