### ISSUE TITLE
[api] "User details" endpoint changes for CM contract v2

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1491]
See https://api.carbonmark.com/#/paths/api-users-walletOrHandle/get

**Requirements:**

* [x] Add expiration timestamp
* [ ] Add `expiredAt` queryparam filter

Talk to @Atmosfearful for any additional engineering details.

**Comment by Atmosfearful** [comment]
Additional requirements we discussed @0xemc :
Filter for `expired` is default `false` which means "do not return expired listings"
support for `expired=true` would included both expired listings and non-expired listings.
