### ISSUE TITLE
[projects] Frontend code changes for CM contract v2 support

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1493]
The underlying assumption for the Marketplace page and a Project Details page is that listings that are either expired or invalid are not shown.

when a user views their own profile, they can see expired listings and edit them.

See related API issues: #1489 & #1490 

# Remaining Todo
 * [x] The User Profile frontend needs to pass expiresAfter=0 when the user is connected *and viewing their own profile*. This would likely be passed down via the useFetchUser hook like `useFetchUser(args, { expiresAfter: "0" })`
 * [x] Update the edit listing logic to support mumbai (see other `actions` for examples)

**Comment by Atmosfearful** [comment]
Update: expired listings were filtered from endpoint responses in #1589 #1588 #1587 

As discussed in #1586 the work to filter `invalid` listings is a post-launch task now.

I have added one more todo to the ticket description before we call this one closed:
* [ ] The User Profile frontend needs pass `expiresAfter=0` when the user is connected

**Comment by Atmosfearful** [comment]
This will be closed in #1623
