### ISSUE TITLE
[profile] Create New Listing code & copy changes

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1494]
Related to support CM contract v2.

**Requirements:**

- [x] Update the copy on the APPROVE / SUBMIT tabs to reflect the contract changes (@jabby09 to provide)
- [x] In the modal, only valid and non-expired projects should be in the Projects drop down list
- [x] Update in the code how Available: tonnes are calculated

![Screenshot 2023-08-31 at 10 14 02 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/e1c47553-7a51-481d-99bf-c2c89643ddc9)

**Comment by Atmosfearful** [comment]
> only valid and non-expired projects should be in the Projects drop down list

I believe this was completed in #1640 but needs final QA

**Comment by Atmosfearful** [comment]
Derp, `expiration` and `valid` only apply to listings, this dropdown is for Assets.
The code is written such that the only assets that appear in the dropdown are:
1. a token with a symbol including VCS- ICR- or PURO-
2. a balance >= 1 (the min default listing quantity)
