### ISSUE TITLE
[portfolio] Listing card & Sell modal code & copy changes

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1495]
Related to support CM contract v2.

Note, assumes this is for a Logged In user.

**Requirements:**

- [ ] On the portfolio cards, change Available tonnes: to two categories; Unlisted tonnes and Listed tonnes. See [design mock here](https://www.figma.com/file/I5hXFeW1DKjV7agHq7T4UZ/Portfolio?type=design&node-id=8-1233&mode=design&t=go1k8Lw2Z2tQGlMR-4).

![Screenshot 2023-08-31 at 10 54 38 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/6e22a0c7-1e67-4e6d-94e0-6e18ccb574fc)

- [ ] Frontend logic change...on the portfolio cards, the SELL button should be disabled when balance of unlisted tonnes is <1
- [ ] SELL modal (i.e. Create new listing)...update the copy on the APPROVE / SUBMIT tabs to reflect the contract changes (@jabby09 to provide) and how Available: tonnes are calculated (assume this is calling same code as in #1494 so should only have to change this in one place)

**Comment by 0xemc** [comment]
@cujowolf which graph can I get the unlisted tonnage from?
