### ISSUE TITLE
[carbon dashboard] Site down, possible 500 server error

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1520]
Carbon dashboard is down https://carbon.klimadao.finance/

![image](https://github.com/KlimaDAO/klimadao/assets/103535195/d84ff643-93ea-4f4f-b885-b28214cdce39)

**Comment by jabby09** [comment]
see #1497

**Comment by biwano** [comment]
> see #1497

It is this one: https://github.com/KlimaDAO/dash-apps/pull/172
