### ISSUE TITLE
[profile] Listing card UI and copy changes for expired/invalid use cases

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1525]
Related to support CM contract v2.

Note, assumes this is for a Logged In user.

See figma designs [here](https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7/Profile?type=design&node-id=616-26544&mode=design&t=3ujjKHLEp59qA9zz-4) (expired) and [here](https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7/Profile?type=design&node-id=616-27977&mode=design&t=3ujjKHLEp59qA9zz-4) (invalid).

### Detailed requirements
- [x] On public facing profile pages, we do not show listings that are expired or invalid - we use UI magic to only show "Expired" and "Invalid" indicators for logged in users
- [x] On profile page load, add a check to determine if a listing is either `Expired` or `Invalid` 
- [x] If either check is "yes", add the related badge to the card. Note that the designs only show one of these cases but it is possible for a listing to be **both expired and invalid** so the implementation needs to support having both badges on the listing card side by side (ensure it works for desktop and mobile)
<img width="558" alt="Screenshot 2023-09-07 at 10 26 21 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ed026506-6912-472c-8ed3-e1d1d02755f9">

- [ ] Implement a tool tip for the `Expired` and `Invalid` badges on the listing cards:
- If `Expired`:
> This listing has expired and is currently hidden from the marketplace. Click "Edit" and resubmit the listing.
<img width="559" alt="Screenshot 2023-09-07 at 10 31 03 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/66fd9612-d826-421a-b897-34f4bfc74f16">

- If `Invalid`:
> This listing has become invalid and is currently hidden from the marketplace. Click "Edit" to delete the listing or change quantity.
<img width="545" alt="Screenshot 2023-09-07 at 10 31 17 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/640c6fa9-8b60-43b5-92b7-f75e698c88ec">

- [x] Update the Edit listing modal:
- Add an Expiration section and provide number of days and date stamp 
- If the listing is actually Expired, add the `Expired` badge and related tool tip (as per on the card)
- Add a check and ensure that SUBMIT LISTING button is active if the listing is expired. If expired, the user should be able to submit the listing without requiring a change to quantity or price.
<img width="301" alt="Screenshot 2023-09-07 at 10 37 13 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/3c1ded86-be40-46fb-864b-3f56d0f4c846">

- If the listing is invalid (i.e. the Quantity to list is > available tonnes in the wallet) then show this error message:
<img width="244" alt="Screenshot 2023-09-07 at 10 39 58 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/04a07022-aa1f-4ebf-873e-62e9bc5a7fb3">

**Comment by 0xMakka** [comment]
@jabby09 / @Atmosfearful / @theprofessora I'm just working through this ticket at the minute and have a some questions:
- When a user edits a listing we show an "Expiration" date and days remaining - should we always be only showing the number of days i.e. 90 days - no hours/minutes etc..?
  - If so, when a listing has 89 days, 55 minutes left to expiration for example - what is the expected behaviour here (should we show 89 days or 90 days?)
  - If a listing has less than 1 day remaining i.e. 55 minutes remaining for example - should we show 0 days?

**Comment by jabby09** [comment]
> @jabby09 / @Atmosfearful / @theprofessora I'm just working through this ticket at the minute and have a some questions:
> 
> * When a user edits a listing we show an "Expiration" date and days remaining - should we always be only showing the number of days i.e. 90 days - no hours/minutes etc..?
>   
>   * If so, when a listing has 89 days, 55 minutes left to expiration for example - what is the expected behaviour here (should we show 89 days or 90 days?)
>   * If a listing has less than 1 day remaining i.e. 55 minutes remaining for example - should we show 0 days?

hey @0xMakka 

@Atmosfearful will need to comment on where the time stamp on the listing is coming from, and what date/time format that is in, however, I don't think we need to get too granular here. 

So to clarify:

- Only showing days, no need for hours or minutes
- Q1 would be 89 days
- Q2 would be < 1 day

**Comment by 0xMakka** [comment]
> > @jabby09 / @Atmosfearful / @theprofessora I'm just working through this ticket at the minute and have a some questions:
> > 
> > * When a user edits a listing we show an "Expiration" date and days remaining - should we always be only showing the number of days i.e. 90 days - no hours/minutes etc..?
> >   
> >   * If so, when a listing has 89 days, 55 minutes left to expiration for example - what is the expected behaviour here (should we show 89 days or 90 days?)
> >   * If a listing has less than 1 day remaining i.e. 55 minutes remaining for example - should we show 0 days?
> 
> hey @0xMakka
> 
> @Atmosfearful will need to comment on where the time stamp on the listing is coming from, and what date/time format that is in, however, I don't think we need to get too granular here.
> 
> So to clarify:
> 
> * Only showing days, no need for hours or minutes
> * Q1 would be 89 days
> * Q2 would be < 1 day

Thanks @jabby09, yep that makes sense, just wanted to make sure before I started the work on the date formatting. 👍

**Comment by Atmosfearful** [comment]
The modal should always show the future date of expiration, which at the moment is always 90 days. I hopped into Makkas PR https://github.com/KlimaDAO/klimadao/pull/1635 and added this. This pr can be closed when https://github.com/KlimaDAO/klimadao/pull/1635 is merged
