### ISSUE TITLE
[carbonmark dashboard] Fix the strange prettier inconsistency between vercel and github CI.

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1528]
If we are not using the full pathname for certain imports in `components/charts/helpers/DataTable/ClientWrapper/index.tsx`, after running `npm run format-all`, github CI prettier check fails but vercel build succeds.

Also, locally, when saving the file with VSCode it changes the import order chosen by prettier.

To test, replace 
```
import Pagination from "components/charts/helpers/DataTable/Pagination";
import Table from "components/charts/helpers/DataTable/Table";
```

with
```
import Pagination from "../Pagination";
import Table from "../Table";
```

**Comment by sprrwhwk** [comment]
I'm facing this right now. Do you have a quick workaround?

**Comment by biwano** [comment]
> I'm facing this right now. Do you have a quick workaround?

No I did not find an answer to that.
I played around with imports until it did not happen.
I tried deleting my node_modules and restoring package-lock from the repository too without success...

**Comment by biwano** [comment]
> I'm facing this right now. Do you have a quick workaround?

Ho yeah as a "workaround, it seems that not using relative path imports solcves the issue.

**Comment by biwano** [comment]
I no longer get this one.
