### ISSUE TITLE
[retire] CC total cost error with one tonne

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1540]
When I change the tonnes to retire to 1, I see a total cost error.

Cost calculation appears to work fine for >= 2 tonnes.

<img width="983" alt="Screenshot 2023-09-12 at 10 05 23 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/9c0a9062-e8b5-4ce8-a6bb-67dab98139d2">

**Comment by jabby09** [comment]
@psparacino I believe this is only happening for the default BCT project
https://www.carbonmark.com/projects/VCS-191-2008/retire/pools/bct

The other projects I try seem to work

**Comment by psparacino** [comment]
@jabby09 Yes, had the same result. Writing up a comment with findings but I haven't gotten the same behavior on any other project. This one is also default BCT (correct?) and the one ton works: http://localhost:3002/projects/VCS-1146-2015

**Comment by jabby09** [comment]
> Yes, had the same result. Writing up a comment with findings but I haven't gotten the same behavior on any other project. This one is also default BCT (correct?) and the one ton works: http://www.carbonmark.com/projects/VCS-1146-2015

My understanding is there is only one default project per pool (@Atmosfearful to confirm) and they are a lower price because we do not charge some of the fees. The default project are:

[BCT](https://www.carbonmark.com/projects/VCS-191-2008) - 0xb139c4cc9d20a3618e9a2268d73eff18c496b991
https://www.carbonmark.com/projects/VCS-191-2008
[NCT](https://www.carbonmark.com/projects/VCS-1529-2012) - 0x6362364a37f34d39a1f4993fb595dab4116daf0d
https://www.carbonmark.com/projects/VCS-1529-2012
[UBO](https://www.carbonmark.com/projects/VCS-1140-2015) - 0xd6ed6fae5b6535cae8d92f40f5ff653db807a4ea
https://www.carbonmark.com/projects/VCS-1140-2015
[NBO](https://www.carbonmark.com/projects/VCS-981-2014) - 0xb6ea7a53fc048d6d3b80b968d696e39482b7e578
https://www.carbonmark.com/projects/VCS-981-2014

**Comment by psparacino** [comment]
@jabby09 thanks👍 , i think we got the fix

**Comment by psparacino** [comment]
@Atmosfearful PR open in fiat repo

**Comment by psparacino** [comment]
closed with this PR: https://github.com/KlimaDAO/klimadao/pull/1551
