### ISSUE TITLE
Release French & German translations.

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#157]
* [x] Trans tags on everything except blog posts, and /buy (/buy will likely be moved / refactored soon)
  - from now on, new tags should get IDs as suggested by @biwano
* [x] extract strings
* [x] translators add FR and DE strings to .po files
* [x] make sure `toLocaleString()` and `Intl.format()` and similar methods reflect the chosen locale.
  - pass locale to `Intl.RelativeTimeFormat`
  - on site, the locale is reflected in the url  `klimadao.finance/fr/blog`
  - on app the locale is at runtime
* [ ] show the language picker on production URL (currently hidden). 
* [x] Make sure Pseudo is only visible on dev/staging/preview urls. https://github.com/KlimaDAO/klimadao/pull/320
* [x] Make sure it looks nice
* [x] Make sure it is tab-navigable.
* [x] #293 
* [x] pass locale to prettifySeconds https://github.com/KlimaDAO/klimadao/blob/staging/lib/utils/prettifySeconds/index.ts#L7
* [x] Update locale on HTML root for `site`'s server-side page generation - might have to read the docs for the correct way to do this using the built-in nextjs localization tools https://github.com/KlimaDAO/klimadao/blob/staging/site/pages/_document.tsx#L10 https://github.com/KlimaDAO/klimadao/pull/320
* [ ] Enable Chinese and Russian on Staging only => https://github.com/KlimaDAO/klimadao/issues/329

**Comment by biwano** [comment]
* [ ] App/NavMenu
* [ ] App/Home & Loading
* [ ] App/Stake 
* [ ] App/ChooseBond
* [ ] App/Bond
* [ ] App/PKlima
* [ ] App/Info
* [ ] Site/Footer & Header & Navigation & PageHead
* [ ] Site/Home
* [ ] Site/Blog
* [ ] Site/Disclaimer
* [ ] Site/Resources
