### ISSUE TITLE
[lib] Investigate issues with fallback provider 

### ISSUE THREAD

**Issue by 0xMakka** [KlimaDAO/klimadao#1578]
Over the past week, I've noticed lots of errors with the default fallback provider (polygon-rpc) when working on tasks locally. It seems like the infura fallback provider isn't working as intended. If polygon-rpc fails the expectation is that the infura provider would be used instead which isn't happening. 

I'm currently investigating the issue to try pinpoint what the issue is and this ticket will be used to track this investigation.

**Comment by Atmosfearful** [comment]
Is this still an issue @0xMakka ?

**Comment by 0xMakka** [comment]
@Atmosfearful apologies I parked this investigation a few weeks back when another higher priority task came up. I haven't seen the issue in many weeks personally and haven't heard any other complaints so I will close it. If the issue arises again in the future, I'll open this ticket again.
