### ISSUE TITLE
[api] Listings model should include project key and vintage

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1600]
Otherwise we can't render listings cards in user profiles (connected & unconnected)

**Comment by 0xemc** [comment]
@Atmosfearful need some more info on this one.

Currently the new subgraph is still returning the project objects:

![Image](https://github.com/KlimaDAO/klimadao/assets/7104689/d3c8599f-7f3c-4649-bcd6-3cfc73dc701b)


So the Listing component should still be rendering. Do you have an example where it is not?

https://api.thegraph.com/subgraphs/id/QmYaSLxLhoqekxuip14HyEKXFuW9DQZE8CndFrHGHyeoB8/graphql?query=query+project%7B%0A++users%7B%0A++++listings%7B%0A++++++id%0A++++++active%0A++++++deleted%0A++++++project%7B%0A++++++++id%0A++++++++projectID%0A++++++%7D%0A++++%7D%0A++%7D%0A++%0A++projects%7B%0A++++listings%7B%0A++++++project%7B%0A++++++++id%0A++++++%7D%0A++++%7D%0A++%7D%0A%7D

**Comment by Atmosfearful** [comment]
The /users endpoint invokes this query:
```gql
query getUserByWallet($wallet: Bytes, $expiresAfter: BigInt) {
  users(where: { id: $wallet }) {
    listings(where: { expiration_gt: $expiresAfter }) {
      ...ListingFragment
    }
    activities(orderBy: timeStamp, orderDirection: desc, first: 10) {
      ...ActivityFragment
    }
  }
}
```

We just need to update the fragment to add this, then pass it down to the response (check if model schema needs updating, test fixtures too, etc.)
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/38a085bd-2b4f-4775-ac48-c915c0f6d300)

**Comment by 0xemc** [comment]
https://github.com/KlimaDAO/klimadao/pull/1610
