### ISSUE TITLE
[carbonmark] Update Purchase page to remove number formatting

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1603]
After we close #1602 and tag a prerelease, we can do this ticket.

* [x] Remove bignumber formatting from  `/pages/Purchases/index.tsx`
* [x] Remove formatBigToPrice and formatBigToTonnes utils from carbonmark/lib -- they are no longer needed as the API does all number formatting.

**Comment by 0xemc** [comment]
@Atmosfearful I'm not convinced doing the formatting in the API is best practice longer term. Formatting changes for visual reasons should probably be kept at the consumer level.

1. The formatting is needed for several attributes across several models (listing.leftToSell, listing.singleUnitPrice, purchase.amount). Meaning for consistency we need to make a blanket rule that BigNumber is formatted everywhere.
2. If the graph decides to change it's format (for whatever reason) then the API needs to change (and so do the consumers)
