### ISSUE TITLE
Bundle API Project

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1611]
**Is your feature request related to a problem? Please describe.**
There are two main devxp issues with the API as it stands currently:

1. Some modules from seperate packages (@klimadao/utils for example) are not able to be imported in to the API package. This is because our tsc compile step is complicated and is fixed to ESM module syntax (where some other packages may use CJS)

2. Relative imports are a pain in the a$$ to maintain and the auto complete feature in vscode provides incorrect imports repeatedly breaking builds by accident.

**Describe the solution you'd like**
The api should be bundled to:

a.) allow imports from other packages
b.) allow import aliases

**Describe alternatives you've considered**
I investigated switching to Bunjs but this is a whole different run time and it's not clear that it's supported by vercel for serverless functions

I also attempted to use various npm packages to replace aliased imports at build time but had varying levels of success.

**Comment by 0xemc** [comment]
Packing it in after attempting the following:

1. [module-alias](https://www.npmjs.com/package/module-alias) -> allows aliases but does not allow imports from other packages because of commonjs/es6 module errors
2. [babel-js](https://babeljs.io/) -> enables mixed module types (sometimes) and importing from other packages but aliases are not resolved during run time
3. [module-alias + babel] -> issues mixing module types..
4. [rollup] -> everything worked except because a single file is produced the Autoload plugin does not work.

**Comment by Atmosfearful** [comment]
We might be able to deprecate lib at least in carbonmark's new monorepo...
