### ISSUE TITLE
[carbonmark] Excessive RPC calls

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1630]
**Describe the bug**
The network tab shows an excessive amount of calls to the polygon-rpc when logging in.

**To Reproduce**
Connect
Visit Profile page
Open Network tab in dev tools
Refresh page

Unclear where these are originating.

**Comment by Atmosfearful** [comment]
This is lower priority as it doesn't seem to impact performance on my machine, but it is a technical debt that we should take some time to understand and optimize if possible.

**Comment by jabby09** [comment]
> This is lower priority as it doesn't seem to impact performance on my machine, but it is a technical debt that we should take some time to understand and optimize if possible.

Probably not required now since we are about to change the account creation / login process
