### ISSUE TITLE
[QA] Test results on CM Contract V2 implementation

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1651]
@0xtapi @ShimonD-KlimaDAO let's consolidate testing results in this ticket.

Recommend we capture each issue as a separate comment as some of these will need to be spun out as new tickets.

In terms of format, let use a task list - check box for the test comment title, that way we can track if the items has been triaged and/or addressed. Examples below.

**Comment by jabby09** [comment]
- [ ] Application error when creating new listing

When I click Buy on a seller listing or Create New Listing from Profile page I am seeing this error
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/377a9db2-ff4c-482b-ba01-9031a3fac8e7)

**Comment by 0xtapi** [comment]
- [ ] Application error when creating new listing **_without assets in your portfolio_**

Similar to the resolved issue @jabby09 posted, I encounter this error when I try to create a listing when my portfolio is empty. Error does not occur when portfolio is not empty:

<img width="1155" alt="bug1" src="https://github.com/KlimaDAO/klimadao/assets/128430614/cde7a24e-372b-4933-a5c0-f496959f21d9">

**Comment by 0xtapi** [comment]
- [ ] Weird (seller-dependent?) behavior when buying assets

I went through the purchasing process of VCS-981-2017 and bought a tonne from Jabby at $4.67. No issues.

Then I tried to buy a tonne listed by Atmos. Approval went through, but immediately upon clicking Submit, I get thrown back to the Approve modal. See error here:

<img width="1259" alt="bug2" src="https://github.com/KlimaDAO/klimadao/assets/128430614/836b1d65-ecdd-47d7-bb17-955380a3e781">


I tried it a few times, same error every time.

**Comment by 0xtapi** [comment]
- [ ] Assets showing in portfolio despite not owning them

I have 0 tonnes of VCS-191, but my portfolio shows this:
<img width="1184" alt="bug3" src="https://github.com/KlimaDAO/klimadao/assets/128430614/ef96d4ac-4472-4aef-ae01-2062c13a0ba5">


I clicked on the project briefly on the marketplace, but did not interact with it it any other way. Don't know how it got into my portfolio, and showing an asset which I can't sell or retire obviously makes no sense in the first place 🤔.

**Comment by jabby09** [comment]
- [ ] Transaction skipping APPROVE tab and then error: something went wrong

- Have tried from https://staging.carbonmark.com/users/jabby and https://carbonmark-git-atmos-expire-testing-klimadao.vercel.app/users/jabby
- Unclear what steps happened that now Create Listing transactions skip right to SUBMIT tab (I have logged out of wallet and CM and closed browser)

<img width="1190" alt="Screenshot 2023-10-12 at 9 41 16 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/6ea28a5b-e022-42ec-b558-474f265e5217">

**Comment by jabby09** [comment]
[ ] Available Tonnes incorrect in Create Listing approve tab

Testing from staging.carbonmark.com

- From Portfolio page, click SELL on VCS-981-2017 asset (note this asset has 1 tonne available to list)
- Select Quantity of 1
- Set Price
- Click Create Listing button
- APPROVE tab has Confirm amount of 2 tonnes??
<img width="549" alt="Screenshot 2023-10-12 at 10 15 05 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/8f10f101-1a55-411c-afa5-946c8547997e">

- Click GO BACK
- Click X on the Create a listing modal

- Next go to Profile page
- Click CREATE NEW LISTING button
- Select Quantity of 1
- Set Price
- Click Create Listing button
- Modal skips APPROVE tab, goes right submit, however, submit amount of 1 tonnes is correct
<img width="529" alt="Screenshot 2023-10-12 at 10 17 28 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/1474d0aa-f711-4099-8867-ae6158bb3342">

- Click SUBMIT and get same error as noted in comment above

**Comment by jabby09** [comment]
all the comments above have been migrated to issues in the milestone https://github.com/KlimaDAO/klimadao/milestone/28
