### ISSUE TITLE
[research] Subgraph id expiration & releases

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1652]
**Describe the bug**
We need to deal with the fact that IDs expire:

- when do they expire?
- can we prevent them from expiring?
- is there another way to create stable subgraph version that allow us to support a prior API version indefinitely?
- how does this change on hosted network vs decentralized net?

Example:
1. subgraph id `abc123456` is consumed in production api version `v2.0.0.api.carbonmark.com`
2. we upgrade the subgraph to change schemas for v3, v4 etc. and get a new id `def789123`
3. At some point `abc123456` breaks, which breaks v2.0.0 completely 

its not clear when/why/how or what our options are around this.

**Comment by cujowolf** [comment]
- when do they expire?
They automatically expire after 45 days if there has been no query traffic. They can also expire if an updated version is pushed to the same named deployment.
- can we prevent them from expiring?
Create a new named deployment for each version that corresponds with an api release, and also submit at least one query every 45 days.
- is there another way to create stable subgraph version that allow us to support a prior API version indefinitely?
Self hosting a graph node or just utilizing the query/endpoint structure outlined above for the hosted service should be enough.
- how does this change on hosted network vs decentralized net?
The decentralized network will most likely continue to index and serve queries as long as there is ample enough signal to drive indexing rewards (and possible query rewards) towards the indexers serving the subgraphs on the decentralized net.

**Comment by Atmosfearful** [comment]
Notes from a dm discussion with Cujo:
- He is actively avoiding by only pushing updates to new named subgraph deployments.
- My question was: then why are we using ids? we could have stuck with names.
- His answer was: the ids will be more useful when we move to the decentralized net.

This is sufficient for me. We need to document our release process, I made a new ticket for that: https://github.com/KlimaDAO/klima-subgraph/issues/90
