### ISSUE TITLE
[contract v2] Expired listing disappeared from Profile once expired

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1655]
Testing on this preview link: https://carbonmark-git-atmos-expire-testing-klimadao.vercel.app/

Steps to replicate:

- Created a listing (worked no problem)
- Open edit listing modal and noted the expiry date field (worked no problem)
- After ~ 5 minutes, went back to Profile page
- Saw the Expired badge briefly but then the listing actually disappeared

**Comment by Atmosfearful** [comment]
I think this is a good one for you @0xemc since you are familiar with the /users endpoint and data fetching with SWR.

Here is how I would approach this:
- use my test branch #1653 to create a listing with a short expiration
- construct an api query to /users with `?network=mumbai&expiresAfter=0` to confirm that the expired listing is appearing as expected
- if it is, then investigate network requests from the client. Perhaps we are not passing params correctly, or caching is causing issues?

**Requirements / success critera**
- when viewing someone elses profile **expired listings should not appear**
- when logged out and viewing your own profile **expired listings should not appear**
- only when you log in and view your own profile should you see the expired listing w/ a red badge.

**Comment by 0xemc** [comment]
@jabby09 to confirm this is on Mumbai? I'm having trouble even creating a listing on that network. Are you still able to replicate this?

**Comment by jabby09** [comment]
> @jabby09 to confirm this is on Mumbai? I'm having trouble even creating a listing on that network. Are you still able to replicate this?

@0xemc @Atmosfearful yes using mumbai testnet
this link https://carbonmark-git-atmos-expire-testing-klimadao.vercel.app/
I also had an error on the APPROVE tab creating a listing
<img width="1219" alt="Screenshot 2023-10-23 at 9 13 33 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/f8e2a464-860a-4499-a9e3-8743ed5e643f">

Error: nonce has already been used [ See: https://links.ethers.org/v5-errors-NONCE_EXPIRED ] (error={"code":-32603,"message":"[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"nonce too low\"}}}'","stack":"{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"nonce too low\\\"}}}'\",\n  \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"nonce too low\\\"}}}'\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at R._processApproval (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:28:131969)\\n    at async qe.newUnapprovedTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:207601)\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:56862\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at R._processApproval (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-2.js:28:131969)\n  at async qe.newUnapprovedTransaction (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-4.js:1:207601)\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:56862\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, method="sendTransaction", transaction=undefined, code=NONCE_EXPIRED, version=providers/5.7.2)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at checkError (json-rpc-provider.js:101:1)
    at json-rpc-provider.js:239:1
(anonymous) @ index.tsx:119

**Comment by jabby09** [comment]
> @jabby09 to confirm this is on Mumbai? I'm having trouble even creating a listing on that network. Are you still able to replicate this?

Yes mumbai testnet

For this issue specifically I am using this preview link: https://carbonmark-git-atmos-expire-testing-klimadao.vercel.app/

One issue I think that is related is I still have this asset showing as a listed tonne in my portfolio:
<img width="1026" alt="Screenshot 2023-10-23 at 9 23 17 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ab93d726-a566-44cf-8a55-ddb3190413b4">

However, if you go to the project (https://carbonmark-git-atmos-expire-testing-klimadao.vercel.app/projects/VCS-981-2017) you won't see a listing by jabby

And in the Create a listing modal for this asset, it thinks I have one available to list.
<img width="555" alt="Screenshot 2023-10-23 at 9 24 45 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/90584b1a-242d-4871-b2bf-93b719618134">

**Comment by jabby09** [comment]
@0xemc @Atmosfearful yes I am having issues creating a listing as well...this is using TCO2-VCS-191-2009
<img width="1213" alt="Screenshot 2023-10-23 at 9 27 03 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/1911dc9f-82b1-4b33-861b-4e460dda0f09">

Error in onAddListing Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x6476edf98Bdc5EE62f9D4E4BF8932d69Ed685483","to":"0x5DC7083cD6Ff9A46C36661750faBcbB9aE2abed2","data":"0x9057f28900000000000000000000000074589f305224c9e1e8aaeb341c6a09e8709a5dab0000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000000986f700000000000000000000000000000000000000000000000000de0b6b3a76400000000000000000000000000000000000000000000000000000000000065366780","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0x72681ef600000000000000000000000074589f305224c9e1e8aaeb341c6a09e8709a5dab0000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000003e73362871420000"},"stack":"{\n  \"code\": -32603,\n  \"message\": \"Internal JSON-RPC error.\",\n  \"data\": {\n    \"code\": 3,\n    \"message\": \"execution reverted\",\n    \"data\": \"0x72681ef600000000000000000000000074589f305224c9e1e8aaeb341c6a09e8709a5dab0000000000000000000000000000000000000000000000003782dace9d9000000000000000000000000000000000000000000000000000003e73362871420000\"\n  },\n  \"stack\": \"Error: Internal JSON-RPC error.\\n    at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\\n    at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\\n    at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\\n    at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\\n    at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\\n    at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935\"\n}\n  at new i (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:10940)\n  at s (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:13880)\n  at Object.internal (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-3.js:16:14490)\n  at c (chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:44665)\n  at chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/background-0.js:7:45664\n  at async chrome-extension://nkbihfbeogaeaoehlefnkodbefgpgknn/common-4.js:19:37935"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at checkError (json-rpc-provider.js:76:1)
    at Web3Provider.<anonymous> (json-rpc-provider.js:575:1)
    at Generator.throw (<anonymous>)
    at rejected (json-rpc-provider.js:6:42)
(anonymous) @ index.tsx:138
tryCatch @ runtime.js:45
f._invoke @ runtime.js:274
r.<computed> @ runtime.js:97
asyncGeneratorStep @ asyncToGenerator.js:3
_throw @ asyncToGenerator.js:29
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js:13
_next @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
CreateListing.Y @ index.tsx:123
onClick @ Submit.tsx:101
Nb @ react-dom.production.min.js:54
Tb @ react-dom.production.min.js:54
(anonymous) @ react-dom.production.min.js:55
nf @ react-dom.production.min.js:55
se @ react-dom.production.min.js:106
(anonymous) @ react-dom.production.min.js:117
Rk @ react-dom.production.min.js:274
Jb @ react-dom.production.min.js:52
hd @ react-dom.production.min.js:109
fd @ react-dom.production.min.js:74
ed @ react-dom.production.min.js:73

**Comment by cujowolf** [comment]
This error is because you are trying to list a total of 4.5 tons across all of your listings, but only currently hold 4 tons in your wallet.

**Comment by jabby09** [comment]
> This error is because you are trying to list a total of 4.5 tons across all of your listings, but only currently hold 4 tons in your wallet.

@cujowolf @Atmosfearful then something else is going on because on the FE is showing I only have 2.5 tonnes listed; which adds up if I look at the two listing I have https://staging.carbonmark.com/users/jabby

<img width="1018" alt="Screenshot 2023-10-23 at 3 06 17 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/bc9e6226-dc6a-4263-a46d-308f9f872e67">

**Comment by Atmosfearful** [comment]
The API reponse for `/users/jabby` for `VCS-191-2009` shows 2.5 listed tonnes out of 4 tonnes held in total.

So you should be able to create a third listing for 1 tonne...

**Comment by 0xemc** [comment]
Hitting the same issue as @jabby09 above :( blocked for now

**Comment by cujowolf** [comment]
> The API reponse for `/users/jabby` for `VCS-191-2009` shows 2.5 listed tonnes out of 4 tonnes held in total.
> 
> So you should be able to create a third listing for 1 tonne...

You should see an expired listing for 1 ton as well. Current value stored is 3.5 + 1 = 4.5 > 4.

![image](https://github.com/KlimaDAO/klimadao/assets/92617969/84b45667-9ba5-4e2f-b28d-3a114771a0e3)
