### ISSUE TITLE
[seller listing] Enable RETIRE NOW functionality on a Seller listing

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1659]
With CM Contract v2 and the return of Seller listings almost released in Production, the time is now right to add the capability to Retire from the listing on a Project page.

We have this functionality for Pool listings...
<img width="685" alt="Screenshot 2023-10-13 at 9 28 46 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/241fbb7d-31b1-42a4-a82d-eb9928766239">

...but it was never added for Seller listings. 

Currently the way this is supported is that a user is required to BUY a carbon asset and then from their Portfolio page they can retire the carbon. The objective of this workstream is to support a RETIRE NOW option on seller listings; which would just be a combination of BUY & RETIRE.

There was a dependency for this to upgrade the retirement aggregator contract (https://github.com/KlimaDAO/klimadao-solidity/issues/48). This is ready to go for Toucan/C3 listings on the `infinity-carbonmark` branch (note: this can't be deployed until we have final contract addresses for carbonmark v2).

### Requirements

- [ ]  Add RETIRE NOW button to a Seller Listing card. The design UI should match what exists for a Pool listing (as per screenshot above).

- [ ] Click RETIRE NOW to open the /retire form, for [example](https://www.carbonmark.com/projects/VCS-1650-2015/retire/pools/nct). Note the UI of the form should match the UI as if the user clicked RETIRE NOW on a pool listing.

<img width="383" alt="Screenshot 2023-10-16 at 9 20 29 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/f2d02c81-0fc1-4410-b3ef-0adfe2a669b7">

**NOTES:**
- will need the new ABI endpoint from the retirement aggregator contract
- will need to decide on the URL path of the form; assume it will be something like: https://www.carbonmark.com/projects/VCS-1650-2015/retire/seller/?

- [ ] As part of this change, note the Asset Details UI (closed by default)
- [ ] Note that in the Total price component, there are no network fees to buy or retire from a seller listing (nothing needs to change on the form, this is covered in the [docs](https://docs.carbonmark.com/get-started/understanding-fees-on-carbonmark))
- [ ] If paying with CC, payment processing fee still applies

**NOTES:**
- to support pay with CC, there is a dependency on changes required on the offsetra API; primarily around needing to support a listing ID from the ABI
- this is covered in a separate ticket #1818

**Comment by sprrwhwk** [comment]
@jabby09 this is the current behavior. Notice the "SIGN IN / CONNECT TO BUY" button. Do we keep that or also make it look like the buttons above?

<img width="737" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/e144deeb-3c66-4896-aad2-2aa9bf49ce6e">

**Comment by sprrwhwk** [comment]
@jabby09 what will be the content of asset details for seller listing retirements?
<img width="296" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/1203eba0-8b20-4f26-81b7-1a1a706434e4">

**Comment by jabby09** [comment]
> what will be the content of asset details for seller listing retirements?

@sprrwhwk 

the same
the only difference for a seller listing is the available to retire amount is from the listing, not the pool
