### ISSUE TITLE
[contract v2] Weird (seller-dependent?) behavior when buying assets

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1662]
From @0xtapi 

I went through the purchasing process of VCS-981-2017 and bought a tonne from Jabby at $4.67. No issues.

Then I tried to buy a tonne listed by Atmos. Approval went through, but immediately upon clicking Submit, I get thrown back to the Approve modal. See error here:
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/b3b138cb-da9a-48d1-bb95-04f61aab09a8)

**Comment by Atmosfearful** [comment]
Merging this ticket with #1673
