### ISSUE TITLE
[contract v2] Submit Amount for 2nd listing of Same Token is Incorrect

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1670]
I created a listing of 11 tonnes.
I then created another listing of 5 tonnes for the same asset with a different price.
The approval modal asked me to approve 16 tonnes. This is logical.
The Submit modal then mentioned that I am submitting a new listing for 16 tonnes, which is not correct.
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/7e23e23b-e26e-4763-8b40-2044dacec4ef)

I expect Submit Amount to show "5 tonnes".

**Comment by Atmosfearful** [comment]
I suspect this is something to do with how we render the input label here:

https://github.com/KlimaDAO/klimadao/blob/af10ec6d2bf7c5eae62e774f6696f5aa35a2fedb/carbonmark/components/CreateListing/index.tsx#L214-L220

gonna try putting up a fix
