### ISSUE TITLE
[contract v2] Activity Modal Shows Amount and Price for Deleted Listing

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1671]
The activity modal shows `0t at $0.00` for deleted listings, which doesn't convey any information. It should just say `You deleted listing`.
![image](https://github.com/KlimaDAO/klimadao/assets/99001851/68c81739-01c0-4d0a-a99b-824325affea1)

**Comment by sprrwhwk** [comment]
@ShimonD-KlimaDAO how about "You deleted **a** listing" to make it a proper sentence?
