### ISSUE TITLE
[contract v2] Purchase USDC Approval Fails

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1672]
I attempted to buy 1.5 tonnes from atmos, and the USDC approval failed. Screenshot and copied log below. Strangely, after trying again, it worked.

![image](https://github.com/KlimaDAO/klimadao/assets/99001851/14496ec3-de3d-4ee7-a145-7b8a52089cd2)

`makePurchase error Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x6F9F81eb4f54512Be8c91833783ee0074328E062","to":"0x5DC7083cD6Ff9A46C36661750faBcbB9aE2abed2","data":"0xfa7ab3afd0afbf0fcc92d0d8cd9992919e8f54c91e4082ac20f485777c772088e1966b0e000000000000000000000000ab5b7b5849784279280188b556af3c179f31dc5b000000000000000000000000ecf4a1b92a463c843cdcb7cb7a2f2ddfe07651bb000000000000000000000000000000000000000000000000000000000044aa2000000000000000000000000000000000000000000000000014d1120d7b160000000000000000000000000000000000000000000000000000000000000066ff30","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0xfbfe3e2a"},"stack":"Error@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/runtime-lavamoat.js:7838:17\nn@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:23613\ns@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:26553\ninternal@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:27164\nc@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/background-0.js:7:44209\nr.createFetchMiddleware/<@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/background-0.js:7:45209\n"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)`

**Comment by Atmosfearful** [comment]
Not able to reproduce this. @0xtapi or @jabby09 are either of you?

**Comment by Atmosfearful** [comment]
Marking `blocked` until we have a repro case we can use to debug

**Comment by jabby09** [comment]
> Not able to reproduce this. @0xtapi or @jabby09 are either of you?

@Atmosfearful this worked for me this morning
