### ISSUE TITLE
[contract v2] Purchase Goes Back to Approval After Clicking Submit

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#1673]
After successful approval for a purchase, I am taken to the Submit modal. Once I click Submit, I get redirected back to the Approval modal with the following:

`makePurchase error Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0x6F9F81eb4f54512Be8c91833783ee0074328E062","to":"0x5DC7083cD6Ff9A46C36661750faBcbB9aE2abed2","data":"0xfa7ab3afd0afbf0fcc92d0d8cd9992919e8f54c91e4082ac20f485777c772088e1966b0e000000000000000000000000ab5b7b5849784279280188b556af3c179f31dc5b000000000000000000000000ecf4a1b92a463c843cdcb7cb7a2f2ddfe07651bb000000000000000000000000000000000000000000000000000000000044aa2000000000000000000000000000000000000000000000000014d1120d7b160000000000000000000000000000000000000000000000000000000000000066ff30","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"message":"execution reverted","data":"0xfbfe3e2a"},"stack":"Error@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/runtime-lavamoat.js:7838:17\nn@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:23613\ns@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:26553\ninternal@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/common-3.js:16:27164\nc@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/background-0.js:7:44209\nr.createFetchMiddleware/<@moz-extension://70694cc7-c3cf-414d-9b4a-4514b61f77dd/background-0.js:7:45209\n"}, code=UNPREDICTABLE_GAS_LIMIT, version=providers/5.7.2)
    makeError index.js:224
    throwError index.js:233
    v json-rpc-provider.js:76
    perform json-rpc-provider.js:575
    s json-rpc-provider.js:6
    promise callback*l json-rpc-provider.js:7
    h json-rpc-provider.js:8
    h json-rpc-provider.js:4
    perform json-rpc-provider.js:549
    estimateGas base-provider.js:1550
    o base-provider.js:5
    promise callback*l base-provider.js:7
    o base-provider.js:5
    promise callback*l base-provider.js:7
    C base-provider.js:8
    C base-provider.js:4
    estimateGas base-provider.js:1545
    sendUncheckedTransaction json-rpc-provider.js:203
    sendTransaction json-rpc-provider.js:253
    o json-rpc-provider.js:5
    promise callback*l json-rpc-provider.js:7
    h json-rpc-provider.js:8
    h json-rpc-provider.js:4
    sendTransaction json-rpc-provider.js:249
    v index.js:323
    o index.js:5
    promise callback*l index.js:7
    f index.js:8
    f index.js:4
    v index.js:312
    e actions.ts:229
    c runtime.js:45
    _invoke runtime.js:27
    t runtime.js:97
    r asyncToGenerator.js:3
    s asyncToGenerator.js:25
    i asyncToGenerator.js:32
    i asyncToGenerator.js:21
    R actions.ts:205
    r PurchaseForm.tsx:151
    c runtime.js:45
    _invoke runtime.js:27
    t runtime.js:97
    r asyncToGenerator.js:3
    s asyncToGenerator.js:25
    i asyncToGenerator.js:32
    i asyncToGenerator.js:21
    F PurchaseForm.tsx:139
    onClick Submit.tsx:104`

**Comment by Atmosfearful** [comment]
Also not able to reproduce, more info needed!

**Comment by Atmosfearful** [comment]
Tapi reported something similar:

```
I went through the purchasing process of VCS-981-2017 and bought a tonne from Jabby at $4.67. No issues.

Then I tried to buy a tonne listed by Atmos. Approval went through, but immediately upon clicking Submit, I get thrown back to the Approve modal. See error here:
```

**Comment by Atmosfearful** [comment]
I am able to reproduce now with a 1.5 tonne purchase. a 1 tonne purchase works.

```
makePurchase error Error: cannot estimate gas; transaction may fail or may require manual gas limit [ See: https://links.ethers.org/v5-errors-UNPREDICTABLE_GAS_LIMIT ] (reason="execution reverted", method="estimateGas", transaction={"from":"0xAb5B7b5849784279280188b556AF3c179F31Dc5B","to":"0x5DC7083cD6Ff9A46C36661750faBcbB9aE2abed2","data":"0xfa7ab3af4fcd9522c425cb1e4d82c52475a45ebd6f11da5b2c4408e50b98d22530f535ee0000000000000000000000006f9f81eb4f54512be8c91833783ee0074328e062000000000000000000000000ecf4a1b92a463c843cdcb7cb7a2f2ddfe07651bb00000000000000000000000000000000000000000000000000000000007270e000000000000000000000000000000000000000000000000014d1120d7b1600000000000000000000000000000000000000000000000000000000000000aba950","accessList":null}, error={"code":-32603,"message":"Internal JSON-RPC error.","data":{"code":3,"data":"0xfbfe3e2a","message":"execution reverted"},"stack":"Error: Internal JSON-RPC error.\n    at getEthJsonRpcError
```
