### ISSUE TITLE
[contract v2] [mobile] Bad element alignment

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1692]
**Describe the bug**
Some elements have bad alignment on mobile, see screenshot below. The left alignment works on desktop, but looks bad on mobile, especially with center alignment of the other elements above. 

**Screenshots**
![Screenshot_20231017-100755-730](https://github.com/KlimaDAO/klimadao/assets/128430614/a799be4d-3029-40c8-a01e-f149b5a0d2fa)

**Smartphone (please complete the following information):**
 - OS: Android 12
 - Browser: MetaMask browser

**Comment by jabby09** [comment]
### LOW PRIORITY

@0xMakka this looks like it is not specific to contract v2

screenshots appear to be from the /retire page

we should first just check that current mobile implementation [matches design](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=672-7089&mode=design&t=d53aUv8yUv39dlDr-4)
