### ISSUE TITLE
[contract v2] 404 page after clicking RETIRE button from Portfolio asset

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1698]
**Describe the bug**
I tried to retire from an asset in my portfolio with listings and get a 404 page.

**To Reproduce**
1. From Portfolio, select an asset and click RETIRE button
(note: the asset I choose has two separate listing, one for 1 tonne and one for 1.5 tonnes - and additional 1.5 tonnes are unlisted)
3. For the example above, this is the URL https://staging.carbonmark.com/portfolio/0x74589F305224c9e1E8aAeb341C6a09e8709A5Dab/retire
4. Results in 404 page

**Expected behavior**
Should load the retire form page.

**Screenshots**
<img width="957" alt="Screenshot 2023-10-17 at 2 12 09 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/bc6fb37f-5857-4cb8-b6a8-d3a55e06f591">
<img width="987" alt="Screenshot 2023-10-17 at 2 12 23 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/a49c2e67-7b79-4b3c-8012-05787974a1ac">

**Desktop (please complete the following information):**
 - brave

**Comment by Atmosfearful** [comment]
This doesn't work for mumbai assets

Why:
- api does not support lookup by asset address (yet) -- only by project id
- to render this page, the server only has the asset address from the URL
- Retire transaction wouldn't work anyways (aggregator is not on testnet), so im fine with just 404ing here
