### ISSUE TITLE
Trim and cleanup ABI JSON files

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#17]
These were exported from hardhat or elsewhere and likely don't need all the metadata, AST, legacy-AST and other fields. Trimming these should improve load and build times by a few ms

Export json objects which only contain two properties:
```
// @klimadao/lib/abi/myContract.json
{
"contractName": "myContract",
"abi": [ ... ]
}
```
Update file names so they all match the contract name, except for generics like IERC20.json

ABIs can be copy-pasted from polygonscan.

**Comment by johnCbogil** [comment]
I've opened a pr for this here: https://github.com/KlimaDAO/klimadao/pull/19

Please lmk if there's anything else I can do to support 🙂

**Comment by Atmosfearful** [comment]
Closing this, thank you for your help!
https://github.com/KlimaDAO/klimadao/commit/eb84466d76345c6991efb7c2c8026925fcab4ce1
