### ISSUE TITLE
[klima data] Info pop-up text not active on SELECTIVE FEE label

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1700]
This page: https://carbon-git-staging-klimadao.vercel.app/
Also this page: https://carbon-git-staging-klimadao.vercel.app/details/price-of-digital-carbon

This section: Digital carbon pricing component
<img width="373" alt="Screenshot 2023-10-17 at 2 50 52 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d3ac7779-3b9c-4a10-ab05-c0cdb60f6e55">

<img width="1165" alt="Screenshot 2023-10-17 at 3 07 28 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/83623bb4-8c8b-4074-b7b1-c028ad2a8575">

Issue:
- There is an info icon beside the SELECTIVE FEE for each carbon asset that is not active (i.e no info pop up on hover)
- I expect the intention was to replicate the logic and content for the info pop ups on the Selective cost field here https://carbon.klimadao.finance/carbon-pricing
- We should probably change the label from SELECTIVE FEE to SELECTIVE COST as well

**Comment by biwano** [comment]
Hi @jabby09,

I could not reproduce the actual issue you described with the popup not showing. I was using the very standard HTML "title" attribute in the code. What browser did you use?
Anyways, In the PR I submitted I took the opportunity to use material UI to render the tooltip making it prettier.
