### ISSUE TITLE
Migrate klima-supply and block-rate endpoints

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1720]
related to launch of new KlimaDAO website
this is a blocker to changing the DNS

**Comment by Atmosfearful** [comment]
Blocked see PR description, just waiting for feedback from data team

**Comment by Atmosfearful** [comment]
#1720 will remove the endpoints, but it is blocked until this gets merged https://github.com/KlimaDAO/discord-bots/pull/69
