### ISSUE TITLE
Remove references to deprecated URLs

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1723]
* [x] Which of these URLs will be absent from the new Wix site?
```js
  home: "https://www.klimadao.finance",
  pledges: "https://www.klimadao.finance/pledge",
  resources: "https://www.klimadao.finance/resources",
  siteBlog: "https://www.klimadao.finance/blog",
  retirements: "https://www.klimadao.finance/retirements",
  contact: "https://www.klimadao.finance/contact",
  community: "https://www.klimadao.finance/community",
  buy: "https://www.klimadao.finance/buy",
  infinity: "https://www.klimadao.finance/infinity",
  mediaImage: "https://www.klimadao.finance/og-media.png",
  disclaimer: "https://www.klimadao.finance/disclaimer",
  ```
  
* [ ] For URLs that will be removed: Check `app` and `carbonmark` packages to make sure they are removed.

![image](https://github.com/KlimaDAO/klimadao/assets/88635679/2cde10a3-eb58-4d45-ba37-a31b2c6a9d30)

**Comment by jabby09** [comment]
@Atmosfearful 

Please find below the ones that will be **absent**: 

  pledges: "https://www.klimadao.finance/pledge",
  resources: "https://www.klimadao.finance/resources", <= we might yet build this page, but won't be present at launch
  retirements: "https://www.klimadao.finance/retirements",
  community: "https://www.klimadao.finance/community",
  mediaImage: "https://www.klimadao.finance/og-media.png",

**Comment by Atmosfearful** [comment]
@0xMakka can you just run through the monorepo and make sure these urls are not being referenced by any packages other than `site`

**Comment by 0xMakka** [comment]
### Urls not references anywhere else apart from `site`
- [X] pledges: https://www.klimadao.finance/pledge
- [X] siteBlog: https://www.klimadao.finance/blog
- [X] community: https://www.klimadao.finance/community
- [X] infinity: https://www.klimadao.finance/infinity

### Urls referenced in other packages
- [ ] home: https://www.klimadao.finance - `app`, `carbonmark`, `site`
- [ ] resources: https://www.klimadao.finance/resources - `carbon`
- [ ] retirements: https://www.klimadao.finance/retirements - `app`, `carbonmark`, `site`
- [ ] disclaimer: https://www.klimadao.finance/disclaimer - `carbon`
- [ ] contact: https://www.klimadao.finance/contact - `carbon`
- [ ] buy: https://www.klimadao.finance/buy - `app`, `site`
- [ ] mediaImage: https://www.klimadao.finance/og-media.png - `app`, `lib`, `site`
