### ISSUE TITLE
Remove `linkWithLocale` logic from `app`

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1725]
* [x] Confirm that the new Wix site will not be localized.
* [ ] This util was used to pass locales from `app` to site, it can be removed (if the new wix site isn't localized)

**Comment by jabby09** [comment]
@Atmosfearful 

> Confirm. Wix supports multilingual by using subdomains – we can build out this functionality later.

**Comment by Atmosfearful** [comment]
Example of utils that need to be removed/updated to no longer inject the `?locale=` into the url string 
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/bbd264ca-8684-40d4-9b66-81bf82d71347)
