### ISSUE TITLE
Migrate domain and apply redirects

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1726]
* [x] In DNS settings remove the vercel deployment and point the url at wix

In wix or in DNS we need to assign redirects:

* [x] Redirects from klimadao.finance to carbonmark:
- `klimadao.finance/retirements/[address]` -> `carbonmark.com/retirements/[address]`
- `klimadao.finance/retirements/[address]/[retirement_index]` -> `carbonmark.com/retirements/[address]/[retirement_index]`
- `klimadao.finance/pledge/[address]` -> `carbonmark.com/users/[address]`
- `klimadao.finance/infinity` -> `carbonmark.com`

* [x] Internal redirects
- `blog/[id]` -> `/resource/[id]`

**Comment by jabby09** [comment]
@Atmosfearful 

> Confirmed all those redirects, aligned.

**Comment by Atmosfearful** [comment]
This can proceed when #1720 is closed

**Comment by jabby09** [comment]
@Atmosfearful 

this redirect `klimadao.finance/pledge/[address]` -> `carbonmark.com/users/[address]`
should be `klimadao.finance/pledge/[address]` -> `carbonmark.com/retirements/[address]`

**Comment by Atmosfearful** [comment]
All redirects should be working now.

https://klimadao.finance/pledge/atmosfearful.klima
https://klimadao.finance/retirements/atmosfearful.klima
https://klimadao.finance/retirements/atmosfearful.klima/2
https://klimadao.finance/infinity
https://www.klimadao.finance/blog/public-goods-for-the-good-of-the-planet
