### ISSUE TITLE
[klima data] Need more scale/balance in detail chart

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1745]
This page: https://carbon-git-staging-klimadao.vercel.app/details/digital-carbon-supply-quick-facts

This component:
<img width="1152" alt="Screenshot 2023-10-24 at 9 37 23 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ae5123a4-3aa8-4ea6-b75e-815d1a15eb77">

Issues:
- All the text seems too small for the available space
- [Design is here](https://www.figma.com/file/mXI4SzNNmoefYnOdcbXZcO/Carbon-Dashboard?type=design&node-id=2787-11826&mode=design&t=U427A2bbO9dFhxv7-4)
- Is it possible to scale up all the text so it is larger and fills the component space better?

**Comment by biwano** [comment]
Hi @jabby09, I cannot reproduce on my PC. Can you provide me with your browser information?

This is how it looks to me: ![image](https://github.com/KlimaDAO/klimadao/assets/11857992/86461060-bc3c-4bbb-80d4-b5924170be67)

**Comment by biwano** [comment]
> Hi @jabby09, I cannot reproduce on my PC. Can you provide me with your browser information?
> 
> This is how it looks to me: ![image](https://user-images.githubusercontent.com/11857992/278221848-86461060-bc3c-4bbb-80d4-b5924170be67.png)

Nevermind, I think I understand now. PR incoming.
