### ISSUE TITLE
[klima data] Component sort issue on Retirement trends page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1747]
This page: https://carbon-git-staging-klimadao.vercel.app/retirement-trends?tab=byToken

This component:
<img width="372" alt="Screenshot 2023-10-24 at 9 53 32 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d1b082f0-3a54-4762-8900-9f0136ed5715">

Issues:
- should be sorted based on total tonnes redeemed, i.e. TC02, MC02, C3

**Comment by biwano** [comment]
Hi @jabby09 . I added programmatic sorting only for that particular card. The other ones are manually sorted. Are there other instances where there should be programmatic sorting for those kind of cards?

**Comment by jabby09** [comment]
> The other ones are manually sorted

@biwano what is meant by manual sorting? 

I'd have to go back and check the other components but this one stood out.

**Comment by biwano** [comment]
> > The other ones are manually sorted
> 
> @biwano what is meant by manual sorting?
It means that it is displayed in the order we load data in the code. It is not based on the values in the data.
> 
> I'd have to go back and check the other components but this one stood out.
