### ISSUE TITLE
[klima data - mobile] hamburger menu not functional

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1761]
The hamburger menu button in the top right corner on all sites is not working at all, tapping it does not do anything. Tested on Chromium-based browsers and Firefox.

**Comment by biwano** [comment]
lolz. I completly forgot about that. @theprofessora I think there is nothing in particular designed for the content of this button. Should we put a quick access menu to the various pages or we just remove it and let users rely on the bottom navigation component?

**Comment by theprofessora** [comment]
@biwano the plan was to re-use the hamburger menu currently employed on the klimadao website:

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/e70aedd2-8894-4434-a8b6-0572e10a648f)

I don't have a design file for this, as it was built before my time at the DAO but i'm sure @Atmosfearful has it as a pre-built component somewhere
