### ISSUE TITLE
[klima data] Token Details - toggle selections need to be indicated on Detail pages

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1762]
This page: https://carbon-git-staging-klimadao.vercel.app/token-details?tab=toucan
Note: applies to all tabs

Issues:
- When I make filter / toggle button selections, the charts on the main page update
<img width="576" alt="Screenshot 2023-10-25 at 3 09 20 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/17c481e7-f756-44ae-a705-23f785ffaaf6">

- If I open a chart Details --> the correct chart is shown, i.e. the filter / toggle button selections are respected. However, I have no indication anymore what the selections are
- Need to indicate the toggle button selections on Details --> pages

**Comment by sprrwhwk** [comment]
@jabby09 is it enough if we indicate the selections of the overview page without the option to make changes on the detail page?

**Comment by jabby09** [comment]
> s it enough if we indicate the selections of the overview page without the option to make changes on the detail page?

yes
