### ISSUE TITLE
[klima data] Token details - filter toggle options disappearing

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1764]
This page: https://carbon-git-staging-klimadao.vercel.app/token-details?tab=c3
Note: Applies to all tabls

This component:
<img width="644" alt="Screenshot 2023-10-25 at 3 15 31 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ad19649b-24e5-4c93-9d9f-4b2aab86efe3">

Issues:
- If I select any specific token option besides All Tokens then Retired option disappears
<img width="527" alt="Screenshot 2023-10-25 at 3 16 28 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/8a8d060f-544b-4991-a743-f5add4a6b826">

- If I select Retired option, then everything All Tokens disappears
<img width="525" alt="Screenshot 2023-10-25 at 3 17 36 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/43a97cd4-77b9-40db-89ca-6c0f50eb0ff5">

**Comment by biwano** [comment]
Hi Jabby, this is done on purpose because we do not have sufficient information to compute retirment charts at pool level (tagging @0xAurelius here in case i am wrong).
In the legacy app, the toogle buttons are not available on pool pages: see: https://carbon.klimadao.finance/bct

**Comment by 0xAurelius** [comment]
Hmm, so the only piece of info we'd be missing is whether a retirement of a specific _project_ came from a pool, unless that retirement was made via the retirement aggregator

That does mean certain charts on this page, like the breakdown of retirements by methodology for a particular pool, wouldn't be able to be rendered unless we limit only to retirements made via the aggregator

**Comment by biwano** [comment]
> Hmm, so the only piece of info we'd be missing is whether a retirement of a specific _project_ came from a pool, unless that retirement was made via the retirement aggregator
> 
> That does mean certain charts on this page, like the breakdown of retirements by methodology for a particular pool, wouldn't be able to be rendered unless we limit only to retirements made via the aggregator

Thanks for the insights @0xAurelius . What do you mean by `only to retirements made via the aggregator` sorry I am not familiar with the inner workings of pools.

@jabby09 From what I understand I can show the retirements options for pools and put in there at least charts showing  deposited/redeemed/retired tonnes over time like it was done in the legacy app.

**Comment by jabby09** [comment]
> What do you mean by `only to retirements made via the aggregator` sorry I am not familiar with the inner workings of pools.

I think it means related to all the notes we have in the legacy app about certain charts only representing retirement from the RA

![Screenshot 2023-10-30 at 9 58 07 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/887c33db-9383-463b-9df8-ebd0383df241)
