### ISSUE TITLE
[carbonmark] `/portfolio/[asset]/retire` form should prevent users from retiring listed tonnes.

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1791]
Currently its possible to use this form to retire tonnes you already have listed
<img width="795" alt="image" src="https://github.com/KlimaDAO/klimadao/assets/88635679/915da0fa-5ce9-4ec2-bbb1-7d9ff57dca38">

currently this button is disabled if `unlistedTonnes === 0`

but this is not enough. The button takes you to a form, and this form needs needs to prevent you from retiring more than your unlisted balance.

# Solution

in /portfolio/[asset]/retire page

1. Fetch the connected /user
2. Utilize the utils we have defined in `listings.utils.tsx`
3. Only allow the user to retire unlisted balance (total asset amount, minus listed tonnes)

May require changes to `getServerSideProps` ?https://github.com/KlimaDAO/klimadao/blob/1aedc35cf348203e5e804469a8e2e5d8f751b9ab/carbonmark/pages/portfolio/%5Bproject_token_0x%5D/retire/index.tsx#L11

Or probably can be done all client side fetching w/ swr ?

**Comment by jabby09** [comment]
@0xemc I spoke with atmos and understand you are going to focus on a different workstream.

@0xMakka please take a look at this one and then book a time with @Atmosfearful if you have questions. This is a high priority one for the contract v2 launch.
