### ISSUE TITLE
[klima data - mobile] section missing in portrait mode

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1797]
Site: https://carbon-git-staging-klimadao.vercel.app/off-chain-vs-on-chain

On mobile, the bottom section ("Credits tokenized vs credits issued by origin") is missing completely.

This might be intentional I guess because the amount of information is difficult to display on a small vertical screen, but I still wanted to raise the issue just to make sure.

Works fine in landscape.

**Comment by biwano** [comment]
Hi @0xtapi it is intentional (done as per the designs). I close the ticket and tag @theprofessora just in case.
