### ISSUE TITLE
[klima data - mobile] details buttons overflowing

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1798]
Site: https://carbon-git-staging-klimadao.vercel.app/off-chain-vs-on-chain

The "Details ->" button sometimes breaks free of his prison and attempts to leave the website jail.

Issue here:
![Screenshot_20231029-112526-145](https://github.com/KlimaDAO/klimadao/assets/128430614/cb343e04-7ade-4ba6-a8bf-15899489663d)

This is on mobile Chrome with text scaling to 100%. I actually can't find any setting (that works!) that lets me change the text scaling on KlimaData. The various settings seem to have no effect.

Mobile Firefox with automatic scaling adjusts the font size to a level where this is not a problem and the website looks good on it (no element breaking or anything of that sort). Text scaling also works as expected.

**Comment by biwano** [comment]
We use the rem unit, I suppose that's why text scaling is "locked"

@theprofessora I am not sure how to solve this. Should we put the detail link on the bottom of the chart when the card text is too long?

**Comment by theprofessora** [comment]
@biwano is it possible to have the text wrap to a second line if it's too long?

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/e83af461-4f12-426d-bbf5-0b54a029fd5b)

If that's not possible then we can put the btn on the bottom
