### ISSUE TITLE
[contract v2] contract annoyed by decimals

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1801]
See here:
![Screenshot 2023-10-29 125909](https://github.com/KlimaDAO/klimadao/assets/128430614/c4779f4a-3ce4-4434-b9b5-13024dbba0f8)

Contract doesn't like too many decimals. Unlikely to ever be a real-world problem, but a bug is a bug I guess...

**Comment by 0xMakka** [comment]
@jabby09 / @Atmosfearful I can limit this to x amount of decimal points and show an error message under if anything over the limit? Is 5/6 decimal points acceptable for this or have we any need to allow more?
