### ISSUE TITLE
[login] wallet selection sometimes not working - MM & Coinbase conflict

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1802]
I have a clean Brave browser with only Metamask and Coinbase wallet installed.

Bug is a bit difficult to reproduce, but sometimes this works:

1.) Shut down Brave completely, open it again.
2.) Go to https://staging.carbonmark.com/retire (or any other subpage of Carbonmark).
3.) Try to log in, select Metamask.
4.) Coinbase wallet pops up instead, asking me to enter my password. If I click Coinbase wallet instead in step 3, Coinbase also pops up, so I cannot access Metamask at all.

But: If I unlock Metamask before I try to log on Carbonmark, it lets me log in instantly.

Second but: If I then log out of Carbonmark and back in, it asks me to pick a wallet again, which sends me back to Coinbase popping up again (despite Metamask being unlocked now).

Feels a bit random, because sometimes I have no issues and sometimes it sends me through all the steps I just described. Could be that it's just two wallets in the background having a fight, so maybe not worth investigating this and instead help users on a case by case basis?

**Comment by jabby09** [comment]
thanks @0xtapi 
I've seen this issue or something similar before. 
Not specific to CM Contract v2 so I've removed from the QA epic and renamed the issue.
Also an edge case and low priority.

For anyone working on this, I believe it had something to do with MM and CB both using a window.ethereum parameter.

#881 and #923 may have clues.

**Comment by 0xMakka** [comment]
Hey guys, I spent some time investigating this and unfortunately I can't find an easy solution to the problem. It seems both are battling for the window.ethereum. I tried some fixes [suggested by coinbase](https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance#:~:text=If%20a%20user%20has%20both,up%20window%20to%20connect%20wallet.&text=%7D%3B,your%20provider%20throughout%20the%20dapp.)and a number of other fixes, but none of them seemed to work as intended. 

One fix I tried worked okayish if your metamask wallet was opened, but it involved making a number of changes through some window.ethereum functions, but the minute your MM wallet is locked, it doesn't work as expected i.e. you get the Coinbase wallet popup again when selecting Metamask.

**Comment by jabby09** [comment]
> Hey guys, I spent some time investigating this and unfortunately I can't find an easy solution to the problem. It seems both are battling for the window.ethereum. I tried some fixes [suggested by coinbase](https://docs.cloud.coinbase.com/wallet-sdk/docs/injected-provider-guidance#:~:text=If%20a%20user%20has%20both,up%20window%20to%20connect%20wallet.&text=%7D%3B,your%20provider%20throughout%20the%20dapp.) and a number of other fixes, but none of them seemed to work as intended.
> 
> One fix I tried worked okayish if your metamask wallet was opened, but it involved making a number of changes through some window.ethereum functions, but the minute your MM wallet is locked, it doesn't work as expected i.e. you get the Coinbase wallet popup again when selecting Metamask.

@Atmosfearful what do you think? Kind of an edge case...any ideas or should we just de-prioritize this one for now?

**Comment by Atmosfearful** [comment]
The code I'm seeing on our end looks correct:
- all we can do is invoke window.ethereum methods, we can't differentiate between different wallets
- we check for `provider.isMetaMask` and only show the metamask button if they have it. Here we would *expect* metamask to pop up if `isMetaMask` is true.... but it seems this is not the case. Nothing we can do about this.
