### ISSUE TITLE
[klima data] missing T or percentage on Tokenized credits by bridge

### ISSUE THREAD

**Issue by ChazSchmidt** [KlimaDAO/klimadao#1810]
On the off and oh-chain page (https://carbon-git-staging-klimadao.vercel.app/off-chain-vs-on-chain), the 'Tokenized credits by bridge' is missing the % information you find on the details page when you hover over

![carbondatadashboardtokenizedcreditsbybridge](https://github.com/KlimaDAO/klimadao/assets/11149889/f8f6844f-0a95-41bf-b34d-39474bfe637e)

**Comment by biwano** [comment]
Yeah, this one is done as per the figma designs (percentage in the details page but not on the main page).
I understand it seems weird. Tagging @theprofessora here.

**Comment by jabby09** [comment]
yea I'm seeing inconsistency with all the various circle charts. sometimes we show % on the details page but sometimes not. 

@theprofessora is the pattern that you want a more basic label on the summary dashboard page and then on details page any circle graph should have the % as part of the label? There are places in the design where this is not consistent.

**Comment by theprofessora** [comment]
@jabby09 @biwano okay I've updated the figma. Jabby is right, the pattern should be a more basic label on the summary dashboard page and then %s on the details page, with MTs provided in the hover tooltip.

**Comment by biwano** [comment]
Hello, @jabby09  @theprofessora,

I created a PR for this issue but it is not complete.
The State of xxx Digital carbon cards, we have tons retired + tons outstanding = tons bridged.
In fact the tons bridged value represent allways 100% of the pie. Actually the pie represents only the tons outstanding and the tons retired. So we cannot use the current figma design for this one.

**Comment by jabby09** [comment]
> I created a PR for this issue but it is not complete.
> In the State of xxx Digital carbon cards, we have: `tons retired + tons outstanding = tons bridged`.
> In fact the tons bridged value represent always 100% of the pie. Actually the pie represents only the tons outstanding and the tons retired. So we cannot use the current figma design for this one.

@biwano I think you mean the `Token details` pages (https://carbon-git-carbon-qa1810-klimadao.vercel.app/token-details?tab=c3)?

@theprofessora take another look at that page in the preview link above and see if you have additional recommendations for this page specifically?
