### ISSUE TITLE
[offsetra API] Changes to support credit card payment on Retire from Seller listing

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1818]
The Offsetra API that used for credit cards payments will need to be updated to support retire from a Seller listing.

Primarily this would involve needing the listing ID from the ABI.

A proper technical review / discovery is required on the Offsetra API to confirm the requirement changes for this issue.

**Comment by jabby09** [comment]
@psparacino when you are free of ICR, this would be a next priority.
You may need to book time with @Atmosfearful to finalize requirements.

**Comment by Atmosfearful** [comment]
**In /checkout**
We constyruct a stripe session and pass in metadata, update this to also pass in the chosen listing_id if present.

**In /checkout -> `estimateRetirementCost`**
This is used to determine the price shown to the user, and the price sent to Stripe for the checkout link.
This function needs to be updated to handle a third case, to determine the total cost of retiring from a listing

**In /retire**
- Upgrade the api to accept a listing_id
- invoke the new retireFromListing method (TBD)

**Comment by jabby09** [comment]
@sprrwhwk can this one be closed now?

**Comment by sprrwhwk** [comment]
Yes! 🚀
