### ISSUE TITLE
[carbonmark] Pricing discrepancies

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1819]
Prices aren't matching between /projects and /projects/[id]

Consider:
1. Are we reflecting the correct "Default pool price" (1 project per pool i.e. 4 specific tokens have zero redemption fee)
default projects are here https://github.com/KlimaDAO/klimadao/blob/dfa39653bbb9a67ccd79c2e13152a3da28b8bec8/lib/utils/getDefaultProjects/index.ts#L17
2. Are we correctly sorting to show the lowest price (in cases where a project exists in multiple pools)

**Comment by jabby09** [comment]
this is resolved by #2049
