### ISSUE TITLE
[Demo] Add Form Route

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1823]
## Feature Request

**Title:** 
Demo Form Route

**Description:**
Create and expose a route within Carbonmark (or as a seperate package) that contains the UI elements of a form to calculate carbon for a chosen flight path and allow the user to retire said amount of carbon.

**Acceptance:**
- [x] Accessible route at `/demo`
- [x] A form containing `from`, `to` & `asset` fields and a retire button

**Comment by jabby09** [comment]
@0xemc I think we can close this one now?

**Comment by 0xemc** [comment]
> @0xemc I think we can close this one now?

Yep done, thanks @jabby09
