### ISSUE TITLE
[klima data] Add monitoring to the carbon dashboard

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1829]
The goal of this ticket is to:
- Monitor the service
- Ping the pages to hit stale caches before the users

The URLs to check are the following:
- https://data.klimadao.finance
- https://data.klimadao.finance/off-chain-vs-on-chain
- https://data.klimadao.finance/supply
- https://data.klimadao.finance/retirement-trends
- https://data.klimadao.finance/token-details

**Comment by Atmosfearful** [comment]
@biwano 

> Monitor the service
Have you looked into the vercel built-in monitoring? https://vercel.com/docs/observability/monitoring
I've never used it-- may cost extra. This would satisfy my needs, let me know if you agree or if there is a specific feature/functionality you had in mind for a monitoring tool

> Ping the pages to hit stale caches before the users

I'm not quite sure what the goal here is-- could you elaborate?

**Comment by biwano** [comment]
> @biwano
> 
> > Monitor the service
> > Have you looked into the vercel built-in monitoring? https://vercel.com/docs/observability/monitoring
> > I've never used it-- may cost extra. This would satisfy my needs, let me know if you agree or if there is a specific feature/functionality you had in mind for a monitoring tool

@Atmosfearful 
The Vercel tool seems okay for the monitoring part I would need someone to enable it (if there is a cost I am not sure it is worth it though)
![image](https://github.com/KlimaDAO/klimadao/assets/11857992/179262a1-9857-47c8-bf8c-f61559abac83)

> 
> > Ping the pages to hit stale caches before the users
> 
> I'm not quite sure what the goal here is-- could you elaborate?

The goal would be to make regular GET requests to the URLs in description, this requests would trigger cache rebuilds when the cache is stale. This would prevent real users to hit stale caches.

**Comment by biwano** [comment]
Hi @Atmosfearful.
Do we implement sentry for the API?
