### ISSUE TITLE
[ICR] Support ex-ante credits in CM Marketplace - Discovery & Design

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1854]
We want to support ex-ante and ex-post credits.
Ex-ante credits would not be used for retirement though. They would be purchased + held until converted to ex-post credits.

ex-antes are just another tokenID on the same project contract so everything should work on the contract level.
the retire function does this check at their contract level, so there's nothing else really needed on our end to check. 
```
function retire(
        uint256 tokenId,
        uint256 amount,
        address beneficiary,
        string memory retireeName,
        string memory customUri,
        string memory comment,
        bytes memory data
    ) public onlyExPostToken(tokenId) returns (uint256 nftTokenId)
```
Will require differentiated the credit types in the subgraph. Realistically though the unique ID for the CarbonCredit entity will include the token Id so there'd be the normal supply and holdings values for that credit id. We will need `isExPost` or equivalent bool as well.

There will also be API and UI/FE changes required to support ex-ante credits.

**Comment by Atmosfearful** [comment]
Latest updates:
- @psparacino spoke with Cujo and it sounds like the subgraph layer is already finished, no additional changes have been identified there.
- API needs to pass ex-ante and ex-post balances
- Disable retirement for ex-ante in the frontend
- We don't have designs for what ex-ante listings look like
- Open questions around stale listings:
  - We need to identify places in the API (users, projects, project details, listings) that can have stale ex-ante listings and filter them accordingly
- Do we know the date that a given credit will be converted from ex-ante to ex-post?
  - No. If we did, we could auto-set the listing expiration date.
- Does the conversion process require user input?
  - Currently, yes. Potentially in the future controlled by ICR admins (?) Peter is still talking to Thor about this.

**Comment by jabby09** [comment]
issue migrated to https://github.com/Carbonmark/monorepo/issues/133
