### ISSUE TITLE
Fix wording for bond 'Pending'

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#191]
Might not be a bug, but I think just poor wording?

![image](https://user-images.githubusercontent.com/88635679/154526691-f605131c-970b-406e-9ca7-e08277bcd257.png)

**Comment by jstirnaman** [comment]
Maybe "Total unredeemed" or "Unredeemed value" (used in the tooltip) would be better than "Pending"? "Pending" is too vague, vs "un/redeemed". The tooltip could say something like "Total amount (vested and unvested) pending redemption".
