### ISSUE TITLE
The retire button is not available when amount < 1 USD even when paying with USDC

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#1931]
**Describe the bug**

**To Reproduce**
1. Go to https://www.carbonmark.com/fr/projects/VCS-191-2010/retire/pools/bct
2. Fill in 1 ton
3. Fill in beneficiary name
4. Fill in message
5. Choose to pay with USDC

**Expected behavior**
The retire button should be available

**Screenshots**
![image](https://github.com/KlimaDAO/klimadao/assets/11857992/78059be5-b0ed-47f7-abf5-e935bde00b06)

**Comment by 0xMakka** [comment]
@biwano this looks like it could be related to the same issue that is being addressed in https://github.com/KlimaDAO/klimadao/pull/1913. Can you check the PR branch from here to see if the issue is still present?

**Comment by biwano** [comment]
@0xMakka Yeah it is the seame issue
Clsed in favor of #1906
