### ISSUE TITLE
[subgraph] Migrate to polygon-digital-carbon

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1938]
Currently site & carbonmark are using the `polygon-bridged-carbon` subgraph for offset and retirement data. This subgraph has been depricated and we should be using `polygon-digital-carbon` https://api.thegraph.com/subgraphs/name/klimadao/polygon-digital-carbon/graphql

**Comment by Atmosfearful** [comment]
@psparacino Did you already migrate more bits of the FE in your ICR PR?

**Comment by psparacino** [comment]
> @psparacino Did you already migrate more bits of the FE in your ICR PR?

working on the retirement receipt now actually yes, which is independent of ICR so I can hold off and/or open as a separate PR.  I haven't gotten to the FE yet as there are some subgraph items I'm sorting out first.

**Comment by psparacino** [comment]
Just fyi, I have an interim solution, using subgraphs not endpoints, almost ready to go using the pdg subgraph here for retirement data: https://github.com/KlimaDAO/klimadao/tree/tufnel/update-subgraph-for-retirement-data as the ICR branch is dependent on using pdg

**Comment by psparacino** [comment]
Just fyi, I made an interim solution that's almost ready to go, just using the pdg subgraph and not endpoints for now, here for retirement data: https://github.com/KlimaDAO/klimadao/tree/tufnel/update-subgraph-for-retirement-data as the ICR branch is dependent on using pdg
