### ISSUE TITLE
[api] Add retirements to carbonmark-api

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1939]
`/retirements` is a nextjs api route managed internally by Carbonmark. It should be brought in line with other subgraph requests and accessed via the API.

**Comment by Atmosfearful** [comment]
Agreed, see my comment here https://github.com/KlimaDAO/klimadao/issues/1938#issuecomment-1842649492

we need /retirements
/retirements/[beneficiary]
and /retirements/[beneficiary]/[index]

**Comment by 0xemc** [comment]
@biwano this is complete now correct?

**Comment by biwano** [comment]
> @biwano this is complete now correct?

Yes complete. 
- /retirements for search
- /retirements/[hash] for single retirement
