### ISSUE TITLE
[profile | portfolio] Screen flashing and content regressions on Profile & Portfolio pages

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1944]
Related issues:
#1940 
#1063 

This PR https://github.com/KlimaDAO/klimadao/pull/1942 was introduced to fix profile bugs in #1940

This appears to have introduced a new set of issues:

- [x] When I access another users public profile (for example https://www.carbonmark.com/users/offsetra) the initial screen view flashes the Listings - No active listings page before rendering properly

- [x] A new login with no Profile created should still show the temp avatar and wallet and stats / activity components. The figma design for a seller that has logged in but not yet set up their profile is [here](https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7/Profile?type=design&node-id=13-13294&mode=design&t=g8WQBIgLuA3J3cXB-4); assuming the Marketplace navigation item is still active; i.e. start from the marketplace, click login, go through the login modal, end up on this page.

<img width="754" alt="Screenshot 2023-12-01 at 9 32 44 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/7813b642-184e-471f-a419-d95457e04cbd">
vs 
<img width="705" alt="Screenshot 2023-12-01 at 9 33 27 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/0c6a4c8d-ddcc-4341-80bd-b16d43acc941">

- [x] Recent portfolio page content changes that were merged as part of #1063 not longer seem to be there anymore. Currently if you do not have a profile, the Portfolio page is completely blank.

**Comment by Atmosfearful** [comment]
> Using social logins, if I've logged in and then log out, if I login again in the same browser session with a different social login (for example google instead of discord) the web3 auth appears to send me to the correct location but I still get connected to carbonmark with the previous user (in this case, my discord user). Basically it appears that within a browser session, if I log out if does not fully release the account I was logged in as.

I think this one should be moved to a separate ticket, I think we can merge michaels PR to resolve the other more pressing issues

**Comment by jabby09** [comment]
> I think this one should be moved to a separate ticket, I think we can merge michaels PR to resolve the other more pressing issues

done
