### ISSUE TITLE
[projects] Sort dropdown should change with list view sorting 

### ISSUE THREAD

**Issue by 0xMakka** [KlimaDAO/klimadao#1957]
**Describe the bug**
On carbonmark on the projects view, when you sort the list view columns the sort dropdown should switch to the sorted value.

**To Reproduce**

** Note - can't reproduce on production at the moment until https://github.com/KlimaDAO/klimadao/pull/1956 is merged as it contains an additional fix for the list view immediately switching back to grid view after trying to sort the table view.

1. Go to projects
2. Click on the list view icon
3. Sort the list view table by Vintage 
4. The sort dropdown doesn't update 

**Expected behavior**
When clicking on vintage or any other sortable column, the sort dropdown should update to reflect the sorted column

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOs
 - Browser: Brave

**Comment by jabby09** [comment]
closing as part of https://github.com/Carbonmark/monorepo/pull/712
