### ISSUE TITLE
[api] VCS-1764-2020 project not appearing in filtered results

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#1958]
**Describe the bug**
The project appears in `search=myanmar`, example: ✅ 
https://api.carbonmark.com/projects?search=Myanmar

However the project does not appear in `country=Myanmar`
https://api.carbonmark.com/projects?country=Myanmar
Nor in `category=Blue Carbon`
https://api.carbonmark.com/projects?category=Blue%20Carbon

**Comment by jabby09** [comment]
@0xemc did this one get resolved in the api fixes?

**Comment by 0xemc** [comment]
Not yet, it is in this PR now

https://github.com/KlimaDAO/klimadao/pull/2029
