### ISSUE TITLE
[retire] URL change needed for Quick Retire projects

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#1964]
I noticed some of the tokens we recommend in the Quick Retire section (at https://www.carbonmark.com/retire) lead to 404s (the Henan and Pacajai project, specifically). To reproduce, open the URL and click either one of those projects.

In both cases, the URL leads to .../retire/pools/bct, but both tokens are only available in UBO/NBO/NCT pools. If you manually change the URL, it opens the projects as expected (in the case of the Pacajai project to .../retire/pools/nct for example). Makes me think whether these links ever worked? 🤔

**Comment by jabby09** [comment]
@0xtapi this section of the page is meant to be the the defaults for each pool. It's the project with the oldest vintage.

[BCT](https://www.carbonmark.com/projects/VCS-191-2008) - 0xb139c4cc9d20a3618e9a2268d73eff18c496b991
https://www.carbonmark.com/projects/VCS-191-2008
[NCT](https://www.carbonmark.com/projects/VCS-1529-2012) - 0x6362364a37f34d39a1f4993fb595dab4116daf0d
https://www.carbonmark.com/projects/VCS-1529-2012
[UBO](https://www.carbonmark.com/projects/VCS-1140-2015) - 0xd6ed6fae5b6535cae8d92f40f5ff653db807a4ea
https://www.carbonmark.com/projects/VCS-1140-2015
[NBO](https://www.carbonmark.com/projects/VCS-981-2014) - 0xb6ea7a53fc048d6d3b80b968d696e39482b7e578
https://www.carbonmark.com/projects/VCS-981-2014

**Comment by 0xtapi** [comment]
> Can you write up the changes below in a comment and then we can get this assigned to someone.

Change the four URLs related to Quick Retire on https://www.carbonmark.com/retire to the following:

- BCT: https://www.carbonmark.com/projects/VCS-191-2008/retire/pools/bct (this is already the correct link in production)
- NCT: https://www.carbonmark.com/projects/VCS-1529-2012/retire/pools/nct
- UBO: https://www.carbonmark.com/projects/VCS-1140-2015/retire/pools/ubo
- NBO: https://www.carbonmark.com/projects/VCS-981-2014/retire/pools/nbo

**Comment by jabby09** [comment]
@biwano I re-opened this just so we don't lose sight of it.
Once the api update is merged, we can confirm the fix in production and close again.

**Comment by jabby09** [comment]
this is now blocked by api version update issue #1987

**Comment by jabby09** [comment]
@0xtapi this is resolved now, closing issue
