### ISSUE TITLE
Add current total supply API

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#198]
In order for CMC to properly display our market cap on their site, we need to provide them with a specific API endpoint that just returns the total supply as a number (and nothing else)

Tried to direct them to use our Subgraph but they don't seem to be that flexible and I can't figure out a way to get a single value out of a GraphQL URL-based query

So we can just create a simple endpoint like `/supply` that fetches the current total supply from the KLIMA contract ABI and returns that single value.

Original request received from CMC:
![image](https://user-images.githubusercontent.com/91024694/155031292-a3927373-a2b4-4ffc-aeef-84bcb38c72e6.png)

**Comment by Atmosfearful** [comment]
@ArchimedesCrypto I'm too lazy to sift through the contracts, what's the fastest way to determine total supply? is there a method similar to `contract.getReserves()` ?

@0xAurelius do I need to just return the KLIMA supply, ignoring sKLIMA?

**Comment by 0xAurelius** [comment]
It should just be a matter of calling the `totalSupply` function on the KLIMA ERC-20 contract - no need to account for sKLIMA or wsKLIMA

Example in Python for the Discord bots here: https://github.com/KlimaDAO/discord-bots/blob/main/src/contract_info.py#L36
