### ISSUE TITLE
[api] Missing Projects from staging & production

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1987]
Over 150 projects are missing from the search results after moving from v2.0.0 to v2.0.2 of the API

https://v2.0.0.api.carbonmark.com/projects
https://v2.0.2.api.carbonmark.com/projects

e.g VCS-1100 & VCS-1162

**Comment by jabby09** [comment]
@0xemc this project https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1382-2015 is showing up in the marketplace:
![Screenshot 2023-12-08 at 9 25 14 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/ebfee810-d05f-4ff1-8a4c-a41efe87df4e)

...but it has a quantity available = 0 so it should be filtered out of the results. UNLESS this is related to #1996 ?
![Screenshot 2023-12-08 at 9 26 07 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/42c79646-5633-445d-8b36-2b0581e8cbff)

**Comment by jabby09** [comment]
@0xemc the VCS-614 vintage projects are now showing up with Industrial Processing image and I can filter for those projects using Industrial Processing category:
![Screenshot 2023-12-08 at 9 29 46 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/dec7bd65-433d-401c-b41f-914fd9fab99a)

However, if I go to a project detail page, in the header section the banner image is correct but the label is still `Other`
![Screenshot 2023-12-08 at 9 31 03 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/1576f154-954a-4da6-b3f1-a86f4b8a5597)

**Comment by 0xemc** [comment]
> @0xemc this project https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects/VCS-1382-2015 is showing up in the marketplace: ![Screenshot 2023-12-08 at 9 25 14 AM](https://private-user-images.githubusercontent.com/103535195/289080498-ebfee810-d05f-4ff1-8a4c-a41efe87df4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQ3MjQsIm5iZiI6MTcwMjI5NDQyNCwicGF0aCI6Ii8xMDM1MzUxOTUvMjg5MDgwNDk4LWViZmVlODEwLWQwNWYtNGZmMS04YTRjLWE0MWVmZTg3ZGY0ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxMTMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02NDc1YTI5NTc2Yzk1YjNkYWE5Zjg4ZWEzODRhMTdhOTE4ZTEzNzdhMTFhNzBhOGExMDBhZThkZDQ3ZTRjNjA1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ud9agKR_0AlYWDwDOQDGWaTtvUqFjnVh-1kQdlQT_tU)
> 
> ...but it has a quantity available = 0 so it should be filtered out of the results. UNLESS this is related to #1996 ? ![Screenshot 2023-12-08 at 9 26 07 AM](https://private-user-images.githubusercontent.com/103535195/289080843-42c79646-5633-445d-8b36-2b0581e8cbff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyOTQ3MjQsIm5iZiI6MTcwMjI5NDQyNCwicGF0aCI6Ii8xMDM1MzUxOTUvMjg5MDgwODQzLTQyYzc5NjQ2LTU2MzMtNDQ1ZC04YjM2LTJiMDU4MWU4Y2JmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxMTMzNDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODE5ODA2ZmIwOGE5ZDFhMzlhOGI4NjkyNzdhODg3Yzg1YzYzNGQ1MjdiYTE1MWJjZjNhOTMzNTUxNDg1ZmQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JyYlYFIs320nGwl0Fx3ss-IBj0_YScRHqEZWkAFo56I)

>...but it has a quantity available = 0 so it should be filtered out of the results. UNLESS this is related to https://github.com/KlimaDAO/klimadao/issues/1996 ?

^ exactly, that's the case

**Comment by 0xemc** [comment]
@jabby09 could you take a second look at https://carbonmark-git-emc-fix1987-sanitize-category-names-klimadao.vercel.app/projects/VCS-614-2013

**Comment by jabby09** [comment]
> could you take a second look

This is good now with the fix introduced with #2013

**Comment by jabby09** [comment]
@0xemc I think we can close this one once the release gets to production
