### ISSUE TITLE
[ICR] ERC1155 Approval Copy changes

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#1989]
The ERC1155 approval mechanism differs from the ERC20 and the approval modal copy should reflect that change as the signing message will be different in MM or other wallets.

The ERC1155 uses setApprovalForAll which allows all amounts for all tokenIds in the contract.

**Comment by jabby09** [comment]
> Whle this task is done, the copy should be conditional on approving an ERC1155

yes I agree, that was the overall point of the issue so if we did not achieve that then will need to revisit

**Comment by psparacino** [comment]
it should be a very quick fix, I'll keep this issue open for the moment and take care of it this week
