### ISSUE TITLE
[retire] Add pay with bank transfer option - user journey priority #1

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1992]
### Related docs & links
[shipped figma designs](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1830-17766&mode=design&t=jZBOtWJqyzfOTFSh-0)

[Design/discovery discord thread](https://discord.com/channels/1135827610434289727/1176908485368233985)

### Requirements & user journey

- User journey starts from a [project details page](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1830-18024&mode=design&t=jZBOtWJqyzfOTFSh-4)
- User clicks RETIRE NOW on a pool or seller listing (support for this is in progress in #1659 )
- This opens the [retire payment form](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1810-16827&mode=design&t=jZBOtWJqyzfOTFSh-4)
- Need to add a Bank Transfer Pay with: option
<img width="472" alt="Screenshot 2023-12-07 at 9 13 26 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/ff9f7e45-21bb-4f57-a3d3-bf21b9354326">

- User clicks Bank Transfer Pay with: option
- User fills in the required "How many tonnes..." field and in this case has also filled in beneficiary name and retirement message (although beneficiary name, beneficiary wallet, and retirement message are optional fields, same as when paying with USDC). This [activates the RETIRE CARBON button which the user clicks](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1810-23803&mode=design&t=jZBOtWJqyzfOTFSh-4)
- User is next presented with a [Confirm Purchase modal](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1810-24185&mode=design&t=jZBOtWJqyzfOTFSh-4); they click CONTINUE (Note...GO BACK returns the user to the retire payment form)
- User completes the [Pay with bank transfer form](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1810-24580&mode=design&t=jZBOtWJqyzfOTFSh-4)

**Pay with bank transfer form notes**
- LEARN MORE will go to a marketing blog post (still to be written, URL to be provided)
- The project, tonne quantity, and any optional fields filled in on the retire payment form needs to be passed to the Pay with bank transfer form. We do not want to have to make the user fill out the information twice.
- Note the form differences between desktop and mobile
- Note required form fields...you will need to add some error handling here using our standard of highlighting the field in a red box and providing helper text

- User completes the form with no required field errors and clicks the SUBMIT button
- ~On SUBMIT, the form contents should be send to **sales email address** (to be provided)~
- Rather than an email, we will write the form data to hubspot using their api, see comment below
- Once that process completes, show the user a [Form complete thank you page](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1830-26135&mode=design&t=jZBOtWJqyzfOTFSh-4)
- The Form complete page should show all the form fields and data that were submitted

- This completes the pay with bank transfer user journey. Clicking BROWSE PROJECTS on the Form complete page returns the user to the Marketplace.

**Comment by Atmosfearful** [comment]
@0xMakka We will use the API for unauthenticated form submissions

https://legacydocs.hubspot.com/docs/methods/forms/submit_form

> POST `https://api.hsforms.com/submissions/v3/integration/submit/:portalId/:formGuid`

```
portalId: 26010207, // carbonmark
formGuid: "2f87cd63-f8a7-43e9-9483-ac541a614762" // a.k.a. `formId`
```

**Comment by jabby09** [comment]
> @0xMakka

I updated the requirements section above to reflect this change
