### ISSUE TITLE
[project] Difference in supply values

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1996]
Description:
There is a discrepancy between the total supply value shown in the pool and the value displayed on the stats card on the /project/[id] page.

![image](https://github.com/KlimaDAO/klimadao/assets/7104689/a3da40d7-1c23-4011-b2de-f440ad9697c1)

**Comment by jabby09** [comment]
@0xemc https://www.carbonmark.com/projects/VCS-1382-2015

**Comment by Atmosfearful** [comment]
@0xemc
Prices.supply should be the quantity actually available for purchase from that pool.
totalsupply is actually the ERC20 contracts total remaining tokens across all holders (which includes pools).
