### ISSUE TITLE
[devops] /get projects tests

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#1997]
It is clear that the API's testing is not sufficient to catch major errors as there have been many issues recently. The /projects route in particular has been inconsistent.

The following cases should be covered:

- [ ] Projects with "dust" (supply less than 1 tonne) should be filtered
- [ ] Projects with 0 price across all assets should be filtered
- [ ] There should be no duplicates in the results
- [ ] Project fields should be sanitised
- [ ] Filters work as expected
- [ ] Same asset in multiple pools and listings
- [ ] Different assets (of the same credit) in multiple pools and listings
- ...

**Comment by Atmosfearful** [comment]
Off the top of my head:
- same asset in multiple pools and listings
- Different assets (of the same credit) in multiple pools and listings

**Comment by 0xemc** [comment]
^ Added
