### ISSUE TITLE
[project] Project missing from Marketplace and breaking retire receipt pdf

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#1999]
reported by user here https://discord.com/channels/841390338324824096/1180425478591479848

discord discussion thread here: https://discord.com/channels/1135827610434289727/1181301694588534924

### To replicate
Search for VCS-1580 and will get no results
![Screenshot 2023-12-08 at 9 40 07 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/9450461c-5a5b-4153-832f-41e72de73ab1)

You can get to the project details page https://www.carbonmark.com/projects/VCS-1580-2017 but note the double counting of the category. This projects also has two methodologies.
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/79c2ce3e-ab8b-4c85-a8a7-1581a0baa302)

This project is own breaking the retirement receipt UI and the ability to generate a pdf of the retirement. See https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/38 for an example.
![Screenshot 2023-12-08 at 9 42 48 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/640f0c6c-77a7-4671-bee3-b547928e80fd)

@biwano identified the issue comes from the fact that the category field is incorrect in the polygon-digital-carbon graph. 
@cujowolf made some subgraph fixes:
`[https://api.thegraph.com/subgraphs/id/Qmd3qX73gm7cRRNZjzYdLH3yPM15AjGFDr2RupW3keKB8U/graphql?query=query+MyQuery+%7B%0A++carbonProjects(where%3A+%7Bid%3A+"VCS-1580"%7D)+%7B%0A++++id%0A++++methodologies%0A++++category%0A++%7D%0A%7D](https://api.thegraph.com/subgraphs/id/Qmd3qX73gm7cRRNZjzYdLH3yPM15AjGFDr2RupW3keKB8U/graphql?query=query+MyQuery+%7B%0A++carbonProjects(where%3A+%7Bid%3A+%22VCS-1580%22%7D)+%7B%0A++++id%0A++++methodologies%0A++++category%0A++%7D%0A%7D)`

The fix was pushed to the prod subgraph for `polygon-digital-carbon`

**Comment by jabby09** [comment]
@biwano @0xemc this one may partially be related to underlying API issues because I can find these projects in the marketplace on the api fix PR link: https://carbonmark-git-emc-fix1987-project-mismatch-klimadao.vercel.app/projects?layout=grid&sort=recently-updated&search=VCS-1580
![Screenshot 2023-12-08 at 9 46 25 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/2f74eca4-70db-4f59-bae3-465348a6950f)

That being said, still have the issue of double category labels.

**Comment by jabby09** [comment]
This is the console error on generating a pdf:
![Screenshot 2023-12-08 at 9 51 30 AM](https://github.com/KlimaDAO/klimadao/assets/103535195/9505c94d-8461-431b-be4a-df2a6b52f3e0)

**Comment by biwano** [comment]
@jabby09 The project has indeed two methodologies with the same category

```
  "methodologies": [
    {
      "id": "ACM0002",
      "category": "Renewable Energy",
      "name": "Grid-connected electricity generation from renewable sources"
    },
    {
      "id": "AMS-ID",
      "category": "Renewable Energy",
      "name": "Grid connected renewable electricity generation"
    }```

If that's OK with you, I will just make a UI fix to have category singletons
