### ISSUE TITLE
Bring back the testnet

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#2]
Many contracts are missing on testnet. So to start, let's enable the following functionality:
- stake/unstake

I am talking with backend to see what other testnet functionality we can add

# Requirements
* [x] When the user selects Mumbai in their wallet, the app will reload itself (should work already)
* [ ] Declare a global variable in `app/lib/globalThis.ts` so the entire app can be aware of whether or not we are in a testnet environment.
```ts
// app/lib/globalThis.ts
declare global {
  var isTestnet: boolean;
}
/** Init with defaults, mainnet */
globalThis.isTestnet = false;
```
* [ ] In our `useProvider` hook, which should run on mount, check which network the user is connected to and set the global var if on testnet
```ts
const network = await provider.getNetwork();
if (network.chainId === appConfig.testnetId) {
  // default is set to mainnetWebservice in globalThis.ts
  globalThis.isTestnet = true;
}
```
* [ ] Export a getAddresses() helper from `lib/constants/index.tsx`
```ts
/** Returns testnet or mainnet addresses map based on runtime network config */
export const getAddresses = () => (globalThis.isTestnet ? testnet : mainnet);
```
* [ ] Contracts which support testnet should be refactored to grab addresses at runtime using `getAddresses()` Otherwise we need to keep hardcoding mainnet like we do right now.
* [ ] Add a "testnet" button back to the InvalidNetworkModal. This let's newcomers quickly add mumbai with the correct RPC config. The button should use a less prominent variant than the MAINNET button (lighter font, no outline).
* [ ] Add a small but prominent banner somewhere that says "You are on testnet. Not all contracts are currently available on testnet".

**Comment by ArchimedesCrypto** [comment]
This is probably a good time to redeploy a lot of the contracts and bring them to parity with mainnet

**Comment by Atmosfearful** [comment]
Cool cool, when the contracts are up just add the addresses here or commit to the constants file linked above. And then I can bring back the `mainnet` vs `testnet` toggle, should be a pretty quick refactor

**Comment by Atmosfearful** [comment]
I feel like this isn't really worth it until we can get more contracts working on testnet (wsklima, retirements, bonds)

**Comment by Atmosfearful** [comment]
Close in favor of #897
