### ISSUE TITLE
[ICR] Whole tonnes messaging in Create a listing modal [MUMBAI]

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2004]
The requirement or use case that ICR credits can only be listed in whole tonnes (i.e. no decimals). Therefore we need error handling and messaging in the Quantity field of the modal.

### Issues

- If I select a token asset other than ICR I am seeing "false"
<img width="560" alt="Screenshot 2023-12-08 at 2 00 25 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/3167b70f-6e8c-4999-b2da-48b6b3e98408">

- We should not show the field helper message before the user has even entered anything in the Quantity field, and only show it if the user inputs a decimal amount
<img width="488" alt="Screenshot 2023-12-08 at 2 01 29 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/1a87c8ad-d5f5-44f5-be0b-d9aea1d9cfa0">

- We should follow modal/form error handling and error messaging design patterns used throughout the site. This includes a red outline around the field input component and message text in red font
- We do not need the Note: part, change the message to read "`ICR credits can only be listed in whole tonnes.`"
<img width="552" alt="Screenshot 2023-12-08 at 2 04 11 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/4a18e11f-b7d4-46fd-bdd0-81f5c317798f">

**Comment by 0xtapi** [comment]
This is working now, but maybe we can improve it slightly. Current behavior:

- When I retire an ICR credit: "ICR credits can only be retired in whole tonnes" pops up instantly when I enter a decimal point.
- When I create a listing for an ICR credit or try to edit an existing listing: "ICR credits can only be listed in whole tonnes" only pops up when I click the "CREATE LISTING" button.

Would be nice if we could make all actions behave in the same way (the instant pop up option seems best).
