### ISSUE TITLE
[ICR] Need whole tonnes messaging in Edit listing model [MUMBAI]

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2005]
Same rules apply when editing a listing, ICR can only support whole tonne quantities.
<img width="518" alt="Screenshot 2023-12-08 at 2 09 57 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/26acf199-7b2a-46c4-808a-07ea3adb1f97">

See #2004 for requirements and design patterns for how to implement the error handling on the UI, in this case for the New Quantity field.

**Comment by 0xtapi** [comment]
Works now, but I left a comment here on how this could be improved slightly (imo): https://github.com/KlimaDAO/klimadao/issues/2004#issuecomment-1853499145
