### ISSUE TITLE
[ICR] Changing quantity or price in Edit listing modal throws an error [MUMBAI]

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2007]
See console message:

```
ListingEditable.tsx:73 Error: missing revert data in call exception; Transaction reverted without a reason string [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (transaction={"to":"0x51298f2F1142ECB129a2DB5e6AFd24f34F2E53f1","data":"0xdd62ed3e0000000000000000000000006476edf98bdc5ee62f9d4e4bf8932d69ed685483000000000000000000000000d973f90a4c49607eabefdb2c45d4f39436c7e7fa","accessList":null}, code=CALL_EXCEPTION, version=providers/5.7.2)
    at Logger.makeError (index.js:224:1)
    at Logger.throwError (index.js:233:1)
    at fallback-provider.js:559:1
    at Array.forEach (<anonymous>)
    at FallbackProvider.<anonymous> (fallback-provider.js:539:1)
    at Generator.next (<anonymous>)
    at fulfilled (fallback-provider.js:5:43)
```
<img width="868" alt="Screenshot 2023-12-08 at 2 15 27 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/c429ea24-1465-4c40-b6cc-14040262d453">

**Comment by psparacino** [comment]
Pushed fixes to branch. Tested with updating quantity only, price only, and both

Keeping open until tested by QA

**Comment by 0xtapi** [comment]
Still doesn't seem to work for me, but it's not the same bugs jabby caught:
![Screenshot 2023-12-11 164401](https://github.com/KlimaDAO/klimadao/assets/128430614/cf76f403-72f0-4df5-99bd-3118ce7ce3bc)

**Comment by psparacino** [comment]
> Still doesn't seem to work for me, but it's not the same bugs jabby caught: ![Screenshot 2023-12-11 164401](https://private-user-images.githubusercontent.com/128430614/289591016-cf76f403-72f0-4df5-99bd-3118ce7ce3bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTAwNzMsIm5iZiI6MTcwMjMwOTc3MywicGF0aCI6Ii8xMjg0MzA2MTQvMjg5NTkxMDE2LWNmNzZmNDAzLTcyZjAtNGRmNS05OWJkLTMxMThjZTdjZTNiYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMVQxNTQ5MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NTA0ZGJlMWQ5NmY1OGJjMjNkNTkxZTI5NzYzODI5Njk0NzY1YzlkMGFhYWJiZTNjYTllNmM5NDFkZGViYmFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WPowlkDgUTbMSjNZOKHzSYeHPfohJ0pZpDgQqZXSB1w)

Jumped the gun, sorry. fixed locally but something broke in the build so the new version didn't deploy. Will confirm here once the deployed preview has the fix
