### ISSUE TITLE
[ICR] BUY payment successful page has Quantity purchased: 0 [MUMBAI]

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2008]
In this purchase example https://carbonmark-git-feature-icr-api-integration-klimadao.vercel.app/purchases/0x354015417c42d01404dbc71ec611b92e26afa054cd42ee102c1a6592423eca0b

I bought 1 tonne
<img width="453" alt="Screenshot 2023-12-08 at 2 23 54 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/b93e080e-d793-4e75-bd58-91741c92d52d">

The buy process did update my asset total correctly.
I started with 100 
Have 5 listed.
Showing 95 Unlisted after buy.
So new total is 101 which is correct.

<img width="574" alt="Screenshot 2023-12-08 at 2 25 50 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/eee156ec-4e53-4e6b-914f-1055e481c822">

**Comment by 0xtapi** [comment]
This is now showing the right amount of tonnes ✅
