### ISSUE TITLE
[ICR] Activity feed on project page showing 0t for all transactions [MUMBAI]

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2009]
This seems to be working in the Activity feed in Portfolio

See https://carbonmark-git-feature-icr-api-integration-klimadao.vercel.app/projects/ICR-ISL-354-78040-14-R-0-2021
<img width="356" alt="Screenshot 2023-12-08 at 2 44 52 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/fa1e66c1-86e2-4e5a-ac70-1d543ec274ec">

**Comment by psparacino** [comment]
this appears to be (mysteriously) now working again. Could have been a silent subgraph error, but will keep tabs.
