### ISSUE TITLE
[ICR] Confirm modal text for BUY and RETIRE flows

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2011]
@ChazSchmidt can you please confirm that the current default APPROVE/SUBMIT text works for buy and retire ICR credits?

### BUY
<img width="535" alt="Screenshot 2023-12-08 at 2 20 44 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/fee9bdcf-9b6f-46ee-93d0-9a00343f32ad">
<img width="520" alt="Screenshot 2023-12-08 at 2 21 30 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/930b3f71-c852-487d-abab-43af8d18def7">

RETIRE
<img width="526" alt="Screenshot 2023-12-08 at 2 31 48 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/f6a30cc8-61f4-45d4-8060-651202b8965b">

**Comment by ChazSchmidt** [comment]
This looks correct to me. The buy and retire flow should use the same available payment methods.

**Comment by ChazSchmidt** [comment]
This looks correct to me. The buy and retire flow should use the same available payment methods.
