### ISSUE TITLE
[listing] Error message when creating a listing

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2014]
**Describe the bug**

**To Reproduce**
1. Go to 'https://carbonmark.com/projects'
2. Click on 'Profile'
3. Click on Create New listing
4. Create listing : Quantity 1 / Single unit price: 1 
5. Click on create listing
6.  Click on approve
7. Click on Submit
8. The listing is created but there is an error message

**Expected behavior**
No error message and Listing created

**Screenshots**
![image](https://github.com/KlimaDAO/klimadao/assets/11857992/660ae8b0-0d2c-4cdc-afc1-1c51990c1871)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser Chrome
 - 120.0.6099.71 

**Additional context**
Only happened once and I cannot reproduce it. Maybe with a fresh account.

**Comment by 0xemc** [comment]
@jabby09 FYI

**Comment by jabby09** [comment]
@biwano @0xemc duplicate of https://github.com/KlimaDAO/klimadao/issues/1891

**Comment by jabby09** [comment]
Not really sure what is happening; as mentioned the error is not consistent. I assume it is related to reading data of the blockchain and transactions/processes not in sync.

**Comment by biwano** [comment]
> Not really sure what is happening; as mentioned the error is not consistent. I assume it is related to reading data of the blockchain and transactions/processes not in sync.



> @biwano @0xemc duplicate of #1891

Thanks. @jabby09 Not sure of the protocol, I close this one then?

**Comment by jabby09** [comment]
> I close this one then?

let's leave it open for @Atmosfearful to consider
while #1891 is related not sure if it's exactly the same error

atmos...any ideas what might be causing this and should we build in some better error handling/messaging?

**Comment by Atmosfearful** [comment]
Definitely duplicate of #1891 moving discussion there.
