### ISSUE TITLE
[ICR] When updating price without updating quantity, the old/new quantity should not show

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#2015]
<img width="280" alt="Screen Shot 2023-12-11 at 1 05 07 PM" src="https://github.com/KlimaDAO/klimadao/assets/72105234/bf0a8176-65b9-431a-993e-2d3103c8d770">

I haven't confirmed on an non-ICR branch, but if the price is updated but the quantity remains constant, I'm guessing the Activity sidebar should not show the redundant information.

**Comment by jabby09** [comment]
> I haven't confirmed on an non-ICR branch, but if the price is updated but the quantity remains constant, I'm guessing the Activity sidebar should not show the redundant information.

correct

**Comment by psparacino** [comment]
should be good now

**Comment by 0xtapi** [comment]
Yup, looks good!
