### ISSUE TITLE
[token] Token detail is incorrect for certain pool projects

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2017]
Was exploring something else and noticed that in the Asset details component on BUY and RETIRE form pages, the `Token you will receive` (BUY) and `Retiring Token` (RETIRE) are different.

The BUY token is C3T while the retire token is TC02.

**NCT pool example**
https://www.carbonmark.com/projects/VCS-934-2015/purchase/pools/nct
https://www.carbonmark.com/projects/VCS-934-2015/retire/pools/nct

**BCT pool example**
https://www.carbonmark.com/projects/VCS-493-2008/purchase/pools/bct
https://www.carbonmark.com/projects/VCS-493-2008/retire/pools/bct

Is this a bug?

**Comment by Atmosfearful** [comment]
Yes this is a bug, BCT and NCT should only contain TCO2s
UBO and NBO should only contain C3T

In the example above, I see a C3T under bct 💀

**Comment by jabby09** [comment]
> Yes this is a bug

ugh...another bug to fix
