### ISSUE TITLE
Link from /blog/post back to /blog

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#202]
Right now you have to click "resources -> blog"

We should add a Back icon. i believe this was part of original designs but got removed at some point

**Comment by 0xAeterno** [comment]
Wholeheartedly agree there's a need for a simple way for our audience to navigate back to the `/blog` from a post. The current UX feels rather janky 🤪 

Been thinking about how we might do this and there are several approaches we play with:

#### a) Promote blog to a top level nav item
- With all the content our writers have been publishing lately, a link to the blog in our main header feels like a sensible.
- Users will be able to go back to the blog index via a post.
- Simple change.
- Drawbacks: 
    - Spacing in the header (we can reduce the gap between nav items - currently `5.4rem`)
    - Is it obvious enough to users if they're halfway down the page, maybe we can play around with introducing sticky headers so those nav links are always accessible.
    
#### b) Introduce a link back to blog via post page
- Simple back button either between the banner image and title or at the end of the post before the disclaimer (or both locations)
- Assumed it was previously designed this way, maybe theres a reason for its removal
<img width="800" alt="Screen Shot 2022-03-03 at 6 47 10 pm" src="https://user-images.githubusercontent.com/97446324/156519965-d82c67a2-0232-4f78-b712-8096b53ff8d9.png">

#### c) Breadcrumbs
- I envision this as more of a further enhancement on the previous proposal.
- With the velocity of posts coming from our writers, breadcrumbs can serve as a way to categorise posts in the future. (`Blog > KIP > KIP-14 Resilience Mode` or `Blog > Partnerships > Klima x Eco`)
- Apparently it's really good for SEO
- Drawbacks:
    - Development time required vs the other two proposals (plus design, sanity schema updates, catergorising past posts)
<img width="800" alt="Screen Shot 2022-03-03 at 7 02 18 pm" src="https://user-images.githubusercontent.com/97446324/156522387-4a4dc12a-d7ae-45d7-9531-02d2754f7375.png">

**Comment by Atmosfearful** [comment]
I love option C, but it requires a redesign of the /blog index page to display these categories, and a schema update to categorize each post.

You seem to have a good sense of UI design, just slap a Back button wherever you see fit. Or should it say "Blog" or "Back to Blog"?
I'll ping a designer for second opinion right now :)
