### ISSUE TITLE
[pricing] QA regression and sanity review of project pricing

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2020]
@0xtapi there has been a bunch of regression happening on the site and I need someone with fresh eyes to take a pass at project "pricing" across the site. I'm seeing variations if I'm on the Marketplace page vs a Project Details page vs the Retire page and we should identify where we have issues and where we are sourcing price data for all these locations (i.e. api endpoint vs subgraph etc).

**Pages to review:**
- https://www.carbonmark.com/projects
- https://www.carbonmark.com/retire
- Related project details pages
- https://data.klimadao.finance/overview/price-of-digital-carbon

**Examples of things I'm noticing:**
- Project prices in CM do not typically match exactly what we report for price and selective cost on https://data.klimadao.finance/overview/price-of-digital-carbon Why??
- Related to #1975 ...these 4 projects represent the default projects in the pool, i.e. the projects with no selective cost fees. Are these prices correct on https://www.carbonmark.com/retire and are they being maintained on other screens (project detail pages, retire or buy forms)? For example:

<img width="347" alt="Screenshot 2023-12-12 at 4 59 27 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d60f5c0f-4cec-45bd-b2ee-5986f1e06974">
<img width="725" alt="Screenshot 2023-12-12 at 4 59 08 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/d9882058-62dc-4851-80eb-bcb27bc01cc5">

- Sort the marketplace cards from low to highest price. Find this project, today at $0.50. Where does $0.50 come from? Now click through to the project detail page, price is $0.67??

<img width="336" alt="Screenshot 2023-12-12 at 4 50 20 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/6c75f34b-f828-42ca-97f5-153a59d1b93d">

**Comment by 0xtapi** [comment]
Identified a bunch of projects with wrong pricing, a bunch of them seem related to the dusting issue. See these for example:

https://www.carbonmark.com/projects/VCS-875-2013
https://www.carbonmark.com/projects/VCS-1577-2012
https://www.carbonmark.com/projects/VCS-1542-2012

They all report $0.42, but that's all dust and no one would be able to buy/retire for those prices. Remove the dust from being displayed on the marketplace and this issue should be fixed.

Then there are a few related projects, like this one: https://www.carbonmark.com/projects/VCS-728-2020

It shows $0.67 on the marketplace, but the cheapest available price is $0.42 - but that's dust. So this one is slightly different from the ones above, as it ignores the dust price on the marketplace (which is actually a better solution for the user, but best would be not to show the dust in the first place).

Then there are projects like this one: https://www.carbonmark.com/projects/VCS-51-2015

Reports $0.67 on the marketplace, but the cheapest one available is actually $0.42, and this time it's not dust either.



> * Find this project, today at $0.50. Where does $0.50 come from? Now click through to the project detail page, price is $0.67??

I have a hunch about that one. There is a similar issue here: https://www.carbonmark.com/projects/VCS-981-2017. This one shows $1.00 on the marketplace, which can't be found anywhere in the project card. The one you showed (the 5MW project) is here: https://www.carbonmark.com/projects/VCS-1547-2020.

In the 5 MW project, the $0.50 price appears in the activity feed as the last price (until I bought a tonne a few minutes ago to test this). In the project I linked (https://www.carbonmark.com/projects/VCS-981-2017), the $1.00 price also is the latest price in the activity feed. Is it possible that the site somehow pulled the price from the activity feed at that time and is now showing that price on the marketplace?
