### ISSUE TITLE
[subgraph] Refactor references to ploygon-bridged-carbon subgraph

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2027]
## Remove `polygon-bridged-carbon`

`polygon-bridged-carbon` has been replaced by the new subgraph: `polygon-digital-carbon` we need to upgrade all references to it.

https://github.com/KlimaDAO/klimadao/blob/694433fab41a70bf41484f28389b098f874c4a46/lib/constants/index.ts#L278

**Comment by Atmosfearful** [comment]
duplicate of https://github.com/KlimaDAO/klimadao/issues/1938
