### ISSUE TITLE
[tech] FastifyDeprecation warning

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2031]
**Describe the bug**

The API displays the following warning: 
```[FSTDEP017] FastifyDeprecation: You are accessing the deprecated "request.routerPath" property. Use "request.routeOptions.url" instead. Property "req.routerPath" will be removed in `fastify@5`.```

**To Reproduce**
1. Run the carbonmark API
2. curl the `/projects` endpoint
3. see error in console

**Comment by biwano** [comment]
PR submitted here: https://github.com/denbon05/fastify-lcache/pull/32

**Comment by Atmosfearful** [comment]
Nice fix @biwano Do you think we should switch to @fastify/caching as the 'official' solution? They provide a simplistic cache which should serve well for our purposes (only caching a few dozen vintages or a few hundred projects at a time) 

https://www.npmjs.com/package/@fastify/caching

```
  fastify.cache.set('hello', {hello: 'world'}, 10000, (err) => {
    if (err) return reply.send(err)
    reply.send({hello: 'world'})
  })
  ```
  
  Migration is quick as it's only used for simple get/set invocations in 1 file
  
  https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark-api/src/utils/helpers/utils.ts#L144

**Comment by biwano** [comment]
> Nice fix @biwano Do you think we should switch to @fastify/caching as it is maintained by the official fastify team and not a community plugin?
> 
> They provide a simplistic cache which should serve well for our purposes (only caching a few dozen vintages or a few hundred projects at a time)
> 
> https://www.npmjs.com/package/@fastify/caching
> 
> ```
>   fastify.cache.set('hello', { hello: 'world' }, 10000)
> ```
> 
> Migration is quick as it's only used for simple get/set invocations in 1 file
> 
> https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark-api/src/utils/helpers/utils.ts#L144

Hello @Atmosfearful 

Yes, it is a good opportunity to switch to the official package.
