### ISSUE TITLE
[offset] Update RA offset page copy to direct user to old build site

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2035]
The form on https://app.klimadao.finance/#/offset was deprecated to shrink maintainable code footprint and to encourage users to retire on Carbonmark.

There are still a small subset of users who want to retire using pool tokens asset that they own (for example, retire carbon using BCT). After taking down the offset form in the RA, there were a number of complaints in the #klima-chat channel on discord.

There was an internal discussion is this [discord thread](https://discord.com/channels/1135827610434289727/1184579974993281064).

The product team discussed and agreed to following changes:

- [x] Take an older build (https://klimadao-3rkq7ymia-klimadao.vercel.app/#/offset) and update the URL domain to `legacy-app.klimadao.finance` that points to that branch (@Atmosfearful)
- [x]  On the current /offset page (https://app.klimadao.finance/#/offset) add a new paragraph to the text component that says:

> For users who want to offset paying with a pool token, please use [this site](https://legacy-app.klimadao.finance/#/offset).

**Comment by Atmosfearful** [comment]
https://legacy-app.klimadao.finance/#/offset

**Comment by biwano** [comment]
> https://legacy-app.klimadao.finance/

Hey @Atmosfearful The offset page is not available on this page.

**Comment by biwano** [comment]
> > https://legacy-app.klimadao.finance/
> 
> Hey @Atmosfearful The offset page is not available on this site.

@Atmosfearful Solved this by forcing a deployment by making a dummy commit (that I reverted afterwards). I imagine that since they were no deployments for the legacy branch the app-legacy domain pointed by default to the main branch?
