### ISSUE TITLE
[ICR] Small UI tweak for listing creation

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2038]
When I create a listing and enter a decimal point, the following message appears:
![sell1](https://github.com/KlimaDAO/klimadao/assets/128430614/73e11f0a-196a-4b89-84b2-5e21896a44d3)

Imo, it should be the same message as the one that appears when I follow it up with any number, see here:
![sell2](https://github.com/KlimaDAO/klimadao/assets/128430614/a7520aa1-464b-4bb0-a282-a65486d849c9)

**Comment by psparacino** [comment]
Haven't yet been able to reproduce

**Comment by psparacino** [comment]
Completed
