### ISSUE TITLE
[buy] Error message on approve step of BUY transaction on default pool project

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2043]
See https://www.carbonmark.com/projects/VCS-191-2008/purchase/pools/bct
This is the default project for the BCT pool

Also confirmed get this error on UBO default pool project
https://www.carbonmark.com/projects/VCS-1140-2015/purchase/pools/ubo

NOTE: buy appears to work if not the default pool project

- Buy 1 tonne - Confirm Purchase modal opens
- APPROVE step works fine
- SUBMIT step throws error

<img width="527" alt="Screenshot 2023-12-18 at 4 19 30 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/a2b06a82-e0eb-4540-8cc8-3d69dde9aab7">
<img width="1041" alt="Screenshot 2023-12-18 at 4 19 53 PM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/694fd69a-b51c-405c-bf28-b866bd04867b">

**Comment by Atmosfearful** [comment]
Some ideas, after looking at the errors and approvals (And reproducing it on my machine)
- Check that we are passing the correct project token addresses down to the actual transaction.
- Check that we are using the correct method
  - for cost quoting, `getRedeemCost` util should invoke `aggregator.getSourceAmountDefaultRedeem()`
  - for the purchase, `redeemCarbonTransaction` util should fall into this case:
  
![image](https://github.com/KlimaDAO/klimadao/assets/88635679/9fe16109-7b30-4430-bcd4-d0447ad08ee3)

**Comment by Atmosfearful** [comment]
More debugging, our inputs seem correct for `toucanRedeemExactCarbonPoolDefault`
```
sourceToken: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174,
poolToken: 0x2f800db0fdb5223b3c3f354886d907a671414a7f,
amount: "1000000000000000000",
maxAmountIn: "312309",
from: 0,
to: 0
```

**Comment by Atmosfearful** [comment]
I did notice that we are not passing the correct value for maxAmountIn but that didn't seem to fix it....

**Comment by Atmosfearful** [comment]
Combination of mistakes led to this. Fix incoming.
