### ISSUE TITLE
[modal] Incorrect logo displayed when retiring raw TCO2

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#2058]
**Describe the bug**
When retiring raw TCO2 (e.g. the Vlindr mangrove project) the UI displays the USDC logo instead of a reasonable logo for the TCO2: 

**To Reproduce**
1. Purchase an individual project
2. Go to Portfolio and retire the project
3. Notice the incorrect logo

**Expected behavior**
A reasonable logo should be provided rather than the USDC logo for spending TCO2

**Screenshots**
![image](https://github.com/KlimaDAO/klimadao/assets/91024694/84f50b8f-2a74-4493-ae80-e1cf3effdc3b)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 121.0

**Additional context**

**Comment by jabby09** [comment]
@0xAurelius I think this is related to #1963 and the designs for these modals have been updated to reflect the required changes, we have just not had dev bandwidth to assign and have the work completed yet.

I'll review this issue in more detail early next week and make sure there are not additional requirements to solve for.

**Comment by Atmosfearful** [comment]
Super super quick fix so I went n shipped it https://github.com/KlimaDAO/klimadao/pull/2060

Hide the icon, which is how the other modals work (create listing, edit listing etc.)
