### ISSUE TITLE
[data] Update frontend to accommodate any changes from migrating to new subgraphs

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#2059]
**Is your feature request related to a problem? Please describe.**
The old `polygon-bridged-carbon` subgraph is outdated and we need to migrate to the new `polygon-digital-carbon` subgraph

The `data.klimadao` frontend will need to be updated to accommodate any changes, though the API should mask most, but for instance data field names may have changed.

**Describe the solution you'd like**
Once the pipeline and API changes are live in staging, test out the frontend against them: 
https://github.com/KlimaDAO/data-pipelines/issues/38
https://github.com/KlimaDAO/dash-apps/issues/181

**Describe alternatives you've considered**
This is a necessary migration for ongoing maintenance of data feeds moving forward

**Comment by 0xAurelius** [comment]
Blocked until pipeline changes and API have been staged

**Comment by Atmosfearful** [comment]
Migration appears to be complete
