### ISSUE TITLE
[pay with] Bank transfers should be disabled when available quantity < 100

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#2063]
**Describe the bug**
Currently the UI shows the bank transfer options even when the total amount available is less than 100. This puts the UI in an invalid state.

**To Reproduce**
1. Go to https://www.carbonmark.com/projects/VCS-1883-2018/retire/pools/bct
2. Click on USDC and login
3. Enter a valid amount (0.001)
4. Select bank transfer
5. See amount change to 100 (more than available)

**Expected behavior**
Bank transfer option is disabled.

**Screenshots**

https://github.com/KlimaDAO/klimadao/assets/138768831/168a6619-7f86-4684-9aa0-59e4d793b3ce

**Comment by jabby09** [comment]
thanks @sprrwhwk 
the quantity < 0 issue will be addressed in #1035 and then we will no longer see those listings.
however, good catch that if min of 100 > available quantity we should show a warning message and keep RETIRE CARBON button greyed out.

cc @0xMakka

**Comment by 0xMakka** [comment]
Nice catch @sprrwhwk, missed this one in our testing. Will provide a fix for this.
