### ISSUE TITLE
[projects] Available quantity on project pages should be more precise

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#2064]
**Describe the bug**
Some projects (e.g. https://www.carbonmark.com/projects/VCS-1190-2017) show an available quantity of zero, but also show the "BUY" and "RETIRE NOW" buttons. This doesn't make sense.

**To Reproduce**
1. Go to https://www.carbonmark.com/projects/VCS-1190-2017
2. Observe 0 quantity with buy and retire options still visible
3. Click on "RETIRE NOW"
4. Observe 0 quantity in retirement form

**Expected behavior**
The small available amounts are displayed correctly so that users can enter sensible amounts.

**Screenshots**

<img width="345" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/b28935d5-671c-4a62-ad7f-a7ac2e26ac22">
<img width="506" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/4b4f2cfc-b059-43f7-a40c-9fa30b7b1a3b">

**Comment by jabby09** [comment]
@sprrwhwk this will be fixed by #1035
