### ISSUE TITLE
[tech] BlockExplorer autodetection

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2072]
The blockExplorer used to show the transactions is bound to the environment: https://github.com/KlimaDAO/klimadao/blob/staging/carbonmark/lib/constants.ts#L116

This is disturbing for testers:
- The blockExplorer should be chosen dynamically using the connected wallet.
- Or testers should always test on mumbai ?

**Comment by Atmosfearful** [comment]
This will go away after wallet abstraction work is done
