### ISSUE TITLE
[form] Accept entering prices with 0.1 precision 

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2073]
Small QOL issue here:

<img alt="numbererr" width="429" src="https://private-user-images.githubusercontent.com/128430614/294141688-5f84ceca-00f7-4591-b02e-2d8459d1928f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0MzYxNDQsIm5iZiI6MTcwNDQzNTg0NCwicGF0aCI6Ii8xMjg0MzA2MTQvMjk0MTQxNjg4LTVmODRjZWNhLTAwZjctNDU5MS1iMDJlLTJkODQ1OWQxOTI4Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwNVQwNjI0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGZiZmUwYTZjNGU0YWMzMjRiNDM5N2Y4NjRkMzM3Y2I2NDZhMDlhODIwMDU5NzZmNjc5NzZiZGJkMzY5MTRkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.mh6GODRvGGPIj9pNfMtw9mzKUGa53oABdU6iAdmOv9E">

It doesn't accept 0.5, only 0.50. Can this be changed so it just assumes an additional 0 if no value is specified?

**Comment by Atmosfearful** [comment]
Let's check all our quantity inputs for both purchase and retire to make sure they accept both 1.5 and 1.50. Should be a quick one
