### ISSUE TITLE
[api] Investigate: unacceptably slow response times for /users endpoint

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#2075]
Observed while debugging with Selim
I believe it is a cold-start issue either in vercel, or maybe firebase? Subsequent responses seem quite fast.
Need to use console.time() to understand where the slowdown is occurring and decide if it's something we can fix now, or later

https://api.carbonmark.com/users/jabby

https://api.carbonmark.com/users/atmosfearful

**Comment by sidneyarida** [comment]
@Atmosfearful 

Investigated a bit and the problem it seems related to firebase.
On the first start or after a bit of inactivity i think is causing firebase to cold start, causing the delay.

![Screenshot 2024-03-21 at 17 52 36](https://github.com/KlimaDAO/klimadao/assets/17513782/fb688280-3c8b-4d8e-b24e-8698c486323d)

I tried to implement the suggestion from this article 
`initializeFirestore(firebaseApp, { preferRest: true })`
https://www.ayrshare.com/speed-up-firebase-cold-starts-with-firestore-rest-calls/

And it seems to speed up a little bit.

![Screenshot 2024-03-21 at 18 55 51](https://github.com/KlimaDAO/klimadao/assets/17513782/fa60707b-c1d0-4813-b6d5-ef2a1b56bab7)

I think some more research is required

**Comment by Atmosfearful** [comment]
When carbonmark moves to Circle wallets, user profiles will be stored in Supabase and not in Firestore, so we can simply close this ticket and re-assess performance at that point.
