### ISSUE TITLE
[vintages] Remove vintages from filter options for which there are no listings 

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2076]
On the marketplace, the Vintage filter option includes three years (at least) for which there are no project results.

This is a sub-optimal UX, the list of available vintages to filter on should match at least one project (i.e. should not be possible to get zero results).

<img width="375" alt="Screenshot 2024-01-06 at 10 02 12 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/4856c244-aaf5-418a-bf8f-37b8fccec91d">

<img width="942" alt="Screenshot 2024-01-06 at 10 04 18 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/bc42f7aa-c553-418a-874b-2bb7cd4fe1cf">

### Root Cause

- Likely related to subgraph magic and picking up on credits that were bridged but never pooled (so they do not appear in the frontend).

### How to Improve

- The logic that generates the list of vintage options should be based on any credit that has a price, not whether it was simply bridged.

**Comment by jabby09** [comment]
assume this is related/duplicate of #2129

**Comment by Atmosfearful** [comment]
Resolved, I don't see any vintages that don't have prices anymore
