### ISSUE TITLE
[api] Projects endpoints improvements

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2078]
Improvements that can be made to the projects endpoints

- [ ] Remove project.listing.project as this is redundant info
- [ ] Make certain fields optionnal in payload. Example: long_description, stats, listings in projects. or other fields are really blowing up the json size we can mark them opt-in via a query parameter eg. `/projects?include=listings&include=stats`
- [ ] Add a pagination mechanism to the `/projects` endpoint

## Suggestions
- [ ] provide a graphql endpoint to allow the user to consume what they need (https://mercurius.dev/#/)

**Comment by Atmosfearful** [comment]
These will be captured in new /carbonProjects for which there is a ticket already in the new monorepo
