### ISSUE TITLE
[tech] Fiat tooling migration discovery

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#2085]
Taking notes here, will break these out into multiple tickets:
- Fiat tooling is separate from the carbonmark-api so it will probably have it's own deployment.
- The Fiat tooling should dogfood the /retire pay-as-you-go endpoint, we can decide if we ship now, refactor later-- or wait for /retire to get up and running.

Requirements and opportunities
- cleanup endpoints (now that vercel supports longer function lifetimes)
- separate endpoints? /quote vs /retire? pool vs listing?

wip

**Comment by jabby09** [comment]
@sprrwhwk (cc @Atmosfearful)

discussed this workstream with Brendan. With all the fiat stuff fresh in your head, the suggestion is could you map the requirements and work in a discovery tree.

We can create the page for you and make sure you have access.
