### ISSUE TITLE
[marketplace] bundle all vintages of a single project

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2086]
Currently, the marketplace looks like this:

<img width="1277" alt="Screenshot 2024-01-08 195823" src="https://github.com/KlimaDAO/klimadao/assets/128430614/690f9029-2b92-4a75-bd82-83ae3af2a38e">

Red rectangle shows essentially the same project with its vintages being the only reason why it appears on the marketplace multiple times. Can we enhance this so that we bundle all vintages of a single project into the same card and, through some UI magic, let the user know that this project offers multiple vintages? This would declutter the marketplace (there are many(!!!) projects like this one) and therefore improve UX.

If this is already done for CM 2.0, this can be ignored 🫡. Pinging @theprofessora for feedback!

**Comment by jabby09** [comment]
@0xtapi yes this will be addressed in CM 2.0. There will be one project in the marketplace and then the different vintages will be listings on the project page https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2024-35192&mode=design&t=bdKOvIqSxYdVsFWY-4
