### ISSUE TITLE
[UI v2 phase 1] Connected wallet component on Portfolio page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2090]
Related to the navigation changes as per #2065 

The Your Wallet Address feature will no longer be available in the navigation.

This is intentional as part of abstracting away web3 concepts from primary user screens.

However, to maintain feature parity, we are moving the wallet address to the users portfolio page.

[Design here](https://www.figma.com/file/I5hXFeW1DKjV7agHq7T4UZ/Portfolio?type=design&node-id=921-9955&mode=design&t=2vpXdUulgwJbIpAP-4)

### Requirements
- Add a Connected Wallet component at the top of the Portfolio page
<img width="605" alt="Screenshot 2024-01-10 at 10 24 52 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/15efdca9-be8b-4140-ac31-1abdb6d0991a">

- The design shows both a copy icon and external link icon
  - The "copy" icon is shown if the user has connected through a wallet connect, metamask or coinbase or wallet connect etc
  - The "external link" is shown if the user has connected through a social login and the link is https://polygon.tor.us/

**Comment by 0xemc** [comment]
@dpolichetti @Najada once you two are setup this might a good place to get involved with CM v2.

**Comment by Najada** [comment]
@0xemc thanks so much! We just got access to the notion and are reviewing everything. If some blockers come up I will ping you directly!
