### ISSUE TITLE
[projects] There is no more liquidity for the default NBO project

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2091]
**Describe the bug**
There is no more liquidity for the default NBO project

**To Reproduce**
1. Go to https://www.carbonmark.com/fr/retire
2. Click on the default NBO project (VCS-981)
3. Quantity available is 0.08

There is NCT liquidity though. So a side effect is that when we see this project in the marketplace we see the NCT price

![image](https://github.com/KlimaDAO/klimadao/assets/11857992/2627700e-ad1e-44b5-8fac-5ebf14e27a6b)

**Comment by jabby09** [comment]
@biwano the link is now throwing a 404 error
https://www.carbonmark.com/projects/VCS-981-2014/retire/pools/bct

or https://www.carbonmark.com/projects/VCS-981-2014 return a blank page
