### ISSUE TITLE
---- UI v2 phase 2 ----

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2094]
With Carbonmark v2, we are introducing a new page to the application as an optimized landing page for user and to better highlight the inventory in the marketplace.

[Page design here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=1855-24157&mode=design&t=osu9BnIlBk2mpp7r-4).

### Important Note
- The updated designs in some cases **show future state of other features** `which can be ignored` as those enhancements will be captured in other specific issues.

### Requirements
- note the designs differences for desktop vs mobile
- this page will need a URL, for now it will be https://www.carbonmark.com/home
  - _product team will brainstorm a better page name and advise_ 

**Hero Carousel**
- supports one or many projects in the carousel
- each project in carousel supports a large hero image, project name, price, and short description
- if > 1 project...
  - circle/dot indicators to show number of items and item being shown
  - very slow auto scroll, advance every 10 seconds
  - user can click a dot to scroll to different projects or can click and drag horizontally
  - if the user clicks and holds on any of these images, the auto scroll is paused
  - supports swipe on mobile
- for the MVP, the projects in the carousel will be identified in code
  - future enhancement to consider is support of project selection from a CMS-like interface (i.e. using Sanity) 
- `RETIRE NOW` button directs the user to the /retire form for that project (example: https://www.carbonmark.com/projects/VCS-985-2013/retire/pools/nct)
- `SHOP ALL PROJECTS` button directs the user to the marketplace (https://www.carbonmark.com/projects)

**Featured Projects**
- space for up to four (4) projects
  - on wider screens there will be some white space on either side 
- card design should match what is on production here https://www.carbonmark.com/retire for example implementation
- on mobile, note that we show one full card and a partial 2nd card to indicate to user there is more to see
- for the MVP, the featured projects will be identified in code
  - future enhancement to consider is support of project selection from a CMS-like interface (i.e. using Sanity) 
- card hover state implementation should match what is on https://www.carbonmark.com/retire 
- entire card is clickable, takes the user to that project page

**Category Based Projects**
- the next sections of the page are derived based on project categories supported in the marketplace that have multi-project inventory
  - for the MVP, likely will manually decide what categories to show
  - future enhancement to consider is support of category selection from a CMS-like interface (i.e. using Sanity)  
- each section includes a banner with category title (i.e. Agriculture projects), a custom category image, short description (content to be provided) and then a series of stats (supply, total retirements, total listings, lowest price)
  - NOTE: assumption here that api changes will be required to supply `total retirements` and `total listings` but to-be-confirmed
- below the banner is space for up to four (4) top-selling projects
  -  NOTE: assumption here that api or other changes will be required to identify "`top selling`"
  - on wider screens there will be some white space on either side 
- card design should match what is on production in the marketplace
- SHOP ALL cta in upper right corner takes the user to the marketplace with the category selected as a query parameter (for example https://www.carbonmark.com/projects?layout=grid&sort=recently-updated&category=Energy+Efficiency)

**Carbon markets 101**
- On desktop, 4 different sized containers for surfacing blogs from https://www.carbonmark.com/resources
- NOTE: to-be confirmed that a custom image per blog will be required (from creative) that supports these different images sizes and bottom darkening for text overlay
- LEARN MORE cta takes user to https://www.carbonmark.com/resources
- READ MORE cta takes user to the resource article, for ex https://www.carbonmark.com/blog/list-now-on-carbonmark-digital-storefronts
-

**Comment by 0xemc** [comment]
@jabby09 

> NOTE: to-be confirmed that a custom image per blog will be required (from creative) that supports these different images sizes and bottom darkening for text overlay

This is not necessary, we can build a gradient overlay over all images
