### ISSUE TITLE
[chore] Versioned subgraph urls

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2096]
**What:** 
Replace named subgraph urls `/polygon-bridged-carbon`, `/klimadao-user-carbon` etc with a unique hash or version number.

**Why**: Currently it is possible to change the content of a target subgraph without any knowledge of the consuming apps (carbonmark & carbonmark-api). This introduces the possibility to silently break the app.

**How**: something like `/QmTfM5TvokuyKXCGWL3wTLZ1z4TqRtQ7PdVfQRVU39ovUC`

**Expected Outcome:**

 - [ ] All naned urls are replaced with hashed or versioned endpoints

**Testing Criteria:**

**Comment by 0xemc** [comment]
FYI @cujowolf @Atmosfearful

**Comment by cujowolf** [comment]
So I pushed the current version of polygon-digital-carbon up to the decentralized studio, and have this versioned dev endpoint: https://api.studio.thegraph.com/query/63694/polygon-digital-carbon/1.2.1

It's rate limited, but I'm not exactly sure what that limit is in case we want to test out the waters.

**Comment by 0xemc** [comment]
Epic, nice one. I'll try to integrate to this one

**Comment by Atmosfearful** [comment]
Klima-subgraphs repo now has release tags following SemVer with the associated version hash so we can always target the most recent version.

Old ids would expire after 30 days without a query or if a new version is pushed over it. This is the best we can do for now afaik
