### ISSUE TITLE
[UI v2 phase 1] Update footer on desktop to match designs

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2117]
Current CM footer on desktop sized screens looks like this:
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/bf22b556-e69d-4767-a7ae-e8fd64f717c7)

### Issues
- not a create UI, we are losing screen real estate and just feels unbalanced overall
- I believe we ended up in this state when we added the Lucky Orange support chat widget; and then I think LO released a change

### Notes
- mobile is not awesome but good enough for now, no changes required on mobile sized screens

### Requirements
- update desktop footer to match designs
- it is understood there may be limitations in what can be done with the Lucky Orange chat badge - please just do your best
![image](https://github.com/KlimaDAO/klimadao/assets/103535195/69f4e98e-410e-482f-9dae-a4e70a8e739c)

**Comment by jabby09** [comment]
@0xemc this one is good to go

**Comment by 0xemc** [comment]
@sprrwhwk I hope you have some capacity now to work on this following the ICR delivery. Assigning to you but let me know if there are any issues.
