### ISSUE TITLE
Add remaining Klima Infinity launch partners to Partners section

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#212]
In addition to Eco, we should include the other KI launch partners to the website:
- [x] Dovu
- [x] Offsetra
- [x] ETC Group
- [x] Digital Charity Art
- [x] thought for food

Need to talk to ptr or mkt to identify a high quality logo asset for each

**Comment by 0xAeterno** [comment]
What are our thoughts on having a separate section for our klima infinity partners.
I think it'll be an amazing distinction to call out :)

**Comment by 0xAurelius** [comment]
> What are our thoughts on having a separate section for our klima infinity partners. I think it'll be an amazing distinction to call out :)

Yeah I think down the line it makes sense to subdivide the Partners section

The two subdivisions that jump out at me are:
1. Carbon Bridges (Toucan, Moss for now)
2. Klima Infinity
