### ISSUE TITLE
[retirements] retirement quantity doesn't display correctly

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2123]
Issue:
![Screenshot 2024-01-15 115639](https://github.com/KlimaDAO/klimadao/assets/128430614/5485ee44-ab67-48c7-ad26-fd2b7aca7788)

Go to https://www.carbonmark.com/retire to reproduce.

While it would be nice to retire a few quintillion tonnes of carbon, we still have some way to go before we get there, so let's fix this bug in the meantime.

I also checked other areas of the site whether they display numbers in some undesired way, but couldn't find anything. Seems like only the Retire page is affected.

**Comment by sprrwhwk** [comment]
> While it would be nice to retire a few quintillion tonnes of carbon, we still have some way to go before we get there, so let's fix this bug in the meantime.

😅 

The URL to reproduce the bug seems to be wrong here…

**Comment by 0xtapi** [comment]
> The URL to reproduce the bug seems to be wrong here…

Is it? You should see this bug in your retirements overview on production... at least I see it there 🤔 You wouldn't see it if you have never retired anything on the account you use to connect to the page.

**Comment by jabby09** [comment]
> The URL to reproduce the bug seems to be wrong here…

You need to be logged in to see your retirement summary
