### ISSUE TITLE
[form] Price estimations are failing

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#2124]
**Describe the bug**
Currently price estimations are failing for all projects.

**To Reproduce**
1. Go to https://www.carbonmark.com/projects/VCS-292-2020/retire/pools/bct
2. Click on amount
3. Enter 1

**Expected behavior**
Estimation is displayed on the right

**Comment by jabby09** [comment]
weirdly now seems resolved
