### ISSUE TITLE
[profile] broken social login via Torus

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2125]
Creating a profile or editing an existing one with Torus is currently failing. Some info from Selim and Jabby: "It says i rejected the approval with my torus wallet even though the torus page isn't even done loading".

First screenshot shows wallet loading loop on attempted profile creation, second screenshot is console while trying to edit an existing profile.

<img width="1000" alt="Screenshot_2024-01-15_at_8 55 56_AM" src="https://github.com/KlimaDAO/klimadao/assets/128430614/af50152f-c0df-47da-94a0-18caefb7b20c">
<img width="373" alt="Screenshot_2024-01-15_at_8 59 59_AM" src="https://github.com/KlimaDAO/klimadao/assets/128430614/13b663f7-279e-402c-bc29-d6d42edc702e">

For what it's worth: no issues when creating/editing profiles with Metamask.

**Comment by 0xemc** [comment]
@0xtapi @sprrwhwk has mentioned that this is working again? Can you double check?

**Comment by 0xtapi** [comment]
> @0xtapi @sprrwhwk has mentioned that this is working again? Can you please double check?

Just tested, seems to work. Created a profile and edited a profile, no issues. The bugs have begun fixing themselves... wonderful ;)

**Comment by Atmosfearful** [comment]
This seemed to be a torus issue based on the error message. If this problem reoccurs we can try upgrading `@toruslabs/torus-embed` in `lib` package to the latest version (4.0 -> 4.2.1)
