### ISSUE TITLE
[discord] Github Activity in KlimaDAO discord not updating

### ISSUE THREAD

**Issue by 0xMakka** [KlimaDAO/klimadao#2126]
**Describe the bug**
I just noticed that the github activity channel in the KlimaDAO discord don't look to have been updated in a few days despite there has been changes.

**To Reproduce**
1. Go to [Github Activity](https://discord.com/channels/841390338324824096/986057835135782912) channel
2. Notice the last update was on - 01/10/2024 3:37 PM

**Comment by 0xAurelius** [comment]
Identified the problem (webhook got deleted by an "Unknown User" according to Discord logs...)

Working with Chaz to recreate and reconfigure

**Comment by 0xAurelius** [comment]
Resolved
