### ISSUE TITLE
[ICR] cannot buy ICR credit on marketplace

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2131]
Here's what I did:

1. Created a listing for an ICR credit on the marketplace.
2. Switched to a different account to buy that credit.
3. Received error message when I tried to buy, see:
![Screenshot 2024-01-16 143831](https://github.com/KlimaDAO/klimadao/assets/128430614/020f1f10-226b-44fa-a10b-4549256aca0e)

I approved the transaction, but that error message instantly popped up when I hit the button to submit the transaction. Also, it threw me back to the Approve modal and told me "Error: something went wrong...".

**Comment by psparacino** [comment]
This bug only exists on the previous version of the APP preview branch, not on the feature branch

Keeping open only until the current version of the APP preview branch is tested
