### ISSUE TITLE
[receipt] Text wrapping issue on Mobile retirement receipts

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2133]
See for example https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/43 (open on mobile device)

Note...there is a related issue in #2134 where the profile display name is not being shown

### Issues

- If Beneficiary is a 0x address the wallet address does not wrap to stay inside the grey profile box (see image below) - please have the 0x address wrap
- Wrapping may change the required height of the component, see not below about padding
- Also there may be padding issues within the profile component, see how the view carbonmark profile link icon is right against the side of the container. Should maintain consistent padding as designs

![Screenshot 2024-01-16 at 2 24 56 PM](https://github.com/KlimaDAO/klimadao/assets/103535195/acaca69b-efbb-4e2c-a060-60e876658bd5)

- In the transaction record section, the TRANSACTION ID is also not wrapping (see image below)

![IMG_8F450B3F093C-1](https://github.com/KlimaDAO/klimadao/assets/103535195/e5d5c2a3-a2e0-4f41-818a-4bfa5b920296)
![IMG_C3D475CFDEA9-1](https://github.com/KlimaDAO/klimadao/assets/103535195/b4a95f85-6d3c-474d-9d07-c6370bcb5480)

**Comment by 0xMakka** [comment]
Hey @jabby09 I can pick this bug up today. 

@theprofessora Just wondering would it make sense to show an ellipsis on the long wallet address without having to cut the long address off at the end. The profile link below still brings the user to that wallet address? 

Something like `0x6476e...483`?

**Comment by theprofessora** [comment]
@0xMakka let's just wrap the address onto a second line, since there is also potential for a user's display name to be long enough that it needs to wrap. Then we already have consistent behavior for both scenarios

**Comment by jabby09** [comment]
@0xMakka I have this one to @sidneyarida
