### ISSUE TITLE
[subgraph] Dynamic Where clauses on gql_sdk

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2143]
## Describe the bug
The where clause on the `searchRetirements` gql method is currently being generated dynamically.

This is inconsistent with the rest of the APIs interaction with external GQL interfaces and has a couple of side effects:

1. Increased complexity and confusion about when to use the generated sdk and when not to
2. No end to end typing for that particular method.

The gql should be extracted to the `digital_carbon.gql` file and its relevant function generated in the SDK.

```gql 
query searchRetirements($where: Retire_filter) {
  retires(where: $where) {
    ...RetireFragment
    credit {
      ...CarbonCreditFragment
    }
  }
  ${RetireFragmentFragmentDoc}
  ${CarbonCreditFragmentFragmentDoc}
}
```

There will likely be other instances of this in the future so we need to investigate.

### Reference
Pull request discussion [here](https://github.com/KlimaDAO/klimadao/pull/2034/files#r1455596625).

**Comment by biwano** [comment]
Migrated to: https://github.com/Carbonmark/monorepo/issues/101
