### ISSUE TITLE
[dashboard] Sign-Up Feature

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2155]
## What:
Create a sign-up feature to allow new developers to register for an account on the Developer Dashboard.

## Why:
To allow new developers to join and access services provided by the Carbonmark Developer Dashboard.

## Question:
What fields does the new user need to provide? What do we want to know?
e.g)
* Who they are
* Why they want access
* Expected retirement amount
* ....?

## Expected Outcome:
- [ ] New developers can sign up and create an account.
- [ ] The sign-up process collects necessary information with appropriate security.

## Testing Criteria:
1. Ensure the sign-up form accurately validates and stores developer data.
2. Check error handling and provide clear user feedback during sign-up.

**Comment by jabby09** [comment]
Now in QA
