### ISSUE TITLE
[dashboard] Key Management System 

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2157]
## What:
Develop features for API key management, including creation and deletion, within the Developer Dashboard.

## Why:
To enable users to manage their API keys for secure and efficient interaction with Carbonmark APIs.

## Expected Outcome:
- [ ] Users can create new API keys through the dashboard.
- [ ] Users can delete their API keys when necessary.

## Testing Criteria:
1. Test the functionality of API key creation and deletion.
2. Ensure that the management system is secure and user keys are protected.

**Comment by jabby09** [comment]
now in QA
