### ISSUE TITLE
[fiat] Support ICR and tokenIds in fiat-to-retirement tooling

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#2159]
- add support for a `tokenId` parameter on quotes and checkout requests
- token id should be an integer
  - added to the "listing struct"  as shown in the new ABI for `retireCarbonmarkListing()` method
- if there is a token id, assumes it's an ICR contract (ERC1155 multi-token) that has zero decimals
- ask peter for example code on what retirements look like for ICR listings, we should have some in our frontend.
Stretch goal:
- ICR will not be pooled into any toucan or c3 liquidity pools (yet), so assume its only listings
- do preliminary work / thinking on what if a ICR was present in a pool... (this will eventually need to be supported)

- [x] Remove special conditional logic for ICR in `RetireForm.tsx`

**Comment by Atmosfearful** [comment]
No reason we cant start on this now since ICR is coming very soon ™️

**Comment by sprrwhwk** [comment]
@Atmosfearful 
>       * added to the "listing struct"  as shown in the new ABI for `retireCarbonmarkListing()` method

It's a new function in the ABI so we need to call a different function for ICR retirements instead of tweaking the params.

**Comment by sprrwhwk** [comment]
@psparacino how can we get a token id for the api here? Say I need the token id for the following: https://staging-api.carbonmark.com/projects/ICR-4-2020

**Comment by Atmosfearful** [comment]
Since we've got the tokenId added to the API and the relevant Offsetra changes put on staging, we should be able to get a PR up on the frontend and close this out
