### ISSUE TITLE
[content] Replace mentions of USDC with USDC.e

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2169]
For a few months now, "USDC" on Polygon has existed in two variants: "Native USDC", issued by Circle themselves, and bridged USDC, which are USDC tokens originally issued on Ethereum and then bridged over to Polygon. Those are called USDC.e. More information here: https://www.circle.com/blog/native-usdc-now-available-on-polygon-pos

Native USDC on Polygon didn't exist when Carbonmark started, so we call it USDC everywhere on the website. Technically, that's incorrect now, as we only accept USDC.e, which is also what it should be called everywhere on the website as well as in some parts of the documentation, like here: https://docs.carbonmark.com/get-started/how-to-get-usdc-or-matic

Users could be wondering (first instance of this occured yesterday on the Klima Discord) why their USDC tokens don't work on Carbonmark even though their wallet is loaded with them. By adjusting the wording, we avoid this.

In most cases, a simple seek and replace for every mention of USDC should be enough. Documentation might need a little more work.

**Comment by Atmosfearful** [comment]
@ChazSchmidt can this be closed?
