### ISSUE TITLE
[design] Design opinion linking from CM to KlimaData

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2173]
@theprofessora there was a feature request in the KlimaDAO server related to linking KlimaData from CM

see [thread](https://discord.com/channels/841390338324824096/841390338324824099/1199207645576437896)

> Also I think the "Klima Data" button should be easy to click in Carbonmark as well, for any person to get a birds eye view of the dynamics... Currently it seems Klima Data is buried in the main menu on KlimaDAO.finance -- but I think this is a really impressive piece of front end dashboard into the whole market that would lend the perception that Klima really is a leader in the space

Looking for a design opinion on this?

(my two cents, maybe it could be referenced in the footer or somehow in Resources)

**Comment by theprofessora** [comment]
I'm wondering if we can't fit it into the new portfolio designs coming out. The hope is to create a sales & traffic dashboard for sellers to track various data points, and it would probably be a good place to also link out to Klima Data so sellers can see how the market is doing as a whole
