### ISSUE TITLE
[dashboard] Usage View

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2182]
### Chore

**Task:** Implement a sortable and filterable table in the Developer Dashboard's Usage View to display retirements.

The table should list all retirements associated with the logged-in account, allowing sorting and filtering by various keys (e.g., date, amount, type). This feature aims to enhance the user experience by providing a comprehensive overview of retirement activities.

**Acceptance Criteria:**
- A table displaying retirement data is present in the Usage View.
- Features to sort and filter the table by different keys are working smoothly.
- The table design is consistent with the current dashboard aesthetics and responsive to different screen sizes.

Assigned to: @0xemc
Labels: dev, dashboard

**Comment by jabby09** [comment]
Now in QA
