### ISSUE TITLE
[retire] PolygonScan url in successful retirement dialog is wrong

### ISSUE THREAD

**Issue by sprrwhwk** [KlimaDAO/klimadao#2184]
We're displaying a link for mumbai instead of the mainnet polygonscan url.

              All good now, but two tiny issues remaining:
![Screenshot 2024-01-25 115333](https://github.com/KlimaDAO/klimadao/assets/128430614/3b96eb13-2b95-44d4-97fb-ae4d6596c409)

1. The link to PolygonScan currently points to Mumbai.
2. There's a space missing in the first link, "your[ ]retirement".

No need to test this again once this is fixed, could not find any problems. Looking great👍

_Originally posted by @0xtapi in https://github.com/KlimaDAO/klimadao/issues/2056#issuecomment-1909921047_

**Comment by psparacino** [comment]
This is most likely because this was checked in a preview environment.

There is a new function, `getPolygonScanBaseUrl` that fetches the correct block explorer root based on network
