### ISSUE TITLE
[tech] Implement Machine Translation and Sync Feature in Lingui

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2185]
### Chore

**Task:** Upgrade our current Lingui integration to leverage machine translation and the newly introduced `sync` feature as described in the [Lingui documentation](https://lingui.dev/tools/introduction).

The objective is to streamline our localization workflow, improve translation quality, and maintain consistency across different languages. The new `sync` capability will enable us to manage our localization resources more efficiently.

**Acceptance Criteria:**
- Lingui integration is upgraded to the latest version supporting machine translation and the `sync` feature.
- Machine translation is configured and tested for accuracy and context relevance.
- The `sync` functionality is implemented to ensure translation files are consistently updated across all locales.
- Documentation is updated to reflect new workflow processes.

Assigned to: 
Labels: dev

**Comment by Atmosfearful** [comment]
We are already utilizing sync, I've gone ahead and enabled openAI translations in the translations.io dashboard. We still will rely on our human translators to review the ai translations, as they are able to view strings in context which sometimes changes the translation. This current version of ai translation lacks context-- a problem I hope they solve some day but will probably add a lot of complexity to the workflow...
