### ISSUE TITLE
[dashboard] Fix sortability for KlimaData Retirement Trends tables

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#2196]
**Describe the bug**
In the old carbon dashboard, tables were typically sortable by all fields. However the tables on the new Klima Data TypeScript frontend, at least in the retirement trends section, are only sortable by some fields. They should be sortable by all fields for which sorting is practical (for instance free text fields don't need to be sortable).

**To Reproduce**
1. Go to https://data.klimadao.finance/retirement-trends?tab=byChain
2. Notice limited sorting options on tables

**Expected behavior**
Tables should be sortable by all reasonable fields

**Screenshots**
![image](https://github.com/KlimaDAO/klimadao/assets/91024694/254846fc-c99d-4bf2-b06a-408f67f741e6)

**Comment by Atmosfearful** [comment]
@sprrwhwk would be good to get a quick assessment of this first, let us know how challenging it is to fix or if this is going to unfold in a larger refactoring (api queries etc...)

**Comment by biwano** [comment]
Hi @0xAurelius, I am very intrigued by this. I have sort options for all columns on my browser.
![image](https://github.com/KlimaDAO/klimadao/assets/11857992/a11a9f6e-780a-4e69-b5a1-d4d6a41d60d4)

What is your OS/Browser/version?

**Comment by wowselim** [comment]
> Hi @0xAurelius, I am very intrigued by this. I have sort options for all columns on my browser. ![image](https://private-user-images.githubusercontent.com/11857992/305838578-a11a9f6e-780a-4e69-b5a1-d4d6a41d60d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgzMzc0MjAsIm5iZiI6MTcwODMzNzEyMCwicGF0aCI6Ii8xMTg1Nzk5Mi8zMDU4Mzg1NzgtYTExYTlmNmUtNzgwYS00ZTY5LWI1YTEtZDRkNmE0MWQ2MGQ0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE5VDEwMDUyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTllOWQyZTM4ODJmZTYyOWM2YTBjOTAxZWFkYjU1ODQwNDNkYzBmM2VkZTNmNjlkNzc3MGMxNWU1ZjI5NDFjNDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.77z9gHedOpLhB-Uxct5cYBTIIeaC5WKEDEJEARWjzuU)
> 
> What is your OS/Browser/version?

I have the same problem with hidden controls on firefox. The SVGs seem to be hidden for some reason.
