### ISSUE TITLE
[UI v2 phase 2] Featured & Index Projects

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2228]
## Feature Projects

*Note: Please re-use the layout or component used for category card layout if that has already been completed*

### Design

https://www.figma.com/file/1ZbPdMCXOE7nmntcfFYAHP/Explore?type=design&node-id=36-5537&mode=design&t=XJewrW6EjSUdN5GC-4

![Image](https://github.com/KlimaDAO/klimadao/assets/7104689/0344c9a8-7017-48d8-92a5-405de450bc90)

![Image](https://github.com/KlimaDAO/klimadao/assets/7104689/fa4dc94d-155f-4d20-ade0-dd297fbb7081)

### Requirements:  
- Card design should match the current production implementation.
- Initially, featured projects will be hardcoded.
- Future enhancement: Support for project selection from a CMS-like interface.
- Card hover state should match the current implementation on CarbonMark.
- Entire card is clickable and directs users to the project page.
- Shop all projects goes to unfiltered marketplace
- Index Projects are hard coded (Moss and one other @theprofessora can you confirm the others?)

### Testing:
- [ ] Ensure each project card displays correctly on different screen sizes.
- [ ] Clicking a card navigates to the correct project detail page.
- [ ] shop all navigates to `/projects`

#### 13/03/2024
- New Screenshot
-Updated design link
- Requirement rework
- Index Projects

**Comment by sprrwhwk** [comment]
@jabby09 what are the four hardcoded project ids?

**Comment by jabby09** [comment]
> @jabby09 what are the four hardcoded project ids?

For now let's go with:
https://www.carbonmark.com/projects/VCS-1052-2012
https://www.carbonmark.com/projects/VCS-1764-2020
https://www.carbonmark.com/projects/VCS-1190-2018
https://www.carbonmark.com/projects/ICR-112-2019

**Comment by theprofessora** [comment]
> Index Projects are hard coded (Moss and one other @theprofessora can you confirm the others?)

Moss and CCO2
![image](https://github.com/KlimaDAO/klimadao/assets/110631623/50b5899f-02b5-421e-9fe8-629986f173ca)
![image](https://github.com/KlimaDAO/klimadao/assets/110631623/4d70c24e-758d-4cfa-9415-619e63d4b0f6)


Right now we don't have a page for these two cards to lead to. But this is what they'll look like. Only 2 cards for this section
