### ISSUE TITLE
[provenance] View issuance on Verra link is wrong is wrong for ICR credits

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2238]
**Describe the bug**
View issuance on Verra link is wrong is wrong for ICR credits

**To Reproduce**
1. Go to https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/44/provenance
2. Notice that the View issuance on Verra link is wrong.

**Expected behavior**
Replace View issuance on Verra link by an ICR link (if it exists)

**Comment by jabby09** [comment]
@biwano have confirmed the requirement.

If retirement is an ICR credit, then:

- [ ] The link should change to View issuance on ICR
- [ ] The link should take the user to the ICR project page / document tab, i.e. https://www.carbonregistry.com/explore/projects/ad2dec62-85d2-46b9-884f-fd218a0453b0?tab=documents
- [ ] The info icon text can be: "On the project Overview tab, click View Vintages to see specific serial numbers."
