### ISSUE TITLE
[provenance] Project name not displaying on retirement page for ICR retirements

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2239]
**Describe the bug**
Project name not displaying on retirement page for ICR retirements. And also on the retirement certificate.

**To Reproduce**
1. Go to https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/44
2. The project name is not showing.

**Expected behavior**
The project name should be displayed

![image](https://github.com/KlimaDAO/klimadao/assets/11857992/8bddacb3-8b41-4993-bead-328ae52d9f7d)

**Comment by psparacino** [comment]
After investigating his actually is the project name, just an extremely long one

**Comment by biwano** [comment]
> After investigating his actually is the project name, just an extremely long one

Ho lol :)
