### ISSUE TITLE
[provenance] Wrong quantity in retirement provenance page for ICR projects

### ISSUE THREAD

**Issue by biwano** [KlimaDAO/klimadao#2240]
**Describe the bug**
Wrong quantity in retirement provenance page for ICR projects

**To Reproduce**
1. Go to https://www.carbonmark.com/retirements/0x6476edf98bdc5ee62f9d4e4bf8932d69ed685483/44/provenance
2. Notice that quantity is 0

**Expected behavior**
Quantity should be 1

**Comment by jabby09** [comment]
this is resolved now
