### ISSUE TITLE
[retirements] Inconsistency in beneficiary display

### ISSUE THREAD

**Issue by 0xtapi** [KlimaDAO/klimadao#2241]
There's a discrepancy between what is shown on the website and what is shown in the certificate PDF after a retirement has been performed. See this example:

1. My input during the retirement process, which specifies "Earth" as "Beneficiary Name":
<img width="389" alt="Screenshot 2024-02-06 140450" src="https://github.com/KlimaDAO/klimadao/assets/128430614/9e625873-8aee-4a3f-8bd2-baa4a67c9e4d">

2. Output on the website and in the PDF:
<img width="428" alt="Screenshot 2024-02-06 140758" src="https://github.com/KlimaDAO/klimadao/assets/128430614/7464f6d8-594d-4b4b-b73b-e103945f6265">

<img width="365" alt="Screenshot 2024-02-06 140738" src="https://github.com/KlimaDAO/klimadao/assets/128430614/c297fead-929e-42af-8466-824861a63667">

The output lists my account name as the Beneficiary while the PDF uses the value I had given, "Earth", while also calling it Beneficiary. Both cannot be true at the same time, so... I guess the website either doesn't catch the "Beneficiary" value or chooses to ignore it?

**Comment by ChazSchmidt** [comment]
My hunch is this issue stems from this commit aceb0245906aea7c21417a6137d1449cd5be1973
