### ISSUE TITLE
[performance] Individual `/project` pages slow load

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#2253]
**Describe the bug**
Individual project loads are lengthy, preceded by a white screen.

This could possibly be caused by the mapbox token:
<img width="300" alt="Screen Shot 2024-02-12 at 10 58 03 AM" src="https://github.com/KlimaDAO/klimadao/assets/72105234/20bca23e-72c3-4ad7-b26d-4437d8358dcd">

**To Reproduce**
1. Go to https://www.carbonmark.com/projects/ICR-112-2019
2. Wait for page to load
3. Open consolve

**Expected behavior**
Page loads without a white screen interlude/delay

**Comment by Atmosfearful** [comment]
Found a fix for the white screen, putting PR up in monorepo.
