### ISSUE TITLE
[sanity] Need to support CM branded disclaimer on blog articles

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2272]
### Issue

https://www.carbonmark.com/resources is powered by klimadao.sanity.studio

On a post page, there is an option to `Show Disclaimer` automatically on an article.
<img width="621" alt="Screenshot 2024-02-15 at 9 27 07 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/c99394c2-d9b5-46d0-b835-b1216bfefd2d">

This issue is that the disclaimer uses KlimaDAO org branding which is no longer relevant for Carbonmark related articles. As an example, see https://www.carbonmark.com/blog/about-carbonmark

### Requirements

Edit: Atmos moved these to comment below

**Comment by Atmosfearful** [comment]
Thankfully this CMS is not used for klimadao at all anymore. So I would expand the scope of this ticket to the following:
* [ ] Remove the Domain dropdown from the schema
* [ ] In the Carbonmark disclaimer replace KlimaDAO with Carbonmark and replace "crypto-assets" with "digital-assets"

**Comment by jabby09** [comment]
> Thankfully this CMS is not used for klimadao at all anymore

ah yes, I totally forgot that so good point.
