### ISSUE TITLE
[retirement] Proposed receipt enhancement

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2279]
See [discord thread here](https://discord.com/channels/1135827610434289727/1208006619397627954).

The solution team has made the following proposed suggestions to the retirement receipts (digital and pdf).

[Figma page for reference](https://www.figma.com/file/mgCvQP7CPtj5tpgfXxTTDC/Untitled?type=design&node-id=0-1&mode=design&t=P0RdLUFOroJqIHEo-0).

**Digital receipt**
- [x] Remove the link to polygonscan? (transaction id should remain)
- [x] Copy for "Official Certificate for On-Chain Carbon Retirement Provided by Carbonmark.com" changed to "Certificate for Carbon Retirement".
- [x] About Carbonmark section can be removed, i.e. "With over 20 million verified digital carbon credits from hundreds of projects, Carbonmark offers the largest selection of digital carbon credits worldwide. Buy, sell, and retire digital carbon from any project instantly with zero-commission trading. Get started today."

**PDF certificate**
- [x] Polygonscan link can be removed (transaction id should remain)
- [x] Copy for "Official Certificate for On-Chain Carbon Retirement Provided by Carbonmark.com" changed to "Certificate for Carbon Retirement".

**Learn more links**
- [x] Remove learn more links in project details

### Updated designs
[Digital receipt (see desktop and mobile)](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6422&mode=design&t=NzpVz2nNjBJBypSq-4)
[PDF receipt](https://www.figma.com/file/L8DIYEw8LbYHyBhUIQa2AY/Retire?type=design&node-id=384-6606&mode=design&t=NzpVz2nNjBJBypSq-4)

**Comment by theprofessora** [comment]
these seem reasonable. no objections here

**Comment by Atmosfearful** [comment]
Fine with me as well!
