### ISSUE TITLE
[Klimadao/klimadao] KlimaInfinity and RetirementAggregatorv2 ABIs duplicate/out of sync

### ISSUE THREAD

**Issue by psparacino** [KlimaDAO/klimadao#2280]
**Describe the bug**
`KlimaInfinity` and `RetirementAggregatorV2` are two different names for the same contract. Right now in lib/ and the frontend both are being used interchangeably and there are two abis (of different versions) for each contract. This is causing issues when the versions fall out of sync or when developers don't know the other exists and are testing against an old abi.

**Expected behavior**
We should decide on one name for that contract, retirementAggregatorV2 is probably clearer, use only that updated abi and change all other references to the alternate name to the decided on name.

**Comment by Atmosfearful** [comment]
Agreed, let's go with retirementAggregatorV2
