### ISSUE TITLE
[provenance] Change "Bridge" terminology to "Transfer"

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2281]
[See discord thread](https://discord.com/channels/1135827610434289727/1208035240291864606)

Overall, let's start using 'transfer' as the term to describe the movement of credits to/from registry accounts to our platform.

- [x] Request to change `Bridge` label on provenance pages to `Transfer`

![image](https://github.com/KlimaDAO/klimadao/assets/103535195/78d2141d-17c5-49d6-8606-8be6070ca876)

**Comment by theprofessora** [comment]
A few changes were necessary here:

1. changed "Bridge" to "transfer"
2. changed "transfer" to "send"
3. added info icon w/ tooltip explaining that a Send is when an "Asset moved from one account to another, either via sale or inter-account transfer."
4. changed "view/hide XX transfers" to "view/hide XX _transactions_"

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/1a32881a-7da8-41b5-a8de-2bdad3687e76)
