### ISSUE TITLE
[header | footer] Remove `Help` from top and bottom navigation

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2282]
When Carbonmark launched we created MVP user docs to guide users of the app on how to create a profile and perform basic transaction such as create a listing, retire, purchase etc.

A [decision was made](https://discord.com/channels/1135827610434289727/1207710259083485214) to modify and update https://docs.carbonmark.com/ to being completely developer focused. Older user docs have been deprecated.

The `Help` option in the navigation header (on CM.com homepage) and footer no longer makes sense as this now directs users to docs that are purely dev/api focused.

### Recommendations
- [x] Remove `Help` from CM.com homepage primary nav and footer

**Comment by theprofessora** [comment]
Changes have been made at the component level. It might take a couple days for them to be reflected across all the figma files
