### ISSUE TITLE
[UI v2 phase 3] Hero Section Update

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2296]
**Requirements:**
- [ ] Remove vintage & registry information from the Hero section.
- [ ] Add methodology to the Hero section.
- [ ] Include a background satellite image.

**Designs:**

![image](https://github.com/KlimaDAO/klimadao/assets/7104689/4d3b8ba3-e63a-4f8f-9d6d-afcd3e389151)

https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2024-35193&mode=design&t=cjuQ469TKnaGRbiV-4

**User Story Reference:** _Not applicable as no specific user story was provided for the Hero section._

**Comment by sprrwhwk** [comment]
Pictures can be generated using mapbox like so:

`https://api.mapbox.com/styles/v1/mapbox/satellite-streets-v12/static/8.6821,50.110924,16/1280x720?access_token=<token>`

where:
* `satellite-streets-v12` the mapbox style (satellite with streets)
* `8.6821,50.110924,16` = `<lon>,<lat>,<zoom>`
* `1280x720` = width x height in pixels (maximum being 1280 x 1280)
* `<token>` = our mapbox token

**Comment by jabby09** [comment]
recreated here https://github.com/Carbonmark/monorepo/issues/307
