### ISSUE TITLE
[UI v2 phase 3] Asset List

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2297]
**Requirements:**
- Collate vintages into a single route (e.g., `/VCS-182-2019` ➔ `/VCS-182`).
- Update the Asset List UI.
- Sortable by price, date created, vintage & available tonnes.

**Designs**

![image](https://github.com/KlimaDAO/klimadao/assets/7104689/21ab500a-bc61-4e85-8272-b294d77501a0)

https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2024-35223&mode=design&t=cjuQ469TKnaGRbiV-4

**User Story Reference:**
cmv2-p3-2 - Asset List
As a user viewing the Project Detail page, I want to see a list of all available Assets for that project so that I can avoid having to compare across tabs

cmv2-p3-3 - Asset Detail
As a user viewing the Project Detail page, I want to be able to easily identify all details relevant to an asset (id, listing vs pool, vintage, available tonnes, best price) so that I can easily make a decision when purchasing & retiring

cmv2-p3-4 - Asset List Sort
As a user viewing the  Project Detail page, I want to be able to sort the Assets by various parameters (price, date created, vintage & available tonnes) so that I can easily find assets I'm interested in.

**Comment by jabby09** [comment]
recreated here https://github.com/Carbonmark/monorepo/issues/303
