### ISSUE TITLE
[UI v2 phase 3] Registry Card

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2298]
**Requirements:**
- [ ] Add the project logo and ID to the Registry Card.
- [ ] Create a direct link to the registry page from the Registry Card.

**Designs**
![image](https://github.com/KlimaDAO/klimadao/assets/7104689/009bd77b-48c5-48e4-92a3-3d7730bf59d2)

https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2024-35226&mode=design&t=cjuQ469TKnaGRbiV-4

**User Story Reference:** cmv2-p3-5 - As a user viewing the Project Detail page, I want to be able to identify the registry for the project and easily navigate to the credit on that registry so that I can easily find more details for a project and its assets.

**Comment by jabby09** [comment]
recreated here https://github.com/Carbonmark/monorepo/issues/304
