### ISSUE TITLE
[UI v2 phase 3] Project Details Layout

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2299]
**Requirements:**
- [ ] Two Column Layout
- [ ] Remove Activity card

**Designs**
![image](https://github.com/KlimaDAO/klimadao/assets/7104689/10850cb6-1ff0-4ec1-a296-c5be7e58839e)

https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2024-35192&mode=design&t=cjuQ469TKnaGRbiV-4

**User Story Reference:** None

**Comment by jabby09** [comment]
recreated here https://github.com/Carbonmark/monorepo/issues/305
