### ISSUE TITLE
Add "Media Requests" link to Google Form

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#23]
In order to funnel media requests to the marketing team, we should add a link to this Google form on the main site somewhere:

https://docs.google.com/forms/d/e/1FAIpQLSdIVolbOvbuw1LHGwT8ec9HHZTWxSluErInZ_TaiqKzAvG30w/viewform

**Comment by 0xAeterno** [comment]
Is this something we'd still like to implement on the current landing page? 😃

**Comment by Atmosfearful** [comment]
Nope, this will make it on the new upcoming Contact page! Thanks for asking @0xAeterno , I can close this ticket.
