### ISSUE TITLE
[UI V2 Phase 3] Projects Single Card Per Project

### ISSUE THREAD

**Issue by 0xemc** [KlimaDAO/klimadao#2305]
**Requirements:**

- [ ] Price shown is lowest across all vintages
- [ ] Vintage removed from cards
- [ ] Filterable/sortable via Vintage
- [ ] Country tag on cards

**Designs**
![image](https://github.com/KlimaDAO/klimadao/assets/7104689/8721a9fa-070a-42bb-88ac-41e1a31166c6)

https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/Projects?type=design&node-id=2112-27115&mode=design&t=cjuQ469TKnaGRbiV-4

**User Story** cmv2-p3-2 - As a user viewing the Project Detail page, I want to see a list of all available Assets for that project so that I can avoid having to compare across tabs.

**Comment by jabby09** [comment]
recreated here https://github.com/Carbonmark/monorepo/issues/306
