### ISSUE TITLE
Use Infura for server-side / build-blocking RPC requests

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#231]
# Requirements
- [x] Add `process.env.INFURA_ID` to env vars in vercel. ✅ 
- [ ] Export from `site/lib/constants` similar to other env vars.
- [ ] Use this ID to construct the infura endpoint `https://polygon-mainnet.infura.io/v3/${INFURA_ID}`
- [ ] Fallback to polygon-rpc instead of infura endpoint, if no INFURA_ID is available. This is the fallback for devs on localhost, as this Id only exists on vercel.
- [ ] use this endpoint to create the `jsonRPCProvider` with `ethers`, for all the functions that run on the serverside. Ensure a clear deliniation for functions that are called on the server and rely on infura-- we don't want these being used client side now or in the future.

**Comment by Vienio99** [comment]
I can grab that one if nobody is working on this
