### ISSUE TITLE
[deposit] New app feature to deposit TC02 to BCT pool 

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2365]
This is part of the BCT User Interface KlimaDAO project. The MVP of these features will be supported in the existing KlimaDAO app.

To support **BUY/REDEEM** capability, the `BUY` tab functionality will be returned to to the app. Currently this implementation can be seen here: https://legacy-app.klimadao.finance/#/redeem

To support **DEPOSIT**, a new tab will be added to https://app.klimadao.finance/

Inspiration can be taken from the same functionality in the Toucan app:
<img width="454" alt="Screenshot 2024-05-27 at 9 20 04 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/27203bc2-a132-430b-8031-54fae12c4d0c">

**Requirements:**
- Only need to support deposit of TC02 to BCT

**Comment by theprofessora** [comment]
First pass here: https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=1-3&t=RNlN3p8cx94OVrAd-1

![image](https://github.com/KlimaDAO/klimadao/assets/110631623/b7dd27a1-a870-4ad5-b075-fb2aecee30bc)
