### ISSUE TITLE
[deposit] Dev implementation in the dApp

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2368]
### Designs
https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=0-1&t=N3wez6P2Tw2so6xj-0

### Requirements

- [x] support for desktop and mobile
- [x] new url path https://app.klimadao.finance/#/deposit
- [x] need to show Risk Disclaimer if user enters site from the /deposit URL
- [x] new `Deposit Carbon` option in side menu
- [x] new [Deposit carbon form](https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=23-1249&t=N3wez6P2Tw2so6xj-4)
- only available for TC02 --> BCT 
- only editable field is Deposit TC02
- MAX button fills in field with value from Available balance
- need to [LOGIN to CONTINUE](https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=23-1293&t=N3wez6P2Tw2so6xj-4)
- [x]  Select token [dropdown modal](https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=23-1425&t=N3wez6P2Tw2so6xj-4)
- lists all tokens in wallet
- indicates which tokens are compatible with BCT and greys out those as selectable
- user clicks token and that closes the modal and populates token to deposit on the form
- [x] [Error states](https://www.figma.com/design/oA67X2DpUOjlpEktwaDZH7/Deposit?node-id=23-1337&t=N3wez6P2Tw2so6xj-4)
- form field checks to ensure user has enough available balance for deposit quantity entered

### Notes
- noticing now we do not have designs for what happens after user clicks CONTINUE; but I assume there would be wallet interactions
- we can follow up on this once Codey is back from vacation
- for now can we follow the pattern used in other transactions (retire and buy) in the dApp?

**Comment by 0xMakka** [comment]
@cujowolf @Atmosfearful do you happen to have a reference to the contract to call for this flow?
