### ISSUE TITLE
[klima data] Broken data on Supply and Retirement Trend pages

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#2388]
user reporting issues 
see https://discord.com/channels/841390338324824096/1281580911292317769

- polygon data on /supply page now showing properly
![image](https://github.com/user-attachments/assets/d00528c4-d9ef-475a-bcdd-9480f7dd9aee)

- on /retirement-trends, issues with redemption/retirement component
![image](https://github.com/user-attachments/assets/892b0f23-1aff-487c-b667-aa86819269e1)

**Comment by 0xAurelius** [comment]
I believe this is a result of the old Polygon Bridged Carbon subgraph suddenly breaking on the decentralized network and returning null values

This can be resolved short term by fixing the Polygon Bridged Carbon subgraph deployment, but long term there are missing entities that need to be ported to the new Polygon Digital Carbon subgraph so we can stop maintaining the old one: https://github.com/KlimaDAO/klima-subgraph/issues/95
