### ISSUE TITLE
Styling issues in Firefox

### ISSUE THREAD

**Issue by kargakis** [KlimaDAO/klimadao#264]
The following issues seem to be unique to Firefox (tried also with Brave but everything looks fine there).

1. The main form is not boxed properly in the Offset page

![offset](https://user-images.githubusercontent.com/3900799/159578381-3810438d-a392-4200-b64c-ad366bb9b405.png)

2. There is no margin at the bottom of the Bond and Info pages

![bond](https://user-images.githubusercontent.com/3900799/159578686-ec9f46a8-42f8-4979-bdef-04935bd70821.png)
![info](https://user-images.githubusercontent.com/3900799/159578806-71f1a385-f17a-48cd-9b8e-93522a064d5f.png)

3. Related to 2, I'd ensure the margin at the bottom is consistent across all pages. Currently even in the rest of the pages where there is some margin, it is not consistent.

**Comment by Atmosfearful** [comment]
fixed in #273
