### ISSUE TITLE
Add link to tokenized carbon dashboard from klimadao.finance

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#266]
Once we're ready to share it with the world

**Comment by Atmosfearful** [comment]
We can add it this week ja? Soft launch? @0xAurelius

**Comment by 0xAurelius** [comment]
Yes let's! The link was already linked in the recent Coindesk article lol

**Comment by Atmosfearful** [comment]
As discussed in sprint planning, we can let marketing decide when they will push this and make sure it goes up before then. Depending on when that is, it will likely be in the new header nav that @goatsOnDrugs is working on here #591

@jabby09 @0xAurelius
