### ISSUE TITLE
Add internationalization framework

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#29]
In order to facilitate the community team adding localizations for as many languages as possible, we need to add a framework for internationalization such as `lingui.js`

This blog post gives a good overview of how to set this type of thing up: https://blog.logrocket.com/complete-guide-internationalization-nextjs/

We should also have a PR template specifically for translators to make sure they have a step-by-step include all necessary changes

**Comment by Atmosfearful** [comment]
We need to wait until the new site and brand refresh is completed done before doing any i18n. I do think we need to get there at some point, but my experience has been that it creates a ton of overhead and can significantly slow down pace of development. I don't think it will add much value until we also have marketing and advertising teams creating content and reaching an audience in those languages.

- Adds QA overhead: testing the feature with different word sizes, and RTL layouts.
- A more rigid translation and release pipeline needs to be set up (feature to staging -> translation to staging -> QA-> release).
- I need to add static generation for locale paths (not that hard).

I only have experience with i18n in two apps: one was a megacorp using a bespoke in-house i18n pipeline. Strings were kept in a set of JSON files and translations were committed by the translation team directly to staging before releases. The other was a smaller mobile app with a 4 person team. There we used lokalise and fetched translations via API before release. That app didn't have much text.

A bare minimum-viable product here will be to translate the docs or user guides first. With a proper reference guide + browser translation, the vast majority of users should be able to interact with the app

**Comment by Atmosfearful** [comment]
Work is ongoing in the `i18n` branch. Hoping to merge ASAP
