### ISSUE TITLE
Rebase & Bond times are inaccurate

### ISSUE THREAD

**Issue by micah** [KlimaDAO/klimadao#31]
Due to the fact that the DAPP uses a constant for the block rate (see https://github.com/KlimaDAO/klimadao/blob/main/lib/constants/index.ts#L95) which is pinned at `2.5` seconds, and because this is not really how often the block rate actually works, the 'time until fully vested' value on the bond dapp can be fairly inaccurate.

I've seen this value be off by as much as 20 hours. The correct way to do this would be to poll polygonscan's API to check what the actual value should be, instead of hard-coding a constant.

**Comment by Atmosfearful** [comment]
@Vienio99 is making progress on this! Just a couple more pieces to integrate.
