### ISSUE TITLE
Add Love Letters link to main site

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#314]
Marketing has requested we link to https://www.loveletter.klimadao.finance from the main site, ideally from the main navbar next to Resources

**Comment by Atmosfearful** [comment]
I slipped this one straight to staging here: https://github.com/KlimaDAO/klimadao/commit/b6c5d3d4037e996c53abbabaf278f4ea9f76fcab
Went live this morning
