### ISSUE TITLE
add "add sKLIMA and add KLIMA" buttons to Menu

### ISSUE THREAD

**Issue by ArchimedesCrypto** [KlimaDAO/klimadao#32]
Add the

"add sKLIMA to Metamask"
and
"add KLIMA to Metamask" buttons in the top right beside the the disconnect button like you see on the Olympus dapp.

**Comment by Atmosfearful** [comment]
I like how sushi does it, with a 'success' modal that has the 'add to metamask' button for the relevant token

**Comment by Atmosfearful** [comment]
@rstycedar is working on a solution that will have the relevant add-token-to-metamask wallet button appear after a transaction is confirmed (stake, unstake, wrap, etc.)

**Comment by Atmosfearful** [comment]
this will be a part of the new site design
