### ISSUE TITLE
Investigate: tree shaking and code splitting for lingui and locales

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#327]
This section caught my eye. Is this running on server + client? Do all locales get loaded regardless of the currently selected one?
If so is that a problem, and can we split this out to only load whats needed?

https://github.com/KlimaDAO/klimadao/blob/5f4d8568ac85ce39acd59c8819711ad5860b01bb/app/lib/i18n.ts#L29-L32

**Comment by biwano** [comment]
Hi @Atmosfearful !

The `loadLocaleData` only sets up lingui with the configuration for the different languages supported by the application.
The actual loading of the translations is done here:
```
async function load(locale: string) {
  const { messages } = await import(`../locale/${locale}/messages.js`);
  i18n.load(locale, messages);
  i18n.activate(locale);
}
```

I checked on my development PC that languages are loaded dynamically. I will check again on staging.

cf:
- linguijs documentation: https://lingui.js.org/ref/core.html
- i18n class source code: https://github.com/lingui/js-lingui/blob/main/packages/core/src/i18n.ts#L107
