### ISSUE TITLE
[EPIC] App /buy view refresh

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#344]
See new designs in Figma.
https://www.figma.com/file/t2suR7Rz8f7lZF3KsCL7gu/Buy-Klima?node-id=0%3A1
* [ ] #325 
* [ ] #241

**Comment by jabby09** [comment]
@Atmosfearful @kaxline the PR  #(470)for this looks like it is waiting for a review or merge.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO this is in the test column and assigned to you

**Comment by ShimonD-KlimaDAO** [comment]
https://github.com/KlimaDAO/klimadao/pull/470#issuecomment-1311245232

Moving back to In Progress

**Comment by Atmosfearful** [comment]
Mobilum has been causing too many problems. I will probably tear this whole thing out and just link users to Transak

**Comment by jabby09** [comment]
@Atmosfearful we can probably close this one correct?
