### ISSUE TITLE
[app] Quick Updates to Info page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#350]
https://app.klimadao.finance/#/info

* [ ] Add these
UBO: 0x2B3eCb0991AF0498ECE9135bcD04013d7993110c
NBO: 0x6BCa3B77C1909Ce1a4Ba1A20d1103bDe8d222E48
NCT: 0xD838290e877E0188a4A44700463419ED96c16107
* [ ] Bonus points if you add the token icons to all

**Comment by jabby09** [comment]
@Atmosfearful @rstycedar looks like UBO and NBO are now there but not NCT
