### ISSUE TITLE
[app] add helper text to Specific Retirement

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#358]
> Hi team, great work on integrating the individual project burning function. It is, however, pretty complex for the average user to figure out how to use this I think. I know a much better UX with search and filters is coming at some point, but in the interim, could we have something like this:

> Below the "Retire specific project tokens" field, could we have a text link saying something like "Where do I find the 0x address of a project token" linking to https://carbon.klimadao.finance/BCT and include a short text saying "Scroll down to the project list table, find a project you like and copy the Token Address from the last column"

> In fact, maybe better, since the token address is not immediately visible and to make it quicker for ppl to find it, can we include a column between Project ID and Vintage called 0x address and just have a small button called "Copy" which copies the address so that the user can then easily paste it? Just one quick and dirty suggestion.

**Comment by jabby09** [comment]
Deprecated by Carbonmark and /retire app migration which is coming by end of May 2023.
