### ISSUE TITLE
[Website] Flagged as Phishing

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#361]
The website is getting flagged by multiple antivirus and phishing screeners as reported by multiple users.

This may be related to the URL redirect from dapp to app, since @Atmosfearful confirmed that the normal domain is fine.

**Examples:**

1. https://phishtank.org/phish_detail.php?phish_id=7494506
2. 
![image](https://user-images.githubusercontent.com/99001851/165855574-ef5409b1-f942-4137-9f71-030e357e06a3.png)

3. https://www.virustotal.com/gui/url/6d5b90966cc520b592edf33a7c1dc6d64d2f2d6cb608deb837cc1f4cc5eb5562

4. 
![image](https://user-images.githubusercontent.com/99001851/165855641-321ba1fc-1f93-4c86-b491-37c8792d0395.png)

**Comment by ShimonD-KlimaDAO** [comment]
Atmos did the following:
1. Sent a support email to vercel and to Valkyrie.comodo.com.
2. Submitted reclassification request to Trend Micro.
3. Submitted a ticket to Fortiguard.

**Comment by Atmosfearful** [comment]
![image](https://user-images.githubusercontent.com/88635679/165990406-f0a85b95-a176-49c5-a052-47ca4d0e322a.png)

**Comment by Atmosfearful** [comment]
![image](https://user-images.githubusercontent.com/88635679/165990688-e1707f53-a94a-4ca4-a2c7-bc3bc4528af6.png)

**Comment by Atmosfearful** [comment]
I filed a request on the forums here:
https://forums.comodo.com/comodo-valkyrie-fls/report-false-positives-for-valkyrie-service-here-2022-t127715.0.html;msg915116#msg915116

**Comment by Atmosfearful** [comment]
There are still 4 vendors flagging us as malicious:
![image](https://user-images.githubusercontent.com/88635679/165992292-a72eae3b-85c9-4753-a302-45a6d0de159b.png)

**Comment by goatsOnDrugs** [comment]
Reproduced on windows 11 (chrome and firefox) brave seems to be working fine

**Comment by Atmosfearful** [comment]
I submitted a request to Sophos to recategorize, their documentation is very unclear. I am also reaching out to them on twitter.

![image](https://user-images.githubusercontent.com/88635679/165995915-d1ac8b0e-97b9-419e-9b21-80d79ed3926d.png)

**Comment by Atmosfearful** [comment]
Comodo has recategorized us. Sophos representative in my DMs says we have been corrected in their system as well. 2 more to go!
Phishtank, and QuickHeal....

**Comment by Atmosfearful** [comment]
Submitted to QuickHeal
![image](https://user-images.githubusercontent.com/88635679/165998208-46f70291-8ce5-4fb9-bc7e-4dee64ead9bb.png)

**Comment by Atmosfearful** [comment]
![image](https://user-images.githubusercontent.com/88635679/166290226-641f191c-d85f-460f-b25b-f2b4107d265b.png)

**Comment by Atmosfearful** [comment]
![image](https://user-images.githubusercontent.com/88635679/166290334-ad581b3c-9eed-4177-a336-351860711d79.png)
