### ISSUE TITLE
Improve "time until rebase" to show hh:mm

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#363]
* [ ] when > 60 minutes remain, show "__ hours, __ minutes" or instead of just "__ hours"
Or any other time format you can come up with that makes sense and looks good!
* [ ] Make sure the output text is localized properly

**Comment by Atmosfearful** [comment]
Discord user Ishmis (Sekula#0203) offered to take a stab at this

**Comment by jabby09** [comment]
checked the dApp, this looks to be already implemented
