### ISSUE TITLE
Translation: Do not translate dynamic values

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#371]
## Problem

You can see in this commit that the dynamic value {beneficiaryAddress} was translated:
https://github.com/KlimaDAO/klimadao/commit/4588be697fb9f82f91dd5f00f15cbe6cd5307fa6#diff-97df1968ed9ec8222e8c69b2b96add299b947ff53176f565c9c00a121b3f7b3aR659-R663

Instead, dynamic values should remain and look like this:
https://github.com/KlimaDAO/klimadao/commit/4588be697fb9f82f91dd5f00f15cbe6cd5307fa6#diff-b93c89149e99aa09e66d429f3ea29d06599180e77984361ba575d54bd0505df3L665-R669

=> {beneficiaryAddress} should stay

# Solution

Re-add the dynamic value {beneficiaryAddress}  on [translation.io](https://translation.io/) for each language again 🙂 
Double check if more dynamic values have been changed.

**Comment by ShimonD-KlimaDAO** [comment]
Re-added missing dynamic values for each language and reverted their translation on translation.io.
I also alerted the translators to this so that they are aware next time. This issue is resolved.

**Comment by ladytrekker** [comment]
Thanks. Closing
