### ISSUE TITLE
Moralis: Local development is missing App ID, Server URL and Modules

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#380]
## Problem

Since the merge of this PR https://github.com/KlimaDAO/klimadao/pull/275 the MoralisProvider was introduced which reads the NEXT environment values: 
- `process.env.NEXT_PUBLIC_MORALIS_APP_ID`
- `process.env.NEXT_PUBLIC_MORALIS_SERVER_URL`

See the implementation here: https://github.com/KlimaDAO/klimadao/blob/staging/site/pages/_app.tsx#L51-L54

When running the Site locally these issues appear:
- `ReactMoralisError: Provide a "appId" provided to <MoralisProvider>`
- `warn  - ../node_modules/moralis/lib/browser/Web3Connector/MagicWeb3Connector.js
Module not found: Can't resolve 'magic-sdk'`
- `../node_modules/moralis/lib/browser/Web3Connector/Web3AuthConnector.js
Module not found: Can't resolve '@web3auth/web3auth'`

## Solution

- Provide a fallback for AppId and ServerURL when running Site locally for the MoralisProvider (Testing values) ?
- Extend the ReadMe on how to add and read these values locally (so far no local set-up is done yet for reading node ENVs) => see the [docs](https://nextjs.org/docs/basic-features/environment-variables#exposing-environment-variables-to-the-browser)
- If not on Vercel: Do not wrap App in MoralisProvider at all?
- ignore the warnings above for the missing modules? => See [Thread](https://forum.moralis.io/t/module-not-found-cant-resolve-magic-sdk/9093/6)

**Comment by ladytrekker** [comment]
Tagging both of you @0xAeterno and @Atmosfearful as you merged the PR.

**Comment by 0xAeterno** [comment]
@ladytrekker sorry for sending you on a bit of a rabbit hole - I've sent you a message on discord for a temp workaround.
I'll put something together in the interim as we move to firebase over moralis

**Comment by ladytrekker** [comment]
Thanks for the workaround. Works fine for me.

**Comment by Atmosfearful** [comment]
Will close this as soon as the firebase migration is done
