### ISSUE TITLE
[wallet] Get Carbonmark listed on the Torus wallet Polygon apps list

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#383]
Low priority

**Comment by Devjohn12** [comment]
Talk to Polygon Support on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

**Comment by biwano** [comment]
@Atmosfearful If you mean this page: https://polygon.technology/ecosystem
There is a form now: https://airtable.com/shrIvwJeBZBKGlojh

**Comment by Atmosfearful** [comment]
Will post in chat and see if someone can plug us in. Not an engineering item.
