### ISSUE TITLE
[ DApp ] Minor issue: strange character displayed in bond "Sold Out" string

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#384]
![image](https://user-images.githubusercontent.com/99001851/167479385-882fa1ff-a576-4eb1-a5df-a995543c61a0.png)

**Comment by goatsOnDrugs** [comment]
@ShimonD-KlimaDAO what device/browser was this on? I'm having trouble reproducing this.

**Comment by ShimonD-KlimaDAO** [comment]
> @ShimonD-KlimaDAO what device/browser was this on? I'm having trouble reproducing this.

Apologies for not being specific. I was able to reproduce this again today on Brave browser on Ubuntu.
