### ISSUE TITLE
Add social proofs section to landing page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#391]
## Description

* [ ] See figma link below https://github.com/KlimaDAO/klimadao/issues/391#issuecomment-1139485243
* [ ] Put the Social Proof in a new Section after blackhole section before mechanics section on [Landing Page](https://www.klimadao.finance/)

**New Section here:**
<img width="600" alt="new_section" src="https://user-images.githubusercontent.com/95881624/169968514-ad3c204b-7533-46c3-bc5f-960b4f0f8019.png">

**Comment by Atmosfearful** [comment]
Sorry no designs for this hope, hopefully you can figure it out!

**Comment by ladytrekker** [comment]
@Atmosfearful To understand what is a Social Proof, can you reference to the code on Loveletter or take a screenshot?

**Comment by Atmosfearful** [comment]
Yup, this part here! 
![image](https://user-images.githubusercontent.com/88635679/170611550-6d832fe9-232c-4788-8b50-e3f9c2a386c0.png)

Problem is we still need dark-mode compatible versions of the images

**Comment by Go-Mori** [comment]
Here they are: 
https://www.figma.com/file/ITpEVoi0pVYDRSLpFOaCiz/LANDINGPAGE?node-id=1603%3A950

**Comment by Vienio99** [comment]
Thanks, will start working on this!
