### ISSUE TITLE
Remove Twitch.tv and TikTok links from footer

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#392]
On site and dapp as well

**Comment by Vienio99** [comment]
I can grab that one

**Comment by Vienio99** [comment]
@Atmosfearful should we leave Icons components for future or delete them as well?

**Comment by Atmosfearful** [comment]
> @Atmosfearful should we leave Icons components for future or delete them as well?

Feel free to delete, let's never leave dead code. We always have Git history if we want to bring something back.
