### ISSUE TITLE
[Tech debt] Optimize loadAccountDetails with promise.all

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#396]
https://github.com/KlimaDAO/klimadao/blob/2506edcd781a504c91e283d6cc410855b88c10c3/app/actions/user.ts#L17

1. Use console.time() to get a rough idea how long this takes right now.
2. Drop all the balance and allowance calls into one giant promise.all(). See the example here: 
https://github.com/KlimaDAO/klimadao/blob/4a2b6f259df11f25f094a2bca261bd626ae6dbf3/app/actions/app.ts#L40-L55
3. use Console.time() to see if this actually improves the total load time.
4. if not, report to me and let's figure out how to reduce the total number of RPC calls on initial app load. We may need to do things view-by-view (e.g. only fetch MCO2 on the mco2 bond view, and offset view)

**Comment by naiknareshh** [comment]
Hi @Atmosfearful, the performance of the network calls improved from 8510ms to 1895ms after dropping all the balance and allowance calls into one promise.all().

Let me know if this sounds desirable or if you have suggestions to improve this further.

**Comment by Atmosfearful** [comment]
@naiknareshh That's a great improvement, would you mind putting up a PR with just that change? Thank you!
