### ISSUE TITLE
Enhance /retirements/ index page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#402]
## Totals Retirement Page 

- URL: `https://www.klimadao.finance/retirements/<WALLET-ADDRESS>`

**Header**
- Title /h1: Carbon Retirements
- Subtitle: for beneficiary 0x1235 (address from URL)

**Content:**
- "They've retired XX tonnes of carbon"
- "They've got 21 Total retirements"
- "They've got XX Total tonnes claimed for NFTs"
- Breakdown: 0.0075 BCT, 1.1 NCT, 0.0003 MCO2 .....
- List all retirements for the given beneficiary
  - Ability to click one and navigate to the retirement: 
  URL: `https://www.klimadao.finance/retirements/<WALLET-ADDRESS>/<NUMBER-OF-RETIREMENT>`
  - Maybe some summary information about each retirement (tonnes, message, date?)
 
**Share Buttons**
- Copy URL
- Share on Social Media (what happens here when clicked?)
 
**Footer**
- Link to the index page from the app/#/offset view (perhaps from the card that shows retirement stats on the right hand column?)
- Same Footer as for the Single Retirement Page which includes all relevant text and Buttons ?

**Comment by ShimonD-KlimaDAO** [comment]
I would also suggest adding "share on social media" functionality. This could be extremely beneficial from a marketing perspective.
