### ISSUE TITLE
Retirement receipt blocked by Chrome pop-up blocker

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#412]
I ran a test retirement and got this :(
Maybe because it's a different domain?
![image](https://user-images.githubusercontent.com/88635679/168664329-55c7011f-8140-4599-b360-dc08284c0404.png)

As a workaround, I will remove the open-in-new-tab functionality and add a strong call to action in the modal which draws the user to click the button themselves.

**Comment by ladytrekker** [comment]
Yeah, that is a thing with window.open. I mentioned this in the PR description.
I like your refactoring with the simplified Modal. In the end an even much better UX 👍
