### ISSUE TITLE
Add Share On Twitter and Share On Linkedin buttons to retirement pages

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#418]
Just a super quick mock for the best place to put them, maybe a call to action text. We can figure out the implementation (it will probably be a hyperlink to twitter/linkedin prefilled with some generic text)

**Comment by jabby09** [comment]
@aarongillett here is the ticket for the share options in Design Needed state. When finished and design shared you can change the label to "design done"

**Comment by Atmosfearful** [comment]
Updated the description

**Comment by aarongillett** [comment]
I’d add these share buttons right at the end of the content, before the generic about Klima CTA. Let me know if that doesn’t make sense.

**Comment by aarongillett** [comment]
Here’s the design. Figma file here if needed: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=839%3A1647
Thanks for bearing with me :)
<img width="943" alt="image" src="https://user-images.githubusercontent.com/4157473/173859548-4a1fbce6-347f-499f-aacd-353444114413.png">
