### ISSUE TITLE
NextJS: Switching language should load same page

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#420]
## Problem

When switching the language on a subpage NextJS redirect to the Home page with the locale attached.
Instead, the user should stay on the same page, only the language should change

**Example:**
- Open `https://www.klimadao.finance/fr/buy`, 
- Switch the language to german 
- => loads the Home page `https://www.klimadao.finance/de` in german 
- Instead should load `https://www.klimadao.finance/de/buy`

**Comment by biwano** [comment]
> @biwano Assigning you because @Atmosfearful said you might be available for this ticket.

Cool
