### ISSUE TITLE
[github actions] Post message to Discord channel on failing builds

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#421]
## Description

With the current set-up of the Github actions we can detect when a Vercel build for Staging or Main failed.

- [ ] create a Discord Webhook
- [ ] add Webhook to Github settings
- [ ] Post message to specific channel (write a custom TS action for that eventually)

See the [discord docs](https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks)

Details TBD first

**Comment by jabby09** [comment]
@ladytrekker almost a year old, still want to tackle this or should we close?
