### ISSUE TITLE
[wallet] MetaMask: Catch "underpriced" error and show better error message

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#422]
## Problem

When trying to confirm an underpriced Offset => MetaMask rejects with the error code `-32603`

Currently, in this case the NotificationModal appears with a generic error message: "❌ Error: something went wrong..."

Let's improve the error message in this case and catch the error code/message in [`getStatusMessage`](https://github.com/KlimaDAO/klimadao/blob/80e738a48d57189349f36883e2eeedfe911b69f0/app/actions/utils.ts#L6-L34) and write a better Error text for the user.

See full JSON error here:

```JSON
{
    "code": -32603,
    "message": "[ethjs-query] while formatting outputs from RPC '{\"value\":{\"code\":-32603,\"data\":{\"code\":-32000,\"message\":\"transaction underpriced\"}}}'",
    "stack": "{\n  \"code\": -32603,\n  \"message\": \"[ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}}'\",\n  \"stack\": \"Error: [ethjs-query] while formatting outputs from RPC '{\\\"value\\\":{\\\"code\\\":-32603,\\\"data\\\":{\\\"code\\\":-32000,\\\"message\\\":\\\"transaction underpriced\\\"}}}'\\n
```

**Comment by jabby09** [comment]
@ladytrekker this is almost one year old, still an issue to keep around or close?

**Comment by ladytrekker** [comment]
Let´s close this!

And open another ticket for "Improving ConnectModal error messages" when we get reports that users are confused.
