### ISSUE TITLE
Add Poppins Google font tag for headings

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#424]
Designers want us to use Poppins

Design system here:
https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1126%3A639

This is required for the KI page #491 #493 #540 #550

* [ ] add the google font script tag to support Poppins and remove any unused sizes for Inter
* [ ] update the typography tags

**Comment by Go-Mori** [comment]
Poppins for all headings, menu items and buttons
Light (300) and Semibold (600) weights
Thks!
