### ISSUE TITLE
[App] Completely messed up style on Microsoft Edge

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#434]
Also, the entirety of the middle and right panes aren't loading at all.

![image](https://user-images.githubusercontent.com/99001851/169419064-e6906610-9b5e-493e-aed1-3e04d1b5e047.png)

**Comment by goatsOnDrugs** [comment]
I was unable to reproduce this on windows + edge. @ShimonD-KlimaDAO are you still seeing this?

**Comment by jabby09** [comment]
Almost a year old, have not seen any recent user reports about this. Closing.
