### ISSUE TITLE
Inverse Bonds

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#445]
Similar to Olympus, we will be implementing inverse bonds.
Input token will be KLIMA and the user gets back some other token
Redemption is immediate so there is no need for a Redeem tab

![image](https://user-images.githubusercontent.com/88635679/170081192-c82800f9-05df-438b-bbad-e18d48a8df10.png)

# TODO
* [ ] design mocks
* [ ] ABI / spec

**Comment by goatsOnDrugs** [comment]
@Atmosfearful we can close this, right?
