### ISSUE TITLE
Klima Infinity Landing Page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#446]
https://www.figma.com/file/6CUpojwfvdV4R3ACk85JYG/Landing-Page?node-id=627%3A1078

**Comment by ZernoKlima** [comment]
Mobile version is completed, Waiting for Ritaaka to do final review before handoff to Engineering.

**Comment by Atmosfearful** [comment]
@goatsOnDrugs has started work on this #493
