### ISSUE TITLE
Security review: signing & nonce implementation of pledges

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#449]
Just tagging @gord0b to do a quick sanity check of our implementation.

In order to edit a pledge, the client must `PUT` the newly updated pledge data, along with a signed message.

1. use ethers to verify the signature and extract the signer address
2. compare the signer address and the nonce to the data held in our database for that pledge
3. if correct, write to the database with the new data

All pledge data is public and available on any client, including the nonce. We only need to worry about preventing unauthorized updates.

API endpoint here:
https://github.com/KlimaDAO/klimadao/blob/staging/site/pages/api/pledge/index.ts

handler logic here
https://github.com/KlimaDAO/klimadao/blob/f123eb6823ceec8ac1c7aa8acc413fc62525f015/site/components/pages/Pledge/lib/firebase.ts#L43

And signature verification here:
https://github.com/KlimaDAO/klimadao/blob/f123eb6823ceec8ac1c7aa8acc413fc62525f015/site/components/pages/Pledge/lib/verifySignature.ts#L10

**Comment by gord0b** [comment]
https://www.klimadao.finance/api has 'access-control-allow-origin: *' set without any request method limitations.

![grafik](https://user-images.githubusercontent.com/34238250/170294124-814c3a49-ffb3-4034-8fab-894cca5e7ced.png)

https://www.klimadao.finance/api/block-rate is the only location that has 'access-control-allow-origin: *' limited to only GET request methods.

![grafik](https://user-images.githubusercontent.com/34238250/170294969-4089b48b-84ec-477c-85c6-c82ead008632.png)

**Comment by gord0b** [comment]
https://www.klimadao.finance/api/pledge - might be worth limiting 'pledge' to the below.

1: `'access-control-allow-origin: *'` to `'Access-Control-Allow-Origin: https://*.klimadao.finance'` so that the resource can be accessed only from *.klimadao.finance origin not by any origin.

2: Limit the methods to "GET, PUT",

          {
            key: "Access-Control-Allow-Origin",
            value: "https://*.klimadao.finance",
          },
          {
            key: "Access-Control-Allow-Methods",
            value: "GET, PUT",
