### ISSUE TITLE
[App] Make BigNumber values consistent across the codebase for token approvals

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#453]
The approval transactions have inconsistent amounts. Typically these should be set to effectively be infinite.

The staking contract uses 1000000000 gwei (1000 Klima) as a BigNumber. -> not sufficient
The bonding contract uses 1000000000 ether (1000000000 Klima) as a BigNumber. -> sufficient

These standards are inconsistent for other parts of the app as well:
https://github.com/KlimaDAO/klimadao/search?q=const+value+%3D+ethers.utils.parseUnits%28

**Comment by Atmosfearful** [comment]
Related to #9

**Comment by goatsOnDrugs** [comment]
@ladytrekker @Atmosfearful can we close this ticket bc the refactor is complete?
