### ISSUE TITLE
Design review of Summary Retirements Page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#455]
@aarongillett this is the current version of the summary retirements page in production: https://www.klimadao.finance/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06

This was done without a design using components available to the dev.

Can you please review this page and provide UI feedback and recommendations.

**Comment by aarongillett** [comment]
Great work! Some suggested improvements, mostly small:

**Carbon Retirements**
- [ ] Currently it’s difficult to get the beneficiary address in the shortened form. Could we add a copy icon after the address (turn the string and icon into a button) to easily copy the address?
- [ ] Replace “..” in shortened address with ellipsis character “…”
- [ ] Switch order of the “Retirements” and “Retired Assets” columns (tonnes retired is more important).
- [ ] Format retired assets as “65,201.25t” (add commas, remove space before t).

**Breakdown**
- [ ] Remove cloud icon (not sure an icon is helpful).
- [ ] Rename “Breakdown” to “Assets used for retirements”
- [ ] Remove “Tokens used for retirements”.
- [ ] Reduce padding between text title (currently “Tokens used for retirements”) and list of tokens below, as well as for the next table.
- [ ] Hide assets with zero balances.
- [ ] Add commas to number formatting for improved legibility.
- [ ] Reduce space between asset icon and number.
- [ ] Remove double space between asset count and token ticker (e.g. “543 BCT”).

**All Retirements**
- [ ] Remove person/tree icon (not sure an icon is helpful?)
- [ ] Remove “List of single retirements” I think this is self-explanatory.
- [ ] Add commas to number formatting for improved legibility.
- [ ] Reduce width of this table to match the width of the breakdown table above.
- [ ] Remove number count from the first column. I think these are unnecessary and a little confusing.
- [ ] Reduce spacing between asset icon and count.
- [ ] Remove double space between asset count and token ticker (e.g. “543 BCT”).
- [ ] Move date stamp to its own column (will make it easier to scan numbers and dates and we have the space).
- [ ] Horizontal dividers should match the lighter style in the breakdown list above.

**Acquire, stake, and get rewarded.**
- [ ] Add rounded corners to bottom of component.

**Comment by jabby09** [comment]
Thanks @aarongillett

**Comment by jabby09** [comment]
@Atmosfearful @ladytrekker Aaron completed the design review, recommendation provided. Over to you!

**Comment by ladytrekker** [comment]
Hi @jabby09 
Can you please point to the final designs in Figma (dark/light/mobile/desktop if available)?
Thanks a lot 🙏

**Comment by ladytrekker** [comment]
Ah I see, there are no designs. 
The list above is the final review.

**Comment by jabby09** [comment]
That's right, you got it. There was never an initial design for this page so the finished page (example = https://www.klimadao.finance/retirements/0x087a7afb6975a2837453be685eb6272576c0bc06) is the design :)

**Comment by ladytrekker** [comment]
@aarongillett Thanks for the feedback 🙇‍♂️ 

Just for clarification and information which impact the following changes will have:

> [ ] Replace “..” in shortened address with ellipsis character “…”

This will change the shorten addresses everywhere in Site and App on all pages and Apps from ".." to "..."

> [ ]  Remove number count from the first column. I think these are unnecessary and a little confusing.

The number indicates the number of retirement (first retirement, second retirement) and so on.
We added those numbered list because each single retirement has exactly that number in its linked URL. 
The linked URL to the single retirement appears also after each successful offset you did here: https://app.klimadao.finance/#/offset 
=> "See your successful offset here: `https://www.klimadao.finance/retirements/<YOU-WALLET-ADDRESS>/<YOUR-NUMBER-OF-RETIREMENT>` "

**Comment by Atmosfearful** [comment]
@ladytrekker moving to `...` should be fine everywhere

3 different people have asked about the numbers so I'm OK with removing them. We can implement a sort dropdown at some point:
```
date (newest)
date (oldest)
quantity
```
