### ISSUE TITLE
Support project name lookup for non-verra retirements (UBO/NBO)

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#459]
This pertains to the project information displayed in the retirement page https://www.klimadao.finance/retirements/0x293ed38530005620e4b28600f196a97e1125daac/2

We currently use a verra API endpoint to look up the project name for a given projectID: https://github.com/KlimaDAO/klimadao/pull/447

I believe NBO and UBO have already started allowing bridging from non-verra registries. I don't know if any retirements have been done with those. If retirements are happening already, then we need to enhance this ASAP.

**If we can confirm the subgraph is properly indexing these non-verra retirements, then the solution should be straightforward:**
* [ ] If token is UBO or NBO, always use the subgraph `retirement.offset.name`
* [ ] Otherwise assume it's a verra retirement

This will be revisited again when BCT/NCT start supporting non-verra retirements (timeline unknown)

**Comment by ladytrekker** [comment]
> * [ ]  If token is UBO or NBO, always use the subgraph `retirement.offset.name`
> * [ ]  Otherwise assume it's a verra retirement
> 

If we then always take the subgraph offset project name for UBO and NBO
where should we link to? Where is the page for the project then if this is not a Verra project?

**Comment by Atmosfearful** [comment]
@ladytrekker According to `carbon.klimadao.finance` everything in the pools is still Verra. So we don't need to tackle this yet.

But for future reference:
The subgraph should expose a property which says which registry the project was on.
GS would link here https://registry.goldstandard.org/projects?q=&page=1
ACR here https://acr2.apx.com/myModule/rpt/myrpt.asp?r=111

**Comment by jabby09** [comment]
Action was won't fix and no bridging currently. Can return to this requirement when necessary.
