### ISSUE TITLE
Migrate from walletlink to @coinbase/wallet-sdk

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#462]
The npm package has been moved to here:

https://github.com/coinbase/coinbase-wallet-sdk

In our app we use it here:
https://github.com/KlimaDAO/klimadao/blob/990873c5734f10d53ee6b43306e7e22df457f24d/app/components/views/Home/index.tsx#L74

And here:
https://github.com/KlimaDAO/klimadao/blob/e783cd6ee3e1201e88b26cd39bd16daaedfb4bcf/site/hooks/useWeb3/index.tsx#L30

**Comment by goatsOnDrugs** [comment]
@Atmosfearful I think we can close this one
