### ISSUE TITLE
Update price calculations to avoid BCT/USDC pool

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#475]
We are planning to deprecate the BCT/USDC pool, so any price calculations done using that pool need to be switched over to the BCT/KLIMA => KLIMA/USDC route instead

**Comment by Atmosfearful** [comment]
This is higher prio because we want to deprecate the pools

**Comment by kaxline** [comment]
Still kind of exploring this part of the app, but it looks like this would be the method to be concerned about, correct?

https://github.com/KlimaDAO/klimadao/blob/eaff5d85bb03d378e2c50803e36f9750fb1435cc/app/actions/bonds.ts#L94

And that looks like it's using the KLIMA/BCT address.

And then it looks like even if you input `bct_usdc_lp` into the `getMarketPrice` method, it still routes to that same method and so uses KLIMA/BCT as well:

https://github.com/KlimaDAO/klimadao/blob/eaff5d85bb03d378e2c50803e36f9750fb1435cc/app/actions/bonds.ts#L206

Do I have that right? Anywhere this may be a concern?

**Comment by 0xAurelius** [comment]
hmm yeah it looks like this has already been addressed, i can't think of anywhere else it might appear and searching for "usdc" in the repo doesn't seem to lead to any other uses of the BCT/USDC pool

we should just open a PR to remove the reference to the `bct_usdc_lp` since we won't need it anymore and the pool will be tiny after all DAO LP is pulled

**Comment by Atmosfearful** [comment]
@kaxline go ahead and remove all references to bct_usdc_lp including the bond!

**Comment by kaxline** [comment]
@0xAurelius @Atmosfearful Should we wait to remove the BCT portion of this method until the LP has been pulled:

https://github.com/KlimaDAO/klimadao/blob/17fcfad12c9ca0695d3518931e93a3db5a362be1/lib/utils/getTreasuryBalance/index.ts#L41

**Comment by 0xAurelius** [comment]
Ah yeah let's maybe do a separate PR for deprecating this, or just leave this PR unmerged until we have pulled the LP

I just didn't want us to move forward with dissolving the LP unless we are sure nothing will break when we do. This particular usage shouldn't break because the pool will still exist, there just won't be any LP held by the treasury so this will go to 0.

**Comment by kaxline** [comment]
@0xAurelius Ok cool, I just created what I think is a comprehensive merge that can wait until the treasury is ready.

**Comment by Atmosfearful** [comment]
@kaxline if you leave `getTreasuryBalance` in as per my change request on #651 we can go ahead and merge now. When the LP is pulled the new total should be reflected immediately, no coordination needed. Then after that we can do another PR to remove those last few lines of code

**Comment by jabby09** [comment]
@kaxline are you currently working on this one? Are we close to having PR's ready?

**Comment by kaxline** [comment]
@jabby09 @Atmosfearful I thought this was ready to merge? We discussed on our sprint planning call. If so, am I the one who is supposed to merge?
