### ISSUE TITLE
Add banner advising users to check URL

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#48]
We should have a banner that reminds people to check the URL and prints our official URL

**Comment by Atmosfearful** [comment]
Great idea! I'll get this on the designers pipeline too, should be a really quick task.
Do you have any examples of this warning on other dapps besides olympusdao?

I'd suggest:
"⚠️Verify the URL and bookmark this page! **klimadao.finance** is the only official domain"

As a full-width top-of-page banner, that appears once every session, and is dismissible.

Weakness here is, the banner doesn't appear on the phishing site, but it could be good for getting people in the habit I guess.

**Comment by ladytrekker** [comment]
I can take look into that 👋 

As far as I can see there are no session cookie handler so far.
Will have to read up on that first with Next.js
