### ISSUE TITLE
Retirement Receipt Enhancements

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#481]
@ShimonD-KlimaDAO did a QA pass on the Retirement Receipt page(s) and documented feedback in [Discord](https://discord.com/channels/841390338324824096/967377329171099648/984625034356199494).

Adding the feedback as a task list.

Testing was done against this [retirement receipt page](https://www.klimadao.finance/retirements/0x293ed38530005620e4b28600f196a97e1125daac/2).

**Comment by jabby09** [comment]
- [ ] I would suggest changing the following string:
"The following projects were retired. Click a project title to learn more about it."
To:
"The tonne(s) retired originated from the following project(s). Click on the project title to learn more."

- [ ] When I input my KNS domain, it shows my KNS domain on the page. When I input the underlying address, it shows the same data, but my address is not resolved to my KNS domain. Compare the two strings under "for beneficiary" below. Same exact issue for ENS.
https://klimadao-site-git-kns-ens-retirement-klimadao.vercel.app/retirements/shimond.klima
https://klimadao-site-git-kns-ens-retirement-klimadao.vercel.app/retirements/0x6F9F81eb4f54512Be8c91833783ee0074328E062

- [ ] I think "Assets Used for Retirements" should be changed to "Retirement Totals By Asset" - it's more accurate.

- [ ] When there are no retirements, there is a blank frame under "Assets Used for Retirement", inconsistent with "No Retirements Found" below it (see screenshot)
![image](https://user-images.githubusercontent.com/103535195/173434112-6160cbdc-c804-4168-b79b-d56831152a4f.png)

- [ ] I think only "here" should be a link. It looks a bit off to have the entire string be a link, and the new line spacing looks off as well. Further to this, Aaron suggested we go further and remove any “click here” text as its superfluous and not everyone uses a mouse. This can just be “{Learn more} about the projects that back…”
![image](https://user-images.githubusercontent.com/103535195/173434279-6d812439-3647-44ee-9af4-b0ed567c16d1.png)

**Comment by Atmosfearful** [comment]
I left some edits to your comment Jabby to clarify requirements. I tore out the KNS one to create a separate ticket as there is some other KNS work to be done here
