### ISSUE TITLE
Pledge Dashboard Touchups and Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#489]
1. (low-medium) I don't see Torus integration like we have in our dapp. If the staging build doesn't have the latest updates, I would consider doing a rebase of the pledge branch onto master to make sure nothing new breaks. 

2.  (low) I'm not a fan of how the cursor flashes in the middle of the search text. This is the first thing users see before connecting their wallets, so stylistically important. Also, capitalization seems incorrect. Finally, when I connect my wallet I expect to be redirected to my pledge page with a search option - not to have to copy-paste my address to get to my page.
![image](https://user-images.githubusercontent.com/99001851/173714722-93fb25b6-46bc-4de2-9ac6-395702c54c6e.png)

3. (low-medium) I don't see my KNS domain nor my KNS profile pic. Can those be pre-filled when the wallet is connected and has a KNS domain? Again this might be related to the branch needing to be rebased onto master.
![image](https://user-images.githubusercontent.com/99001851/173714983-c082fd6e-bace-47c6-8eb1-c323a095e4d3.png)

4. (Medium) See image in (3). I would suggest to stick to the same capitalization style (all caps) across the page. If we don't, the title capitalization is still wrong according to pretty much all grammar style standards ("Offset" not "offset"). Also, the past tense feels a bit off. See example:
https://capitalizemytitle.com/style/MLA
![image](https://user-images.githubusercontent.com/99001851/173715275-8b7ffd3e-d47b-4e7b-b85a-f9cfbe14309d.png)

5. (low-medium) Why is this italicized and in quotations? I would suggest removing the text entirely if there is no pledge/methodology to make it appear cleaner, or at least removing the quotations. Also, the "Methodology" icon of the verified person doesn't really make sense to me.
![image](https://user-images.githubusercontent.com/99001851/173715434-23589280-564d-451a-ae64-4c90b864cac1.png)
![image](https://user-images.githubusercontent.com/99001851/173715721-119abf2a-977d-45a0-a0df-c9354aa87d50.png)

6. (low-medium) Where is UBO, NBO, NCT, and wsKLIMA? Also, I would suggest removing "Holding" or just putting it in the title. When it appears next to each asset it's a bit crowded and also almost looks like there's another option that can be chosen in lieu of "Holding".
![image](https://user-images.githubusercontent.com/99001851/173715617-7968dab8-9798-43d8-8711-7834f37bd4b6.png)

7. (low-medium) When there isn't a footprint calculation, this area gives the appearance like it's loading:
![image](https://user-images.githubusercontent.com/99001851/173715861-585cc35e-867e-4b75-bc1c-5303a17e5994.png)

8. (low) Before I saw this description, I thought that the "METHODOLOGY" text was to describe a strategy to offset my footprint. Turns out it's the method by which I calculated my footprint. I think this is a bit confusing.
![image](https://user-images.githubusercontent.com/99001851/173719639-954092e1-3f6b-423f-8e51-191375020097.png)

9. (low-medium) The METHODOLOGY section has a 280 char limit, whereas the Footprint section doesn't have a limit - I tried putting in a really long string.

10. (low) I can't screenshot this, but the portions of the pie chart are rounded to the nearest 1%. I think this should have at least 1 or 2 decimals.
![image](https://user-images.githubusercontent.com/99001851/173717009-352c5862-6c1f-4dad-9163-567c623b33e5.png)

11. (low) The "|" delimiter should be aligned vertically.
![image](https://user-images.githubusercontent.com/99001851/173717167-ddf7412f-0ed4-4293-8d72-69aad8f28695.png)

12. (medium) Image not loading (https://www.citypng.com/public/uploads/small/51611436216ubmzusk7cbsdwpdjfmmxvbwplr3mhi0eqruqwa8jhflyqpjeitsgdygluzb00f8g3jecrvltoylopgx6i06oy4qzoacz72vzutyg.png):
![image](https://user-images.githubusercontent.com/99001851/173717239-04614356-c6ee-45ab-9657-23fadbf1ee9f.png)

13. (low-medium) See image in (12) - I would suggest that if the pledge is met, just write "100% OF PLEDGE MET" or "PLEDGE MET" rather than giving a 1235% figure. 1235% just looks strange and doesn't make sense linguistically. A ceiling of 100% would resolve this.

14. (low-medium) The following as well as the PLEDGE section are still in quotation marks and italicized even after I input my pledge, which doesn't look clean (related to 5):
![image](https://user-images.githubusercontent.com/99001851/173717548-7076ce51-ad06-4457-9515-6766a45be2e6.png)

15. (low-medium) I added a footprint category with 0.001 tonnes and I get 0%. Since the percentages are rounded to the nearest integer (see 10), if a company has a category with 1000 tonnes but their footprint is 300,000 tonnes, It would look strange to have "1000 | 0%" there.
![image](https://user-images.githubusercontent.com/99001851/173717854-c0440150-522b-4e01-8e3f-41a5c94cfead.png)

16. (medium) Last footprint category cuts off (with ...). I feel like this is an important section where companies would want to show exactly what they wrote. For example, there could be two long categories that end with "a" and "b" and would be indistinguishable in the current dashboard given the existing char limit. Perhaps there should be an option to expand the section?
![image](https://user-images.githubusercontent.com/99001851/173718515-959b7763-6bcd-4d4b-8623-317d21c9582d.png)

17. (medium) I don't see the "METAMASK" connection option on mobile.

**Comment by sy-zygy** [comment]
Thanks for the feedback, I don't see any of these as showstoppers so we should proceed with pushing to production and then proceed to iterate.

1. Pledge should support Torus like the dApp

2-4. Agree

5. Perhaps we can change this up but the idea is to communicate that this dashboard should be claimed and filled in. Perhaps we can remove placeholder text and add a banner saying something like 'this wallet hasn't made a pledge, if you own this wallet, connect now to claim" -- as for the icons, I agree they don't really match but we should keep them until we have something better to replace them

6. Agree, holding is redundant

7. Again, we want to communicate that this is a possible area that would have data if it were claimed but it does look like it's loading, perhaps we need a 'no data's label somewhere

8. The text description seems adequate to explain what it is

9. Methodology should support longer text, we anticipate links to PDFs etc.

10. I don't think we need another decimal

11. Agree

12. Looks like a bug

13. Agree, perhaps if it's greater than 100% we put '>100%'

14. Agree, having the pledge italicized and in quotes makes sense, but the other fields including methodology don't really need to be in quotes and italicized

15. Good point, and since the font is smaller on the categories it makes sense to support 2 more decimals

16. Perhaps this can be handled by a tooltip on rollover that shows entire label but space is limited  regardless

17. May be bug

**Comment by Atmosfearful** [comment]
@ShimonD-KlimaDAO 17. is a built in 'feature' of web3modal-- if it doesnt detect window.ethereum, it doesn't show the metamask option. I believe if you tried this via the metamask in-app browser, it should appear.

**Comment by 0xAeterno** [comment]
- [ ] Add translations to pledge dashboard
- [ ] Attempt to treeshake recharts library

**Comment by jabby09** [comment]
@0xAeterno what is the status of the items in this ticket? thanks

**Comment by Atmosfearful** [comment]
Also @ShimonD-KlimaDAO  As discussed in sprint planning today, please let us know if you still have outstanding feedback or see any other high prio improvements here

**Comment by ShimonD-KlimaDAO** [comment]
1. I tried editing my pledge to change image and add decimals and long string, and received an error:
![image](https://user-images.githubusercontent.com/99001851/184515876-f96244f3-985a-484a-8497-a1931dfa4777.png)

2. The image is different for KNS domain and raw address even though they point to the same pledge.

Address:
![image](https://user-images.githubusercontent.com/99001851/184516398-d3b35a60-21d5-4af9-925a-72d89c8a31b3.png)

KNS:
![image](https://user-images.githubusercontent.com/99001851/184516441-4992b3e7-a129-4dbd-92e2-e5a2fa85cf28.png)


3. Regarding "9" in the original description, is there a way we can change the bottom right expansion to something more attractive?
![image](https://user-images.githubusercontent.com/99001851/184516172-7d960390-5e2b-4749-bf8c-30ebb806d469.png)

4. Delimiters are still not vertically aligned, and the text wrapping overlaps with the number:
![image](https://user-images.githubusercontent.com/99001851/184516369-84012668-32d9-419d-8503-eb038d7e0cc2.png)


PS - I love the new design with the ownership over time!
![image](https://user-images.githubusercontent.com/99001851/184516490-bf4a4743-f6fe-4dbb-a0e8-2f94b5dab358.png)

**Comment by 0xAeterno** [comment]
@ShimonD-KlimaDAO @jabby09 

1. I think you may be running into a new validation we've put in place to limit the string length of footprint category names. There is a PR up that aims to surface these errors to the user if they've been affected by the changes in form validation (https://github.com/KlimaDAO/klimadao/pull/635)

2. Atmos and I agreed on only resolving a user set domain profile picture if a kns/ens domain is in the url. 

3. The textarea expansion icon is pre-determined by the browser.

4a. We're not aligning the delimiters as the space on that is already quite limited. 
4b. The overlapping text scenario above is an edge case as the values a both intentionally long. IMO the limiting factor here is the design, it's tricky to strike the balance without wrapping text across multiple lines :/

**Comment by jabby09** [comment]
@0xAeterno @Atmosfearful hey guys, is this issue essentially closed? alternatively, if not, maybe we should create new issues per enhancement?

**Comment by 0xAeterno** [comment]
> @0xAeterno @Atmosfearful hey guys, is this issue essentially closed? alternatively, if not, maybe we should create new issues per enhancement?

I think that's a reasonable decision @jabby09. I think we can raise tickets to address if they come up again
