### ISSUE TITLE
Update Landing page to funnel users towards Klima Infinity

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#499]
Beyond just "infinity" at the top nav,
1. What can we do to funnel viewers of the landing page into the klima infinity journey?
- Perhaps just the nav is fine?

As discussed on calls the v1 MVP journey will be:
1. arrive on KI landing page
2. click the CTA and read an explainer (eventually a modal with options) #
3. calculate footprint with an external partner
4. return to dapp and offset

Similarly, I created this ticket: #500

@Go-Mori if you could invest some brainpower into these questions and make suggestions I'd appreciate! Text-only or figma mocks are fine.

**Comment by Go-Mori** [comment]
hi there. I'm doing the discovery in this Figma file:
https://www.figma.com/file/YM245UOgve7XknodVL9IX1/Navigation-discovery?node-id=0%3A1
Let's all add comments there?

**Comment by jabby09** [comment]
@Atmosfearful I think this ticket is now a duplicate to #597

**Comment by jabby09** [comment]
This is now redundant / dregs as the functionality has been added.
