### ISSUE TITLE
Invite users to create a Pledge

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#500]
Similar to #499

As discussed on calls the v1 MVP journey will be:

1. arrive on KI landing page
1. click the CTA and read an explainer (eventually a modal with options) #
1. calculate footprint with an external partner
1. return to dapp and offset

Where in this journey do we invite them to create a pledge and showcase their footprints?

**Comment by jabby09** [comment]
Deprecated by Carbonmark, Infinity is going away.
