### ISSUE TITLE
Blog: Content Filtering

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#512]
Request for implementation of a partitioned Blog – featured posts vs. the rest. The rest can be filtered. 

1. We need our content to be easier to find, navigate, and consume 
2. We need to prepare for on-site SEO project – where we’ll be writing Blogs that we don’t want mixed in with our Thought Leadership pieces

Task definition in Notion: https://www.notion.so/klima-dao/Blog-Content-Filtering-c719a5da309c4084a8aecca597de19c3

## Requirements & Design Inspiration

- Ecosystem Component: Klima Infinity (Product), Protocol, Partnerships
- Type of Content: Press Release, User Guide, Thought Leadership / Deep Dive, Announcement, Emissions Analysis, Policy, Video, Podcast
- Theme / Tag / Keyword: NFTs, C3, etc
- Examples:
    
    [[Gemserv](https://gemserv.com/our-thoughts/?sector_category=low-carbon&thought_category=thought-leadership-papers&region=)](https://gemserv.com/our-thoughts/?sector_category=low-carbon&thought_category=thought-leadership-papers&region=) 
    
    [[Warhammer](https://www.games-workshop.com/en-WW/Warhammer-40-000?N=430568322+2769960934&Nr=AND%28product.locale%3Aen_WW_gw%2Csku.siteId%3AWW_gw%29&Nrs=collection%28%29%2Frecord%5Bproduct.startDate+%3C%3D+1651742640000+and+product.endDate+%3E%3D+1651742640000%5D)](https://www.games-workshop.com/en-WW/Warhammer-40-000?N=430568322+2769960934&Nr=AND%28product.locale%3Aen_WW_gw%2Csku.siteId%3AWW_gw%29&Nrs=collection%28%29%2Frecord%5Bproduct.startDate+%3C%3D+1651742640000+and+product.endDate+%3E%3D+1651742640000%5D)
    
    [[Chainlink Blog](https://blog.chain.link/)](https://blog.chain.link/)
    
- Similar to Chainlink Blog, have a section for “101” / beginner content. This is a repository that we can pull in selected posts, that are best suited for beginners
- Similar to Chainlink Blog, along the vertical / side bar of the page, insert filters:
    1. Category (Product / Protocol / Partnerships) 
    2. Type (Press Release, Video, etc…) 
    3. Tag (# - like, NFTs, C3, ReFi101, etc.)

**Comment by jabby09** [comment]
@Atmosfearful I'm pretty sure the design for this is done, link above. Upon your review I believe this could now be assigned to a dev.

**Comment by Atmosfearful** [comment]
Great, thanks guys! Closing in favor of #534 where I will flesh out the nitty gritty details
