### ISSUE TITLE
LoveLetters: Improve Share Feature

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#513]
Requirements and design inspiration from [[discord thread](https://discord.com/channels/841390338324824096/964698337230086174/989582461556105276)](https://discord.com/channels/841390338324824096/964698337230086174/989582461556105276).

- Improve share feature for LoveLetters to surface the actual loveletters card as a PNG alongside the polyscan transaction details. (current state below)

![Image](https://user-images.githubusercontent.com/103535195/175542175-c8fb94a2-9ef1-47a8-b841-8d4c6daedfc4.png)

**Comment by jabby09** [comment]
@Atmosfearful 

1. Does this task need a design first or is it pure dev work? 
2. On the dev side, is this happening on the Wix end?

**Comment by Atmosfearful** [comment]
This is purely Wix work, I have no control over this at the moment and don't know what Wix supports-- should be possible though. We would need to update the `<meta>` tags in html to point at an image, examples in our code here: https://github.com/KlimaDAO/klimadao/blob/f272b23253fc3cec39d157cd906458b07a0d44ca/app/components/PageHead.tsx#L46

**Comment by jabby09** [comment]
Not doing any more active feature dev for LL.
