### ISSUE TITLE
`postinstall` script not running on Vercel builds

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#518]

**Comment by ladytrekker** [comment]
Here was the fix:
https://github.com/KlimaDAO/klimadao/pull/517

Do not run important scripts in postinstall because Vercel might use a former cache for the installed module and doe snot run postinstall again.

Closing

**Comment by Atmosfearful** [comment]
Ohhh that makes so much sense thank you @ladytrekker 

Minor side effect of #517 I notice is now devs need to run `npm run compile-strings` once when they clone the repo.

**Comment by ladytrekker** [comment]
Actually the postinstall should still work:

- clone the repo
- npm install which runs postinstall
- => all lingui JS files are compiled for App & Site

I just tested it.
Let me know if you experience something else?
