### ISSUE TITLE
Retirement / Offset - Selective Retirement - Advanced Filters

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#521]
The overall design vision and UX for selective retirement is to allow a user to use a filter interface to explore and select specific projects; see the quota of available tonnes based on those selections, and auto fill the retirement tool fields once the user has made their selections.

See Notion roadmap bet for more details and requirements: https://www.notion.so/klima-dao/Retirement-Offset-Selective-Retirement-Advanced-Filters-ebd9fa3e15024fc58500eb981a355b2a

Text based design is here: https://www.notion.so/klima-dao/Text-Based-Design-73a5f96ebffd45fb8e6b4bac47352908

**Comment by jabby09** [comment]
@Atmosfearful Iteration #2 for review:

https://www.figma.com/file/SWBWzyejzFBNOSgH2ghQIN/Projects?node-id=0%3A1 

Also as a prototype: https://www.figma.com/proto/SWBWzyejzFBNOSgH2ghQIN/Projects?page-id=0%3A1&node-id=135%3A932&viewport=-12423%2C7111%2C0.9&scaling=min-zoom&starting-point-node-id=135%3A932&hide-ui=1

**Comment by jabby09** [comment]
@Atmosfearful iteration #3 for review:
https://www.figma.com/file/SWBWzyejzFBNOSgH2ghQIN/Projects?node-id=0%3A1#234445082

There is a prototype in there as well (flow 2)

**Comment by jabby09** [comment]
@0xAeterno this is the latest figma file on this: https://www.figma.com/file/SWBWzyejzFBNOSgH2ghQIN/Projects?node-id=284%3A1908#241210951

**Comment by Atmosfearful** [comment]
@theprofessora is this latest iteration ready for feedback?
https://www.figma.com/file/SWBWzyejzFBNOSgH2ghQIN/Selective-Retirement?node-id=359%3A2097

**Comment by jabby09** [comment]
hey @0xAeterno just confirming you are back working on this feature as your top priority?

**Comment by 0xAeterno** [comment]
@jabby09 Yup just about to after one small ticket related to caching on /pledges

**Comment by jabby09** [comment]
Testing this preview link: https://klimadao-app-git-advanced-selective-retirement-filters-klimadao.vercel.app/#/offset

**Comment by jabby09** [comment]
@0xAeterno QA feedback package #1:

- [ ] The **Pay with** and **Select carbon offset token** to retire options in the form need to be reversed as per the design, i.e. selecting the carbon offset token comes first and pay with option comes last
- [ ] For Default option, need to add "This option avoids paying extra fees." to the content block below.
![Image](https://user-images.githubusercontent.com/103535195/202774800-223bd4c0-97a9-4aa4-acf7-feed8f346aac.png)

**Comment by 0xAeterno** [comment]
@jabby09 actioned those two feedback points!

**Comment by ShimonD-KlimaDAO** [comment]
@0xAeterno @jabby09 

Initial QA is summarized in #800 .

**Comment by ShimonD-KlimaDAO** [comment]
Left additional comment on #800
