### ISSUE TITLE
[bonds] Bonding Redeem and Autostake does not work

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#530]
I have some leftover redeemable Klima from an old BCT bond on a testing wallet.
I tried redeeming and autostaking, and it causes a failure. It says there's an RPC issue, but the issue only happens when checking the autostake box. 
Just redeeming by itself triggers a metamask popup, but when including the autostake checkbox there's an immediate failure.

This is low priority since regular bonds are all disabled anyway right now.

Hopefully this screenshot provides all the necessary context, but please let me know if more context is needed. Perhaps there's not enough Klima allowance for the staking contract?

![image](https://user-images.githubusercontent.com/99001851/179099953-b030e1f5-fd02-46dd-b50b-16349385d2a9.png)

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO this issue was created last July and does not look like any work has happened on it, can you confirm this is still an issue and what would be the priority?

**Comment by jabby09** [comment]
[shimon]
It's still an issue but very low priority since we don't have bonds open
