### ISSUE TITLE
Create KlimaDAO branded PDF receipts for retirements

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#531]
# Summary
Customers are asking for old-school PDF certificates similar to those created by the Verra registry.
The original plan was to get these from the underlying bridge (c3 or toucan). But we don't want to wait anymore.
Now we think it makes sense to generate a KlimaDAO specific one.

# PDF Requirements
See design https://www.figma.com/file/RtYPQewQkz4RENj81ugUnc/PDF-Certificate?node-id=0%3A1

# Technical Requirements
- Nextjs API endpoint that accepts `address` and `index` and responds with a PDF download
- Cache response for 1 day
- Use a lightweight JavaScript PDF generator library for server-side pdf generation, like `JSPDF` or `PDFMake` or `PDFKit`
- "Download PDF" button on all retirement pages (where the "coming soon" button is)

**Comment by jabby09** [comment]
@Atmosfearful here is the figma file: https://www.figma.com/file/RtYPQewQkz4RENj81ugUnc/PDF-Certificate
