### ISSUE TITLE
New Nav header + mobile menu

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#532]
The current header is not scaling as we increase the number of products and landing pages.
@Go-Mori has completed a design  https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1133%3A2881

This is a blocker for completing work on the upcoming Resources section #534, but we can start on both in parallel.

Edit: This is ready to go! We are not implementing this in the dapp or /pledge pages yet.

**Comment by jabby09** [comment]
https://www.figma.com/file/YM245UOgve7XknodVL9IX1/Navigation-discovery?node-id=2%3A343#228527672

**Comment by Atmosfearful** [comment]
@Go-Mori @jabby09 two things need to be resolved that I'm aware of:
1. my comment here https://www.figma.com/file/YM245UOgve7XknodVL9IX1?node-id=2:343#230043438
2. mobile version of the nav!

**Comment by Go-Mori** [comment]
Moved to the design library:
https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1126%3A671

**Comment by jabby09** [comment]
@Atmosfearful I think the design for this is now done and can be handed off to a dev.

**Comment by ladytrekker** [comment]
## Questions

- How does the toggled navigation look like on Mobile when clicking on the Hamburger Menu icon?
- Where is the "change language" button on Mobile navigation now?
- How does the opened "Languages" menu look like?
- It it possible to get all states for the "Inifinity" page too as many colors are different on that page?


### Infinity
<img width="1272" alt="Bildschirmfoto 2022-07-29 um 15 50 40" src="https://user-images.githubusercontent.com/95881624/181775398-da8efd23-001b-404b-874f-32a1ed38601b.png">

**Comment by Atmosfearful** [comment]
> Moved to the design library: https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1126%3A671

@ladytrekker I believe this answers all your questions, here is the mobile view:
https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1133%3A2881

Assume that the language dropdown uses the same exact menu components and colors as the main one. The only difference for infinity page is that the button is swapped out for the blue one

**Comment by Atmosfearful** [comment]
> - How does the toggled navigation look

You can see here https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=1133%3A2881

> - Where is the "change language" button on Mobile navigation now
> - How does the opened "Languages" menu look like?

Also in the mock above. I would say we try just using the same language popper in there, and see how it looks. Is this what you intended @Go-Mori ? I left a comment in figma too.

> It it possible to get all states for the "Inifinity" page too as many colors are different on that page?
Good question, the main difference is the blue button. @Go-Mori Do we want to re-use the blue for the menu hover as well? Or do we want to keep the green from the light mode mock you gave us above?

**Comment by Go-Mori** [comment]
> Also in the mock above. I would say we try just using the same language popper in there, and see how it looks. Is this what you intended @Go-Mori ? 
Yes please @Atmosfearful

**Comment by goatsOnDrugs** [comment]
@Atmosfearful this was design reviewed and approved
