### ISSUE TITLE
[seo] Submit KlimaDAO App section as TWA to App Stores to gain SEO Traffic and start competing

### ISSUE THREAD

**Issue by ArchimedesCrypto** [KlimaDAO/klimadao#548]
##### **Summary**

Update the site manifest.json to include a valid TWA serviceWorker.js so that we can submit it as a TWA to Google Playstore/iOS Store/Microsoft Store without having to build native apps. or refactor into react-native.

##### **Motivation**

With the advancement of the App in its current form and the ability for Fiat to Crypto ramps with wallets that enable SSO via Web2 means. The app is in a state that can be shipped onto the App stores as a TWA. Benefits of this are 

* TWAs update in realtime as the webApp does so no need to maintain an app CI/CD, same build pipeline works
* Can start to compete against Mobile Native offsetting apps. (ex Klima.com, Earth Hero, Decarbon)
* Additional SEO and Backlinking to KlimaDAO
* More exposure to non-native crypto users and ability to garner feedback and refine the user journey

Cons of this proposal

* TWAs are technical and prone to sometimes breaking if devs are unaware of its existence (will need an monitor setup)
* Will require having a Dev account on google, microsoft and ios
* App stores have little experience with dApps as TWAs and in short sometimes prematurely ban them
* TWAs are still a new experience, and few devs know how to work with them 

Use this issue to discuss

**Comment by kaxline** [comment]
I love this idea. Let me know how I can help.

Maybe we could identify super stable old commits to safely base the app off of so that it's not generated from the latest? That might give us the ability to move quickly on web and selectively push out new versions to the app stores.

Also, maybe coming up with a regular release schedule would help us book reliable QA for a specific time.

**Comment by jabby09** [comment]
@Atmosfearful this is old, maybe it was done.
