### ISSUE TITLE
[App] Mobilum Swap Error When Fetching Prices

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#549]
Lots of users have been reporting an issue with Mobilum. This should be treated as high priority since it's preventing less technical US users from buying Klima.
I found that the issue only occurs when selecting "Swap Klima". It looks like there's an issue in the widget when it tries to fetch the Klima price in USDC.

"Swap Klima" selected:
![image](https://user-images.githubusercontent.com/99001851/180878124-3edb4999-0709-4eb8-aeab-f20c0530fe51.png)

"Swap Klima" not selected:
![image](https://user-images.githubusercontent.com/99001851/180878183-b0c6a8ed-d7d6-478e-ab11-6e64ad24c960.png)

**Comment by Atmosfearful** [comment]
@ShimonD-KlimaDAO mobilum team says this is fixed now. Can you confirm on your end?

**Comment by ShimonD-KlimaDAO** [comment]
@Atmosfearful this is now resolved, thanks. Closing.
