### ISSUE TITLE
Reusable Social Proof Feature Section

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#554]
## Description

This PR https://github.com/KlimaDAO/klimadao/pull/550
as well as this PR https://github.com/KlimaDAO/klimadao/pull/538
integrate a "Featured On" Social Proof Section.

As soon as both PRs are merged to staging
=> Let's create a re-usable component for this section and use this in both pages "Home" and "Infinity"

<img width="927" alt="image" src="https://user-images.githubusercontent.com/97446324/181396619-f9644da0-8636-4f38-a544-02c1c17e6409.png">

**Comment by 0xAeterno** [comment]
Hey @goatsOnDrugs, hope you don't mind me taking this ticket.
Needed this piece completed so I can start work on the pledges landing page :)
