### ISSUE TITLE
Site Infinity: Desktop Navigation tweaks

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#556]
## Description

The active state for the Infinity page's desktop navigation should be green
and the links are in CamelCase

- [ ] If page is "infinity" => give the active state for the Desktop navigation item "klima-green"
- [ ] If page is "infinity" => render navigation links in CamelCase not in UPPERCASE
- [ ] ensure that this only applies for the navigation on Infinity

Relates to https://github.com/KlimaDAO/klimadao/issues/532

#### See screenshot from Figma:
<img width="951" alt="Bildschirmfoto 2022-07-29 um 15 02 59" src="https://user-images.githubusercontent.com/95881624/181766413-7b678dc7-a181-4646-9681-9eb4b5aecc48.png">

**Comment by Atmosfearful** [comment]
Closing in favor of the new nav work! I will create an issue ticket for it rn
