### ISSUE TITLE
Site Infinity: Mobile Navigation tweaks

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#557]
## Description

The Infinity page has a completely different color scheme than the rest of Site.
This includes the Header Navigation too.

For the Desktop Navigation the background color was set to "transparent" in order to show the color gradients from the main page below. This required to move the whole page a few rems up.

The same should happen with the Mobile Navigation which includes a few more tweaks:

- [ ] if page is "infinity" set the background color for Mobile Nav to "transparent"
- [ ] if page is "infinity" remove the buttons from the Mobile Navigation 
- [ ] if page is "infinity" add a new Hamburger Menu icon
- [ ] **Ask design how the toggled menu should look like** 
- [ ] **Ask design where the "change language" button should be now**

Relates to https://github.com/KlimaDAO/klimadao/issues/532

### Screenshot from design
<img width="355" alt="Bildschirmfoto 2022-07-29 um 15 16 59" src="https://user-images.githubusercontent.com/95881624/181769225-f2c0dbb1-5f46-4ec1-9499-61719a5a1d3c.png">

**Comment by Atmosfearful** [comment]
similar to get clarification from designers on how to unify this as best we can across all views, if possible, and do it as part of the new nav header

**Comment by jabby09** [comment]
Deprecated, /infinity is now going away with Carbonmark release
