### ISSUE TITLE
Site Infinity: Footer Navigation tweaks

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#558]
## Description

The Infinity page has a completely different color scheme than the rest of Site.
This includes the Footer Navigation too.

- [ ] if page is "infinity" make the footer navigation break into rows on smaller screens
- [ ] if page is "infinity" give the footer navigation links the color "white" 
- [ ]  if page is "infinity" make the footer background to "transparent" to let the background gradient from the site visible
- [ ] if page is "infinity" give all social icons the color "white"

Relates to https://github.com/KlimaDAO/klimadao/issues/532

### Screenshot from design

<img width="252" alt="Bildschirmfoto 2022-07-29 um 15 22 02" src="https://user-images.githubusercontent.com/95881624/181769814-c0d4b646-4b44-4004-8616-9b4d0bf200a6.png">

<img width="806" alt="Bildschirmfoto 2022-07-29 um 15 25 11" src="https://user-images.githubusercontent.com/95881624/181770069-1153cca1-fa32-48ae-9364-c6bda59102c9.png">

**Comment by Atmosfearful** [comment]
I know that @Go-Mori is eager to unify the header and footer across all pages, and I think it's better if we keep reusing it like we do now.

We can however still do the transparent bg (background-color prop or css override from parent)
and then negative margin so the gradient overlaps (also css override from parent)

**Comment by MColl92** [comment]
Hi @Atmosfearful @goatsOnDrugs, I might be late to the party on this but I put together a PR for this ticket a couple of days ago (before your comment).

I'm new to the community and wanted to contribute so just grabbed a random ticket. Feel free to disregard the change if not needed.

**Comment by MColl92** [comment]
Heads up this has been merged as of https://github.com/KlimaDAO/klimadao/pull/572

Before someone jumps on this ticket 🙂
