### ISSUE TITLE
[app ui] Utilize dead space at top

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#563]
![image](https://user-images.githubusercontent.com/88635679/182223178-87e69e74-968c-4260-af58-5c87496cc43a.png)

Currently, the content is placed in the center row and below. Can we move it up to the top row?
![image](https://user-images.githubusercontent.com/88635679/182223945-72f9020e-4ddc-43cc-b39b-f77bf345bb7c.png)
 This may require a rethinking of the grid layout that we use for the dapp.
 
Please make yourself aware of a past issue we had, to make sure this is solved as well: https://github.com/KlimaDAO/klimadao/issues/273
https://github.com/KlimaDAO/klimadao/issues/264

**Comment by jabby09** [comment]
moving this to blocked/waiting as team need to regroup with professor on design questions.

**Comment by jabby09** [comment]
@Atmosfearful transitioning this goats issue to you.
two closed PR's associated but I can't tell if those issue should be closed.
seems like a low priority.
