### ISSUE TITLE
Retirement receipt 404

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#568]
From riitaka. Probably subgraph delay.
> Hi guys, after I executed this retirement using MetaMask on mobile: https://polygonscan.com/tx/0xf9242c93dc91c0a4bd3bad0616ae69fd097040a15bde997dc7bc772912ea32e5
I got the attached error when clicking to view and share my retirement page + the retirement doesn’t appear on the aggregated overview page https://www.klimadao.finance/retirements/rittaaka.klima
EDIT: the tx now appears on the retirement overview but when I click it, I get another 404 

- can we improve subgraph speed?
- should we add a fallback state?
in theory the RPC node should have data before the subgraph, so we could query the rpc and see if a retirement exists. If it does, we can show something like 'On-chain data is being indexed, this may take a few minutes.'

**Comment by ladytrekker** [comment]
Not sure how to increase the speed of the subgraph.

What I would do now:

- divide fetching data from RPC and subgraph (currently [wrapped in promise.all](https://github.com/KlimaDAO/klimadao/blob/staging/site/pages/retirements/%5Bbeneficiary%5D/%5Bretirement_index%5D.tsx#L90-L102))
- fill missing data with "Loading data..." and the text 'On-chain data is being indexed, this may take a few minutes.'
- in `useEffect` start a timer for fetching the data from subgraph every XY seconds
