### ISSUE TITLE
[retire] Disable KLIMA as a source for retiring UBO or NBO

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#569]
Trident swaps are not supported by the retirement aggregator (see [Solidity repo corresponding issue](https://github.com/KlimaDAO/klimadao-solidity/issues/22)).
The user should not be allowed to select "Pay with KLIMA" to offset UBO or NBO, which both use Trident pools.

The following is invalid and causes transactions to revert:
![image](https://user-images.githubusercontent.com/99001851/182296092-f7968a07-d57e-49b2-9070-b5a846553211.png)

**Comment by ShimonD-KlimaDAO** [comment]
Need to also disable USDC->NBO and USDC->UBO for now.

**Comment by Atmosfearful** [comment]
Closed as Offset tooling has been moved to Carbonmark
