### ISSUE TITLE
[retirements] Better Fallbacks on missing subgraph data

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#578]
## Description

The subgraph query became much slower recently which led to this bug: https://github.com/KlimaDAO/klimadao/issues/568
where the retirement pages generation do fail with a 404.

The first quick fix was implemented with this PR https://github.com/KlimaDAO/klimadao/pull/571 which renders string fallbacks or dismisses components on the page when the subgraph data is missing.

Here are some ideas to push a fallback page even more forward:

## Render page with RPC data, Start Timer to fetch subgraph data again
- [ ] if subgraph data is missing, start a timer in `useEffect` which queries the subgraph again every XY
- [ ] Render the pages without the subgraph data (=> see screenshot sin this PR #571)
- [ ] while the timer polls the data, show a Loading Spinner on the components which await for the data
- [ ] while the timer polls the data, show a fallback string "Indexing on-chain retirement data, this may take several moments..."

## Show Fallback Page with Loading spinner
- [ ] if no subgraph data is present, do not render the page with RPC data only
- [ ] Instead show a full page with a loading spinner and the text "Indexing on-chain retirement data, this may take several moments..."
- [ ] start timer to reload the page / query the subgraph again until subgraph data is present
- [ ] if both RPC and Subgraph data are present, render the pages as usual
- [ ] revalidate page from NextJS 10 seconds if subgraph is missing

**Comment by Atmosfearful** [comment]
I'll close this ticket and #578 in favor of #1096 #1018 and #1290
