### ISSUE TITLE
"Get Started" modal for Klima Infinity

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#581]
Requirements:
links to the three calculators:
- carbon.fyi ethereum emissions calc
- creol business calc
- creol lifestyle/personal calc

**Comment by theprofessora** [comment]
@Atmosfearful here i am

**Comment by jabby09** [comment]
Attaching the figma: https://www.figma.com/file/6CUpojwfvdV4R3ACk85JYG/KI-Landing-Page?node-id=1436%3A1870#243064615

**Comment by goatsOnDrugs** [comment]
Hey @kaxline I'm gonna grab this one bc I'm out of tickets.

**Comment by jabby09** [comment]
@goatsOnDrugs here is the shipped design: https://www.figma.com/file/6CUpojwfvdV4R3ACk85JYG/KI-Landing-Page?node-id=1533%3A3207

**Comment by jabby09** [comment]
@goatsOnDrugs latest shipped design: https://www.figma.com/file/6CUpojwfvdV4R3ACk85JYG/KI-Landing-Page?node-id=1467%3A2601

note you can ignore the light mode versions for the KI page. depending on where else we use this component the light mode might be relevant

**Comment by jabby09** [comment]
@goatsOnDrugs 
I'm a business. = https://klima.creol.io/#/office
I'm an individual = https://klima.creol.io/#/footprint
I want to offset crypto = https://carbon.fyi/

**Comment by goatsOnDrugs** [comment]
@ShimonD-KlimaDAO this is ready for testing. Note that there is a follow up ticket

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO QA link https://klimadao-site-git-goats-581-infinity-modal-klimadao.vercel.app/infinity

**Comment by ShimonD-KlimaDAO** [comment]
Submitted new issue with feedback:
https://github.com/KlimaDAO/klimadao/issues/693
