### ISSUE TITLE
KI Landing Page - Add Video Layer

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#585]
The current version of the KI Landing page (https://www.klimadao.finance/infinity) has an image placeholder where I video needs to be:

![Image](https://user-images.githubusercontent.com/103535195/182982506-9d8e7e29-261d-4d6f-9382-24fa13887473.png)

This is meant to be the DeFi that defies climate change video - https://www.youtube.com/watch?v=eRmmDh1ingU&t=2s

Next steps:

- [x] Need to add a play button to the current graphic that’s there so users knows to click
- [x] Need GH issue to add video layer to page

**Comment by jabby09** [comment]
@Atmosfearful here is the figma design for this, ready to hand off to dev
https://www.figma.com/file/6CUpojwfvdV4R3ACk85JYG/KI-Landing-Page?node-id=109%3A12#241339005

**Comment by Atmosfearful** [comment]
Closed in #676
