### ISSUE TITLE
[sanity] Separate out dedicated Partners page under Resources

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#611]
Rather than having our partners tucked awkwardly under the community links, we should have a dedicated partner page where we can showcase our partners and link to their sites

This is a low priority issue but should be pretty straightforward

**Comment by theprofessora** [comment]
https://www.figma.com/file/hMz6ecbna21CqADRrc5Zmm?node-id=1:12#253404803

**Comment by jabby09** [comment]
no longer needed with new website
