### ISSUE TITLE
Avoid rounding to 0 on retirement certificate PDFs

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#612]
![image](https://user-images.githubusercontent.com/91024694/184972012-659cfc18-d3d1-4360-a31d-f44ec51937d6.png)

not ideal.. this was a tiny retirement and we have to have a cutoff somewhere but this isn't ideal

**Comment by 0xAeterno** [comment]
@0xAurelius what was the precision on that retirement. The rounding is set to 2 decimal points so it must be less than 0.01 tonnes retired.

Maybe for retirements greater than 1 carbon tonne, we can round to 2 decimal points. For smaller retirements less than 1 tonne, we can be more precise and show 4 decimal points. What are your thoughts?

**Comment by 0xAurelius** [comment]
Hmm yeah it was quite tiny according to the user

Understand we need some kind of precision cutoff to keep the cert looking clean

I'm thinking instead of 0 for very small retirements below some cutoff, we just say "<0.01 tonnes" rather than rounding to 0

**Comment by 0xAeterno** [comment]
That makes sense, happy to push that change through asap :)
