### ISSUE TITLE
[pdfs] Retirement PDF - Open in Browser Tab

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#633]
The initial implementation of the retirement PDF is a download CTA.

An improved UX would be to open the PDF first in a tab of the users default browser (desktop and mobile) to allow the user to preview the PDF first and then decide on download or other share options.

Acceptance criteria:

- [ ] Change button CTA to "Preview PDF"
- [ ] When user clicks button, open the generated PDF in a tab of the users default browser
- [ ] Should work in desktop and mobile

**Comment by 0xAeterno** [comment]
@jabby09 
Poked around on this ticket to see whats involved.
Discovered a couple drawbacks with opening the PDF into another tab before saving:
- When downloading from the new tab, the set pdf filename is no longer preserved and defaults to the browser default eg. "download.pdf"

Will upload an example pic a little later

**Comment by Atmosfearful** [comment]
We can give this another shot when we finish the other PRs in the milestone and get them up and running in carbonmark https://github.com/KlimaDAO/klimadao/milestone/8

**Comment by jabby09** [comment]
no longer an issue as the pdf just downloads now
