### ISSUE TITLE
[bonds] Add "Auto-stake for sKLIMA" checkbox to bond redemption view

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#64]
# Requirements
* [ ] checkbox appears in the Redeem view for any bond
* [ ] when checked, pass `true` as the second argument to the `redeem()` contract method
* [ ] checkbox can be focused with Tab and toggled with Spacebar (or Enter, or both, whatever the browser default is?)

If you don't have any LP to spend @Atmosfearful can test for you :)

**Comment by Atmosfearful** [comment]
I think this is ready to go? And we can port it to the new design when that comes.
@ArchimedesCrypto are you able to give a brief summary of implementation steps so hopefully a dev can jump on this?

**Comment by 0xAurelius** [comment]
> Any news here?

Nothing implemented yet on the frontend but we are in a position to move forward with this now that the redesigned website is live

If you're feeling inspired you're welcome to take a stab at this and open a PR!

**Comment by Atmosfearful** [comment]
Updated the issue description with implementation details
