### ISSUE TITLE
Nav header cleanups

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#646]
Merge #591 first and do these in a follow-up PR

# Related to
#591 
#532 

# Desktop issues
These first three can be solved by using tippy.js around a natively-focusable element like `button`
* [x] 1. Desktop dropdowns can not be reached with the Tab key
* [x] 2. When a dropdown is open, items in an open menu should also be reachable with the tab key
* [x] 3. We need aria labels to indicate to screen-readers that a popper is open. `aria-expanded` and `aria-describedby`  (tippy does by default)

# Other issues
* [x] Mobile menu items which are expandable should have `aria-expanded="false"` by default (`true` when expanded)
* [x] Mobile menu on narrow desktop Windows 10 screens has visible X and Y scrollbars. Probably using overflow: scroll, when you should be using overflow: auto?
![image](https://user-images.githubusercontent.com/88635679/186526742-000eb5d0-69cf-4898-8feb-ddea770ecc56.png)
* [x] When clicking a menu item in the mobile menu, it should not close the other one. This causes a jarring jump in the content which is disorienting. A menu should only close itself when you click it, or when the other
* [x] Remove the "mousedown" / click animation on the button. I always thought it was a bit overkill and it is particularly jarring on this new mobile menu
* [x] add 2.4rem padding-top to `hero_container` on mobile views only, because the white News banner clashes with the white sticky header
Before: 
![image](https://user-images.githubusercontent.com/88635679/186525099-a7fd7f91-a98a-4a84-b009-fb98c024e754.png)
After:
![image](https://user-images.githubusercontent.com/88635679/186525148-2ef6e68b-d186-49fc-8cd7-4456681e68ee.png)

* [x] especially for string ids starting with `shared`, but as a general best-practice, the English source strings should not be capitalized, because we might use it somewhere that doesn't want it capitalized. Use `text-transform: uppercase` in css instead
For example:
```ts
// 🔴 bad
t({
    message: "COMMUNITY",
    id: "shared.community",
})}

// 🟢 good
t({
    message: "Community",
    id: "shared.community",
})}
```

# Stretch Goals
* [ ] Mobile menu should also support tab-navigation. This would require the creation of a "focus trap" so that focus can't leave the mobile menu until the user closes it.
* [x] When the mobile menu is open, the main content and/or `body` should have a scroll lock to prevent un-knowingly scrolling the content underneath when you are trying to scroll the menu list

**Comment by 0xAurelius** [comment]
Noticed a couple of minor issues on staging:
1. There is no link to the Podcast page from the header about the `About` header dropdown (only from the sidebar once you go to an "About" subpage
2. "Carbon Dashboards" is plural right now under `Resources` dropdown, but it really should be singular, "Carbon Dashboard"
