### ISSUE TITLE
Pledge dashboard error when entering address or kns/eth

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#653]
When I enter a KNS address and click search, I see this error looking message while the site is searching/updating. It does take me to the pledge page but with this message I initially think something is wrong.

![Image](https://user-images.githubusercontent.com/103535195/187032173-338afec3-36e2-4604-a9f6-7fc5a147c91d.png)

**NOTE the new /pledge landing page which is in dev () will fix this but creating the issue just in case release of the landing page is delayed.

**Comment by 0xAeterno** [comment]
Addressed in new pledge landing page
