### ISSUE TITLE
Fiat to Retirement

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#654]
This work stream is related to defining the user journey and designs related to a work flow of using fiat to retire/offset carbon. It will build off of the existing [retirement aggregator app](https://app.klimadao.finance/#/offset). The UX and designs may impact other related pages/apps (for example, the retirement receipt page).

**Noted app features that will need design changes:**

- dApp retirement aggregator
- net new payment modal
- retirement summary page and/or retirement receipt

**Related design issue:** KI User Journey Design Review (#478) 

**Roadmap card here:** https://www.notion.so/klima-dao/Fiat-to-Retirement-b957f0f460794bdcade38634987ebeee

**Notes from design ideation meeting:**
- current dApp workflow assumes user has a wallet
- need to inject a payment step to support also pay with fiat
- “connect wallet btn” becomes “continue”
- choose payment method
- all the info entered in the offset form gets sent to the modal pre-loaded
- modal should be in our design language
- credit card —> confirmation page pre-populated
- go to stripe payment flow (”checkout with offsetra”)
    - using offsetra stripe account, they are our payment provider partner
- status of transaction (loading modal)
- a confirmation page for success —> click next
- error page for failed payment
- end on a retirement receipt
- CTA = claim your pledge

**Comment by theprofessora** [comment]
Version 1 is ready for review @jabby09 @Atmosfearful https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr?node-id=0:1#255764402

**Comment by jabby09** [comment]
Shipped design: https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr/Fiat-2-Retirement?node-id=1%3A236#258974662
