### ISSUE TITLE
Multi-wallet pledges

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#658]
User's need the ability to associate several wallets to a pledge.

## Push vs Pull pattern
These have subtle engineering and UX implications, but it is worth discussing. On our original call we leaned towards "push" but I've decided that "Pull" is a better pattern.

"Push" pattern:
  1. Secondary wallet owner visits the pledge, connects and "pushes" their address onto it
  2. The pledge owner wallet accepts or denies any pushed addresses
  
"Pull" pattern:
  1. Pledge owner enters the secondary addresses they would like to "pull" in.
  2. The pulled wallets then connects and visits the pledge, and are prompted to accept or deny the pull.
  
 I believe that **Pull** is **better** for three reasons:
 1. With the Push pattern, we would have to prompt **every** connected user who visits *any* pledge: 'would you like to pin your address to this pledge?'. This is irrelevant for 99.9% of wallets. Whereas with the Pull pattern, **only pulled wallets see the prompt 👌**.
 2. With the Push pattern, I can write a few lines of code that spams a pledge with randomly created addresses.
 3. It's somewhat easier (engineering and UX wise) to enforce that a wallet not be Pulled into to multiple pledges, it's a minor tweak to the Edit Pledge API. Pushing would require a separate API.
  
 # Core UX Requirements
 * [x] Impermanence: the pledge owner has the power to unpin any wallet at any time
 * [x] Secondary wallets also reserve the power to unpin themselves at any time
 * [x] When accepting the "Pull" into another pledge, we must prompt users that any existing pledges under their address will be redirected to the new pledge.
 
  ## Other engineering requirements
* [x] If someone creates a pledge, then later decides to pin themselves to a different pledge, we need to update existing pledge documents in the db to record this state.
 ```json
 {
   "pinned_to": {
      "pledge_id": "[database_id_of_pledge]",
      "pledge_owner_address": "[0x_address]",
    }
 }
 ```

**Comment by jabby09** [comment]
Latest designs: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4/Multi-Wallet-Pledge?node-id=1%3A3

**Comment by jabby09** [comment]
@Atmosfearful @goatsOnDrugs here are the shipped designs.
Let me know if you create a new issue/PR for the dev work.

**Comment by jabby09** [comment]
#712

**Comment by goatsOnDrugs** [comment]
This issue is in code review right meow

**Comment by ShimonD-KlimaDAO** [comment]
Feedback: #778 
Putting back to In Progress.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO moved to test, this is the PR https://github.com/KlimaDAO/klimadao/pull/729

**Comment by ShimonD-KlimaDAO** [comment]
Added a new comment. Found a critical bug. We're getting close.

**Comment by ShimonD-KlimaDAO** [comment]
@goatsOnDrugs the two issues I highlighted in #778 are resolved. This is ready to be merged into prod.
