### ISSUE TITLE
Connect Modal Redesign

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#660]
This issue is the next iteration of the Connect modal on the app. We need to enhance and change this to help make the bridge between web2 users and web3.

The current version assumes a the user is web3 and has a wallet created.
![Image](https://user-images.githubusercontent.com/103535195/187316859-3c7f0c0e-2bbd-4bdb-923c-7f13cf0d7236.png)

In the next iteration, we need to redesign the modal to assume be inclusive of web2 users.

## Requirements

- Change journey entry point button CTA to:
    - “Login / Connect” or
    - “Login / Connect Wallet”
- Once in the modal, two sections:
    - “Login / Signup”
    - “Connect Wallet”
- “Login / Signup”
    - Social login powered by Torus
    - Show primary social login icon options on the card, i.e. google, facebook, twitter, discord
- “Connect Wallet”
    - Same options as we have currently
        - Wallet Connect
        - Coinbase Wallet
- Include some CTA for a user to get help/support if not sure how to proceed

## Design Sketch
![Image](https://user-images.githubusercontent.com/103535195/187316735-6b555ede-6713-42ac-972f-af9185f766cd.png)

## Other Notes
- For the social login with Torus, note cannot change or customize the current Torus implementation

**Comment by jabby09** [comment]
Shipped design: https://www.figma.com/file/yhjZJKulthgEtixt6L6XPW/Login-%2F-Connect-Modal?node-id=0%3A1#258979350

**Comment by jabby09** [comment]
@Atmosfearful ready for dev assignment

**Comment by Atmosfearful** [comment]
@jabby09 Kicked off with @angusfretwell 
I hope this also fixes #659 as I don't have any idea how to debug that with our current modal 0_0

**Comment by jabby09** [comment]
hey @angusfretwell how are things going on this task; any updates you can share?

**Comment by jabby09** [comment]
Hi @angusfretwell have not heard from you in a bit, hope things are going well. Can you please share an update on status of development for this feature? When do you anticipate being ready for QA?

cc @Atmosfearful

**Comment by jabby09** [comment]
@goatsOnDrugs design is above in one of the comments and this is the Notion roadmap card: https://www.notion.so/klima-dao/Connect-Modal-Redesign-49fbbac5d59647e1b475896aa727d3d0

**Comment by Atmosfearful** [comment]
@goatsOnDrugs Documenting some behavior and expectations:
- when metamask is not present in the browser `window.ethereum` (double check metamask docs) hyperlink the user to `https://metamask.io/`

**Comment by ShimonD-KlimaDAO** [comment]
Approved. Commented on PR #799 and moved to "Done"

**Comment by ShimonD-KlimaDAO** [comment]
Moved back to "In Test". See comment in #799

**Comment by ShimonD-KlimaDAO** [comment]
Moved back to "In Progress". See comment in #799
