### ISSUE TITLE
Fix 0% rounding issue on main landing page

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#661]
![image](https://user-images.githubusercontent.com/91024694/187502664-fb5a6fd8-046c-4837-8dca-fc9931852770.png)

This is rounding to 0 places, but now that AKR is lower weekly rewards are below 1%

We should either round to more places (probably need 2) or do something more dynamic like rounding to more places if the rate is below a certain amount (e.g. round to 1 place between 1 and 0.1, round to 2 places between 0.1 and 0.01, etc.

**Comment by Atmosfearful** [comment]
Let's try Monthly rewards, and add 1 decimal. I'm not sure what the value will be, but for example:
```
0.9% MONTHLY REWARDS
```
