### ISSUE TITLE
[wallet] Opera Browser Not Connecting With Native Wallet

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#674]
EDIT: This is also true for MetaMask on Opera, not just the native browser.

Multiple users reported this issue.

For example, on "Opera Version is 89.0.4447.83 and Operating System is Windows 10", the native Opera browser crypto wallet doesn't pop up.

Screenshot from one user:
![image](https://user-images.githubusercontent.com/99001851/187796682-b9e7a56c-b6b2-4c80-978f-b9a9afbea128.png)

**Comment by Atmosfearful** [comment]
Closing as stale
