### ISSUE TITLE
Modal fixes & useFocusTrap

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#684]
Forgot to test a11y when @ladytrekker made the modal. I think I found some issues:
* [ ] Close button isn't tabbable. Not sure why not. Maybe the focus outline is just hidden?
* [ ] Focus trap. Make a hook called `useFocusTrap()`.
This should use a [callback ref](https://reactjs.org/docs/refs-and-the-dom.html#callback-refs) which, if the element is rendered, parses the html to find focusable elements, then sets a blur event listener on the container to identify when the last element in the modal has been blurred.
```jsx
const ModalDemo = (props) => {
  const focusTrapRef = useFocusTrap();
  
  if (!props.showModal) return null;
  return (
  <div className="modalContainer" ref={focusTrapRef}>
     <button className='close' />
     {props.children}
  </div>
)
```
There are probably some edge cases to handle for the focus trap that I'm not remembering :)
here is some sample code for how to query-select focusable elements. Instead of using the container id, you would use the ref https://uxdesign.cc/how-to-trap-focus-inside-modal-to-make-it-ada-compliant-6a50f9a70700

* [ ] To improve tab navigation, we might need to render modals immediately below the button that opens them. That way when the user clicks (focuses) the button, and presses tab, the first item in the modal is focused. Another option is to force-focus the modal when it opens. Which could be accomplished with `useFocusTrap` as well
```ts
<button onClick={toggleModal} />
<modal />
```

**Comment by Atmosfearful** [comment]
I'm happy to pair-program and take the wheel on useFocusTrap if you want @goatsOnDrugs sounds fun

**Comment by ladytrekker** [comment]
@Atmosfearful 
You mean the Modal for the dApp which I aligned in this PR => https://github.com/KlimaDAO/klimadao/pull/537 ?
Definitely missing accessibility features. This will target then all Modals in the dApp. Especially the TXN Modal.
