### ISSUE TITLE
Live Offsetting Functionality

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#688]
Live offsetting is a great marketing tool for events, allowing people to experience offsetting in real time without any obstacles. The offsets, gas, and everything web3 related is prepaid and done by us - the user just submits a love letter and a name.

The idea is to have a frontend page that controls private keys to a wallet with some gas, and calls a contract function. The contract calls the aggregator, but it’s also configurable for each event, deciding how much to offset per love letter, which project to use, beneficiary details, etc.

We need input from Creative, Marketing, and Engineering.

## Requirements

- Frontend design from @Professor A and @Onyxmony.
    
    A **mobile friendly and simple** UI mock with:
    1. Input state with textboxes for: Name, Love Letter to the Planet. 'Submit' button.
    2. Pending state.
    3. Success state leading to page saying something like: "Congratulations on offsetting 1 tonne of carbon! See your retirement certificate *here*, with your love letter permanently etched on the blockchain! See how the event's *pledge* is doing so far." 
    4. Error state. 
    
Some nice looking static content/images/extra call-to-actions are OK. No need for multi-step flows or animations or anything fancy like that. Assume the klimadao header/footer are visible.
    
- Frontend dev work to have the design come to life, and to use the following lambda function @Atmosfearful came up with a call to contract when “submit” is clicked. ABI, and address, and function to call will be provided by me (@Shimon).
- Contract with configurable parameters for everything needed by the retirement aggregator, as well as:
    - Tonnes per offset
    - Event beneficiary address
    - Event goal
    - Contract will own the offset, which can be transferred before live offsetting takes place at the event

Lambda function from @Atmosfearful  to use in the frontend:

```
const retire: NextApiHandler<RetireResponse | APIDefaultResponse> = async (
  req,
  res
) => {
  try {
    const data = req.query.data;
    if (!isValidData(data)) {
      throw new Error("Invalid request");
    }
    await retireCarbonTransaction(data);
    res.status(200).json({ message: "success" });
  } catch (e) {
    console.log(e);
    if (e instanceof Error) {
      res.status(500).json({ message: e.message });
    }
    res.status(500).json({ message: "Unknown error, check server logs" });
  }
};
export default retire;
```

**Comment by jabby09** [comment]
Current shipped design: https://www.figma.com/file/gHgAK8ZPmYs5YFip8YGRmA/Live-Offsetting

**Comment by jabby09** [comment]
### Contract dev deliverable for frontend
...thanks @ShimonD-KlimaDAO 
...cc @Atmosfearful 

Let me know when the frontend wallet has been generated, and I'll set the "offsetter" to the new wallet address and send it some matic. Only "offsetter" can call this function, and only I ("owner") can change the offsetter, withdraw funds from the contract, and change "event parameters" for live offsetting events.

The code can be [seen here](https://github.com/ShimonD-KlimaDAO/ShimonD-KlimaDAO/tree/main/LiveOffset).

**1. ABI:**
`[{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"uint256","name":"_offsetPerLetter","type":"uint256"},{"indexed":false,"internalType":"address","name":"_eventBeneficiaryAddress","type":"address"},{"indexed":false,"internalType":"address","name":"_carbonToken","type":"address"},{"indexed":false,"internalType":"bool","name":"_retireSpecific","type":"bool"},{"indexed":false,"internalType":"address","name":"_specificAddress","type":"address"}],"name":"LiveOffsetEventUpdate","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOffsetter","type":"address"},{"indexed":true,"internalType":"address","name":"newOffsetter","type":"address"}],"name":"OffsetterTransferred","type":"event"},{"anonymous":false,"inputs":[{"indexed":true,"internalType":"address","name":"previousOwner","type":"address"},{"indexed":true,"internalType":"address","name":"newOwner","type":"address"}],"name":"OwnershipTransferred","type":"event"},{"inputs":[],"name":"KlimaRetirementAggregator","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"address","name":"CarbonToken","type":"address"},{"internalType":"address","name":"eventBeneficiaryAddress","type":"address"},{"internalType":"uint256","name":"OffsetPerLetter","type":"uint256"},{"internalType":"bool","name":"retireSpecific","type":"bool"},{"internalType":"address","name":"specificAddress","type":"address"}],"name":"changeEventParams","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"offsetter","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"owner","outputs":[{"internalType":"address","name":"","type":"address"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"renounceOffsetter","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"renounceOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"string","name":"Name","type":"string"},{"internalType":"string","name":"LoveLetter","type":"string"}],"name":"singleOffset","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOffsetter","type":"address"}],"name":"transferOffsetter","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[{"internalType":"address","name":"newOwner","type":"address"}],"name":"transferOwnership","outputs":[],"stateMutability":"nonpayable","type":"function"},{"inputs":[],"name":"withdrawBalanceOwner","outputs":[],"stateMutability":"nonpayable","type":"function"}]` 

**2. Contract address:**
`0x63fb3e5a855e3f6523af267f670FaC517B0b944d`

**4. Function to call:**
`singleOffset(string memory Name, string memory LoveLetter)`

**Comment by ShimonD-KlimaDAO** [comment]
New contract was deployed. Code is still in the same github location mentioned above.
