### ISSUE TITLE
Nextjs server mismatch errors

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#690]
low-ish priority but we should still fix
Reproduce:
load /infinity, this error appears on first page load
![image](https://user-images.githubusercontent.com/88635679/189211529-0bf6dea8-d03f-4617-b359-1696ffea9c23.png)

**Comment by jabby09** [comment]
Low priority, Infinity is being deprecated. Not seeing any user reported bugs.
