### ISSUE TITLE
PageContainer for site

### ISSUE THREAD

**Issue by goatsOnDrugs** [KlimaDAO/klimadao#694]
Dev Notes: 
goal is to remove header height css var. Use padding-top on mobile bc header is fixed.
header-height css var is creating some tricky bugs.

AC:

- [ ] make PageContainer component for site
- [ ] remove breakpoints.css on site
- [ ] remove header height css var

**Comment by jabby09** [comment]
@goatsOnDrugs note that a white bar at the top of the infinity landing page was flagged as an issue in discord [here](https://discord.com/channels/841390338324824096/964698508751949824/1068475159851302912). We discussed that this is related to this existing issue.

**Comment by jabby09** [comment]
Deprecated by Carbonmark. KlimaDAO homepage is being redesigned. Will leave with what we have at this point.
