### ISSUE TITLE
Image optimizations

### ISSUE THREAD

**Issue by goatsOnDrugs** [KlimaDAO/klimadao#696]
Scale images down with https://www.reduceimages.com/ and use sizes prop where we are using full sized images and use the `sizes` prop. Use `blur` for next.js images.

**Comment by Atmosfearful** [comment]
Reassigning to @biwano as he is looking for a ticket

The most important piece for this ticket is either using the `sizes` prop, or using the smallest possible image dimensions
(first checking where an image is used)

I recommend starting with the `/infinity` page

**Comment by Atmosfearful** [comment]
See this comment for more background  https://github.com/KlimaDAO/klimadao/pull/676#discussion_r963149970

**Comment by biwano** [comment]
@Atmosfearful 
Investigation on the sizes property. I worked on the green mountains side image on the infinity page (behind "Fast"): 
Is seems that in this property you cannot mix units:
`sizes="(max-width: 768px) 100px,  404px"` works
`sizes="(max-width: 768px) 100vw,  10vw"` works
`sizes="(max-width: 768px) 100vx,  404px"` unfortunately does not work

And given the layouts we would like to have 100vw on mobile and a fixed size on desktop

Given the context we want to improve display on desktop So I will try for now with the definition in pixels.
