### ISSUE TITLE
[pledges] Integrate unpooled retirements into Pledges

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#701]
In addition to retirements made from a pool like BCT via the KlimaDAO retirement aggregator, Pledges should also include retirements made directly on the bridge's native retirement interface using the underlying "raw" credit (e.g. TCO2, C3T) instead of a specific pool.

The Bridged Carbon subgraph must first be updated to include this data: https://github.com/KlimaDAO/klima-subgraph/issues/55

**Comment by jabby09** [comment]
pledges is now a deprecated feature
