### ISSUE TITLE
[Site] Pledge Landing Page Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#703]
Not much to say this time - it's a beauty!

1. "Learn more" is not centered on mobile.
![Screenshot_20220914-205244_Brave](https://user-images.githubusercontent.com/99001851/190310625-2ee49ff6-9aff-4a41-92fb-0885570387e5.jpg)

2. The "Enter ENS or 0x address" bar should also mention KNS since we support it as well.
![image](https://user-images.githubusercontent.com/99001851/190310447-1c74731b-a6fb-4161-8293-06a6bc59c961.png)

**Comment by jabby09** [comment]
Thanks @ShimonD-KlimaDAO 

@Atmosfearful @angusfretwell couple of minor tweaks here but no reason the current page cannot be released.

**Comment by jabby09** [comment]
hey @angusfretwell just checking in, any progress on this one? (cc @Atmosfearful)
