### ISSUE TITLE
[Pledge] Remaining enhancements to complete beta

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#712]
### What needs to be completed to remove the beta label from the pledge dashboard:

- [ ] Move the carbon assets card to the bottom
- [ ] Only show the assets with a history to graph (assets that have never been owned will be hidden)
- [x] De-capitalize the card titles, that's too much weight for that specific title
- [ ] Hide image profile placeholder is the user does not have one
- [ ] Change Footprint graph colour scheme to support accessibility for colour blind users. HEX values available in the [figma design](https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4/Multi-Wallet-Pledge?node-id=9%3A621)
<img width="187" alt="Screen Shot 2022-10-01 at 9 55 53 AM" src="https://user-images.githubusercontent.com/103535195/193410593-b0ab9b63-3ab9-4e61-a941-73f7adfc2e50.png">

**Comment by jabby09** [comment]
@Atmosfearful ready for dev assignment

**Comment by Atmosfearful** [comment]
I think this is an easy one for you to get started with @MColl92

**Comment by MColl92** [comment]
Sure, sign me up 👍

**Comment by MColl92** [comment]
@jabby09  do you have an updated figma link? It seems the one from the description is broken (or I don't have access).

![image](https://user-images.githubusercontent.com/7104689/194744604-0d8507aa-26eb-449c-9651-46dc0ab48d85.png)

**Comment by jabby09** [comment]
@theprofessora can you please give @MColl92 access to this [figma file](https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4/Multi-Wallet-Pledge?node-id=9%3A621). thanks!

**Comment by theprofessora** [comment]
michaeljosefcollins@gmail.com has been given editing capabilities

figma file here: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4/Multi-Wallet-Pledge?node-id=1%3A3

**Comment by MColl92** [comment]
> [michaeljosefcollins@gmail.com](mailto:michaeljosefcollins@gmail.com) has been given editing capabilities
> 
> figma file here: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4/Multi-Wallet-Pledge?node-id=1%3A3

Excellent, thank you
