### ISSUE TITLE
[Pledge] Organization website as an option

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#713]
- [x] The website of the organization should be an **option** to include in the pledge dashboard

optional addition of website: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=144:2704#278550135

- [x] As part of this ticket, remove the beta label on the page
![Image](https://user-images.githubusercontent.com/103535195/198832727-0683e939-fb73-4fdb-ac9a-cac35da47c6b.png)

**Comment by jabby09** [comment]
These will need designs first @theprofessora

**Comment by theprofessora** [comment]
upload profile pic: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=1:3#276250186

**Comment by theprofessora** [comment]
report a pledge: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=1:3#276252768

**Comment by jabby09** [comment]
@Atmosfearful designs above for review and dev assignment

**Comment by jabby09** [comment]
@theprofessora added this one to this ticket:
_The website of the organization should be an option to include in the pledge dashboard_

This should be optional so should be designed on the UI to support either being there of not.

One thought is to just make the profile logo clickable is a URL is provided??

**Comment by theprofessora** [comment]
optional addition of website: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=144:2704#278550135

**Comment by Atmosfearful** [comment]
@jabby09 let's break these into separate tickets.
1. `photo upload` - this is a rabbit hole that needs some research (IPFS uploads vs firebase, expected costs etc.)

2. `Report this pledge` - this we need to figure out who the reports go to and via which form-- let's pass this to Sy

3.  website url for pledge looks good to go, let's assign that to @MColl92

**Comment by jabby09** [comment]
> @jabby09 let's break these into separate tickets.
> 
> 1. `photo upload` - this is a rabbit hole that needs some research (IPFS uploads vs firebase, expected costs etc.)
> 2. `Report this pledge` - this we need to figure out who the reports go to and via which form-- let's pass this to Sy
> 3. website url for pledge looks good to go, let's assign that to @MColl92

@Atmosfearful sure no problem

**Comment by jabby09** [comment]
@0xemc as suggested by @Atmosfearful I have broken the original issue into 3 different ones and this (as the original) has been renamed. Ignore the design link comments that were for other tasks, those are now captured in new issues.

**Comment by 0xemc** [comment]
> @0xemc as suggested by @Atmosfearful I have broken the original issue into 3 different ones and this (as the original) has been renamed. Ignore the design link comments that were for other tasks, those are now captured in new issues.

@jabby09 could you assign me to the new issue related to the website url for pledge? I can see this issue has been renamed but unsure if the designs are up to date.

**Comment by jabby09** [comment]
> https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=144:2704#278550135

@0xemc this issue is now focused on the website url for pledge and you are already assigned. Figma design in the desc above but also shared here: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=144:2704#278550135

Let me know if any questions!

**Comment by 0xemc** [comment]
Perfect, thanks @jabby09 🙏

**Comment by jabby09** [comment]
@0xemc is this on your radar for this week? thanks
