### ISSUE TITLE
Update KI Navigation for Pledge Landing Page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#722]
With the recent launch of the /pledge page (https://www.klimadao.finance/pledge) the website navigation (desktop and mobile) needs to be updated to include two option for Klima Infinity, as per the designs.

Design file: https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D?node-id=0%3A1

![Image](https://user-images.githubusercontent.com/103535195/192342749-a587d5b3-1f3b-40cd-a54f-a969a5f00b81.png)

Introduction = https://www.klimadao.finance/infinity
How to Pledge = https://www.klimadao.finance/pledge

**Comment by jabby09** [comment]
@Atmosfearful small task for @goatsOnDrugs when he has a minute

**Comment by Atmosfearful** [comment]
Another potential low hanging fruit for you @MColl92

**Comment by MColl92** [comment]
No problem, assign me to this and I'll get on to it asap.
