### ISSUE TITLE
[Pledge] Improvements to "pending signature" state

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#732]
Small improvements needed when clicking "save edits" on the pledge:

1. We need some user education here. It's not clear that I need to go to my wallet to confirm. For metamask this is obvious (it pops up) but for other wallets it is not, e.g. gnosis or mobile apps.

2. Also the white font for disabled button is hard to read.

![image](https://user-images.githubusercontent.com/88635679/193155024-2bdafc7c-1b26-4ba2-85f3-5738227eb6b8.png)

**Comment by theprofessora** [comment]
See updated disabled button style here: https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd?node-id=1126:641#292038604
