### ISSUE TITLE
Migrate away from ethers getDefaultProvider to avoid unecessary network calls

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#739]
This method is creating network requests to cloudflare and a bunch of other services we don't need.
We need to just pick an ethereum provider URL (infura?) and run with it so we don't have to invoke this method.

**Comment by kaxline** [comment]
@Atmosfearful Looking into this now. Do we have an API KEY for Infura or any other provider that we'd like to use?

**Comment by Atmosfearful** [comment]
@goatsOnDrugs I can create a new infura project id that is only for client-side requests and expose it via ENV vars. Hopefully we don't get too much traffic and blow up the free tier.

**Comment by goatsOnDrugs** [comment]
@Atmosfearful adding the INFURA_ID should do the trick here. We use defaultProvider in app/lib/hooks/useENS.ts but useENS is not used anywhere so I think we can delete it.

**Comment by jabby09** [comment]
@goatsOnDrugs @Atmosfearful this one has a HIGH PRIORITY label on it but has been open of over 2 months. Are we blocked?

**Comment by goatsOnDrugs** [comment]
@jabby09 No, I picked this one up last week and plan on finishing it up next year. I have a PR up for it that should work but probably better to leave for a monday haha.
