### ISSUE TITLE
[sanity] Embed Videos in Blog Posts

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#740]
Is there a way we could easily / quickly implement video embedding into the KlimaDAO blog? 
Videos are very important for SEO, but right now it's not possible to embed them in an article on Sanity.

**Current implementation**
Had to do it like this for now https://staging-site.klimadao.finance/blog/klima-data-carbon-dashboard-unprecedented-transparency

**Acceptance criteria**
The LinkedIn CMS version of the article is a state we should strive to! https://www.linkedin.com/pulse/klima-data-carbon-dashboard-unprecedented-market-transparency-/?published=t

**Comment by Atmosfearful** [comment]
KlimaDAO blog is now on wix
