### ISSUE TITLE
[sanity] Add share option to post preview and post single view

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#749]
## Description

For the new resources page a "share this post" functionality is planned.

Designs: https://www.figma.com/file/NQTGQDrS7PEfB3QOzYMBN3/RESOURCES?node-id=5%3A833

#### PREVIEW POST
<img width="680" alt="Bildschirmfoto 2022-08-25 um 08 01 47" src="https://user-images.githubusercontent.com/95881624/188130599-7950d88b-e25f-4882-a4a8-3700ff12e394.png">

#### SINGLE POST
<img width="728" alt="Screen_Shot_2022-10-19_at_8 59 57_AM" src="https://user-images.githubusercontent.com/95881624/196695611-bb47160a-3bde-495a-a85d-5b2cdb0de4fa.png">

#### SHARE POST

<img width="352" alt="share_post" src="https://user-images.githubusercontent.com/95881624/196696012-3bb9d8ef-3569-42af-81fb-312ee9459d7a.png">

### RELATED TICKETS

New resources page: https://github.com/KlimaDAO/klimadao/issues/534

**Comment by jabby09** [comment]
@rstycedar this is an old one that was in the backlog, I added it to the epic but it would need to be reviewed first to make sure it is still relevant
