### ISSUE TITLE
Update CNAME records in NameCheap for reducing emails hitting Spam

### ISSUE THREAD

**Issue by hughklima** [KlimaDAO/klimadao#752]
We discovered a few of our emails being sent from Hubspot were going to spam. To resolve, HubSpot recommends we connect our domain (https://knowledge.hubspot.com/domains-and-urls/connect-your-email-sending-domain). To do this, we need to update our CNAME records in NameCheap. Detailed instructions can be found here https://knowledge.hubspot.com/domains-and-urls/update-your-dns-records#namecheap. 
![image](https://user-images.githubusercontent.com/112615952/196706523-42326e7f-7c4e-4031-9b8e-c568e200c7b7.png)

hs1-26010207._domainkey
klimadao-finance.hs07a.dkim.hubspotemail.net.

hs2-26010207._domainkey
klimadao-finance.hs07b.dkim.hubspotemail.net.

**Comment by AleksandrMikhail0x1337** [comment]
We have been blacklisted, two issues causes 
1. we have an open relay (not sure who manages this on our google email setup/configuration but it's now a serious issue).  

This is what I picked up on the external "soft" pentest.
*** - Email security *** 
Test open relay mail and confirm risk if any (in-progress/on-going).
SMTP	alt3.aspmx.l.google.com.	**Open relay**.
SMTP	alt3.aspmx.l.google.com.	Reverse DNS does not match SMTP Banner.
DNS	klimadao.finance	SOA Expire Value is out of recommended range.
DNS	klimadao.finance	SOA Serial Number Format is Invalid.

2. We have not added an extra layer of security on our mail management. 
DKIM record create - needs to be completed.


<img width="798" alt="Screenshot 2022-10-27 at 09 22 47" src="https://user-images.githubusercontent.com/109509644/198217607-11c45ad8-c0a4-4d9c-9f89-1fff0f0ed6ea.png">

HTH.

**Comment by hughklima** [comment]
This looks like it can be closed
