### ISSUE TITLE
Update Retirement Receipt Page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#755]
As part of the Fiat 2 Retirement workstream, the [retirement receipt page design](https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr/Fiat-2-Retirement?node-id=11%3A9010) was enhanced.

![Image](https://user-images.githubusercontent.com/103535195/197342350-900facff-2c45-46e7-8818-1c4b2aac4598.png)

- [ ] Include new CTA button in top retirement info section called "Claim Your Pledge Dashboard".
- [x] Remove current social share icons.
- [x] Include new section called "Share Your Impact" (note new location of social share icons).

**Comment by jabby09** [comment]
@theprofessora can you make sure my to-do list above captures a summary of all the design changes compared to current production version of the receipt ([example here](https://www.klimadao.finance/retirements/brice.klima/2))

**Comment by theprofessora** [comment]
yes, if you go to the figma file, you'll see 2 "claim your pledge dashboard" ctas. Please include both of them in the enhancement

**Comment by jabby09** [comment]
@0xAeterno @Atmosfearful with fiat2retire now live, I think the updates to this page become more of a priority given the connection of the journey through to the pledge page.

**Comment by 0xemc** [comment]
@jabby09 Could I please be added to the figma file with these changes?

https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr/Fiat-2-Retirement?node-id=11%3A9010

**Comment by jabby09** [comment]
> @jabby09 Could I please be added to the figma file with these changes?
> 
> https://www.figma.com/file/gIsDanJUvVwQE4QqSh36Rr/Fiat-2-Retirement?node-id=11%3A9010

@0xemc email to use?
@theprofessora another figma file share request coming your way

**Comment by 0xemc** [comment]
All sorted now @jabby09 thanks 🙏

**Comment by Atmosfearful** [comment]
OK as I discussed with @theprofessora a large "claim your pledge" button does not make sense for two reasons:
1. It only applies to a user who is connected, and the beneficiary of this retirement
2. going from Offset -> Retirement Page requires you to reconnect your wallet.

Ignoring the larger architectural problem of having two apps for the same journey (a solution for that is being explored), I recommended a few options to Professor but we need a design. Let's split that into a separate ticket @jabby09 

So hold off on that bit. We can continue with the improved Social Share section @0xemc @jabby09

**Comment by theprofessora** [comment]
@Atmosfearful @jabby09 @0xemc new retirement receipt as discussed: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk?node-id=1609:1771#307609267

**Comment by jabby09** [comment]
@0xemc you should be good to go now!

**Comment by 0xemc** [comment]
Hey @jabby09, on it now. Will  be ready by 19th Nov at the latest.

There are also a few other small differences between the designs and the current page, if you're ok with it I will go ahead and update those too.

**Comment by Atmosfearful** [comment]
@theprofessora @jabby09 quick design task that has been mentioned on calls but never made it to the figmas:
1. Each receipt page should only have one project (designs show several).
2. We currently show the "total available tonnes" below each project which isn't that informative IMO Remove that number entirely?

**Comment by 0xemc** [comment]
@jabby09 there are a fair few differences between the design and the current page.

* Poppins font has been replaced with Inter for headers (h1...h5) 
* Some colors I can't find in the design system (eg. surface-05) I think they're no longer in the new system?
* Font sizes don't match any existing definitions in the codebase (20px for the titles in the retirement summary)

Happy to make these changes here specifically but I want to make sure it's consistent with the rest of the site (if so we might need to update our defined styles in the codebase)

**Comment by jabby09** [comment]
@theprofessora please see atmos and Oxemc comments above, sounds like this design might need one more pass?

**Comment by theprofessora** [comment]
Hi everyone, I think I've fixed everything. Sorry a lot of the components were legacy from previous designers and from before we had a slight font rebrand. I hadn't taken the time to go through the minutia; had instead dragged the components in and placed them. Spent all morning fixing the root components so they're all aligned now. @Atmosfearful I can't find where you're talking about the hyperlink icon

**Comment by jabby09** [comment]
@theprofessora what @Atmosfearful is referring to is the icon beside the project hyperlink that indicates you will be redirected to a different site, so for example:
![image](https://user-images.githubusercontent.com/103535195/202772452-3fd6c2c2-28a1-4088-aa33-699b6d8ed604.png)

**Comment by theprofessora** [comment]
OK All set!

**Comment by jabby09** [comment]
> 

@0xemc you should be good to go now, let me know if there are still any questions or unclear requirements

**Comment by 0xemc** [comment]
Thanks @jabby09 on it! 👍

**Comment by jabby09** [comment]
Hello @0xemc hope things are going well. Do you have an ETA on when this would be ready for QA? thanks!

**Comment by 0xemc** [comment]
Hey @jabby09 sorry for the delay. The fixes have been deployed now as part of this PR:

https://github.com/KlimaDAO/klimadao/pull/804

**Comment by ShimonD-KlimaDAO** [comment]
@0xemc I left a comment in #804 with feedback.

**Comment by ShimonD-KlimaDAO** [comment]
I'll wait for #816  to be addressed and referenced here. Meanwhile moving this to "In Progress". The social share portion is complete and passed QA.
