### ISSUE TITLE
Update Website Buy Page to Encourage Torus

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#756]
The current website [/buy page](https://www.klimadao.finance/buy) does not discuss our wallet integration with Torus. There is a suggestion to encourage the use of Torus over Metamask as Torus supports non-web3 connection options and will be easier for most users.

This is related to the Beginner section of the page.

![Image](https://user-images.githubusercontent.com/103535195/197342936-f9c5d71b-d083-465f-b4da-8671b7a19692.png)

**Comment by jabby09** [comment]
@theprofessora not sure if you want to tackle this one or hand-off / coordinate with the creative/content team since this is on the external marketing website?

**Comment by theprofessora** [comment]
@jabby09 Do you want a mock-up or can we just change the text here?

**Comment by jabby09** [comment]
@theprofessora good point, maybe this is just a content update. I'll ask @rittaaka

**Comment by rittaaka** [comment]
> @theprofessora good point, maybe this is just a content update. I'll ask @rittaaka

We have created a task for this for the Content team and tagged @jabby09 for visibility

**Comment by jabby09** [comment]
Marketing discord thread tracking this work: https://discord.com/channels/841390338324824096/1034743927774912543

**Comment by jabby09** [comment]
Revised text version 1: https://docs.google.com/document/d/1pwPreYjg-_InrYZo3NC6Wg-xQu9-pRYDZLiwoh00MSE/edit#heading=h.r3kgchw13ba0

**Comment by jabby09** [comment]
[Revised content for beginner section](https://docs.google.com/document/d/1pwPreYjg-_InrYZo3NC6Wg-xQu9-pRYDZLiwoh00MSE/edit#heading=h.dca1zy37n4ib). This text is intended to replace both 001 and 002 of the current flow. Thus, 002 becomes 'Buy KLIMA', etc. in a four-step process.

**Comment by jabby09** [comment]
NOTE: this issues is now deprecated by #826 
Closing this issue.
