### ISSUE TITLE
Balance fetch error on dApp load

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#759]
I notice this in the console when developing. Needs investigating

**Comment by kaxline** [comment]
@Atmosfearful The error I get is at line 226 of `actions/bonds` that calls `marketPrice` on the bond contract.

Is that the one you're seeing or how can I find the one you're talking about?

**Comment by Atmosfearful** [comment]
Only info I have is this 
![image](https://user-images.githubusercontent.com/88635679/199526536-5c957152-37db-49fb-a6a1-666751f6822b.png)
