### ISSUE TITLE
[pledge] Addition of a “Report this dashboard” feature

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#768]
Addition of a “Report this dashboard” feature. Likely a small clickable link in the footer that goes to a simple form.

Design: report a pledge: https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=1:3#276252768

The form in the design should be sent to this email with the form contents: report@klimadao.finance

**Comment by Atmosfearful** [comment]
We should use a different email alias for this, I don't want users to expect a bounty payout just for reporting a pledge!

**Comment by jabby09** [comment]
@Atmosfearful sounds good, I'll ask Sy for another email.

**Comment by jabby09** [comment]
@Atmosfearful this has been updated to [report@klimadao.finance](mailto:report@klimadao.finance)

**Comment by jabby09** [comment]
Low priority enhancement.

**Comment by jabby09** [comment]
This is likely deprecated as /pledge moves to Carbonmark but we will see what @theprofessora does with this one.
