### ISSUE TITLE
[pledge] multi wallet improvements

### ISSUE THREAD

**Issue by 0xAeterno** [KlimaDAO/klimadao#773]
- [ ] How do we improve `PledgeForm` to remove the need of `isDeleteMode`
  - Required to persist form state when editing secondary wallets
  
- [ ] Refactor accept and reject secondary wallet invitations to seperate endpoints
  - Actions are independent from putPledge => single responsibility 
  - Consider what validation is required

- [ ] move isOwner check to server
   -  formSchema should be independent from dependancies like the window object.
   - add translated error on pledge form

**Comment by goatsOnDrugs** [comment]
@0xAeterno moved the schema refactor to here

**Comment by jabby09** [comment]
moving to backlog, now a low priority

**Comment by jabby09** [comment]
no longer relevant
