### ISSUE TITLE
[Site] "/resources" feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#774]
#534 

1. "couldn't" is misspelled. 
![image](https://user-images.githubusercontent.com/99001851/199124360-9283b96b-0351-42d2-bf01-41e478d7f41a.png)
I would also change:
"Double check your search for any typos or spelling errors - or try a different search term."
To: "Check your search for typos or try a different search term."

2. Under 'Featured Articles', only "Read more" is clickable, whereas under "Explore All", every part of the tile is clickable.

3. I'm unable to put in a search term at the same time as clicking a box.

**Comment by ladytrekker** [comment]
Thanks for the feedback.

1. Thanks, is changed
2. We will keep the "read more" link for now because of mobile users and the swipe versus click on the sliders item
3. This is intended, a text search disables all checkbox categories as the text search is over all available documents
