### ISSUE TITLE
[App] Fiat2Retirement Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#775]
#746 

Consolidating feedback.

**Jabby:**
* [x] When enforcing the 1 tonne minimum, once I type in the input box and it default to one I can never clear the input with backspace or delete. To change from 1, I have to use the incriminator control or select one and type from keyboard. Not 100% intuitive, should be able to clear the input box with normal keyboard functions.
* [x] On the transaction complete page, the "Return to..." cta, maybe that should be https://app.klimadao.finance/#/offset vs just back to the homepage.
* [x] Should we include a support email to Klima as well or is that just confusing or not necessary?

**Additional Feedback (Shimon):**
* [x] Maximum ($2000) should be enforced in the same way that minimum tonnage (1 tonne) is enforced. I am currently able to type in any tonnage amount >1.
![image](https://user-images.githubusercontent.com/99001851/199127929-de1e00cd-d872-47b6-b2b2-5f50582fd30d.png)

* [x] When I type in an amount exceeding $2000, I see a loading wheel in the cost calculation.
/> $2000:
![image](https://user-images.githubusercontent.com/99001851/199128665-40da62fe-a086-4d07-b3c5-58b294b77d6f.png)

< $2000:
![image](https://user-images.githubusercontent.com/99001851/199128711-451a0b3b-0ee9-4f2d-a6c6-f55ccb43705d.png)

* [x] When I type in something like 0.5, it adds 1 to the amount and shows 1.5. I think this is strange and should just be red text or replaced with 1. Also, I was able to trick the quantity check by selecting a token (UBO) to pay with, typing 0.5, and then switching to credit card. I then saw the same 'loading' icon as the one in (2):
![image](https://user-images.githubusercontent.com/99001851/199130187-9408c8c1-2b3f-4cb3-90a5-620339c7a793.png)

* [X] When I don't connect to my web3 wallet, the bottom button says "CONNECT WALLET". This is unnecessary since payment is made in fiat, and it's also confusing, since wallet can imply "credit card" in this instance to a non-web3 native. The question becomes - who should be the beneficiary if we don't enforce web3 wallet connection?

![image](https://user-images.githubusercontent.com/99001851/199129052-0bcbabac-3e3d-4a68-b7fb-3405d5963fa5.png)

* [ ] "Country or Region" defaults to Canada. Why is this? Is there any geographic limitation?

**Comment by Atmosfearful** [comment]
> Should we include a support email to Klima as well or is that just confusing or not necessary?

There is nothing that the DAO can do w.r.t. payment disputes, errors etc. If there is general product feedback landing in the `support` email we will make sure it gets captured and forwarded along from Offsetra to KlimaDAO
