### ISSUE TITLE
[Site] Multi-wallet Pledge Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#778]
#729 

1. I can add the same address twice, a non-address, and the same address as the pledge address. All of this should be prevented at the "save" level I believe.
![image](https://user-images.githubusercontent.com/99001851/199397627-8ee77fbc-9758-4812-a4fe-deff320c8505.png)

2. I tried adding an address that already has a pledge, and I am able to save the address in the original pledge (status "pending"), but nothing shows up in the added wallet. If that's intentional:
 - We shouldn't allow adding the wallet in the first place (updating the pledge with a new "pending" input).
 - I think there should be a way to add the wallet anyway - this would require deleting the existing pledge in the added wallet, but that's currently not possible.
 
 3. The sum total (142.54) seems to be incorrect in the pledge. It should be 142.65 according to the individual wallet retirement totals.
 
![image](https://user-images.githubusercontent.com/99001851/199407853-42d26d14-ed6d-4393-b75d-f744367777b5.png)

Wallet 1: 
![image](https://user-images.githubusercontent.com/99001851/199407918-fcccb5b5-6a78-4947-8e85-05fd9b54b6ff.png)

Wallet 2:
![image](https://user-images.githubusercontent.com/99001851/199408010-9e8ee93a-4715-4bde-8b67-ace4f51de31f.png)

4. After adding a wallet that didn't have a pledge, I made a 0.1 tonne retirement. After making the retirement, I was able to edit the pledge of that wallet, despite it already being part of another pledge (same example as the one in 3). I called the title "double counting" because this is the concern.

![image](https://user-images.githubusercontent.com/99001851/199408456-ed20b709-4ee5-4ebb-896b-4a7b0f6dfaaf.png)

**Comment by ShimonD-KlimaDAO** [comment]
@goatsOnDrugs 

1- I can still add the same address as the pledge, and moreover as many times as I want. The ability to add a non-address seems to be fixed, but I simply can't click the save button on it. I also can't remove it without closing the entire edit modal.
![image](https://user-images.githubusercontent.com/99001851/201270951-915b8f4b-6a3d-42d3-bb2b-b5e83522b8b2.png)

3 seems to be fixed. I will check 2 and 4 tomorrow.

**Comment by goatsOnDrugs** [comment]
Hey, @ShimonD-KlimaDAO thanks for testing again. 
1. I fixed the bug where the error message/style wasnt displaying when clicking "save" with an invalid address. The duplicate address check happens on save so you will se an error for the duplicate wallets after clicking "Save Pledge". 
2. When visiting a pledge that is pinned to another wallet the user should now be redirected to the parent wallet if the user has accepted the invitation.
4. should be fixed with the redirect

**Comment by ShimonD-KlimaDAO** [comment]
> Hey, @ShimonD-KlimaDAO thanks for testing again.
> 
> 1. I fixed the bug where the error message/style wasnt displaying when clicking "save" with an invalid address. The duplicate address check happens on save so you will se an error for the duplicate wallets after clicking "Save Pledge".
> 2. When visiting a pledge that is pinned to another wallet the user should now be redirected to the parent wallet if the user has accepted the invitation.
> 3. should be fixed with the redirect

This is minor, but when I try adding an invalid address and then click "add wallet" again, I get to a place when I now can't delete the original invalid address row:

**Comment by goatsOnDrugs** [comment]
@ShimonD-KlimaDAO I am working on adding validation for pledge owner adding themselves and adding a remove button for adding wallets but I believe the other issues should be fixed.

**Comment by jabby09** [comment]
Based on an new working agreement, all QA will now be included in the PR. Closing this issue.
