### ISSUE TITLE
[Website] Primary navigation has lost hover state

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#785]
On https://www.klimadao.finance/ the primary nav for most options has lost the solid green hover state (with the exception of Love Letters).

![Image](https://user-images.githubusercontent.com/103535195/200135146-326c7a23-7876-41c5-b463-8072b22426d0.png)

This may have been a regression when the nav changed for launch of the new resources page.

**Comment by ladytrekker** [comment]
The green hove state is only defined for menu items which do not have a submenu.

Sidenote: This is not a change from the Resources Release as this did not change any styles for the Main Navigation.
