### ISSUE TITLE
[App] Advanced selective retirement filters - QA Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#800]
#743 

1. The cost info message should also mention the selective retirement fee.

2. The following is not accurate. Maybe "Allow the default project in the pool to be retired", since KlimaDAO is not responsible for choosing here?
![image](https://user-images.githubusercontent.com/99001851/202835343-04ca7321-0be4-4665-a761-6948aa3d75c1.png)

3. (a) Retiring default BCT using NCT as payment encounters an error (this might be smart contract related since the error is "execution reverted"):
![image](https://user-images.githubusercontent.com/99001851/202835457-2efea485-c265-495b-98f0-f4b726bbdfe8.png)

    (b) Retiring default BCT using BCT as payment encounters same error as (3):
![image](https://user-images.githubusercontent.com/99001851/202835485-fab12b34-5df6-4891-84be-efa76459f549.png)

    (c) Selective UBO (paid with UBO) - same issue:
    
![image](https://user-images.githubusercontent.com/99001851/202835767-038754f0-52fb-4605-83aa-09b22229e354.png)

4. I don't see a scroller. Only the down arrow works. (Chrome and Brave on Desktop at the very least).
There is also no scroller in the filters.
![image](https://user-images.githubusercontent.com/99001851/202835536-ab60ef8f-4fe3-44bb-9313-b19287261fc8.png)
![image](https://user-images.githubusercontent.com/99001851/202836137-a0797f17-7be1-46ff-963a-a561cf5b7165.png)

5. There seems to be lots of duplicate projects (VCS875, VCS929 below):
![image](https://user-images.githubusercontent.com/99001851/202835570-6d518051-6bf6-48a7-aa87-6c1f1521465f.png)
![image](https://user-images.githubusercontent.com/99001851/202835682-ade61ac1-c39c-4f68-9dab-7cb8deac568e.png)

6. I believe the reason for (3) might be that I'm allowed to select projects that aren't in the pool. The following is a UBO project, not a BCT project. Highlighted address in the 2nd screenshot.
![image](https://user-images.githubusercontent.com/99001851/202835933-785ab88f-6b87-449b-9ec3-1dfedca5b987.png)
![image](https://user-images.githubusercontent.com/99001851/202835962-865fe1fc-790e-4a04-91aa-e934a65d6d0a.png)

7. What is vintage 1970? That shouldn't be possible.
![image](https://user-images.githubusercontent.com/99001851/202836160-514456dc-c51c-4ea7-ba17-1279f26f898b.png)

**Comment by 0xAeterno** [comment]
@ShimonD-KlimaDAO 
Let's forward this feedback to the data peeps. The frontend results is representative of the underlying subgraph data.
That said, I believe the team is aware that there is subgraph data refinement work to clean up the source we're querying from.

**Comment by 0xAeterno** [comment]
Also @ShimonD-KlimaDAO on point 4.
They should all be scrollable, I believe the design was intentional.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO @0xAeterno @cujowolf  re #6 above, I noticed that as well.
The intent with the form flow is we limit the available projects based on the users selection of offset token to retire (i.e. the first field in the form). So if I select BCT I should only be able to filter/select projects from the BCT pool (https://carbon.klimadao.finance/BCT), or if I select NBO only be able to filter/select projects from the NBO pool (https://carbon.klimadao.finance/NBO).

On the front end, if I have explored projects based on a token pool and have results, if I then change my offset token to retire to another token, the Find Project area should reset back to nothing selected and the Find Project CTA

**Comment by ShimonD-KlimaDAO** [comment]
> Also @ShimonD-KlimaDAO on point 4. They should all be scrollable, I believe the design was intentional. cc: @theprofessora

It scrolls, but I meant that we are missing a visible scroll bar. Similar to the ones we have elsewhere in the app.

**Comment by 0xAeterno** [comment]
@ShimonD-KlimaDAO @jabby09 

1) Could you please elaborate on #1. Not quite sure what we're referring to here.

2) Actioned

3 & 6) Great pick up! Updated to return projects belonging in a given token pool. @jabby09 could we please include details like this in the brief next time. These specifications aren't clear based off the designs themselves, ty! :)

4) Yep, the scroll bars were intentionally omitted in the designs. I chucked them back in for the filter selections. The scroll bar looks a bit weird on the project selection section though. (cc: @theprofessora)

Questions:
- How should we handle if a user selects MCO2 as their retirement token. Should we block them from advanced retirement filters?

**Comment by jabby09** [comment]
@0xAeterno 100% we can do a better job on the design --> dev handoff. Will make a better effort to ensure the figma files have business logic comments as well.

**Comment by ShimonD-KlimaDAO** [comment]
> @ShimonD-KlimaDAO @jabby09
> 
> 1. Could you please elaborate on 1). Not quite sure what we're referring to here.
> 2. Actioned
> 
> 3 & 6) Great pick up! Updated to return projects belonging in a given token pool. @jabby09 could we please include details like this in the brief next time. These specifications aren't clear based off the designs themselves, ty! :)
> 
> 4. Yep, the scroll bars were intentionally omitted in the designs. I chucked them back in for the filter selections. The scroll bar looks a bit weird on the project selection section though. (cc: @theprofessora)
> 
> Questions:
> 
> * How should we handle if a user selects MCO2 as their retirement token. Should we block them from advanced retirement filters? There's only one Moss half filled "project" on the [subgraph](https://graphlooker.com/explore?uri=https%3A%2F%2Fapi.thegraph.com%2Fsubgraphs%2Fname%2Fklimadao%2Fpolygon-bridged-carbon&e=CarbonOffset&th=undefined&efd=carbonOffsets&filterObj=%5B%7B%22filterName%22:%22_is%22,%22columnName%22:%22bridge%22,%22inputValue%22:%22Moss%22%7D%5D). Feels like we should force them down the "default" path.
> * Have we heard from data about carbon projects that have been indexed with a 1970 vintage?
> * What are (if any) the blockers from qa preventing this release?

For (1), I meant that the message the user sees when hovering over the info icon next to 'Cost' should include "selective retirement fee", since that's a substantial part of the cost (about 33% in the case of BCT).

`How should we handle if a user selects MCO2 as their retirement token`
- We should not allow advanced retirement for MCO2, since it is not possible to do selective retirements with MCO2. I see that you've already disabled the two tabs for MCO2, and it looks great!

`Have we heard from data about carbon projects that have been indexed with a 1970 vintage?`
- The "Vintage" column is correctly populated with a unix timestamp, but the "Vintage Year" column is not populated correctly for C3. We are discussing right now on Discord, and I'll update this note later.
**This is the main blocker for release**


In addition:
1. (medium impact) We shouldn't have the option to select a single box that doesn't have any matching records. For example, there is 1970 vintage in UBO and NBO, but not in BCT and NCT, but it's available as an option in NCT, returning nothing with a single box selection. That seems to me like poor UX.
![image](https://user-images.githubusercontent.com/99001851/204961052-795bfc0c-e4bd-433b-b78e-cc5cb56b2443.png)

2. (low impact) I'm only able to select BCT or MCO2 to retire by paying with wsKlima.

**Comment by ShimonD-KlimaDAO** [comment]
@0xAeterno 

It's really smooth and great UX! I was just going to say it's ready when I noticed something strange with c3 pools. There are selective projects available, but I can't find them using the vintage. When selecting all vintage years, I get nothing. 

![Screenshot_20221207-103206_Brave](https://user-images.githubusercontent.com/99001851/206267538-5db01848-d3e2-4e31-a515-62ed3168fe9e.jpg)
![Screenshot_20221207-103213_Brave](https://user-images.githubusercontent.com/99001851/206267563-8c4e1bdd-fe31-48e8-9aa9-2844a5536889.jpg)


Selective projects exist when filtering by other categories:
![Screenshot_20221207-103234_Brave](https://user-images.githubusercontent.com/99001851/206267739-2a8b506b-43bb-4131-b456-3734ab45d6cf.jpg)

**Comment by ShimonD-KlimaDAO** [comment]
Issue above is resolved.

Probably the last feedback:
Can we make the text red when the user tries to retire more than available in the selected project?
![Screenshot_20221207-205651_Brave](https://user-images.githubusercontent.com/99001851/206360500-3437902e-6608-48c1-8286-962c2e134204.jpg)
