### ISSUE TITLE
[retirement] PDF receipt not rendering properly

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#802]
As reported by Dionysus, the PDF receipt download is not rendering properly.

![Image](https://user-images.githubusercontent.com/103535195/203345286-81bd0596-abd4-4fdb-9324-f19f7c198398.png)

Can use this as an example: https://www.klimadao.finance/retirements/brice.klima/8

Also include an actual PDF.

[retirement_8_0xea4d28f8218f44c84c8d7cbae5deac41acf66ced.pdf](https://github.com/KlimaDAO/klimadao/files/10068468/retirement_8_0xea4d28f8218f44c84c8d7cbae5deac41acf66ced.pdf)

**Comment by Atmosfearful** [comment]
#803 here is where I did some experimentation (unsuccessful)

**Comment by jabby09** [comment]
@0xAeterno @Atmosfearful this appears to be resolved. Is the pdf page now using the new code or did we uncover why the production version of the pdf started working again pre-merge of this fix?

**Comment by 0xAeterno** [comment]
@jabby09 

> @0xAeterno @Atmosfearful this appears to be resolved. Is the pdf page now using the new code or did we uncover why the production version of the pdf started working again pre-merge of this fix?

I think how the certificates resolved itself is going to remain a mystery @jabby09. We may have updated some dependancy or maybe vercel updated fixed something in their deployment environments 🤷‍♂️.
The PR for server rendering certificates via an api is still up (https://github.com/KlimaDAO/klimadao/pull/822)

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO did you have a chance to QA the PR #822?

I will also try and give a test run on Thursday.

**Comment by jabby09** [comment]
@0xAeterno @Atmosfearful I've tested a bunch of my retirements, seems to be working well. Tested in Chrome, FF, and Safari (I don't have Edge). Also worked well on my iPhone.

A nit pick on long project names, they are not wrapping and getting cut off but probably not a high priority ([example](https://klimadao-site-git-retirement-certificates-via-api-klimadao.vercel.app/retirements/brice.klima/10))

Thumbs up from me to release to production.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO see above, anything you want to add or are we good to release this?

**Comment by jabby09** [comment]
@Atmosfearful this one is good to go to production

**Comment by ShimonD-KlimaDAO** [comment]
This looks good. Closing.
