### ISSUE TITLE
[retirement] Add "Pledge" CTAs to the retirement receipt page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#816]
As part of the Fiat 2 Retirement workstream, the retirement receipt page was enhanced.

Enhancements related to social share icons was handled in #755 

This ticket addresses the updates required to complete the user journey following an offset and adds logic and CTAs for accessing or creating a "pledge"

[Figma file here](https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=1609%3A1771&t=kUrcizNSoUOMp6Vo-0#307609267).

Logic (designs provided for each case)

```
query for pledge
if exists -> VIEW PLEDGE
if not -> “This user has not created a pledge” - Is this your retirement? Create a pledge now
```

**Comment by jabby09** [comment]
@0xemc here you go for 2nd part of retirement receipt page enhancement. Let me know if you have everything you need?

**Comment by jabby09** [comment]
@0xemc I think this is good to go and your next priority? (let me know if you have something else already in progress)

**Comment by jabby09** [comment]
Hi @0xemc checking in on this one, what is the ETA to have this ready for QA?

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO this is ready for QA  https://klimadao-site-git-816-retirement-pledge-ctas-klimadao.vercel.app/retirements/brice.klima/1

I will also take a look at this over the weekened.

**Comment by jabby09** [comment]
@0xemc first QA pass had success! Need to try a few more environments and edge cases but so far so good!

**Comment by ShimonD-KlimaDAO** [comment]
@jabby09 @0xemc minor feedback I left on the PR - missing a period. All else looks good with this PR (although I found some issues with the pledge dashboard that are unrelated and will be in a different ticket).
