### ISSUE TITLE
[retirement] Add project details to MCO2 receipt

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#821]
When a user offsets/retires from the Moss MC02 pool, the retirement receipt is missing the project details.

[Example](https://www.klimadao.finance/retirements/brice.klima/5)

There is only one project in the MC02 pool, however, should still display the details on the project.

**Comment by jabby09** [comment]
After discussion with Sy, we should go ahead an make a UX improvement on this receipt page.

**Current display**

![Image](https://user-images.githubusercontent.com/103535195/209154703-9198fbad-0405-4e5f-8583-0e875fae9424.png)

**Suggested improvements**

- Make a link to https://mco2token.moss.earth/ and the primary CTA or main link since it describes the projects.
- Have a secondary CTA link like "View MCO2 pool activity" and link to the MC02 page on the carbon dashboard.

@theprofessora will need a quick design for this one before handing off to a dev.

**Comment by theprofessora** [comment]
Would something like this do the trick?

![Image](https://user-images.githubusercontent.com/110631623/209174862-c0226b63-9084-4e01-b36e-2b7f3b30b896.PNG)

**Comment by jabby09** [comment]
@theprofessora works for me!
