### ISSUE TITLE
[dApp + Website] Update /buy Website Page & Buy Klima App Feature

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#826]
See [product roadmap card](https://www.notion.so/klima-dao/Buy-KLIMA-Simplification-6193d6c9ac3346ad9de5c1eaf7031193) for problem statement and solution summary.

### Solution

We will tear out the Mobilum widget and improve this journey over several iterations.

### V1 - no-code solution

- Instead of Mobilum, after connecting a wallet, the app will send **all users to read our tutorial at [[klimadao.finance/buy](http://klimadao.finance/buy)](http://klimadao.finance/buy)**
- We will rewrite the buy tutorial
- The new tutorial will direct all users to an **external Polygon MATIC onramp** (moonpay, transak, or a CEX) and then to ************************************************swap MATIC for KLIMA on [sushi.com](http://sushi.com/)************************************************
- The final step of the tutorial directs them back to the app where they should see their new KLIMA balance

The copy for the update /buy page (to replace [this page](https://www.klimadao.finance/buy)) is here:

[Final draft buy tutorial](https://www.notion.so/klima-dao/Final-Draft-buy-tutorial-0b95e7fc17914223a9d60d35643e9ffb)

Next step:

- [x] The new content does not match the existing template layout very well anymore. Need @theprofessora to do a quick redesign and maybe create some better screenshots (like fancy fullwidth resolution ones w/ bg colors?). Engineering pretty much just need to know what headings, subheadings etc. to use and how to position the example images.

DEV AC:
- [ ] unconnected user should see message to connect and connect button
- [ ] connected user should see a link to "klimadao.finance/buy" 
- [ ] connect button text should be updated app wide to "Login / Connect" 
- [ ] remove mobilum (including any packages)

**Comment by theprofessora** [comment]
updates to the app UI: https://www.figma.com/file/pAbTJif04VlidcPM491ahS/BUY-KLIMA?node-id=801%3A501

**Comment by theprofessora** [comment]
@Atmosfearful @jabby09 Isn't the blog managed by a CMS? If so, then I don't think I'll be able to do much design on the article itself.

**Comment by theprofessora** [comment]
Okay @Atmosfearful @jabby09 I've laid everything out here: https://www.figma.com/file/pAbTJif04VlidcPM491ahS/BUY-KLIMA?node-id=801%3A501

**Comment by jabby09** [comment]
Thanks @theprofessora 

@Atmosfearful does this give you what you need, ready to hand off to goats?

**Comment by goatsOnDrugs** [comment]
@jabby09 @theprofessora is this AC I wrote correct? "connect button text should be updated app wide to "Login / Connect"" and if so is this app and site wide or just app?

**Comment by theprofessora** [comment]
@goatsOnDrugs both app and site wide

**Comment by jabby09** [comment]
@goatsOnDrugs the AC looks good to me
