### ISSUE TITLE
[retirement] Fee breakdown details panel enhancement

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#827]
[Discord thread](https://discord.com/channels/841390338324824096/967377329171099648/1049734250523533362)

**Enhancement request:** Have a more robust "fee breakdown" panel instead of just referring to the fees

**Inspiration:** kind of like how sushi shows it with "Liquidity provider fee: ", "Retirement aggregator fee: ", "Selective retirement fee: " (if applicable)

![Image](https://user-images.githubusercontent.com/103535195/207868621-7f1adcf4-134d-42d8-894b-79563c6a9174.png)

**Comment by jabby09** [comment]
More insights from @0xAurelius 

- I don’t think we need to update the carbon dashboard since we’re just quoting prices and cost to selectively retire there - we can’t define slippage without knowing the amount to be retired and the 1% convenience fee only applies if people retire via the aggregator
- I think the fee breakdown just needs to be shown once on the retire interface, similar to how Sushiswap or 1inch shows the fee breakdown before you send the transaction

**Comment by theprofessora** [comment]
Okay I have a first draft here that includes 2 options: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=1824%3A6421

Option 1 is a simple panel that lists what the fees are, and the % of the transaction they'll be.

Option 2 is a dynamic panel that updates in real time to show the user the actual cost of the fee as they increase or decrease the total tonnes offset

**Comment by jabby09** [comment]
@0xAurelius see professors comment above and link to design file. Since you raised this enhancement, any feedback on the options?

**Comment by jabby09** [comment]
@Atmosfearful this is [final shipped design](https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk/CARBON-OFFSETTING?node-id=1915%3A6962&t=5X13FWj1tUSoYIX5-0)

Ready for dev handoff when we have capacity.

**Comment by sy-zygy** [comment]
@theprofessora we should add this breakdown a line item like:

Carbonmark fee: $0

**Comment by Atmosfearful** [comment]
@cujowolf can you tell me if there is a convenient way to know what fees are actually being applied?
- how do I know if it's the default project being retired (hardcode it? 🤮 )
- how do I know what the bridge fee is (hardcoded map for each pool token?🤮)

If these fees are additive, can I safely multiply a % by the quoted price, or is the math more complex than that?

**Comment by Atmosfearful** [comment]
@0xAeterno this will probably destroy all assumptions that the modal has, if you are unsure why the modal acts a certain way maybe set up a call with @ladytrekker to ask

**Comment by jabby09** [comment]
@Atmosfearful see https://github.com/Atmosfearful/bezos-frontend/issues/441 which is related to this issue, but on the Carbonmark side

I asked similar question in that ticket, [marcus replied](https://github.com/Atmosfearful/bezos-frontend/issues/441#issuecomment-1491862949)

> fee info is available on the smart contracts for each pool. see the logic we use in the Carbon Dashboard here: https://github.com/KlimaDAO/dash-apps/blob/3d806e19a6a9258ce5f5845a8a97a62e016ed919/src/apps/tco2_dashboard/helpers.py#L640
> 
> the 1% retirement aggregator fee is fixed, and should also be available as a smart contract read function, need to check with @cujowolf on that

**Comment by Atmosfearful** [comment]
This was resolved on the fee side in #1355
