### ISSUE TITLE
[connect modal] Tech debt - separate modal from button

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#828]
After merging #799 

Rather than rending a new modal wherever the button is used, we can render one modal and place it higher in the react component tree in Site and in App. It can be controlled to show/hide based on react context

The react context which controls the modal can be triggered using a hook, ideally `useWeb3`. For example
```jsx
const { toggleModal }  = useWeb3();

return <button onClick={toggleModal}>Click Me To Show The Connect Modal</button>
```

Why this pattern?

- We can use any button or any component to trigger the Connect modal
- We won't need style overrides like we do in all the app views (`100% width`)
- Can remove a lot of lines of code repeating those modal props over and over

**Comment by goatsOnDrugs** [comment]
This will also fix the bug where two modals pop up if you have cached provider on pages with two modals (ex: buy page)
