### ISSUE TITLE
[connect modal] app button wiggles when the modal opens

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#829]
After merging #799 

it moves to the left a bit. Probably rendering a blank space or something

![image](https://user-images.githubusercontent.com/88635679/207989492-072eb886-f462-4824-aba3-8d6e4ec4f919.png)

**Comment by 0xAeterno** [comment]
Decoupling the modal from the button should fix this layout shift

**Comment by jabby09** [comment]
@goatsOnDrugs @Atmosfearful this one has a status of Done but is still open and I do not see a PR?
