### ISSUE TITLE
useWeb3Modal - remove all `any`s and write proper types for all interfaces

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#831]
There are several uses of `any` in the useWeb3Modal hook. I know it's a pain but strict typing pays off in the long run.
We can at least write custom types and assert the type rather than asserting `any`.

**Comment by goatsOnDrugs** [comment]
@Atmosfearful I think this one was completed in other PRs. we now only have this case of any which seems intentional `const getWeb3Provider = (p: any): TypedProvider => {
  return new providers.Web3Provider(p) as TypedProvider;
};` and this error type is any `catch (e: any) {`
