### ISSUE TITLE
[retirement] Retirement message text wrapping bug

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#836]
On this [retirement receipt](https://www.klimadao.finance/retirements/0x918bbF4aB4516a79461B4A12eba98cc52C742d88/1), the retirement message is not rendering properly, i.e. not wrapping to stay within the contain with appropriate padding.

![Image](https://user-images.githubusercontent.com/103535195/208438190-6b0ff266-08dc-4b32-a289-12df28b3d407.png)

**Comment by Atmosfearful** [comment]
@0xemc easy fix just needs `word-break: break-word;` 
![image](https://user-images.githubusercontent.com/88635679/208715357-6cbdbcad-90da-43ed-a8d1-72f6077a4cba.png)

**Comment by jabby09** [comment]
@0xemc any chance we can get this one fixed this week?
