### ISSUE TITLE
[connect modal] Metamask option not showing

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#847]
Even if I have already connected to metamask, the option is not showing up in the modal

![Image](https://user-images.githubusercontent.com/103535195/209346843-33d82f8f-3643-423d-b1b5-15ffc296962d.png)

**Comment by Walletsuppport** [comment]
We'd be happy to look into this for you. kindly file a support ticket below 
https://forms.gle/Wmpm6NLzYm9uXYuU9

**Comment by jabby09** [comment]
This was related to having multiple wallet extensions and related conflicts.
