### ISSUE TITLE
[Pledge] Multi-Wallet Missing Redirect

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#850]
@goatsOnDrugs 
The wallet I added to my pledge does not redirect to it. This is not a latency issue - I gave it some time.

[This wallet](https://www.klimadao.finance/pledge/0xcb5e908541c595d102e0b9c67d6bc224a86ef34a) should redirect to [this wallet](https://www.klimadao.finance/pledge/shimond.klima) since it accepted the push request from the latter (shimond.klima's) pledge. 

I see the former as a wallet on the latter's page (note that it's not "pending"), but the former doesn't redirect to the latter:
![image](https://user-images.githubusercontent.com/99001851/209452021-cdc673ee-1e22-4bd5-a90f-04f0896669f7.png)

Note that I created the pledge for the former after accepting the push request from shimond.klima. 
This should not be allowed, or at a minimum redirect should still happen.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO looks like the PR attached to this ticket is ready for retest
