### ISSUE TITLE
[Selective Retirement] Community Feedback

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#851]
Recording useful community feedback from Garmon#6089. NOTE: This needs to be reviewed by Professor and approved before dedicating time to it.

1. It would be nice if it's possible to use the filter without needing to select a carbon offset token. The token required for said project could be displayed after you hit find project. Otherwise it's quite time consuming to go through each carbon pool. 

2. It's not obvious that to go to the corresponding Verra page for the project, you need to click the VCS code of the project. "Project Details Page" or something could be a band aid solution.

CC: @theprofessora @0xAeterno @jabby09

**Comment by jabby09** [comment]
thanks @ShimonD-KlimaDAO for capturing this feedback and @0xAeterno for your review/assessment.

I figured (1) would be a bigger change. Given we are moving towards bezos and eventually migration of selective retirement in that application is is unlikely we would prioritize this feature in the aggregator. However, I will capture this in my [Feature Request page](https://www.notion.so/klima-dao/Feature-Requests-8ba32bb6d44446669b9edcd05774dd51#4095314c914949599a56bd56cc08ac80) in Notion in case it comes up again or does become a priority. 

Re: (2) that sounds like an easy but high value enhancement, I will create a new enhancement ticket for that and assign to @theprofessora for a quick design.

**Comment by jabby09** [comment]
See #863 which is the action item and closes this issue.
