### ISSUE TITLE
Update /retirements/ page footer CTAs

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#856]
This should be a shared component on both /retirements/ and /retirements/[index]

Instead of pitching KLIMA tokens, let's pitch offsets which aligns better with our current sales strategy.

# Current
![image](https://user-images.githubusercontent.com/88635679/210415261-1911e431-f5ac-420c-b42f-c7a46a9a2daa.png)

# New Text

~ABOUT KLIMA~ ABOUT KLIMADAO

| left column | right column |
| --- | --- |
| We've radically enhanced the transparency, liquidity, and efficiency of the Voluntary Carbon Market. | Our tools make it easier and cheaper for any business to buy, hold, trade and retire any verified quality carbon offset project. |

| card |
| --- |
| Pledge, acquire, retire. |
| Create a pledge page to highlight your sustainability goals, then use our webapp to retire from a massive selection of verified carbon projects. |

| button left | button right |
| --- | --- |
| CREATE A PLEDGE | BROWSE PROJECTS |
| navigates to /pledge/ in new tab | navigates to app.klimadao.finance/#/offset in new tab |

**Comment by jabby09** [comment]
This is being redesigned for Carbonmark.
