### ISSUE TITLE
regression: various buttons have a circle style applied

### ISSUE THREAD

**Issue by 0xAeterno** [KlimaDAO/klimadao#861]
Various buttons which previously did not have a circle style applied are now styled as circles.

| What | Before | After |
| ----- | ----- | ----- |
| Resource bar search and filter option button | <img width="388" alt="image" src="https://user-images.githubusercontent.com/97446324/211015646-3305d340-0539-41db-b59b-d278c6b7afcd.png">|<img width="390" alt="image" src="https://user-images.githubusercontent.com/97446324/211015780-2a19c18c-4f75-4191-b749-cab2d6f577ff.png">|
| Pledge form |  <img width="528" alt="image" src="https://user-images.githubusercontent.com/97446324/211016246-7ebf1a72-2dcb-440b-81ac-3406ca9a56e8.png"> | <img width="548" alt="image" src="https://user-images.githubusercontent.com/97446324/211016357-127a9a0d-7d72-42f2-967a-14f2e2102e19.png"> |

Link to previous build before regression introduced: 
- [Resource center](https://klimadao-site-git-goats-icon-bug-klimadao.vercel.app/resources)
- [Pledge](https://klimadao-site-git-goats-icon-bug-klimadao.vercel.app/pledge)

I've tracked the style regressions to this line that applies the circle styles:
https://github.com/KlimaDAO/klimadao/blob/038e1a4666a8ab9984b0089afa0653aa7584c4b7/lib/components/Buttons/ButtonBase.tsx#L33-L37

**Comment by 0xemc** [comment]
Hmm this was dangerous to effect existing styles.. I've made the functionality `opt-in` now.  That should fix any other cases of this throughout the app and site.

https://github.com/KlimaDAO/klimadao/pull/882
