### ISSUE TITLE
[retirement] Improve UX of Verra project page link

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#863]
This feature request came from a community member and was captured in #851 

**Feedback/Suggestion:** It's not obvious that to go to the corresponding Verra page for the project, you need to click the VCS code of the project. "Project Details Page" or something could be a band aid solution

**Developer Comment:** Agree with this. The verra project page link wasn't part of the initial brief but I included it because it felt sensible to do so. I think we can more intentionally expose the link.

**Next steps:**

- [ ] @theprofessora to provide design recommendation to improve the UX of this feature

**Comment by theprofessora** [comment]
I think this is the solution for now (see below). It's starting to feel a bit cluttered visually, but everything will improve once we start to publish the new designs from our re-imagined KI User Journey



![Image](https://user-images.githubusercontent.com/110631623/211610425-f203a941-c5d8-4d8b-a228-065e7ce4e936.png)

**Comment by theprofessora** [comment]
> - Take the font down to 14px (and reduce the size of the icon accordingly)
> - remove underline
> - change wording to "view project details"

sounds good

**Comment by 0xAeterno** [comment]
Thanks @theprofessora, I'll have a play around and tag you in the PR for final approval :)
