### ISSUE TITLE
[offset] Add link to the retirement page

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#864]
Feature request from Dionysus in [Discord](https://discord.com/channels/841390338324824096/964698337230086174/1060540942802763846)...

**Suggestion:**

On the [Offset page](https://app.klimadao.finance/#/offset) of the app, can we provide a link to the users retirement page? For example, could we have a box above "you've retired" with a link to the retirement page? You can 'view retirement' directly after completing one but otherwise you would need to bookmark the retirement page link for your wallet.

![Image](https://user-images.githubusercontent.com/103535195/211077848-b5ce4c54-6f8f-4f98-bdec-ca451e2551bd.png)

**Other Considerations:**

- The design would just need to also account for the initial state of your first retirement (so no link yet)

**Next Steps:**

- [ ] @theprofessora to provide a design recommendation, taking into account a first time user with no retirements, and an existing user with retirements.

**Comment by theprofessora** [comment]
I think the easiest and most practical solution is to add some sort of secondary CTA directly to the "You've Retired" card like this: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk?node-id=1892:6454#342437209



![Image](https://user-images.githubusercontent.com/110631623/211613890-215e54c4-3465-4a42-877a-f74656829f02.png)

**Comment by theprofessora** [comment]
jk there's a new design w/ a btn instead. see here: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk?node-id=1892:6455#342516717



![Image](https://user-images.githubusercontent.com/110631623/211634033-5ddd0d17-8135-47c3-988f-6dfaf90ca2e0.png)

**Comment by jabby09** [comment]
@Atmosfearful design complete and ready for dev assignment when we have bandwidth.

Drew asked for this one so that probably gives it a higher priority and it is a nice enhancement.

**Comment by jabby09** [comment]
@0xMakka checking in that you noticed this one was assigned to you?

**Comment by 0xMakka** [comment]
@jabby09 Yes apologies, will be picking up later today. 👍

**Comment by jabby09** [comment]
cool, cool - just checking in. All good, thanks for the update!
