### ISSUE TITLE
[connect modal] Torus/ walletconnect issues found

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#868]
- Torus threw a 'browser not supported' error
- WalletConnect got stuck and kept popping up, even when id click torus

Still need to figure out the reproduction steps
This might just be stale sessionstorage/cookies

**Comment by goatsOnDrugs** [comment]
@Atmosfearful I'm able to connect with wallet connect and torus. Were you able to reproduce this?
