### ISSUE TITLE
[retirement] Receipts rounding to 0 is inconsistent

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#869]
I believe the following three areas should all follow the same convention. At the very least, I would expect the 2nd bullet point to follow the convention of the 3rd, since 0 doesn't look good.

1. The \retirements\ page shows exact amounts. For example:
![image](https://user-images.githubusercontent.com/99001851/211638562-55860f9d-32f6-4506-bef7-b10486e43aa3.png)

2. The retirement receipts themselves round anything less than 0.01 to 0. [Example](https://www.klimadao.finance/retirements/shimond.klima/35)

3. The actual PDF shows "<0.01". Example:
![image](https://user-images.githubusercontent.com/99001851/211638772-de7e0093-8dfa-4a97-a78e-40ad062f8d4d.png)

**Comment by Atmosfearful** [comment]
Low effort one when you get some down time @0xAeterno 
We have some utils that trim trailing zeros
I would show 2 decimals if it's moer than 1 tonne retired

And 4 decimals if it's less than 1 tonne retired. Open to suggestions though.

**Comment by jabby09** [comment]
@sprrwhwk note since this ticket was created the retirement receipt design has changed. 

May or may not still be an issue.

If you want to see examples you can start from this page: https://www.carbonmark.com/retirements/brice.klima

**Comment by wowselim** [comment]
@jabby09 do we support localization here? Should we for example show 1,3 tonnes instead of 1.3 tonnes for German users?

**Comment by sprrwhwk** [comment]
@jabby09 do we support localization here? Should we for example show 1,3 tonnes instead of 1.3 tonnes for German users?

**Comment by jabby09** [comment]
> do we support localization here? Should we for example show 1,3 tonnes instead of 1.3 tonnes for German users?

@ShimonD-KlimaDAO I assume this is not part of our translation work?

**Comment by jabby09** [comment]
> Low effort one when you get some down time @0xAeterno We have some utils that trim trailing zeros I would show 2 decimals if it's moer than 1 tonne retired
> 
> And 4 decimals if it's less than 1 tonne retired. Open to suggestions though.

I reviewed this one again, I think it's fine for now.
