### ISSUE TITLE
[pledge] Cosmetic Issues

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#871]
1. When a pledge doesn't exist ([example](https://www.klimadao.finance/pledge/0xfd12a9686a719094d940682ea944ca4afffc9493)), we shouldn't say the following, but just something like "This wallet has not yet created a pledge" (refer to @theprofessora for wording)
![image](https://user-images.githubusercontent.com/99001851/211652319-1849679e-cb9c-48e4-a433-0b9fa7a92dc5.png)

2. My test wallet [pledge](https://www.klimadao.finance/pledge/shimond.klima) has wrapping text.
![image](https://user-images.githubusercontent.com/99001851/211652565-d39332f5-972c-491a-8fd9-5852572b85f8.png)

**Comment by 0xAeterno** [comment]
@theprofessora is there an alternative design you could provide for point 2.
I feel like this is more of a design constraint given the space we've got to work with.

**Comment by theprofessora** [comment]
Sure thing. Sorry somehow i completely missed item 2. Let's go with something like this:
https://www.figma.com/file/moDUIfGjQaISUGDjLxyko4?node-id=408:1784#347416027

also seen here:
![image](https://user-images.githubusercontent.com/110631623/212950909-902ad0f4-545d-43ba-9b7e-816f822a22a7.png)

**Comment by jabby09** [comment]
@theprofessora for consideration as you migrate /pledge to Carbonmark
