### ISSUE TITLE
[retirement] Selective retirement option for redeemed tokens (tco2, c3t) user owns

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#879]
Need to support selective retirement of redeemed tokens (like tco2 or c3t) that a user already has in their wallet.

This is in support of the ability to Redeem specific project tokens #735 

This feature has been covered off in bezos but needs to also be added to the retirement aggregator with timing aligned with rollout of redeem capability.

- [x] TASK#1 need a design review and updated designs to support this feature

**Comment by theprofessora** [comment]
Here's the first draft: https://www.figma.com/file/HXwNOLfM9CQHgwmouz0rpk?node-id=1923:7226#345457472

**Comment by jabby09** [comment]
hey @0xAeterno I believe you mentioned you are now working on this issue so I've assigned to you. Let us know if you need more detailed/flushed out requirements in the ticket.

**Comment by jabby09** [comment]
leaving a comment here from a DM with @Atmosfearful 

> So I got all the ui work done and wrote all the transaction code for retiring-own-carbon with the v2 aggregator
> However the transaction itself fails, as does the code to fetch previous retirements
> so that got me stuck and im gonna write up my exact inputs and pass to cujo
> also I realized I don't think the retirement pages are set up well to handle own-carbon.
> 1. the retirement pages refer to pool token (bct, nct, ubo), which doesn't exist when you retire tco2 directly, and which I now feel like is the completely wrong approach to UI/UX. Future thinking: carbonmark should try to hide all this pool stuff away-- so future design ticket for us is to revist the pages and rethink the page heirarchy and what we emphasize (projects, not pools!) 
> 2. I need to get the tco2 and c3 icons in there as well as pass down the token name (C3-VCS-123-2022) not sure how hard that is
> 3. and potentially (hopefully not) rewire how we actually fetch previous retirements, if it turns out the current wiring isn't picking up these tco2 retirements at all. But first, to do that, I need to get a retirement txn to work lol

**Comment by cujowolf** [comment]
v2 contract changes are made to resolve the issues outlined. 

Specifically the updates to properly storing the amount of a project token retired. Our docs are also updated to reflect the latest abi.
