### ISSUE TITLE
[resources] Podcast filtering auto downloading on Safari

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#890]
Original report on the issue in [discord](https://discord.com/channels/841390338324824096/964698508751949824/1062347009488601148).

> Hi guys, whenever i interact with the "Podcast" filtering feature on /resources, i get a bunch of files downloaded to my desktop. See a recording of how this looks, screenshot of the files in my downloads.

**Triage Notes**
This is only happening in Safari. Chrome and Firefox do not initiate an auto download. I changed the setting to "ask" for downloads and then you are prompted
![Image](https://user-images.githubusercontent.com/103535195/212544887-b4be0f4e-d86b-4f05-9104-8366c18bf59c.png)

Also happening on mobile safari:
![Image](https://user-images.githubusercontent.com/103535195/212544906-9ec3c490-1524-41a3-8d37-226f812c4a33.png)

Likely about 20% of the users who visit that page will get that

**Action Items**

- [ ] @Atmosfearful adding a research item on todo list need to see if other people have this problem with spotify iframes

**Comment by Atmosfearful** [comment]
Fixed in https://github.com/KlimaDAO/klimadao/pull/913
