### ISSUE TITLE
[resources] Mobile view button text missing in lightmode

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#891]
In light mode on the Resource Center, the button text Search and Sort by select are not visible. On desktop in lightmode the search button text (magnify glass) is also not visible.

![Image](https://user-images.githubusercontent.com/103535195/212545230-ce00708b-8b1a-4b48-b4b2-89cad5a71b58.png)

**Comment by 0xAeterno** [comment]
@jabby09 raised this with @0xemc - this is addressed with his great work in https://github.com/KlimaDAO/klimadao/pull/882 :D

**Comment by Atmosfearful** [comment]
@0xMakka can you see if this is still reproducible, if not lmk and ill close this

**Comment by 0xMakka** [comment]
@Atmosfearful the issue looks to be resolved with the search icon, however on light mode the icon is missing from the sort button.

<img width="360" alt="Screenshot 2023-01-23 at 20 34 11" src="https://user-images.githubusercontent.com/92357475/214144510-42812c46-afc4-4970-8b00-ac28e174dc10.png">

Also the circle button looks to have a different height than width making it look slightly skewed, so I'm happy to address these issues under this ticket? Below is the proposed UI fixes I would be making

<img width="360" alt="Screenshot 2023-01-23 at 20 37 26" src="https://user-images.githubusercontent.com/92357475/214144703-ef71c4be-ea5b-4b18-a7ec-d02b630d7239.png">

**Comment by 0xMakka** [comment]
Ignore what I mentioned above, I've just noticed on production this is resolved. 

@Atmosfearful I reckon this ticket can be closed off. 👍

**Comment by jabby09** [comment]
@0xMakka @Atmosfearful can confirm this is now resolved!
