### ISSUE TITLE
New approval and transaction modal experience

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#9]
We can solve bug reports related to insufficient approvals for a few users, and improve UX significantly.
Migrate from "max approvals" like 1000000000 to "as-needed" approvals based on the desired input quantity.

* [x] Get designs from Aaron. We agreed to break out into a multi-step modal that walks you through both the approve and submit process
https://www.figma.com/file/GtTkd4y6ksWyrDwg5g5YDd/%5B-Design-System-%5D
* [x] Replaces the existing txn status modals for all views
* [x] If the user has already approved that specific amount, auto-advance to the next step
  * [x] If the approval is larger, or smaller, than the desired quantity, re-do the approval txn. This way, everyone with an existing "max approval" will be migrated to the safer "as-needed" approval.
* [x] When approval is done, set the approval in state
* [x] When spend txn is complete, reset the state to "0"

# Stretch goals
- Optimization: only fetch the approval balances needed for a given view, when the view mounts. Don't fetch them all at app load anymore.

# Considerations
- The modal should support multiple approvals, like for pklima (spend bct + pklima)
- We may need to refactor state to handle the different approval pairs without so much copypasta. Every approval is a `token.(owner, spender)` pair. So perhaps this could be abstracted to something like this:
```ts
interface Approvals {
  [tokenName: string]: { // "bct" | "klima" | "sklima" etc.
    [spender: string]: string; // spender: value approved
  }
}
```
- Token decimals!!! Be careful. Properly format from `BigNumber` units before doing any comparisons. Properly format back to `BigNumber` with appropriate decimals before submitting the txn or manipulating state.
- Probably a good space for writing some tests (format/parse/compare)

## Implementation TODOS

- [x] refactor how allowances are stored in state
- [x] select allowances from new state shape
- [x] let user approve the amount which was entered (not 100000 gwei by default no more)
- [x] skip allowance only if the entered amount is the same as the allowance, otherwise always let the user approve first  => `if (allowance !== value) { showApprovalStep() }`
- [x] combine all approval transactions into one reusable action
- [x] use getTokenDecimal and formatUnit helpers everywhere
- [ ] load allowances when specific view was mounted
- [ ] implement all new changes for the BOND view too (getContract, getAllowances, getBalances etc...)

**Comment by Dakavon** [comment]
> We need to catch this (rare) error where allowance is exceeded, and show the `allow` state request in the UI.

The dApp just throws an error without further explanation what to do.

![KlimaDAOstakingError](https://user-images.githubusercontent.com/3898916/152615133-96c1e131-8ee3-483b-b18a-9014d9d4bf92.png)

Within the console, there is more info
```
{
  "code": -32603,
  "message": "Internal JSON-RPC error.",
  "data": {
    "code": 3,
    "message": "execution reverted: SafeMath: subtraction overflow",
    "data": xxx
  }
}
```

- [ ] UI should allow an increaseAllowance by the differential amount

**Comment by Atmosfearful** [comment]
Going to be assigning this to a potential contributor candidate. Will post updates here

**Comment by Atmosfearful** [comment]
@goatsOnDrugs this is the one I mentioned on our call, we can set up a kickoff to go over this. I need to refresh my memory on the state of designs and potential speedbumps

**Comment by ladytrekker** [comment]
First step is too refactor the approval / allowance actions and state.

According to our internal discussion the state would be changed to collect all allowances according to their tokens.

```TS
allowances?: {
  klima: {
    stake: string,
    offset: string
  },
  bct: {
    exercise: string,
    bond: string,
    offset: string
  },
  klima_mco2_lp: {
    bond: string;
  }
  ...
}
```

**Comment by Atmosfearful** [comment]
> First step is to refactor the approval / allowance actions and state.
> 
> According to our internal discussion the state would be changed to collect all allowances according to their tokens.
> 
> ```ts
> allowances?: {
>   klima: {
>     stake: string,
>     offset: string
>   },
>   bct: {
>     exercise: string,
>     bond: string,
>     offset: string
>   },
>   klima_mco2_lp: {
>     bond: string;
>   }
>   ...
> }
> ```

That looks good, but maybe we should use the same names that we use in our `contracts` address map.
```
bct: {
  klima_mco2_lp: string;
  ...
}
```

**Comment by Atmosfearful** [comment]
I wonder what the tradeoffs would be using a flexible type like?
```
allowances?: {
  [token: string]: {
     [spender: string]: string;
  }
}
```
