### ISSUE TITLE
[sanity] Support use of HTML block

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#904]
The content team has requirement for an HTML block in Sanity to support the ability of doing things like pasting in hubspot code or a hubspot CTA button.

See these discord chats for further context:
[Klima Newsletter Landing Page](https://discord.com/channels/841390338324824096/1064520742131212318)
[Blog Hubspot Embed](https://discord.com/channels/841390338324824096/1064520742131212318)

**Comment by Atmosfearful** [comment]
@jabby09 could you please track down the exact snippet we want to embed? I don't see anything in the discord links there.
Even better would be a sample of how it should look.

**Comment by jabby09** [comment]
@Atmosfearful here is one example:

```
<script charset="utf-8" type="text/javascript" src="//js-eu1.hsforms.net/forms/embed/v2.js"></script>
<script>
  hbspt.forms.create({
    region: "eu1",
    portalId: "26010207",
    formId: "7eeaa834-912a-4a37-8bfc-3b6a47899006"
  });
</script>
```

**Comment by jabby09** [comment]
@Atmosfearful another example:

An example of what we are trying to solve for by having actual CTAs
![image](https://user-images.githubusercontent.com/103535195/219066762-db527502-214f-480b-897b-fcde2a5e09b4.png)

**Comment by jabby09** [comment]
Duplicated by #1046
