### ISSUE TITLE
Remove babel.rc to opt-in to SWC for faster compilations

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#91]
I believe a babel config was added for lingui, which opted us out of SWC. More research needed. But hopefully at some point we can remove the babelrc for faster builds.

https://github.com/lingui/js-lingui/issues/1158

https://nextjs.org/docs/messages/swc-disabled

**Comment by biwano** [comment]
@Atmosfearful There is an issue opened in lingui repo: https://github.com/lingui/js-lingui/issues/1224

**Comment by biwano** [comment]
And we should also follow this issue too: https://github.com/swc-project/swc/issues/1321

**Comment by Atmosfearful** [comment]
closed in favor of #922
