### ISSUE TITLE
[connect modal]: warn user if on wrong network

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#914]
## Description

Problem: Right now, it is possible to use the Wallet on any network.
Solution: Inform the user when the current network is not correct

## TODO
- [ ] extend the connect modal with a prop "network" or alike to pass the desired network the user should use ("polygon", "mumbai", default => "polygon"
- [ ] detect if user is connected to incorrect network and return errorMessage

**Comment by goatsOnDrugs** [comment]
@Atmosfearful @ladytrekker I think we can close this one and use only the issue for bezos since we are moving the component over, right?
