### ISSUE TITLE
[tech] Very slow initial page loads

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#918]
The critical pages are (in carbonmark)
- /retirements/[beneficiary]/[index]
- /projects/[project-key]
- /projects/[project-id]/purchase
- /projects/retire/pools/[pool]/
- /purchases/[txn-hash]

I suspect the subgraph is to blame. We need to do some performance profiling here to identify the problem.

Once #855 is merged we can use it to profile in production as well.

**Comment by jabby09** [comment]
@Atmosfearful added this to /retire epic as a performance testing task

**Comment by Atmosfearful** [comment]
I observed very slow page loads for this page https://www.carbonmark.com/purchases/0xcad9383fba33aaad6256304ef7b103f3f00b21afbaffbbff14423bf074b699e8

**Comment by psparacino** [comment]
Now that the refactor of the `projects/:id` endpoint has been merged, new action items:

- [ ] Complete second pass performance profile of the `project/:id` as it is the basis of `getCarbonmarkProject`,` which is reused for a multitude of pages.
- [ ] Optimize firebase calls if possible. Resource: https://firebase.google.com/docs/firestore/query-data/queries#in_not-in_and_array-contains-any

**Comment by psparacino** [comment]
current progress and findings in this issue: https://github.com/KlimaDAO/klimadao/issues/1360
