### ISSUE TITLE
[Connect Modal] Brave Browser with Metamask

### ISSUE THREAD

**Issue by ShimonD-KlimaDAO** [KlimaDAO/klimadao#923]
I have the Brave wallet in my Brave browser, which always worked well.
I recently added the metamask extension as well to load a different seed phrase for other purposes.
I now only see the option to connect Metamask, and can no longer connect with my Brave wallet.
Both options should be available.

![image](https://user-images.githubusercontent.com/99001851/216240944-b7d257de-31f6-467a-a9d8-3e9c97213d47.png)

In addition, **before** I installed metamask on Brave, I saw the following behavior:
I saw both Metamask and Brave as options (although I did not yet have Metamask). I selected Metamask on Brave, and it automatically prompted the Brave wallet. I believe displaying both should only be an option when the MM extension is installed on Brave. Otherwise - just Brave wallet.

**Comment by goatsOnDrugs** [comment]
This requirement may have been lost in the mele but I think we want to show a link to download metamask if the user doesnt have metamask installed. Do we still want to show that link if the user has brave or another wallet extension that uses window.ethereum?

**Comment by Atmosfearful** [comment]
I would define the requirements as such:

If the user does not have window.ethereum.isMetamask -> do *not* show metamask
Same for brave.
Always show Coinbase and Walletconnect and social login.

If the user has both (is this possible???) show both. However When you have two wallet extensions installed, I suspect one is simply overriding the other. So I don't think it's possible for `window.ethereum` to have both `isMetamask` and `isBrave` at the same time. If this is the case, we just show whichever one is true. You'll have to do some research @goatsOnDrugs 

As far as encouraging ppl to download metamask, we don't need that as we are leaning in to Torus instead.

**Comment by goatsOnDrugs** [comment]
If the user has brave wallet and metamask is disabled `isMetamask` is still true. It seems `isMetamask` is always true even if metamask is disabled. If use has metamask and brave wallet both enabled it seems metamask overrides brave and `isBraveWallet` doesnt exist on window.eth. If metamask is disabled then the user does see the brave wallet button.
