### ISSUE TITLE
Torus social login visual improvements

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#928]
I watched my mother-in-law click Google, and then act very confused when the torus modal popped up and she was prompted to click Google a second time. She asked "did I do something wrong?"

![image](https://user-images.githubusercontent.com/88635679/217107939-c883bf56-178f-4717-80ab-ce0b10b9dc7f.png)

Let's update the visual style of these buttons so that it is clear they are one button to trigger the torus modal.

Stretch goals: On that button, or in the overline text there, can we indicate that the social logins are powered by torus, or show the torus logo, or something?

I also just noticed the icon color is broken. We can fix that in this ticket as well

**Comment by jabby09** [comment]
@Atmosfearful isn't the plan to move away from this custom modal? There is an issue (#917) to investigate using the web3auth modal as-is.

**Comment by jabby09** [comment]
This is resolved with updated design pattern implemented for Carbonmark.
