### ISSUE TITLE
[connect] Twitter social login throwing connection error

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#931]
### Summary
When I use the twitter option for social login, the process throws a connection error.

### How to replicate

- Go to the Login/Connect modal and select social login option (torus)
- On the Torus modal, select Twitter option
- On the Authorize Web3Auth to account screen, click Sign in
- Sign in to twitter with your account
- You will end up at a screen that says "Select an account to continue" and the Klima app tab will show a Connection error. Clicking the "Continue to app" button on the web3auth screen does not do anything.

![Image](https://user-images.githubusercontent.com/103535195/218571099-5bca40d7-88a6-4c31-ba8c-68a67f450f00.png)

- Cancel the web3auth tab screen and click Ok to clear the error message on the Klima app
- Try signing in again, it will work without an error.

It looks like on the first handoff from torus/twitter to the klima app something is not being captured properly.

**Comment by jabby09** [comment]
@goatsOnDrugs did you investigation lead to a next step or recommendation?

**Comment by goatsOnDrugs** [comment]
@jabby09 I dont have a good solution here. Torus throws an error "User closed popup" when the user logs into twitter and we have no control over that unfortunately.

**Comment by goatsOnDrugs** [comment]
This seems to be fixed by the upgrade. @ShimonD-KlimaDAO passing to you for verification.

**Comment by jabby09** [comment]
@ShimonD-KlimaDAO when you have time can you add this one to your QA cycle

**Comment by ShimonD-KlimaDAO** [comment]
@jabby09 this looks good on both mobile and desktop.
