### ISSUE TITLE
[retirement page] Pulling from two separate projects & subgraph index

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#933]
### Description
See [discord thread here](https://discord.com/channels/841390338324824096/1075434761096540161).
It was reported by a contrib that when you click on the 2nd retirement (54.62 NCT), then the next page shows the wrong retirement amount as 794.378 NCT. 

https://www.klimadao.finance/retirements/0xb2b8c7ea4619327101e591828600f62616ad8e12

The retirement certificate shows the right amount though.

**Comment by jabby09** [comment]
[cujo]
> looks like this happened because there were only 794 project tokens left for the default project, so it pulled in the remainder from the second in the list. Both of them happened in the same transaction

**Comment by jabby09** [comment]
interesting...the /2 retirement page exists (https://www.klimadao.finance/retirements/0xb2b8c7ea4619327101e591828600f62616ad8e12/2) but it does not have a date or pdf. 
these two retirements appear separate but point to the same /3 retirement page`
![Image](https://user-images.githubusercontent.com/103535195/219871008-b411c40d-5a5f-42b4-a2d2-b2c54616c9ee.png)

**Comment by jabby09** [comment]
[atmos]
> indeed there seems to be a bug in how we render that list of All Retirements
> its not linking to the correct index
> And that /2 retirement page is indeed funky
> So we made some wrong assumptions about what happens when a retirement pulls from two separate projects

**Comment by jabby09** [comment]
[atmos]
> @cujowolf so the subgraph is returning index '2' twice

```
{
      id: '16610969610x68e65cc375f10baf74ac41773658dd00b5de1eaa',
      pool: '0xd838290e877e0188a4a44700463419ed96c16107',
      beneficiaryAddress: '0xb2b8c7ea4619327101e591828600f62616ad8e12',
      index: '2',
      timestamp: '1661096961',
      retirementMessage: 'Completing our Pledge!',
      amount: '794.37810595804719612',
      offset: [Object]
    },
    {
      id: '16610969610x463de2a5c6e8bb0c87f4aa80a02689e6680f72c7',
      pool: '0xd838290e877e0188a4a44700463419ed96c16107',
      beneficiaryAddress: '0xb2b8c7ea4619327101e591828600f62616ad8e12',
      index: '2',
      timestamp: '1661096961',
      retirementMessage: 'Completing our Pledge!',
      amount: '54.62189404195280388',
      offset: [Object]
    }
```

**Comment by jabby09** [comment]
[atmos]

> indeed index 1 is missing
```
{
  "data": {
    "klimaRetires": [
      {
        "amount": "160",
        "token": "BCT",
        "index": "0"
      },
      {
        "amount": "54.62189404195280388",
        "token": "NCT",
        "index": "2"
      },
      {
        "amount": "794.37810595804719612",
        "token": "NCT",
        "index": "2"
      }
    ]
  }
}
```

> so this explains why the page has no timestamp or certificate (this stuff depends on subgraph), but we are still able to get the retirement message and beneficiary name from the storage contract itself 
> https://klimadao.finance/retirements/0xb2b8c7ea4619327101e591828600f62616ad8e12/2
> theres no fix for me there so im just gonna wait on subgraph fixes @jabby09

**Comment by Atmosfearful** [comment]
fixed in new subgraph
