### ISSUE TITLE
Add linting or ts rule to throw error on unused imports.

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#94]
a bunch of unused imports are making it into the app. they are hard to catch during code review, need a lint rule

**Comment by 0xAeterno** [comment]
@Atmosfearful keen to help out and work on issue up :)

Any preferences on the implementation, I noticed each of the monorepos have their own respective eslint config files.
A bit unfamiliar with how the repo is structured but a shared eslint config at the root level could be a future potential enchancement? :D

**Comment by Atmosfearful** [comment]
> @Atmosfearful keen to help out and work on issue up :)
> 
> Any preferences on the implementation, I noticed each of the monorepos have their own respective eslint config files. A bit unfamiliar with how the repo is structured but a shared eslint config at the root level could be a future potential enchancement? :D

Awesome great to have you!
A shared eslintconfig would be nice, I'm not sure how that works though, I'm gonna ask a colleage how they do it in their monorepo. Looking over your PR now :)

**Comment by Atmosfearful** [comment]
Looks like you can create a json in the root dir, then do this from each of the package eslintrc.json files:
```
"extends": "../.eslintrc.json"
```

Or maybe even delete the ones from the sub packages and eslint might pick it up automatically? More info:
"extends": "./config/packages/eslint-config/react/.eslintrc.json"
