### ISSUE TITLE
[retirement] Receipts are not recognizing .kns domains

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#940]
## Description
As reported [here](https://discord.com/channels/841390338324824096/964698508751949824/1078977253792292864)
It appears a bug may have been introduced into the retirement receipt since mid-day Friday Feb 24.

Receipts URLs are using the wallet address (https://www.klimadao.finance/en/retirements/0xEa4d28F8218F44c84c8d7CBAE5deaC41Acf66ceD/12) vs kns domain (https://www.klimadao.finance/en/retirements/brice.klima/12)

This worked properly for me when I did a retirement earlier on Friday.

To repeat, do a new retirement using a wallet that has a kns domain setup.

**Comment by jabby09** [comment]
domain is resolving on the dApp itself

![Image](https://user-images.githubusercontent.com/103535195/221364094-b8a6f5f1-a640-4651-a4ff-4ea1df13c64a.png)

**Comment by Atmosfearful** [comment]
The reverse domain lookup (from 0x -> .klima/.eth) was the source of 0.5-1s delay in page generation in #932 
I think speedy page loads are way more important..
One low effort workaround is, in the "view your retirement button", I can use the users .klima or .eth to construct the URL.

**Comment by jabby09** [comment]
@Atmosfearful changed this to a low priority enhancement to implement your low effort workaround.
