### ISSUE TITLE
Landing page re-work

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#953]
Currently the landing page emphasizes tokenomics and "buy klima". We have matured, and with the launch of carbonmark, it's time to update the page.

KlimaDAO.finance should be reworked to emphasize
1. Our mission and vision
2. Our role as an org that builds products and infrastructure
3. ? Governance, other benefits of a DAO?
4. ? Participation and exposure via the KLIMA token?
5. Hiring / join us etc.

* [ ] ideally with no changes to layout, just content :)
* [ ] Make sure to connect Carbonmark and link users to it
* [ ] Re-visit the content in /community and /contact
* [ ] What to do about love letters and infinity? I say, scrap em'

**Comment by jabby09** [comment]
The klimadao homepage is being redesigned
