### ISSUE TITLE
MCo2 retirement seems to have broken some pages

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#963]
got a "fun" one for ya... 

this is 404ing for me after i retired a MCO2 
https://www.klimadao.finance/retirements/0xab5b7b5849784279280188b556af3c179f31dc5b

the retirement page itself is also 404ing https://www.klimadao.finance/retirements/0xab5b7b5849784279280188b556af3c179f31dc5b/9

you mind logging around the getStaticProps for both pages and seeing what you find?

I used the new v2 aggregator in #960 to create these retirements
Perhaps some data is missing or subgraph is not indexing these new retirements properly?

**Comment by goatsOnDrugs** [comment]
@cujowolf Hey, I think this one is subgraph related. Here is the query for ya https://api.thegraph.com/subgraphs/name/klimadao/polygon-bridged-carbon/graphql?query=%7B%0A++klimaRetires%28%0A++++where%3A+%7BbeneficiaryAddress%3A+%220xab5b7b5849784279280188b556af3c179f31dc5b%22%7D%0A++++orderBy%3A+timestamp%0A++++orderDirection%3A+desc%0A++%29+%7B%0A++++id%0A++++pool%0A++++beneficiaryAddress%0A++++index%0A++++timestamp%0A++++retirementMessage%0A++++amount%0A++++offset+%7B%0A++++++id%0A++++++tokenAddress%0A++++++totalRetired%0A++++++projectID%0A++++++country%0A++++++region%0A++++++bridge%0A++++++registry%0A++++++standard%0A++++%7D%0A++%7D%0A%7D

**Comment by cujowolf** [comment]
Waiting on this to finish indexing to verify that this PR resolves the subgraph issue:
https://github.com/KlimaDAO/carbon-subgraph/pull/40

**Comment by Atmosfearful** [comment]
Fixed!
