### ISSUE TITLE
[projects] Project summary should fill remaining space

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#967]
It seems to have a max height that prevents it from filling free space when the title is short.
- ensure cards have a uniform height
- full title is always shown
- paragraph fills the remaining space
![image](https://user-images.githubusercontent.com/88635679/229634523-d3c60423-ae00-46d9-b6f7-a5185c1a05f0.png)

**Comment by Atmosfearful** [comment]
Oops this one should be on carbonmark repo. I'll leave it here as we are migrating those issues over soon :)

**Comment by jabby09** [comment]
@0xMakka goats is not working in the dao any longer so transitioning this one to you - low priority and made have been fixed

**Comment by 0xMakka** [comment]
@jabby09 is this still an issue? Looking through some projects, the description is always shown in full without the faded effect as shown by atmos above.

![Image](https://github.com/KlimaDAO/klimadao/assets/92357475/b84990a8-43c4-4d7b-ae21-dd166006a350)

**Comment by jabby09** [comment]
@0xMakka if my memory is correct, this content is now provided by the `short_description` field in https://api.carbonmark.com/api/projects. I believe @Najada is providing that content at a fixed character length which for the most part works but does end up sometimes getting cut-off in strange ways...

<img width="930" alt="Screenshot 2023-07-04 at 10 07 22 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/7ff1dd8f-14b7-4047-a1cf-fe57cafca29c">

I wonder if the better approach is for the full `short_description` content to be provided in the api call and we adjust to fill the remaining space on the front end, implementing the text fade as required? If yes, will need to get @Najada to adjust on the backend first.

cc @Atmosfearful

**Comment by Atmosfearful** [comment]
@sprrwhwk I think this would be a good first ticket for you!

* [ ] We just need to remove the max- char limit on the project short_descriptions within the /projects endpoint
