### ISSUE TITLE
[project details] Add tooltips to project detail page

### ISSUE THREAD

**Issue by 0xAurelius** [KlimaDAO/klimadao#969]
There are a bunch of concepts that could use tooltips, most notably the far fight chart showing project/vintage supply and retirements: 
![image](https://user-images.githubusercontent.com/91024694/229856517-9aa9b402-e2eb-4bef-85db-4bc6b20cf73a.png)

Draft tooltip text:
Total Retirements - "Amount of credits from this project/vintage combination that have been retired."
Remaining Supply - "Amount of credits that have been bridged from this project/vintage combination but not yet retired."

Would also be good to link out to the Polygonscan project/vintage token page here so people can see the stats themselves

**Comment by theprofessora** [comment]
New Card layout:

![Image](https://user-images.githubusercontent.com/110631623/236037047-a55c1f46-3b46-421f-85ef-ebc0ab86ed71.png)


Total Retirements Tooltip:

![Image](https://user-images.githubusercontent.com/110631623/236037349-1945e04d-1bae-478f-a378-d9ae0bff5b54.png)

Remaining Supply Tooltip:

![Image](https://user-images.githubusercontent.com/110631623/236037541-b53efe00-23b0-4efd-a945-5f1127a88729.png)

**Comment by psparacino** [comment]
got it, thanks
