### ISSUE TITLE
[portfolio] Use CMS endpoint for reading unlisted project data

### ISSUE THREAD

**Issue by ladytrekker** [KlimaDAO/klimadao#974]
## Description

In order to render the portfolio and the create-listing dropdown for every token asset a user owns,
the frontend checks for each token if:
- is this token already listed as a project on Carbonmark? => get the project data from Carbonmark API
- If not => is this a C3 token? => create a contract for this C3 token and call contract methods to get the project data
- is this a TCo2 token? => create a contract for this TCo2 token and call contract methods to get the project data

See the [code here](https://github.com/Atmosfearful/bezos-frontend/blob/bezos-main/carbonmark/lib/actions.ts#L251-L268)

=> The creation of token contracts can be replaced with a new API endpoint which reads data from the CMS!

## TODO
- [x] wait until the new endpoint for the CMS token data is live
- [x] replace the contract methods with Carbonmark API endpoint requests to get the project data for each token asset a user own

**Comment by Najada** [comment]
@Atmosfearful do we wait?

**Comment by jabby09** [comment]
@psparacino another old one that may not be required anymore. Will require investigation and perhaps a chat with @Atmosfearful

**Comment by Atmosfearful** [comment]
This was addressed in https://github.com/KlimaDAO/klimadao/pull/1640

which refactored the addProjectsToAssets endpoint to use the API
