### ISSUE TITLE
[performance] Loading spinner feedback for slow project pages

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#981]
When clicking the link on a project card in the /projects page
Try showing a loading spinner or some other feedback.
Be careful that it only appears when they really are navigating-- not on accidental taps (touch screens).
For this you might want to rely on router events, not onClicks, but mess around and see what you think is easiest

https://nextjs.org/docs/api-reference/next/router#routerevents

**Comment by jabby09** [comment]
This PR was closed, I believe other enhancements deprecated the need for this change.
