### ISSUE TITLE
[ui issues] Design QA bugs

### ISSUE THREAD

**Issue by goatsOnDrugs** [KlimaDAO/klimadao#982]
Design QA items found in QA call with professor. Gonna add a check list after I fix retire links. Its gonna be great.

- [ ] on filter results project page make dropdown items touch select input (no padding). width 100% left aligned text with same padding/aligned with select text
- [x] update space between stats and activities from 2.4rem to 1.2rem
- [ ] for project stats (not seller state) if !currentSupply or !totalRetired (should this be || or &&?) then dont show stats . we can change "Data for this project and vintage" text to ""No data found for this project and vintage"

**Comment by jabby09** [comment]
@jabby09 to review if these are still design bugs
