### ISSUE TITLE
[projects] Add blue carbon category to Carbonmark

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#986]
We are now starting to see Mangrove credit projects be added to the Carbonmark marketplace, https://www.carbonmark.com/projects/VCS-1764-20200615

There has been a request to add a Blue Carbon category in Sanity https://carbon-projects.sanity.studio/desk/methodology

**Comment by ShimonD-KlimaDAO** [comment]
All looks good to me - I think we can remove the "In Test" label.
