### ISSUE TITLE
[projects] Add registry pill label to project header

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#991]
[Designs](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=11-58928&t=Y5I6vpISjdKsrVHH-0) show a registry pill label in the project header on a project details page.

![Image](https://user-images.githubusercontent.com/103535195/227943010-c74eb776-f0ab-46a4-a244-3fc071b94adb.png)

We do have this data in Sanity.
![Image](https://user-images.githubusercontent.com/103535195/227942979-da032c59-3959-4399-9775-198a5c69252c.png)

Note that current options are Verra, Gold Standard, and EcoRegistry but expect to support more options.

**Comment by jabby09** [comment]
Right now all of the projects are VCS = Verra, I'll have to find out what the graph results would be for other registries but not an issue currently.

**Comment by jabby09** [comment]
@0xemc I found out from cujo that currently Verra = VCS and Gold Standard = GS

**Comment by 0xemc** [comment]
@jabby09 I used the `registry` field that already existed on the Project type from the API and tested for GS and VCS projects.

We'll need to update this once we get other registries

https://github.com/KlimaDAO/klimadao/pull/1031
