### ISSUE TITLE
[projects] Link to Verra (or other registry) project details

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#992]
In the retirement aggregator (and carbon dashboard) we include a link to the associated verra project details page for a project. For [example](https://registry.verra.org/app/projectDetail/VCS/1052).

This appears to be missing for Carbonmark unless it was intended to be a link under Project Documentation? ([figma link](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=11-58928&t=yi9uQcysBZblHpnW-0))

![Image](https://user-images.githubusercontent.com/103535195/227941637-a437d096-9d19-4c15-a4bb-3105ab4c3b05.png)

**Other Notes:**

- Most of the projects are currently Verra but we expect more projects to come into the marketplace from other registries

**Comment by jabby09** [comment]
url path you need is now in the API data:

![Image](https://user-images.githubusercontent.com/103535195/231461077-4773d854-f6ad-49a5-89e0-7626982073b5.png)

**Comment by 0xemc** [comment]
Hey @jabby09 implementation is here:

https://carbonmark-git-emc-992-link-to-registry-page-klimadao.vercel.app/projects/VCS-1052-2012

I haven't added the "Project Documentation" section yet until we have access to these urls.

**Comment by jabby09** [comment]
> Hey @jabby09 implementation is here:
> 
> https://carbonmark-git-emc-992-link-to-registry-page-klimadao.vercel.app/projects/VCS-1052-2012
> 
> I haven't added the "Project Documentation" section yet until we have access to these urls.

Yup makes sense, I should have made that more clear since Project Documentation was in the design.

**Comment by jabby09** [comment]
Backend fixed for verra URLs, the preview link in the PR passes. Good to go to prod!
