### ISSUE TITLE
[profile] Link from profile listing to project page

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#996]
If I am on a profile of a seller, and I see a listing, I might want to compare pricing for that listing, but right now there is no way to navigate to the project page.

**Comment by theprofessora** [comment]
here: https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7?node-id=211:19680#419810717

**Comment by jabby09** [comment]
@sy-zygy @Atmosfearful see link above for review

**Comment by jabby09** [comment]
@psparacino more low effort KOL front-end enhancements...

[Design link here](https://www.figma.com/file/tnBViWV19Ln9jjFDekksY7?node-id=211:19680#419810717)

On the /profile page:

- [ ] Make project titles and images clickable (target is the project details page)
- [ ] For project titles, change from default black text to clickable URL style only on hover
- [ ] In the Activity feed, also make the project title clickable (again only changes from default black text to clickable URL style only on hover) --> target is the project details page

![Image](https://user-images.githubusercontent.com/103535195/233170021-576178f5-5cb2-4205-b29a-06fb639fbf5e.png)
