### ISSUE TITLE
[wallet] Add a View Wallet On Torus button

### ISSUE THREAD

**Issue by Atmosfearful** [KlimaDAO/klimadao#998]
Users using torus should be shown how to get to their wallet on polygon.tor.us to manage their other crypto assets there.

This might be a good spot, in the sidebar?
![image](https://user-images.githubusercontent.com/88635679/226454360-fccd575c-c4df-4e7e-bc0c-14f619ee9d7e.png)

Keep in mind this should be reuseable for other web wallets like Circle in the future.

**Comment by theprofessora** [comment]
This solution doesn't break the current design and also stays modular so other web wallets can be supported in the future. Would open the link in a new tab.

![Image](https://user-images.githubusercontent.com/110631623/232580073-6d91b8e5-c3fb-488f-b65b-4d915b3af332.png)

**Comment by theprofessora** [comment]
details on the carbonmark design system figma page: https://www.figma.com/file/0vb829fJKYWWKszeSOvTTN/Carbonmark-Design-System?node-id=31%3A1581&t=6wnVHnML6KBkzlw0-1

**Comment by sprrwhwk** [comment]
@jabby09 how are the links built? Say I have an address `0x123456789`, how would we link to the torus website for that address?

**Comment by jabby09** [comment]
> how are the links built? Say I have an address `0x123456789`, how would we link to the torus website for that address?

not 100% sure if it is possible to deep link into torus if you already have the wallet 0x address - might be in their docs?

will need @Atmosfearful for this one likely

but to start we can just direct user to https://polygon.tor.us/ where they can login in again

**Comment by sprrwhwk** [comment]
@theprofessora what happens to the "copy to clipboard"-icon and logic?

**Comment by theprofessora** [comment]
@sprrwhwk that logic and icon go away in this instance, if the user has a torus wallet

**Comment by jabby09** [comment]
@theprofessora was the intent here to also change the styling? In the screenshot, left is logging in with wallet, right is logging in with Torus. @sprrwhwk matched the design you provided above for Torus but now it is not consistent with wallet login.

<img width="479" alt="Screenshot 2023-07-20 at 9 28 30 AM" src="https://github.com/KlimaDAO/klimadao/assets/103535195/fd137904-b16a-4f0d-81f3-820b8af708e4">

**Comment by theprofessora** [comment]
Hey @jabby09 and @sprrwhwk, Let's update the colors on the wallet login to match the colors on the torus login. Thanks for pointing out the inconsistency! I lost it in the shuffle.

**Comment by sprrwhwk** [comment]
> Hey @jabby09 and @sprrwhwk, Let's update the colors on the wallet login to match the colors on the torus login. Thanks for pointing out the inconsistency! I lost it in the shuffle.

Hey @theprofessora , for 100% consistency I would propose one of the following:

* We split the copy button in two parts:
A label with the address (0x123…789) and a button that reads "COPY" with the copy icon:

> <img width="197" alt="grafik" src="https://github.com/KlimaDAO/klimadao/assets/138768831/2a165672-73b3-4313-ad2c-f5b70794dfe0">

* We remove the "VIEW" label from the torus version and only display the address and the external link icon.

Otherwise they will still look inconsistent. What do you think?

**Comment by theprofessora** [comment]
Both are great suggestions. Let's roll with option A, @sprrwhwk.
