### ISSUE TITLE
[marketplace] Filter / sort selection feedback to user & improved UX

### ISSUE THREAD

**Issue by jabby09** [KlimaDAO/klimadao#999]
## Description
Proposed enhancement for project filtering and sorting.
We should have something that reports to the user (1) how many projects matched their filter (2) the current filter selections, (3) ability to clear without opening the modal
Should work whether in card or table view.

**Comment by jabby09** [comment]
Updated [designs here](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?node-id=268-19204&t=brqBuO1J0ztEzweK-0)

**Comment by jabby09** [comment]
@sy-zygy @Atmosfearful see link above for review

**Comment by theprofessora** [comment]
All shipped designs have been updated to reflect the filtering updates. The new filter flow is now in the Shipped section.

**Comment by jabby09** [comment]
@0xMakka 

Here are the [updated designs](https://www.figma.com/file/5GewbdVaM1Q06CwHmF7d3F/%2Fprojects?type=design&node-id=518-35606&t=lrdWGniyV4SsFlG4-4) for enhancing the filter modal plus location and how filter/sort features work (notice we are moving some of the functionality to the marketplace page).

I will go through the design and break down the to-do tasks, will have that done by Monday sometime. But if you have time and want to start reviewing I wanted to make sure you had the latest designs.

Also as mentioned, the front end work for the new retirement page design will take priority over this work so you can just pick away at this one as you have time.
